### ISSUE TITLE
Vapor crashes when creating new MPAS renderer

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1003]
To reproduce:

1) Spin up vapor and import the MPAS file:
        /little_glade/data/Source/MPAS/MPAS-O/hist.mpas-o.0001-01-01_00.00.00.nc
2) Create a TwoDData renderer and Vapor will crash

Note, this also happens with the files in /little_glade/data/Source/MPAS/MPAS_V4.0

**Comment by clyne** [comment]
This is stalled pending resolution of #1050
