### ISSUE TITLE
TFWidget: broken after deletion and re-creation of renderer

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1007]
To reproduce:
1. Create an Isosurface renderer, enable it, change the iso-value a little bit.
2. Delete this Isosurface renderer.
3. Re-create an isosurface renderer.
4. Go to Appearance tab. The TFWidget looks broken, as the screenshot shows.

![screenshot from 2018-09-18 12-05-07](https://user-images.githubusercontent.com/814885/45708513-df171b00-bb3e-11e8-8c95-0f1befb21ff3.png)

**Comment by shaomeng** [comment]
Though no more broken fonts, now it has no font! 

![screenshot from 2019-01-03 15-55-26](https://user-images.githubusercontent.com/814885/50666057-4b901b80-0f70-11e9-9e4d-73920e52c7f6.png)

**Comment by StasJ** [comment]
@shaomeng This is not a bug. There is the letter P in the top middle of the TF widget in the screen shot you took.
