### ISSUE TITLE
Rename "Transfer Function Editor" in contour renderer

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#101]
The widget that displays a histogram in contour renderer is named "Transfer function editor," see screenshot from issue #100.

It isn't a transfer function editor actually. Should be "Isovalue picker" etc.

**Comment by shaomeng** [comment]
Update on 4/4/2018:
"Isovalue selector" would be a better name.

**Comment by NihanthCW** [comment]
@shaomeng is this still relevant?

**Comment by shaomeng** [comment]
> @shaomeng is this still relevant?

No, it's not relevant anymore.

**Comment by shaomeng** [comment]
No longer applicable.
