### ISSUE TITLE
vapor crashes when shaders contain compilation errors

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#1014]
vapor will crash if the shader files contain syntax errors

To reproduce:
1. Edit the 2DData.frag file and introduce a syntax error. E.g add the line:

a bug

at the start of the main program.
2. Start vapor, load any data set, and create and enable the 2D data renderer.

**Comment by StasJ** [comment]
This only applied to the 2DRenderer because it was not checking if the shader was valid in its _paintGL. Fixed.
