### ISSUE TITLE
Unused output variable

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1029]
The following line of code states an output variable of the vertex shader, but there's no corresponding input variable declaration in the fragment shader. 

In pursuit of a higher standard of software engineering, I recommend this line being removed, as well as similar occurrences in other shaders. 

https://github.com/NCAR/VAPOR/blob/91ffcd3af217777479d4b18c312d0db0bd17e610/share/shaders/2DData.vert#L11

**Comment by StasJ** [comment]
This value is used by OpenGL when generating fragments. From the GL4 docs:

‘’’
In fragment shaders, it is intrinsically declared as: in float gl_ClipDistance[] ;
‘’’
