### ISSUE TITLE
Interactive refinement not implemented?

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#103]
It seems the function(s) to adjust interactive refinement levels are not implemented. Should we go implement it, or disable this functionality?

https://github.com/NCAR/VAPOR/blob/7da9baba1595c4c039fbac69d25117a1674f6f90/apps/vaporgui/MainForm.cpp#L1363-L1368

**Comment by clyne** [comment]
Let’s just ifdef it out for now, and leave an open ticket on GitHub.

jc


> On Oct 18, 2017, at 2:55 PM, Samuel Li <notifications@github.com> wrote:
> 
> It seems the function(s) to adjust interactive refinement levels are not implemented. Should we go implement it, or disable this functionality?
> 
> https://github.com/NCAR/VAPOR/blob/7da9baba1595c4c039fbac69d25117a1674f6f90/apps/vaporgui/MainForm.cpp#L1363-1368
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
Not applicable anymore.
