### ISSUE TITLE
Capture Image only works for the 1st image

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#104]
After successfully capture the 1st image, the image capturing functionality stops saving images on disk.

Note: this bug might be related to issue #50

**Comment by shaomeng** [comment]
I located the cause of the bug being that the following capture commands don't generate a "paintEvent()" in the Visualizer. Need to figure out how/where the "paintEvent()" is generated.

**Comment by StasJ** [comment]
See Issue #75

**Comment by shaomeng** [comment]
@StasJ , could you review my pull request #108  and see if it fixed #75  as well? 
@clyne , could you review my pull request #108 and see if it fixed #50 as well? 

Thanks to both!
