### ISSUE TITLE
Use of GL_ERR_BREAK

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#1051]
GL_ERR_BREAK , which generates an assert on an OpenGL error, is being used in places where a recoverable error should be generated. For example, Visualizer.cpp and TwoDDataRenderer.cpp are calling GL_ERR_BREAK and crashing on OpenGL errors when they should be generating an error message, and returning error status back up the call stack.

**Comment by StasJ** [comment]
GL_ERR_BREAK is only used for debugging. It is a no-op for release builds. It is meant to catch programmer error, not runtime recoverable errors.

In many places where it exists, there either already is a mechanism for returning an error message (e.g. in Visualizer after a renderer initializes or paints) or it is just a check thrown in to catch developer mistakes more easily.

If we wanted a more general catch-all OpenGL error report, I would add a check single at the end of Visualizer::paintEvent which could report an error to the user.
