### ISSUE TITLE
Axis annotation text does not honor depth buffer

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1055]
Text that should be obscured shows in front of rendering.

**Comment by clyne** [comment]
Please add step-by-step instructions to reproduce. At present the fix cannot be verified

**Comment by StasJ** [comment]
1. Open a dataset
2. Add a 2D renderer
3. Enable Axis Annotations
4. Rotate scene so the annotation should be obscured by the renderer

![50505193-873a5b00-0a2f-11e9-9f13-1bb0f993b5ac](https://user-images.githubusercontent.com/2772687/50667511-d3792400-0f76-11e9-8568-e667265134e4.gif)
