### ISSUE TITLE
TF Widget does not work for volume renderer in some cases

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1059]
1. Open Katrina
2. Add/enable a volume renderer
3. Select variable QCloud
4. Move TF max/min slider (optional?)
5. Click on the TF widget (optional?)
6. Select timestep 5

I kept running into this at first but then once I tried to intentionally reproduce it, it didn't happen every time. I think there are multiple ways to get this bug but the above method is pretty consistent.

![out](https://user-images.githubusercontent.com/2772687/49671527-76488c00-fa25-11e8-8206-6fe94ec9abb1.gif)

**Comment by shaomeng** [comment]
Cannot verify, since upon opening Katrina, the TFWidget isn't operational:

![issue1059](https://user-images.githubusercontent.com/814885/50665880-99f0ea80-0f6f-11e9-8e92-8bdf66c83825.gif)

**Comment by sgpearse** [comment]
@shaomeng WRF has an initialization sequence, when some variables are not present.  I suspect that you may have missed step 5 in the bug report.  It's not clear which dataset we need to load.  I'm guessing it's /little_glade/data/VDC/vapor-3.0.0/WRF/Katrina/Katrina-3.0.0.nc

**Comment by shaomeng** [comment]
The screenshot was taken using time step 0, which has legitimate all-zero values. This behavior isn't there using later time steps.
