### ISSUE TITLE
Transform tables need floating point validators

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#106]
The TransformTable class does not use floating pointer validators (i.e. QDoubleValidator). Hence,
it is possible to enter non-numerical values.

To reproduce:
1. Load any data set and enable the 2D data rendere
2. In the Translate Transform of the Geometry tab enter any string (e.g "abc"). Hit return.

**Comment by sgpearse** [comment]
Ready for review

**Comment by clyne** [comment]
Scott, can you ask Sam what he does so that GitHub generates a review (pull) request with a link to the changes in your branch? That really helps the process a ton! 

thanks - jc

> On Oct 19, 2017, at 11:51 AM, sgpearse <notifications@github.com> wrote:
> 
> Ready for review
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
Let's get over this in the upcoming meeting this afternoon.
