### ISSUE TITLE
Possible memory leak in TransformTable?

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#107]
Each time the Update method on the TransformTable class is called it rebuilds its table from scratch without freeing the current table. Qt has complex memory model that does a lot of cleanup, but I'm not sure that table is being deleted. The RenderHolder, for example, also builds its table dynamically, but it frees the previous table. Need to confirm cleanup is being done.

**Comment by sgpearse** [comment]
Fortunately, QTableWidget handles its memory management for QTableWidgetItems.

https://stackoverflow.com/questions/21997025/qtablewidget-memory-leak-or-not
