### ISSUE TITLE
Volume renderer not guaranteed to render last

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1081]
Volume renderers are currently rendered in the same order as any of the other renderers. They should always be rendered last

**Comment by clyne** [comment]
I think currently the renderers are fired in the order that they are enabled. We should add an exception that pushes the volume renderer to the end of the list. This is not an ideal solution, but probably the best that we can do for now.

**Comment by shaomeng** [comment]
It's clear that when multiple renderers are enabled, the volume renderer should be the last one to draw. Is it still the case between the annotations and the DVR? I.e., between the white bounding box, axis labels, etc. and the DVR?
