### ISSUE TITLE
Volume renderer does not render anything on thin grid

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1087]
On Katrina, if you don't stretch the extents vertically, by default the volume renderer does not display anything. This could be confusing for users who might assume the renderer is broken.

At 1x stretch nothing is shown except at almost 180 degrees

At 10x stretch, we can see the volume at certain angles

At 100x stretch, the volume is fully visible

![out](https://user-images.githubusercontent.com/2772687/49956354-391b4880-fec2-11e8-906c-e52715cdb894.gif)

**Comment by shaomeng** [comment]
Seems the same problem reported in #1058
