### ISSUE TITLE
Volume Renderer is not consistent as refinement level increases

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1090]
Dataset: Katrina
Variable: U

![out](https://user-images.githubusercontent.com/2772687/49973913-39343c00-fef4-11e8-8e02-b7ef20e35e8a.gif)

**Comment by shaomeng** [comment]
I wasn't able to reproduce this bug on development branch `issue1073`. Will try again once this branch is merged.

**Comment by shaomeng** [comment]
After PR  #1091 got merged, I still cannot reproduce this bug. Need more detail.
