### ISSUE TITLE
Force VDC "master" files to use .nc extension

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#1111]
The various *create command line utilities (vdccreate, wrfvdcreate, etc.) should probably force the resulting file to use the .nc suffix. It makes life easier for the vapor gui file browser to select master files. 

This is an issue we should discuss as there may be better alternatives.

**Comment by StasJ** [comment]
Could we consider changing the official extension to .vdc to avoid confusion with regular netCDF files?

**Comment by clyne** [comment]
We should discuss.

> On Dec 19, 2018, at 1:37 PM, StasJ <notifications@github.com> wrote:
> 
> Could we consider changing the official extension to .vdc to avoid confusion with regular netCDF files?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu
