### ISSUE TITLE
Black hole in Volume Renderer

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1114]
1. Open Katrina
2. Add Volume renderer for variable U
3. Scale Z axis by 3000
4. Enable
5. Increase refinement

![out](https://user-images.githubusercontent.com/2772687/50252371-fff04600-03a3-11e9-9add-3779ff725422.gif)

**Comment by shaomeng** [comment]
Cannot reproduce. I suspect it's fixed by PR #1260
