### ISSUE TITLE
Katrina's extents change when renderers are enabled

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1180]
To reproduce:

1) Load a Katrina VDC
2) Create a 2D Data renderer and enable it
3) The extents grow

![screen shot 2019-01-04 at 8 45 31 am](https://user-images.githubusercontent.com/9522770/50696670-5218a480-0ffd-11e9-8f19-7bf28fcb11ce.png)

**Comment by clyne** [comment]
Closing. We can validate with the next release.
