### ISSUE TITLE
compiler warnings

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#1183]
There are still lots of compiler warnings (118 in total) being generated on the Mac.

**Comment by StasJ** [comment]
What warnings are you getting?

I only have one warning from XCode which is a warning I manually added about a broken function. When building from the command line, I get that one warning and also the linker warns me that some of my system library files are out of sync but this is not related to vapor. To fix those warnings, the solution I found online was to reinstall the OSX XCode command-line tools.

On linux I also get that one warning, and then it also warns me that our third party Python.h overrides some system #defines. I moved around some #includes to reduce the number of times this warning comes up.

![scrot](https://user-images.githubusercontent.com/2772687/50705700-dfb5bd80-1018-11e9-8803-7856332d599b.png)

**Comment by StasJ** [comment]
Only in release mode
