### ISSUE TITLE
Error performing paint event with VAPOR3

### ISSUE THREAD

**Issue by winash12** [NCAR/VAPOR#1195]
I tried the latest version of VAPOR3 provided recently and I am getting this error  now - 

Vapor 3.0.0.e511d88
OS: Linux 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018
Distro:
LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch

-------------------
Paint failed
-------------------
Error performing paint event
No variable name specified
Undefined variable name : NULL
GL Vendor String is MESA.
Graphics drivers may need to be reinstalled

Sequence of events to reproduce this bug

Follow this youtube URL - https://www.youtube.com/watch?v=gfj2PSd2rvE
 with COSMO weather model p file.
1) Loaded the 'p' file
2) Clicked on New
3) Clicked on TwoDData
4) Then click on Enabled and got that error message.

**Comment by sgpearse** [comment]
Ashwin, I think that you have a TwoDData renderer enabled when this is happening.  The files you shared with me have no 2-Dimensional variables in them, and Vapor cannot find anything to render, hence this error.

Admittedly, we should probably disable the ability to create a 2D renderer if no 2D variables exist.  Likewise for 3D variables.  I'll write a new bug report about this.  Thanks for reporting this usability issue!

**Comment by sgpearse** [comment]
Ashwin reports that this issue persists even with the TwoDData renderer disabled :(

**Comment by winash12** [comment]
I am unable to save out the image as a PNG file.

**Comment by sgpearse** [comment]
I'm going to open a new ticket #1266 regarding the image capture issues reported by winash12.
