### ISSUE TITLE
Undo with IsoSurface renderer causes error state which leads to crash

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1204]
The following steps are approximate. I did not narrow down exactly what caused this bug, but I was able to reproduce it 3 times in a row.

1. Open a dataset. (I confirmed with `/little_glade/stasj/lee.nc` and `Katrina`)
2. Add/enable an IsoSurfaceRenderer
3. Change the main variable a couple times
4. Change the fidelity
5. Play with the min/max values and iso values
6. Move the view
7. Undo between 5-20 steps

(Upon further testing, it appears steps 3 and 5 are most important)

Vapor will show the following error:

```
Error performing paint event
Failed to initialize renderer IsoSurface
Failed to load shaders!
Resource does not exist and unable to load by name
Failed to link shader:
ERROR: Compiled vertex shader was corrupt.
ERROR: Compiled fragment shader was corrupt.

Undefined variable name : NULL
```

If you close the error and delete/add a new IsoSurfaceRenderer, vapor will crash.

I ran a sanity test and performed the a similar series of actions with the TwoDData renderer without any issues.

**EDIT**

This issue appears to be limited to the IsoSurfaceRenderer. I tested the volume renderer too without any issues.

**Comment by shaomeng** [comment]
There are two issues in this report: 1) OpenGL failure upon undo, and 2) crash. 2) seems to be caused by 1), so we address 1) first. 

Upon looking at the code, `_initializeGL()` was called at an `undo` event. Should an undo call `_initializeGL()`?  @clyne
