### ISSUE TITLE
cfvdccreate + cf2vdc on CAM data

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1210]
The command line utilities do not seem to be able to convert the file below.  

/little_glade/data/Source/CAM/Gaussian/b30.030a.cam2.h0.TS.1870-01_cat_1999-12.nc

There is no output given from 'cfvdccreate /little_glade/data/Source/CAM/Gaussian/b30.030a.cam2.h0.TS.1870-01_cat_1999-12.nc cam.vdc'

And there are a lot of time related errors from 'cf2vdc /little_glade/data/Source/CAM/Gaussian/b30.030a.cam2.h0.TS.1870-01_cat_1999-12.nc cam.nc'

**Comment by clyne** [comment]
cfvdccreate does not output anything unless there is an error. It would probably be helpful if it were more verbose like its vapor2 predecessor, but this is a usability issue.

I don't seen any errors on my Mac when running cf2vdc.
