### ISSUE TITLE
Contour Renderer: Line Width

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1212]
Changing the line width results in a failed paint event under the following procedure:

1) Import the NetCDF-CF data /little_glade/data/Source/CAM/Gaussian/
2) Create a Contour renderer, and enable it
3) Increase the line width to 2

![screen shot 2019-01-07 at 3 55 24 pm](https://user-images.githubusercontent.com/9522770/50798178-a8534500-1294-11e9-8217-66686264ecaa.png)

**Comment by shaomeng** [comment]
Line width slider doesn't seem to have any effects. Not sure if that's intentional.
