### ISSUE TITLE
Scaling broken with Barbs

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#1215]
Scaling a data set is still problematic with the Barbs renderer. The attached image shows the default home viewpoint of the Barbs renderer with a MOM6 data set. N.B. if any other renderer is enabled the results are as expected for that renderer.

1. Make sure "auto stretching" is enabled. 
2. Load MOM6/19900101.ocean_month.nc 
3. Create a Barbs renderer
4. Select the 2D variable "ustar" as both the X and Y component (there is no "vstar" variable in this data set)
![untitled](https://user-images.githubusercontent.com/6777736/50800114-13544a00-129c-11e9-88e8-b69de96d3e19.png)

Note, if 3D variables are used the results look correct.

**Comment by clyne** [comment]
Note: this problem also occurs with the contour renderer

**Comment by StasJ** [comment]
This issue is specific to MOM6/19900101.ocean_month.nc. I've tried Katrina, DUKU and ROMS/Kaufmann and they all work.

**Comment by shaomeng** [comment]
Following the steps, I got this result. Not sure if it's correct.

![screenshot from 2019-01-15 16-01-24](https://user-images.githubusercontent.com/814885/51215710-0c05ef80-18df-11e9-9620-c42049076602.png)
