### ISSUE TITLE
Incorrect volume rendering of ROMS/Kauffman

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1216]
This could simply be due to an unsupported grid.

1. Load ROMS/Kauffman
2. Stretch the Z axis by 3E6
3. Add a volume renderer with variable `temp`

You get the following:

<img width="695" alt="screen shot 2019-01-07 at 6 56 10 pm" src="https://user-images.githubusercontent.com/2772687/50805171-6e8f3800-12ae-11e9-8d16-446218ef18da.png">

What it is supposed to look like:

<img width="697" alt="screen shot 2019-01-07 at 6 55 36 pm" src="https://user-images.githubusercontent.com/2772687/50805177-7949cd00-12ae-11e9-859e-06a35b6673b5.png">

**Comment by shaomeng** [comment]
Does the following screenshot look more plausible with PR #1260 ?

![screenshot from 2019-01-09 15-17-39](https://user-images.githubusercontent.com/814885/50932144-f34e9300-1421-11e9-855f-4f567e7baec9.png)

**Comment by StasJ** [comment]
With cell traverse I am missing data on the left:

![screen shot 2019-01-15 at 11 48 20 am](https://user-images.githubusercontent.com/2772687/51202287-a48a7880-18bb-11e9-81f7-36f85870accf.png)

**Comment by shaomeng** [comment]
cannot reproduce on Linux. May need more specific steps.

**Comment by shaomeng** [comment]
@StasJ , could you verify if this problem still exists on Linux?
