### ISSUE TITLE
OSX: Volume renderer depth glitch

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1217]
1. Load ROMS/Kauffman
2. Stretch the Z axis by 3E6
3. Add a volume renderer with variable `temp`
4. Observe the volume from a shallow angle from near the inner ring

The side wall will be rendered in front of the top of the volume.

![out](https://user-images.githubusercontent.com/2772687/50805548-2c66f600-12b0-11e9-945b-e747a99253cd.gif)

**Comment by shaomeng** [comment]
Cannot reproduce. How `Stretch the Z axis by 3E6` was performed?

**Comment by StasJ** [comment]
@shaomeng type “3E6” into the Z axis scale input

**Comment by StasJ** [comment]
Problem still exists with fixed step size and with cell traverse it is missing the volume.

![screen shot 2019-01-15 at 11 44 52 am](https://user-images.githubusercontent.com/2772687/51202084-1910e780-18bb-11e9-8c87-462f1dc36c25.png)

**Comment by shaomeng** [comment]
Cannot reproduce on Linux with Cell Traverse Ray Casting. May need a more specific sequence of steps. 

![screenshot from 2019-01-16 13-16-27](https://user-images.githubusercontent.com/814885/51276186-3fa15200-1991-11e9-9650-2d0b31bff515.png)

**Comment by shaomeng** [comment]
@StasJ can you verify if this problem still exists on Linux?

**Comment by clyne** [comment]
Rejected: using wrong algorithm for curvilinear grids (using fixed step method)
