### ISSUE TITLE
Image Renderer has a Z component in its Geometry Tab

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1232]
The Image Renderer should only have X and Y components in its geometry tab.

To reproduce:
1) Load any georeferenced dataset (DUKU, Katrina)
2) Create an Image Renderer and go to its Geometry tab

![screen shot 2019-01-08 at 9 38 14 am](https://user-images.githubusercontent.com/9522770/50845000-219c7780-1329-11e9-9694-37b4fa704d92.png)

**Comment by StasJ** [comment]
It appears that this is caused when `GeometryWidget::Update` updates the widget extents, it queries the current extents and since the image does not have a variable, it simply uses the default variable which happens to be a 3D variable so it updates the geometry widget as a 3D variable.
