### ISSUE TITLE
Volume renderer crashes with Katrina

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1259]
System: cisl-vapor
Branch: master

1. Open Katrina
2. Add a volume renderer
3. Enable it

Vapor will crash with the following error:

```
vapor: /home/stasj/vapor/lib/vdc/CurvilinearGrid.cpp:896: bool VAPoR::CurvilinearGrid::_insideGridHelperTerrain(double, double, double, const size_t&, const size_t&, size_t&, double*) const: Assertion `inside' failed.
Aborted (core dumped)
```

TwoDData and Wireframe renderers work

**Comment by shaomeng** [comment]
Update: 

This crash isn't reproducible using the master branch of today (Jan 11th), and also not reproducible using the code 1 day prior this bug was filed (Jan 8th). We'll need a better description here.

**Comment by StasJ** [comment]
![out](https://user-images.githubusercontent.com/2772687/51051923-6d058e80-1592-11e9-907c-c95701447d84.gif)

**Comment by shaomeng** [comment]
Ugh, my build does not crash on my desktop, but crashes on Stas' and Scott's desktops. John, you need to take a look at it.

This is the steps Stas and Scott took to reproduce the crash on cisl-vapor.

1. go to folder: /home/shaomeng/Build/VAPOR-master-build
2. run this command: ./bin/vapor /little_glade/data/VDC/vapor-3.0.0/WRF/Katrina/Katrina-3.0.0.nc
3. create a volume renderer, and then enable it
