### ISSUE TITLE
Screen Capture broken with Ubuntu+Intel Graphics

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1266]
Our user @winash12 is reporting that he is getting the error message in the screenshot below when trying to capture an image on his Ubuntu system that uses Intel integrated graphics.

![screenshot_20190110_085402](https://user-images.githubusercontent.com/9522770/50983356-8cca8300-14bc-11e9-8a4f-0195a9b22b08.png)

**Comment by winash12** [comment]
Vapor 3.0.0.e511d88
OS: Linux 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018
Distro:
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
The text message of the error
-------------------
Error capturing image
-------------------
Visualizer (Visualizer_No._0) failed to paint and thus not capturing image.
Failed to save image
Unsupported image file type "/home/winash12/aaa"
GL Vendor String is MESA.
Graphics drivers may need to be reinstalled

**Comment by winash12** [comment]
@StasJ Do I get a new install to try ?

**Comment by StasJ** [comment]
Hi @winash12, here is the most recent Linux installer. Let me know if you run into any difficulties.

https://drive.google.com/open?id=14PQV4qz9_RPpkv9QcLFu98-tH04NG69r

**Comment by winash12** [comment]
@StasJ I still get the same error. So please reopen the defect.

**Comment by StasJ** [comment]
@winash12 Does the error still say `Unsupported image file type "/home/winash12/aaa`? That shouldn't be possible with the updated code I sent you.

**Comment by winash12** [comment]
@StasJ No ! Ir works ! Wonderful I can upload this image to you now . 
![aaa](https://user-images.githubusercontent.com/9129700/51220956-62b20e80-195d-11e9-956a-6698a65af8af.png)

**Comment by StasJ** [comment]
@winash12 thats great! Please let us know if you run into any more issues or if you have any suggestions on how we can improve our software.
