### ISSUE TITLE
Undo: results in renderer not usable

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1280]
To reproduce: 
1. Create a Slice renderer, enable it.
2. Move the scene a little bit.
3. Delete this renderer.
4. Click "undo"
5. The slice renderer comes back, but no GUI elements to operate it, as the screenshot shows.
Note: it doesn't have to be a slicer; other renderers suffer from the same issuel 
![screenshot from 2019-01-11 21-21-58](https://user-images.githubusercontent.com/814885/51069209-956ba800-15e7-11e9-8393-9b3e54a40a24.png)

**Comment by StasJ** [comment]
My fix introduced regression so I removed it.

**Comment by shaomeng** [comment]
No longer applicable.
