### ISSUE TITLE
Windows: Isosurfaces do not draw

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1295]
Isosurfaces do not seem to draw anything on Windows when looking at an imported Katrina file.

To reproduce:
1) On windows, import a Katrina file
2) Create an isosurface renderer.  Nothing gets drawn :(

**Comment by shaomeng** [comment]
I run into a different show stopper: 
It throws error:
`Error performing paint event
Failed to retrieve a StructuredGrid
UserCoordinates::GetCurrentGrid() isn't on a StructuredGrid; the behavior is undefined in this case.`

**Comment by shaomeng** [comment]
Update: 

The StructuredGrid error is gone using Sam's copy of the Katrina data. I suspect Scott got a corrupted data set for his test.

@sgpearse , please verify if this bug still exist using Katrina VDC data at `C:\Users\shaomeng\test-data`, and also verify similar StructuredGrid failures in other bug reports.

**Comment by sgpearse** [comment]
Seems to work with your dataset!
