### ISSUE TITLE
GUI: broken table

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1299]
Follow the 1st two steps in issue #1244, you'll find the table not able to read. 

![peek 2019-01-15 15-26](https://user-images.githubusercontent.com/814885/51214125-40c37800-18da-11e9-8680-a4b11499a225.gif)

**Comment by clyne** [comment]
@shaomeng please see if this is still a problem or if fixed by Qt5

**Comment by shaomeng** [comment]
It's no longer a problem as of 1/12/2021.
