### ISSUE TITLE
Windows: Image Renderer

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1302]
The Image renderer does not retrieve any extents when performing on the file below.  This is resulting in a failed paint event.

1) On windows: import the NetCDF file /little_glade/data/Source/CAM/Gaussian/b30.030a.cam2.h0.TS.1870-01_cat_1999-12.nc
2) Create an Image renderer.  The paint event will fail.  Note the extents in the Geometry tab.

**Comment by shaomeng** [comment]
Duplicates with #1311
