### ISSUE TITLE
CAM/Gaussian volume renderer does not work

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1312]
1. Import CF: CAM/Gaussian/b30.030a.cam2.h0.TS.1870-01_cat_1999-12.nc
2. Create and enable a volume renderer

Vapor will throw error with the following message:
```
Error performing paint event
Failed to retrieve a StructuredGrid
UserCoordinates::GetCurrentGrid() isn't on a StructuredGrid; the behavior is undefined in this case.
```

**Comment by shaomeng** [comment]
There's really nothing DVR can do for a 2D data set. PR #1317 should provide just a band aid.
