### ISSUE TITLE
Usability with VAPOR 3

### ISSUE THREAD

**Issue by winash12** [NCAR/VAPOR#1320]
I have a usability issue and it is really low priority right now because VAPOR 3 has to be released but I would like to compare these two images (one from VAPOR 2 and the other from VAPOR3) 
![screen shot 2018-12-21 at 2 23 29 pm](https://user-images.githubusercontent.com/9129700/51296893-17bef680-1a44-11e9-8625-26c7c1750d22.png)
![aaa](https://user-images.githubusercontent.com/9129700/51296897-1ee60480-1a44-11e9-8eae-6680253ca462.png)

As you can see in the first one the map of India is at the bottom of the "cube" and the data(REL_HUM_) are above and we can see a 3-D image. This one was generated using VAPOR 2. This one also has the topography of India laid out in the background with the mountains et al. 

In the second one(with the identical data) generated by me the topography is invisible , the 3D effect is missing (although I have used a 3D renderer) . So I am not sure whether VAPOR 3 is pulling out all the data on all the levels to display this or only one layer. But to me and this is just me it seems only one layer is being displayed.

Also it would be nice to know how to display various colors rather than just two.

**Comment by sgpearse** [comment]
Hi Winash, you need to use the transfer function.  Check this out:

https://youtu.be/gfj2PSd2rvE?t=383

**Comment by winash12** [comment]
@sgpearse The transfer function handles the colors yes but what about the 3D renderer ? It seems to be absent in VAPOR 3.

**Comment by sgpearse** [comment]
Both of those images were made using Vapor3.  Use the installer we gave you to make a Volume renderer.  Then apply opacity to some of the data values using the transfer function.  You can then add an Image renderer to see India beneath your volume.

We'll have more demonstrations for you to watch after we release.

**Comment by winash12** [comment]
@sgpearse At the moment it appears as a non trivial exercise. I will just wait for VAPOR 3 to release before I ask further questions.
