### ISSUE TITLE
VDC performance issue

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1325]
On little_glade, we have Katrina converted to two versions of VDC:

**New**: `/little_glade/data/VDC/vapor-3.0.0/WRF/Katrina/Katrina-3.0.0.nc`

**Old**: `/little_glade/data/VDC/vapor-3.0.0-old/WRF/Katrina/Katrina-3.0.0.nc`

I timed both versions through the following steps:
1. Start the timer
2. Run `vapor <dataset>`
3. Create and enable a new volume renderer
4. Stop the timer when the volume rendering appears

**New**: 12 seconds
**Old**: under 4 seconds

This test was run on cisl-vapor, however the same issue exists on OSX

**Comment by clyne** [comment]
I'm rejecting this. The older VDC version didn't support conversion of vertical coordinate pressure values to elevation (meters above the ground). The latter results in a terrain following grid that is more expensive to operate on.
