### ISSUE TITLE
Manipulators stop working after Appearance tab gets displayed

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1354]
To reproduce:
1) Open Vapor with /little_glade/data/VDC/vapor-3.0.0/WRF/DUKU/DUKU-3.0.0.nc
2) Create any renderer
3) Go to Region mode to enable the manipulators.  Note that they are functioning at this point.
4) Go the the Appearance tab.  Manipulators no longer register mouse press events

Optional:
5) Create a different kind of renderer
6) Note that the manipulators work
7) Go the Appearance tab again.  Manipulators no longer work.

This bug seems to affect all renderers of a certain type.  Once the manipulators stop working for one instance of that type, they remain broken for all instances.

**Comment by StasJ** [comment]
If you remove the mapping frame, the problem still exists. Also, I tried removing the TF widget and it somehow still appears. Finally why to TF widgets have multiple mapping frames?
