### ISSUE TITLE
DVR black hole

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1357]
**OS**: Ubuntu
**Build**: Release

1. Open `MOM4/19990101` or `MOM4/om3/ocean_residency_snap`
2. Add/enable a DVR

![screen shot 2019-01-23 at 12 05 58 pm](https://user-images.githubusercontent.com/2772687/51630413-56065b00-1f07-11e9-9023-90faa9435c67.png)

**Comment by shaomeng** [comment]
This specific data set is relatively thin (50), and this "black hole" artifact only happens in 2 cases:
1) fast mode
2) low sampling rate multipliers.
In either case, this artifact is mitigated by applying a bigger sampling rate multiplier. 
I intend to reject this bug.

**Comment by sgpearse** [comment]
No longer applicable.
