### ISSUE TITLE
Eye inside volume glitches

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1358]
1. Create a volume
2. Move camera inside volume
3. Fiddle with camera

[Eye_Inside_Volume.vs3.zip](https://github.com/NCAR/VAPOR/files/2789095/Eye_Inside_Volume.vs3.zip)

![out](https://user-images.githubusercontent.com/2772687/51099676-6001be80-178f-11e9-8865-06cdb1abb63e.gif)

**Comment by shaomeng** [comment]
Could @StasJ clarify which data set should I load to use this session file?

**Comment by shaomeng** [comment]
Got the following image upon load data and session. Further rotation does not reveal the bug reported. Will need @StasJ to do a live demo. 

![screenshot from 2019-01-23 19-02-33](https://user-images.githubusercontent.com/814885/51649692-caaabb00-1f42-11e9-8b94-5c741899cfe7.png)
