### ISSUE TITLE
Control panel needs better resizing capabilities

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1359]
From @leigh.orf

See Leigh's "Orf Notes For Vapor Team" for context

So, I can't get that window to get any bigger. The "Data Set" text is pretty useless as you can see. I can drag the handle to the right of the smaller white box but that nukes the "New Delete Duplicate In:" buttons, and still doesn't display enough text in the Data Set region. Not sure what to suggest here, using the file name as the Data Set clearly is an issue with this configuration. Since this window tears off nicely, perhaps the easiest solution is to make it such that the window can get bigger than its current locked in horizontal geometry.

**Comment by clyne** [comment]
@sgpearse please see if you can find Leigh's notes

**Comment by sgpearse** [comment]
Leigh is referring to the renderer table, and how we name our data sets as their corresponding file-name.  The file-name is usually long, and gets clipped.  Expanding the left panel has been improved since this report, so we can display more text, but I don't think anybody wants to use Vapor with the control panel taking up half of the window.  

While this problem has a workaround, we might be able to do better by removing one of the columns in the renderer table.  Since all of the renderers are named after their type, ihe "Type" column is redundant, imo.

![Screen Shot 2021-01-14 at 8 32 25 AM](https://user-images.githubusercontent.com/9522770/104612105-13ce0b00-5643-11eb-832f-19caa883c76a.png)
