### ISSUE TITLE
Contour: spacing shows inf and cannot recover

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#136]
To reproduce:
1) Load Duku-3_0_0_alpha0.nc, create a contour renderer, enable it. 
2) In the Appearance subtab, set "count" to 1.
3) Uncheck the "Lock properties to TF bounds" checkbox.
4) Try to move the "Spacing" slider slightly.
5) "Spacing" field shows "inf", and later "Contour Minimum" field shows `nan`.
![screenshot from 2017-11-10 11-09-07](https://user-images.githubusercontent.com/814885/32672504-88b871d6-c608-11e7-9b63-73a034f575c7.png)

**Comment by clyne** [comment]
Works for me

**Comment by shaomeng** [comment]
It's not working on at least Linux. I've updated the procedures to reproduce, and attached a screenshot.

**Comment by shaomeng** [comment]
Since @sgpearse  is working on refining the isoline selector, it'd make more sense for Scott to look at this as well. So I'm re-assigning.
