### ISSUE TITLE
Disable Fast Mode

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1360]
@leigh.orf

Is it possible to *not* "degrade" the isosurface image when rotating or moving the cube? I understand why this is done, but it does get kind of annoying over time to see the image always snap back and forth between "beautiful" and "degraded". I suspect that many modern graphics cards will rotate the box w/out any degradation needed and get good performance. So maybe what I am requesting is an option (buried somewhere perhaps) that keeps the full rendering fidelity when doing box movement operations. At least it would be interesting to see whether performance is degraded on "normal" consumer hardware.

**Comment by shaomeng** [comment]
This is very simple to do once we decide that this is something we want to pursue.

**Comment by clyne** [comment]
@stasj please explain why you think this is not a good idea and tag @leigh.orf

**Comment by StasJ** [comment]
@leighorf The Volume and Isosurface renderers automatically determine the maximum possible resolution that your computer can render smoothly by dynamically monitoring the frame rate and adjusting the resolution. If you are seeing any degradation in image quality that means that your computer cannot handle a higher resolution. It would be possible to disable this feature but it would just result in choppy renderings when moving the scene which makes it difficult to navigate.
