### ISSUE TITLE
Contour renderer: catching every mouse movement on the widgets? 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#137]
Follow steps reported in bug #136, you can see the terminal window printing an empty line every time the mouse has a moment. 

It doesn't have obvious performance impacts, but is definitely a bug...

**Comment by clyne** [comment]
Remove print statement.

**Comment by shaomeng** [comment]
I no longer observe the empty line prints, thus I'm going to close this issue.
