### ISSUE TITLE
DKRZ-Ocean/gr15/gr15_uvw_vis.nc corrupt grid

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1373]
1. Import `DKRZ-Ocean/gr15/gr15_uvw_vis.nc`
2. Add a wireframe renderer

You will get the image below:

![screen shot 2019-01-24 at 10 01 53 pm](https://user-images.githubusercontent.com/2772687/51726256-b25e9d00-2023-11e9-989a-e57fd9da3415.png)

**Comment by clyne** [comment]
I'm closing this issue. The displayed rendering is correct. This is a complicated curvilinear grid that wraps around itself when projected into Cartesian coordinates. Attached is an image from a 2d version of the data now available in data/Source/DKRZ-Ocean/gr15. 

![MPL wireframe](https://user-images.githubusercontent.com/6777736/124041921-04f6cd00-d9c5-11eb-8354-909a571e5498.png)

Also attached is an image generated by Matplotlib that exhibits the same overlapping grid

![wireframe](https://user-images.githubusercontent.com/6777736/124041963-1dff7e00-d9c5-11eb-97f4-8002f7140518.png)

**Comment by sgpearse** [comment]
FYI - The full file path to the dataset is below.  I believe the data format is NetCDF-CF.  @stasj please specify if this is wrong.  I currently get an error on importing the data as described above.

/glade/p/cisl/vast/vapor/data/Source/DKRZ-Ocean/gr15/*

<img width="1599" alt="Screen Shot 2021-07-12 at 5 28 25 PM" src="https://user-images.githubusercontent.com/9522770/125368056-a7ed0680-e336-11eb-8b75-80f6aa90ec96.png">
