### ISSUE TITLE
Vapor's application window problem on Windows

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1378]
On Windows, displays that have greater than 1920x1080 resolution cause Vapor's control panel to condense to the left.   Undocking it helps, but there are other widgets (the fidelity controller) that are having trouble with scaling.

Observed on cisl-gadson.

![resolutionissue](https://user-images.githubusercontent.com/9522770/51756199-b15a5980-207d-11e9-8ea0-4c17d59a1f72.PNG)

**Comment by StasJ** [comment]
On cisl-gadsden, I still cannot access the right portion of the TF widget
