### ISSUE TITLE
Barb GUI Weird look and button

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1385]
![screenshot from 2019-01-25 16-29-23](https://user-images.githubusercontent.com/814885/51778414-c6a3a800-20be-11e9-9244-f0a731cb11b0.png)

Three comments regarding the Barb GUI. None is fatal, but they all help make VAPOR look less polished.
1. Three sliders have names `X Dimension`, `Y Dimension`, etc, but what it actually does is to control the number of barbs. It's poor naming. 
2. There are five sliders in this tab. The middle one has about twice height of the rest. I don't understand why. 
3. There's a button `Recalculate Scales` sitting there doing nothing...

**Comment by sgpearse** [comment]
No longer applicable.
