### ISSUE TITLE
TwoD renderer copy data from image renderer 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1394]
Copy region from an image renderer to a 2D renderer, the X dimension will be reset to the middle , resulting no rendering on screen, as the screenshot shows. 

![screenshot from 2019-01-25 17-30-17](https://user-images.githubusercontent.com/814885/51779855-23a35c00-20c7-11e9-942a-91e2403d66ad.png)

**Comment by sgpearse** [comment]
Duplicate of #1371, which we classified as medium last week.
