### ISSUE TITLE
Failed to capture TIFF

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1399]
To reproduce: 
1. Open VAPOR, import CF data: `/little_glade/shaomeng/nc-vapor3/cm1.nc`
2. Create a volume renderer, then choose Navigation->Viewpoint->Map Orthographic. Notice something is rendered at this point. 
3. Type a random string to the the "Data Projections" box. Notice VAPOR pops up an error window. 
4. Click Ok, notice the "Data Projections" box goes back to "Custom". Notice that VAPOR seems to be at a healthy state with the rendering able to be dragged around
5. Try to capture a TIFF image, another error message pops up, followed by failure to save this TIFF image. 

Note: I'm not sure the failure of save TIFF is because of the error in step 3, or the error in step 5, or TIFF exporter, or it's completely legitimate to not be able to capture the image. 

![peek 2019-01-25 23-17](https://user-images.githubusercontent.com/814885/51783533-806b3a80-20f8-11e9-9d73-fdf24ae3bb00.gif)

**Comment by sgpearse** [comment]
We should disable to Orthographic Projection option if there is no active projection string.

**Comment by shaomeng** [comment]
A summary of this bug: what renders on the screen is not able to be captured: while some image is displayed, attempting to capture it will result in an error message saying "Visualizer (Visualizer_No._0) failed to paint and thus not capturing image.
Failed to save image
Unsupported projection ""
------------------
Vapor 3.3.0.64fc00fe
OS: Linux 5.8.0-36-generic #40~20.04.1-Ubuntu SMP Wed Jan 6 10:15:55 UTC 2021
Distro:"

**Comment by shaomeng** [comment]
Confusing description. Closing.
