### ISSUE TITLE
Conflicting HDF5 library on Windows

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1418]
Issuing wrfvdccreate on a wrfout file on Windows leads to the following error on Windows:

![screen shot 2019-01-30 at 9 06 55 am](https://user-images.githubusercontent.com/9522770/51994790-be58bd80-246e-11e9-88cf-a2d87ab37736.png)
![screen shot 2019-01-30 at 9 07 09 am](https://user-images.githubusercontent.com/9522770/51994770-ba2ca000-246e-11e9-9c0b-b3a4144aed11.png)

**Comment by StasJ** [comment]
Works on cisl-gadsden

**Comment by StasJ** [comment]
I just logged onto cisl-augustine and importing and converting wrf worked fine.
