### ISSUE TITLE
isosurface: opacity control doesn't work with constant colored variable

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#1425]
The global opacity control and the opacity function in the TFE are both no-ops for isosurface if the surface is constant-colored.

1. load any data set with 3D variables
2. Enable the isosurface and selected an isovalue
3. Decrease the opacity. The image is unchanged

Note, if a variable is color mapped to the isosurface transparency works fine

**Comment by StasJ** [comment]
This applies to the wireframe and contour renderer too.
