### ISSUE TITLE
Wireframe rendering missing

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1428]
Summary: wireframe renderer will miss the rendering at some angles.

To reproduce: 
1. Open VAPOR with dataset checker: `./bin/vapor /little_glade/shaomeng/synthetic/checker.nc`
2. Create a wireframe renderer. Change variable to be "sphere".
3. Adjust TF so that there's no opacity at the very left end. 
4. Rotate the scene. Notice that the rendering is present sometimes, but not other times. 

![peek 2019-01-30 12-13](https://user-images.githubusercontent.com/814885/52006267-f240dc80-2488-11e9-89b1-079cc48669b6.gif)

**Comment by clyne** [comment]
@stasj I'm kicking this one over to you to look at. Disabling z-buffering seems to fix the problem (except then there is no depth buffering). Is it possible there is not enough z buffer precision?

**Comment by StasJ** [comment]
@clyne This is correct behavior. Our wireframe renderer does not support opacity. It is meant for viewing the grid, not for creating visualizations. The odd behavior you are seeing is caused by the render order orientation changing as you rotate. I will add a PR that disables the opacity editor.

**Comment by clyne** [comment]
Yes , of course. That makes complete sense. Thanks.
