### ISSUE TITLE
Windows IsoSurface does not work

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1437]
1. Open vapor and add an IsoSurface

If you use cell-traversal, it will partially render and then throw a paint failed error.
If you use fixed-step, nothing will render and vapor will show paint failed.

Tested on cisl-gadsden

**Comment by shaomeng** [comment]
Does a super small data set work on Windows? (see attached)
[sphere8.nc.zip](https://github.com/NCAR/VAPOR/files/2814851/sphere8.nc.zip)

**Comment by StasJ** [comment]
I was using 50x50x25

**Comment by shaomeng** [comment]
Update on Feb 4th: the reported behavior still exists even with a super small data set, i.e., sphere8.nc
