### ISSUE TITLE
Fixed step volume renderer gives paint error on Windows

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1447]
OS: Windows (high dpi loaner)

1. Open lee orf's tornado dataset
2. Add/enable a DVR (it will default to fixed step)
3. Rotate the scene a couple times

Eventually vapor will show a paint failed error

* This problem exists with an 8x8x8 sphere

**Comment by shaomeng** [comment]
Update: 
I feel this window machine has a GPU that's too weak... It shows very slow rotation on the 8x8x8 sphere (fixed step method) before it throws a paint error.
