### ISSUE TITLE
Image Renderer Corrupt:  Windows/Ubuntu + Intel Graphics

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1453]
The image renderer is corrupt with [this WRF file](https://drive.google.com/file/d/1z7nRpP44UB-mODHSKchtWW7FHRAIcIAq/view?usp=sharing) on Windows systems that use Intel graphics cards.  Windows with Nvidia cards are fine.

To reproduce:
1) Import the linked WRF file and create an image renderer.
2) Move the scene around.  The northern portion of the image is usually missing.  Sometimes the image renders.  Most of the time it is corrupt.

![windowsimagebug](https://user-images.githubusercontent.com/9522770/52354634-02f3d400-29ee-11e9-88b2-a8383f90bce1.gif)

**Comment by StasJ** [comment]
There is a similar issue on Ubuntu with Intel graphics that @winash12 has been experiencing.

![india_map](https://user-images.githubusercontent.com/2772687/55773955-4c918700-5a50-11e9-94be-190dca3d3a76.png)

**Comment by winash12** [comment]
@StasJ I get the identical behavior as @sgpearse when I move the image around. Parts of the image disappear and parts of the image do NOT render. Well here I thought I was using VAPOR incorrectly. Makes me feel better !

**Comment by winash12** [comment]
@clyne Do I get a new build to try ?

**Comment by StasJ** [comment]
@winash12 We are working out getting a release out soon (end of June at the latest) and will let you know as soon as it is ready. We think that we will be able to reproduce a system similar to yours and we will try our best to make sure everything works on your system before we release.

If you'd like, however, I can make you a installer of the current beta to try out sooner, just let me know.

**Comment by winash12** [comment]
@StasJ I would rather wait. I was preparing to do a switch of the graphics card from Intel to AMD. I am quite sure that is non trivial. But if the release makes me not want to do that i am prepared to wait.
