### ISSUE TITLE
Image Renderer: Ignore image transparency option broken

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1466]
Ignoring image transparency no longer works in the Image renderer.  See the screenshot below.  We should see the waters of the Gulf of Mexico.

![screen shot 2019-02-20 at 11 29 44 am](https://user-images.githubusercontent.com/9522770/53115251-f8176400-3502-11e9-8989-ea8491bc11ac.png)

**Comment by clyne** [comment]
The Natural Earth imagery does not contain ocean imagery. Try Blue Marble
