### ISSUE TITLE
Error when loading a python script

### ISSUE THREAD

**Issue by winash12** [NCAR/VAPOR#1473]
I am not sure where I should download the latest version of the VAPOR code base. When I download the release candidate from github I do not see a vapor binary in that.

So I am using the last build given to me by @StasJ .

In that here is the sequence of events to reproduce this bug-given a script by @sgpearse I opened a COSMO netCDF z file and then I went to tools and then opened Python variables and then clicked on "Open" in order to open an existing script that @sgpearse had sent me. When I do that I get this message 
 - An error has occurred. There are no scripts to open in this session.

**Comment by sgpearse** [comment]
@winash12 Try downloading the most recent version [here](https://www.vapor.ucar.edu/internal/downloads/vapor3).  (login required)

**Comment by winash12** [comment]
On Ubuntu 18.04 this version of VAPOR simply does not work. I install it and I try to open it and I get a dialog box that says 
"Vapor 3.1.0.RC0.01c9b53
OS: Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
Distro:
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch

-------------------
Failure to initialize Visualizer
-------------------
InitializeGL failure
OpenGL Version "3.0 Mesa 18.2.2" is too low and is not supported"

**Comment by winash12** [comment]
It looks like the changes @StasJ  made have not made it into RC0.

**Comment by winash12** [comment]
@StasJ Any update on this ? I am unable to use VAPOR at all.

**Comment by sgpearse** [comment]
Hi @winash12, we're currently looking into this.  Hopefully we will put out a full release soon.  We'll probably get you a pre-release installer when we think we have it fixed.

**Comment by winash12** [comment]
@StasJ This problem persists in the latest build. I am unable to load an existing Python script. 

Vapor 3.1.0.RC1.3d1f6ab
OS: Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019
Distro:
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch

-------------------
There are no scripts to open in this session
-------------------
GL Vendor String is MESA.
Graphics drivers may need to be reinstalled

**Comment by sgpearse** [comment]
Solution would be to rename "Open" to "Load from session" or something like that.
