### ISSUE TITLE
New opacity widget crash

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1503]
If you add any new opacity widget to a TF widget, vapor will crash. I did this by accident when simply trying to add a control point.

**Comment by StasJ** [comment]
Delete "New Widget" Option (verses new control point)

**Comment by sgpearse** [comment]
I cannot reproduce this :\

![Screen Shot 2019-05-13 at 9 30 14 AM](https://user-images.githubusercontent.com/9522770/57634128-ea053c80-7561-11e9-8123-cd6f32384798.png)

**Comment by shaomeng** [comment]
Now if you delete a widget after adding a few, it crashes.
