### ISSUE TITLE
Potential memory error

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1508]
**Describe the bug**
A potentially memory bug for object `fileDialog` at line 197. It might be double deleted. 

https://github.com/NCAR/VAPOR/blob/2bc9884cf88b84a2c3eb51cb41d8498dc27f4a38/apps/vaporgui/VaporWidgets.cpp#L195-L223

**Reasoning**
1. Object `fileDialog` was created on the stack, so this object is automatically destroyed by C++ at the end of the current function, at line 223.
2. Object `fileDialog` was created with a pointer to its parent, so it's added to the QT hierarchy tree. When VAPOR quits, all QWidgets on this hierarchy tree are deleted by QT. 
3. For the same object, step 1 and 2 each attempts a deletion. A double deletion thus occurs.

**Comment by sgpearse** [comment]
QFileDialog can be created on the stack and still receive a 'this' pointer to its parent.  It will destroy itself when it leaves scope, unregister itself as a child of its parent at this point.   However, if the parent is destroyed while the QFileDialog is on the stack, the parent will attempt to destroy the dialog.  The dialog will then try to free itself upon leaving scope, resulting in a double delete.  For this reason, we want to always allocate QFileDialogs on the Heap.
