### ISSUE TITLE
VFileSlector: more intelligent space and layout management 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1509]
**Describe the bug**
The current composite widget `VFileSelector` doesn't seem to be very intelligent in managing spaces/layouts. This is not ideal, since a key promise of these rebranded `VaporWidgets` is to manage layout/spaces intelligently. Without such capability, the benefit of `VaporWidgets` is in doubt. 

**To Reproduce**
1. Checkout a branch that makes use of `VFileSelector`. In this report I'd use `flow`.
2. Create a flow renderer.
3. Switch to `Seeding` tab, and select a file at the bottom.
4. Notice the layout of the `VFileSelector` in the screenshot. There's much white space between the label and the button, while not enough space to display the full name of the file in the text box.
5. A more intelligent layout manager would give enough space for the text box to display the full filename when there's still white space left. 

**Screenshots**
![Screenshot 2019-04-22 17 25 38](https://user-images.githubusercontent.com/814885/56539641-b7988e80-6523-11e9-879d-4cb01bedbcfe.png)

**Comment by clyne** [comment]
Related to #265
