### ISSUE TITLE
vapor: error while loading shared libraries: liblzma.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xigrug** [NCAR/VAPOR#1516]
vapor: error while loading shared libraries: **liblzma.so.5**: cannot open shared object file: No such file or directory

my system is Red Hat Enterprise Linux Server release 6.5 (Santiago)  2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

If VAPOR support the  Red Hat system?

**Comment by shaomeng** [comment]
Hi @xigrug , which version of VAPOR are you using? For VAPOR3 and VAPOR3.1, there are library out-of-date issues that prevented us from building an installer on Red Hat 6.5 .

**Comment by xigrug** [comment]
VAPOR is 3.0，so which verison is ok for this ? 


And I also have a question on CentOS for VAPOR3: When I import a wrfout, the vapor will breakdown with the problem：
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
kbuildsycoca4 running...
kdeinit4: kio_trash [kdeinit] trash local:/run/user/1006/ksocket-hysplit/klauncherT39994.slave-socket local:/run/user/1006/ksocket-hysplit/startkdeinitlockZ31418.slave-socket: symbol lookup error: /lib64/libQtNetwork.so.4: undefined symbol: _Z12qt_safe_pollP6pollfdiib
vapor: symbol lookup error: /lib64/libQtNetwork.so.4: undefined symbol: _Z12qt_safe_pollP6pollfdiib
kdeinit4: kio_file [kdeinit] file local:/run/user/1006/ksocket-hysplit/klauncherT39994.slave-socket local:/run/user/1006/ksocket-hysplit/startkdeinitlockt31418.slave-socket: symbol lookup error: /lib64/libQtNetwork.so.4: undefined symbol: _Z12qt_safe_pollP6pollfdiib




At 2019-05-08 14:42:23, "Samuel Li" <notifications@github.com> wrote:


Hi @xigrug , which version of VAPOR are you using? For VAPOR3 and VAPOR3.1, there are library out-of-date issues that prevented us from building an installer on Red Hat 6.5 .

**Comment by shaomeng** [comment]
Hi @xigrug , let's separate the VAPOR3 and VAPOR2.6 issues. 

VAPOR3 does *not* support CentOS6.5, so if it doesn't run, then you'll have to upgrade to CentOS7 or find another system. 

The Vapor2.6 issue sounds like a environment variable problem. Did you follow the instructions to set up your environment before invoking vaporgui?
