### ISSUE TITLE
Renderer Controls disappear with multiple visualizers

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1523]
**Describe the bug**
The controls of multiple visualizers (bottom left of VAPOR) would display with multiple visualizers. 

**To Reproduce**
1. Open VAPOR, load a data set, create another visualizer. 
2. Create a renderer in one of the two visualizers. 
2. Click on the second visualizer.
3. The renderer controls disappear for both visualizers. 

**Screenshots**

![May-12-2019 14-05-55](https://user-images.githubusercontent.com/814885/57587238-22a00a00-74bf-11e9-97e7-ee3d88b751fd.gif)

**Comment by sgpearse** [comment]
John fixed this bug with one of his own PR's.  

@clyne says:
"The fix I just merged for #1481 also fixes #1523. I think we can reject this PR and close 1523."



https://github.com/NCAR/VAPOR/pull/1536
