### ISSUE TITLE
VaporSubtabs fail to respond to user operations

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1528]
**Describe the bug**
Follow the steps below, and then VaporSubtabs reach a state where they refuse to respond to user interactions.

**To Reproduce**
1. Open VAPOR, load a data set, create a second visualizer.
2. Create an IsoSurface renderer in a visualizer, and a Slice Renderer in another visualizer.
3. Enable both renderers, switch between the visualizers back and forth a few times.
3. Go to the "Appearance" tab of the Slice renderer. Try to adjust the Max value below the TFWidget.
4. Notice that the slider and the text box are out of sync, and they refuse to honor the user selection. 

**Screenshots**
![May-13-2019 15-43-00](https://user-images.githubusercontent.com/814885/57656532-d7a4f600-7595-11e9-9c96-0c378348fbac.gif)

**Comment by sgpearse** [comment]
Might be fixed, need to verify before release.
