### ISSUE TITLE
Paint failure on Ubuntu

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1534]
User Winash12 has reported that he's getting paint failures on his Ubuntu 18.04 machine with intel graphics.  

Note: What I'm writing is a summary of issue #1195, which included multiple problems that I've broken into individual issues.  #1195 was submitted way back on Jan 5, so this problem may no longer persist.

Graphics info:
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630 (rev 04)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Venus LE / Tropo PRO-L [Radeon HD 8830M / R7 M465X] (rev 87)
So it it a Intel graphics card.

Steps to reproduce:
1) Load any dataset
2) Create a 2D renderer and enable it.

Error message:
Paint failed
Error performing paint event
No variable name specified
Undefined variable name : NULL
GL Vendor String is MESA.
Graphics drivers may need to be reinstalled

**Comment by sgpearse** [comment]
Update:

@winash12 tried working with an installer built off of master on 5/24/2019 @1:00pm (MST).  He is reporting that the volume renderer just hangs.  No error reports, just a frozen application :(

**Comment by clyne** [comment]
Duplicate. Closing. Better explained in #1679
