### ISSUE TITLE
Can't open MPAS data files with missing vertical dimension

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#1545]
### Describe the bug
vapor will generate an error message 

Missing required dimension "nVertLevels"

if an MPAS NetCDF file contains only 2D variables and does not contain the nVertLevels dimension.

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [x] Did you get wrong results?

**Impact**
- [x] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
Import the following MPAS files from data/Source/MPAS/FalkoJudt/7.5km:

diag.2016-08-01_00.00.00.nc
x1.static.nc

An error message will be generated

### Desktop
Vapor version 3.1

**Comment by sgpearse** [comment]
I'm currently failing to open the referenced dataset.

![Screen Shot 2019-06-04 at 10 25 06 AM](https://user-images.githubusercontent.com/9522770/58990717-cff6fc80-87a3-11e9-9cc8-ae1e996bda48.png)

**Comment by clyne** [comment]
@sgpearse are you opening the diag* file and the x1.static.nc file? Both are needed
