### ISSUE TITLE
MPAS data visualization corrupted 

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#1547]
### Describe the bug

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [x] Did you get wrong results?

**Impact**
- [x] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
1. Load the MPAS files on glade  in data/Source/MPAS/FalkoJudt/7.5km:

diag.2016-08-01_00.00.00.nc
x1.static.nc

2. Create a 2D data renderer and enable it with the "q2" variable. The attached image shows the result which is obviously wrong.

*Additionally, please attach a session file to this ticket to easily reproduce (use File->Save Session).*

### Attachments
![MPAS_Falko](https://user-images.githubusercontent.com/6777736/58134037-cc2f7b80-7be2-11e9-804e-7b286e13b4d6.png)

### Desktop
Version 3.1

**Comment by sgpearse** [comment]
I'm currently failing to open the referenced dataset.

![Screen Shot 2019-06-04 at 10 25 06 AM](https://user-images.githubusercontent.com/9522770/58990717-cff6fc80-87a3-11e9-9cc8-ae1e996bda48.png)

**Comment by clyne** [comment]
@sgpearse are you opening both the diag* file and the x1.static.nc file? The solution variables and grid info are stored in separate files.
