### ISSUE TITLE
VAssert implementation

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1570]
This feature request would be composed of two parts: 

1) implement a VAssert() function that acts just like CAssert() in both RELEASE and DEBUG mode. (@StasJ  will take on that. )
2) replace all existing assert() function calls with VAssert(). (@shaomeng  will take on that. )

**Comment by StasJ** [comment]
it is implemented on the vassert branch

**Comment by shaomeng** [comment]
@StasJ 
File `VAssert.cpp` fails to compile.

**Comment by shaomeng** [comment]
@StasJ 
I went ahead to fix the compilation error. 
Also, I've fixed a memory leak of `VAssert.cpp`. Feel free to take a look at it:
https://en.cppreference.com/w/c/experimental/dynamic/strdup

**Comment by StasJ** [comment]
@shaomeng Its not a memory leak. The program terminates immediately afterward which frees the memory. Also, you can free a const char*

**Comment by shaomeng** [comment]
@StasJ 
From `strdup` documentation:
` The returned pointer must be passed to free to avoid a memory leak. `
