### ISSUE TITLE
VAPOR Master fails to compile on CentOS7

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1581]
The following compilation error occurs on CentOS7 build system: cisl-garibaldi.

![Screenshot 2019-06-03 12 42 44](https://user-images.githubusercontent.com/814885/58826142-3c83c700-85fd-11e9-9266-5a90992122ee.png)

**Comment by clyne** [comment]
If we’re able to build installers on our build platforms I’d suggest we move ahead with testing and address this in the next round.

jc


> On Jun 3, 2019, at 12:44 PM, Samuel Li <notifications@github.com> wrote:
> 
> The following compilation error occurs on CentOS7 build system: cisl-garibaldi.
> 
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
John, let's wait 10 min. I fixed it on CentOS, and only need to test if it still works on other platforms.

**Comment by clyne** [comment]
ok

> On Jun 3, 2019, at 1:45 PM, Samuel Li <notifications@github.com> wrote:
> 
> John, let's wait 10 min. I fixed it on CentOS, and only need to test if it still works on other platforms.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu
