### ISSUE TITLE
Isosurface Renderer: Curvilinear ray caster

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1586]
I believe that the Curvilinear ray caster is giving incorrect results on a certain use case.

To reproduce:
1) Load the attached session file
2) Load /little_glade/data/VDC/vapor-3.0.0/WRF/DUKU/DUKU-3.0.0.nc from cisl-vapor
3) Enable the isosurface renderer, and compare its results when using the Regular and Curvilinear ray casters.

The gif below shows the Regular ray caster, and this looks correct.  Then Vapor is switched to the Curvilinear ray caster and the isosurface seems to change shape depending on the viewing angle.
 
![CurvVsRegular](https://user-images.githubusercontent.com/9522770/58834017-85447b80-860f-11e9-8fd8-993ddfa8d992.gif)

**Comment by clyne** [comment]
@sgpearse verify by not navigating while examining rendering
