### ISSUE TITLE
Contour: opacity isn't honored

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1597]
To Reproduce:
1. Open VAPOR, load VDC data: `/little_glade/data/VDC/vapor-3.1.0/CAM/AdamPhillips/F2000C5_new120_025/F2000C5_new120_025-3.1.0.nc`
2. Create a Contour renderer and enable it.
3. Attempt to adjust the opacity. Notice the adjustment isn't honored. 

![Peek 2019-06-03 16-10](https://user-images.githubusercontent.com/814885/58837996-77e0be80-861a-11e9-95e8-b4cae617928c.gif)

**Comment by sgpearse** [comment]
Does not exist.
