### ISSUE TITLE
Contour: line width adjustment isn't honored

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1598]
To Reproduce:
1. Open VAPOR, create a contour renderer. 
2. Enable it, and then attempt to adjust the line width.
3. Notice that line width does not change. 

![Peek 2019-06-03 16-20](https://user-images.githubusercontent.com/814885/58838374-c0e54280-861b-11e9-8a22-60d852739a5d.gif)

**Comment by sgpearse** [comment]
Related to #1368 and #1251
