### ISSUE TITLE
Plot Utility: No Plot Shown

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1609]
To Reproduce:
1. Open VAPOR, load data `/home/shaomeng/little_glade/Bipin/Part.nc`.
2. Open Plot Utility, go to Time Mode, Select time step 0 to 14.
3. Try to plot. Nothing shows. 

![Screenshot from 2019-06-03 17-47-22](https://user-images.githubusercontent.com/814885/58841636-11fb3380-8628-11e9-8776-ec350e25b5b6.png)

**Comment by shaomeng** [comment]
This might be related to #1588

**Comment by sgpearse** [comment]
Sam will look further into this.

**Comment by shaomeng** [comment]
Update: 
After re-converting VDC data a plot shows up. I'm closing this issue now.

![Screenshot from 2019-06-06 12-20-10](https://user-images.githubusercontent.com/814885/59056587-c62dd180-8855-11e9-8523-44a8539f8b03.png)
