### ISSUE TITLE
Statistics: Broken Undo

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1612]
On Windows 10, Undo does not work when the modal statistics window is active.

To reproduce:
1) Load any data, open statistics
2) Change a setting, and try to undo it.  Nothing happens.
3) Close the statistics window.  Issue an Undo command.
4) Open the statistics window, and the undo will be applied to the change that was made to the StatisticsParams.

**Comment by clyne** [comment]
undo/redo is not currently supported for Statistics.
