### ISSUE TITLE
Error thrown on volume enabled without 3D variable

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1619]
1. Open a 2D only dataset
2. Add/enable a volume renderer

We get the following error:
```
Error performing paint event
Failed to read variable "" at time step (0), and
refinement level (-1) and level-of-detail (0)
Invalid variable reference : 
```

We should have a cleaner error message or just grey out the option to select a 3D renderer if there are no 3D variables present.

**Comment by sgpearse** [comment]
Need to improve error message
