### ISSUE TITLE
Import ROMS Crash

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1620]
To reproduce:

1) Launch Vapor on Casper.  Import the a few files in /glade/p/cisl/vast/vapor/data/Source/ROMS/jsmall.  **DO NOT INCLUDE THE GRID FILE**
2) Vapor crashes

**Comment by clyne** [comment]
Kicking this back to @sgpearse. The code in AnnotationRenderer::_calculateDomainExtents assumes a data set will contain 2D or 3D variables. It may not.
