### ISSUE TITLE
Volume: missing rendering from the back

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1621]
Description: 
Volume rendering seems to be missing from the back of the data set.

System: cisl-vapor

Steps to reproduce:
1. Open VAPOR; import CF data: `CAM/FiniteVolume/cam_fv`
2. Create a volume renderer
3. Rotate the scene; the rendering disappears from the back of the volume.

![Peek 2019-06-04 11-41](https://user-images.githubusercontent.com/814885/58901733-fe4edc00-86be-11e9-8e12-37003d4509a4.gif)

**Comment by shaomeng** [comment]
Note: this behavior seems to affect IsoSurface renderer as well.

**Comment by StasJ** [comment]
This dataset has extremely shallow cells on the bottom. You cannot distinguish them with the wireframe renderer, even at the maximum zoom before you hit the near clipping plane:

![1](https://user-images.githubusercontent.com/2772687/58919361-0755a280-86eb-11e9-99c5-5e854a31f9e3.png)
![2](https://user-images.githubusercontent.com/2772687/58919365-0886cf80-86eb-11e9-9309-326ed70e4506.png)

**Comment by shaomeng** [comment]
Well, though it's not "missing" anymore, it isn't pleasant either: 

![back](https://user-images.githubusercontent.com/814885/60128259-70ab5d00-974f-11e9-8221-d434832c780d.png)
