### ISSUE TITLE
Python Editor: Delete button refuses to delete.

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1628]
To Reproduce:
1. Open VAPOR, load a data set, create a python script.
2. Edit the script with a few lines of python program, for example, what's shown in the screenshot.
3. Click `Delete` button to delete this script. 
4. The editor reports there's no scripts to delete. 

![Screenshot 2019-06-05 10 55 04](https://user-images.githubusercontent.com/814885/58974830-aaa4c700-8780-11e9-9aef-f4e90e6909ae.png)

**Comment by sgpearse** [comment]
Scripts need to be saved to the current session before they can be deleted.
