### ISSUE TITLE
Wireframe: No depth testing

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1632]
![out](https://user-images.githubusercontent.com/2772687/58977847-c65f9b80-8787-11e9-934e-d33770494ff6.gif)

**Comment by StasJ** [comment]
I am unsure whether we should enable depth testing. If we want to support opacity with the wireframe renderer, we would have to add sorting too. @clyne

**Comment by clyne** [comment]
Agreed. I’m inclined to say we should enable depth testing, and disable opacity. Thoughts, @stasj?

> On Jun 5, 2019, at 8:22 PM, StasJ <notifications@github.com> wrote:
> 
> I am unsure whether we should enable depth testing. If we want to support opacity with the wireframe renderer, we would have to add sorting too. @clyne
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by StasJ** [comment]
Sounds good. I've created a branch, `issue1632`, that has depth testing enabled for the wireframe renderer. I'll work with @sgpearse to disable opacity in the GUI.
