### ISSUE TITLE
Break visualizer and GUI update trigger

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1635]
OS: Linux

1. Open a dataset and add/enable a renderer
2. Start dragging an opacity control point
3. While still dragging, right click inside the MappingFrame
4. Click elsewhere (inside the MF works) to dismiss the popup

Changing parameters in the GUI will no longer trigger an update (i.e. the visualizer will not redraw and other elements in the GUI, except for the one manually changed by the user, will not update)

**Comment by shaomeng** [comment]
This might be related to issue #1592
