### ISSUE TITLE
Histogram calculation suspeciously fast

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1646]
Summary
The cyan histogram calculation is suspiciously fast. That is, it calculates **instantaneously** on a `1024^3` grid. It could be either of these 2 cases, and in each case, we better patch VAPOR.
- It uses a method that **does** calculate super fast. 
    - In this case, we should remove the "Update Histogram" button. 
- It does the calculation wrong. 
  - In this case, we should fix it. 

To reproduce: 
1. Load VDC data: `/little_glade/shaomeng/vorticity/wx.vdc` (`/glade/p/cisl/vast/vapor/Bugs/vorticity/wx.vdc`)
2. Create a volume renderer. 
3. By default it's at the resolution of 32^3. Click "Update Histogram" to make it cyan.
4. Change the resolution to 1024^3. Go to "Appearance Tab". Notice the histogram is in gray color. 
3. Change min and max sliders to min and max positions. Notice the histogram is still in gray color. 
4. Click "Update Histogram" button. Notice the histogram turns Cyan instantaneously. This is suspiciously fast.

**Comment by clyne** [comment]
@shaomeng please verify that a bug does indeed exist.

**Comment by shaomeng** [comment]
Re-phrased in issue #1670
