### ISSUE TITLE
DVR seems missing corners 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1667]
Using the VDC data at: `/glade/p/cisl/vast/vapor/Bugs/spheres/sphere128.nc`, a DVR seems missing corners as the animation shows.

To Reproduce:
1. Open VDC data mentioned above; create a DVR.
2. Adjust opacity, and then rotate the scene. Notice the missing corner.

Platform: MacOS. 
Code: master branch on 6/11: c6ed00d28b09dc3fcb11e750c74dc9668b3493e1
Compile: Debug Mode.

![Jun-11-2019 14-11-35](https://user-images.githubusercontent.com/814885/59303583-bfd39700-8c53-11e9-98bb-fd5084117e78.gif)

**Comment by StasJ** [comment]
Same as #1658
