### ISSUE TITLE
Dataset transformation GUI location is unintuative

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1694]
Users have trouble finding the dataset scale GUI since it is located under `Navigation` -> `Viewport`, neither of which have anything to do with the dataset transformations (they do from our perspective, but not from the users')

**Comment by clyne** [comment]
Need discussion

**Comment by clyne** [comment]
We will revisit in context of providing a separate "Data" tab that would provide metadata information about each data set. E.g. list of variables, number of time steps, variable attributes, etc.

**Comment by sgpearse** [comment]
Fixed with #3395.
