### ISSUE TITLE
Naviage and Navigation do completely different things and are right next to eachother

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1695]
Throughout the tutorial we often directed users to click on the `Navigation` tab. In most cases users ended up clicking the `Navigate` dropdown which is right next to it.

![2](https://user-images.githubusercontent.com/2772687/59572829-f272fa80-906c-11e9-90fa-f2d2e62d7e23.png)

**Comment by clyne** [comment]
Consider whether top Navgiate/Region selector button is needed.
