### ISSUE TITLE
Items under the Navigation tab generally don't relate to navigation

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1696]
- `Annotation` tab: nothing to do with navigation
- `Animation` tab: you could argue that you are navigating through timesteps but I don't think that is intuitive
- `Viewpoint` tab: 2 items in here relate to navigation. The other two relate to dataset parameters.

**Comment by clyne** [comment]
Need discussion

**Comment by clyne** [comment]
Change "navigation" tab name to "Scene"
