### ISSUE TITLE
Variable default range is based on its first timestep, even if it is uninitialized

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1705]
1. Open Scott's WRF tutorial dataset (will be copied to Bugs directory when I have a better connection)
1. Set timestep to 5
1. Add a volume renderer
1. Select variable `QCLOUD`
1. Enable the renderer

The variable is uninitialized at the first timestep. The default data range will be 0 -> 0. This caused a decent amount of confusion at the WRF tutorial.

**Comment by sgpearse** [comment]
I could still reproduce this bug using [this dataset](https://drive.google.com/drive/folders/1pWJdze4J0wgLBbSKTxfNHveMa2M0Hnw_?usp=sharing).

**Comment by StasJ** [comment]
> I could still reproduce this bug using [this dataset](https://drive.google.com/drive/folders/1pWJdze4J0wgLBbSKTxfNHveMa2M0Hnw_?usp=sharing).

@sgpearse The first timestep in the dataset you linked is initialized.
