### ISSUE TITLE
WRF dataset causes crash

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1710]
Import `little_glade/bugs/1710/wrf3hr_d02_2016-04-01_00.00.00`

Vapor will crash with a bad memory exception

There are 2 datasets in there. The user tried to import both at the same time which does not crash but instead shows an error stating invalid timestep.

There is also an email in that directory. The user asked to email them if we happen to fix this issue

**Comment by clyne** [comment]
The crash has been fixed, but you still can't open both data sets.
