### ISSUE TITLE
Lack of support for high DPI Linux machine

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1732]
VAPOR has fonts that are too small for a high DPI linux machine, see screenshot. 

This issue probably sits in between of a bug and a usability issue. 

![Screenshot from 2019-06-21 16-00-05](https://user-images.githubusercontent.com/814885/59953761-c970b200-943e-11e9-8d04-390323810b84.png)

**Comment by clyne** [comment]
@sgpearse Isn't this fixed with Qt5? If so we can close this ticket.

**Comment by clyne** [comment]
@shaomeng please verify and close if fixed.

**Comment by shaomeng** [comment]
The original reported issue is that VAPOR displays fonts much smaller than the rest of the applications. As of 1/12/2021, this issue is no longer there.
