### ISSUE TITLE
Using VAPOR with Windows ]

### ISSUE THREAD

**Issue by rahulagrawal29** [NCAR/VAPOR#1734]
Hello all

I am new to VAPOR and hence my question might be naive, but I would like to know : 

Due to space constraints on my ubuntu, I've installed VAPOR ( source installation: .msi file ) on my windows. From my simulations, I have .viz files, as vizualisation files. I think I would need to convert them to vdf files for using VAPOR, since the Windows VAPOR GUI doesn't seem to have script based conversion of .viz files to .vdf.
Does anyone here, know how to do this within Windows using the VAPOR GUI itself or will I have to do it using Ubuntu  (install VAPOR in ubuntu) or Windows command prompt

Thanks
Rahul Agrawal

**Comment by sgpearse** [comment]
Hi Raul,

We only support WRF-ARW, NetCDF data that follows the CF conventions, and raw binary data for conversion to VDC.  I'm not sure what .viz files are, but you'll need to convert the file into one of those three categories to produce VDC.
