### ISSUE TITLE
Potential excessive GPU memory use by DVR

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1736]
Summary: 
I found the GPU memory usage by DVR is unexplainably high. This might become a problem with the combination of large data set + smaller GPU memory cards, or DVR+IsoSurface combo, or multiple users sharing a GPU card (cislv-vapor).

To reproduce: 
1. Open VAPOR, load CF data: `/glade/p/cisl/vast/vapor/Bugs/cm1.nc`
2. Create a volume renderer, and enable it.
3. Notice that the variable dimension is `500x410x380`. That's 311.6MB in floating point values.
3. Use `nvidia-smi` to see the GPU memory usage by VAPOR. It's 1709MB. That's 5.48X of the grid size. 

![Screenshot 2019-06-24 14 58 23](https://user-images.githubusercontent.com/814885/60051936-5d39bc80-9691-11e9-80dd-467ee7df1152.png)

**Comment by StasJ** [comment]
```
Scalar data: 500x410x380*FLOAT32 = 297 MB
Missing mask: 500x410x380*BYTE_MASK = 74 MB
Coord data: 500x410x380*FLOAT32*3 = 891 MB
Acceleration tree: ~40MB

Total: 1302 MB
```
