### ISSUE TITLE
Hurricane Sandy compare failed

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1749]
This appears to be a regression

To reproduce:
1. Add vapor to your path
1. `cd /little_glade/data`
1. `./convert.sh --force compare HurricaneSandy`

The commands used and the log can be found in the output folder/status

`/little_glade/data/VDC/vapor-3.1.0/WRF/HurricaneSandy/status`

**Comment by StasJ** [comment]
When you run the comparison, the shell prints process killed rather than a crash?

**Comment by clyne** [comment]
This works on Casper. I suspect cisl-vapor doesn't have enough memory and the process is being killed by the OS. The memory requirements are around 32GB.
