### ISSUE TITLE
Curvilinear Raycaster crashes on AMD (Mesa drivers) + Ubuntu

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1750]
To reproduce:

1) On CISL-VAPOR2, start up vapor, import the WRF files in ~/Downloads/wrfout*
2) Create a volume renderer and enable it

**Comment by StasJ** [comment]
In this case the Mesa drivers are being used (I updated the title). I managed to get the curvilinear renderer to work with Mesa drivers albeit with some graphical glitches that are only visible at lower grid resolutions.
