### ISSUE TITLE
Remaining documentation website comments

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1790]
## Ancillary Tools
- missing period

### Python Engine (replacement)
The Python Engine allows users to derive new variables from existing data. The UI allows for selecting input variables (to be used in the calculation), the output variables to be derived, and an area for editing the python code that does the conversion. Upon successful completion, the derived variables are accessible throughout the rest of Vapor.

- Also, we may want to mention how to use the python editor. For example the fact that numpy needs to be imported as in the photo.

### Statistics
- "is adjustable" -> "are adjustable"

## Other
- Should we mention citations in the Quick Start Guide?

**Comment by sgpearse** [comment]
The Python documentation is very coarse.  There's a lot that needs to be fleshed out, particularly documnting vapor_utils.

For citations, we have a section for it at the bottom of the table-of-contents.  I don't think we need to include in in the quick-start guide.
