### ISSUE TITLE
Can't apply transforms to multiple data sets

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#18]
When multiple data sets are loaded into vaporgui transforms (e.g. translation) can only be applied to one of them.

To reproduce

1. Load the wrf data set in Data/CoupledWrfRoms
2. Load the ROMS data set in Data/CoupledWrfRoms
3. Go to the Navigation/Viewpoint tab. The transforms have two rows (one for each data set), but one of the rows is empty.

**Comment by StasJ** [comment]
<img width="857" alt="screenshot" src="https://user-images.githubusercontent.com/2772687/32412145-313c63fc-c1b4-11e7-93a0-79f9119f094f.png">

**Comment by clyne** [comment]
This is still a bug. However, note the following: if no renderers are created the transform table is empty. Once any renderer is created for a data set the transform table is populated for that data set. I'm lowering the priority and re-opening

**Comment by StasJ** [comment]
I tested this with the datasets you specified:

<img width="1159" alt="screen shot 2017-11-23 at 2 24 50 am" src="https://user-images.githubusercontent.com/2772687/33162091-9ef90e1e-cff5-11e7-918f-1d20fbddaf75.png">
