### ISSUE TITLE
Change license to apache 

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#1800]
Documentation/License

We need to change our open source license to Apache (2.0?)

**Comment by sgpearse** [comment]
Do we need to consult with NCAR's legal team for the correct wording?

**Comment by clyne** [comment]
It’s one of the blessed licenses and they’re using an unmodified version. So, no.

> On Jul 24, 2019, at 3:47 PM, sgpearse <notifications@github.com> wrote:
> 
> Do we need to consult with NCAR's legal team for the correct wording?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by clyne** [comment]
We need to figure out how to handle other components of the package that may have different licenses. Do we simply note them on the main license page for VAPOR, etc?

**Comment by sgpearse** [comment]
Awaiting more information from legal.

From Michael Anderson:
_We do need to identify the components that are subject to a different license than Apache.  I'm not sure that it matters where we do so, just so long as it is obvious to the user.  Make sense?_

**Comment by sgpearse** [comment]
Michael Anderson has informed us that we do need to list all licenses for our libraries so that the average user is put on notice about them.  This will require some digging.
