### ISSUE TITLE
Python Crash

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1806]
1) Import the NetCDF-CF file linked below
2) Create a new Python variable named speed, and check the three 3D variables vx, vy, and vz
3) Leave the script field blank (or enter anything, it doesn't matter) and click "Test"
4) Vapor will crash due to not being able to find a time coordinate variable

Data: https://drive.google.com/open?id=1bxftiSGwyRFYsQazu4mACDHlhYvLGS-u

Note we can render without a time coordinate variable, but we crash in python.

**Comment by clyne** [comment]
The test data set for this has been added to /glade/p/cisl/vast/vapor/Bugs/1806
