### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1811]
![Screenshot 2019-07-30 16 42 49](https://user-images.githubusercontent.com/814885/62170590-263a7480-b2e9-11e9-9427-dd94434056fc.png)

**Comment by sgpearse** [comment]
This is a problem with the theme (Koru).  It's outside of our purview.  I'll submit a ticket to the repository, linked below:

https://github.com/NCAR/koru-jekyll
