### ISSUE TITLE
Update 3rd party libraries

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#1820]
The third party libraries should all be updated (when possible). In particular, python, Qt, and NetCDF are out of date

**Comment by shaomeng** [comment]
And HDF5.

**Comment by clyne** [comment]
We should probably abandon the old glade installation path and see if we can come up with something that makes more sense. E.g.: 

/usr/local/vapor-libs

**Comment by sgpearse** [comment]
Mac/Linux:
/usr/local/vapor/2019

**Comment by shaomeng** [comment]
Note on Assimp: since loading 3D objects isn't on the to-do list of release 3.2, it's not included in the 2019-Aug build.

**Comment by shaomeng** [comment]
Note on `FTGL`: vapor3.2 calls freetype directly, so no need to build FTGL anymore.

**Comment by clyne** [comment]
Sam, I’d suggest including Assimp so that we don’t have to change the library collection when we do add Model rendering. Also, model rendering was something we had listed as a “might do” for 3.2.



> On Aug 14, 2019, at 3:14 PM, Samuel Li <notifications@github.com> wrote:
> 
> Note on Assimp: since loading 3D objects isn't on the to-do list of release 3.2, it's not included in the 2019-Aug build.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
Note on `jpeg`: it was used to build `tiff`, but currently `tiff` seems to have jpeg enabled even without our build of jpeg, so no need to build jpeg anymore.

**Comment by shaomeng** [comment]
Note on `SQLite`: this is a new dependency, since it's required by `proj`.

**Comment by shaomeng** [comment]
Note on `Grib-api`: we don't include it for this round. If in the future we decide to use it, we can add it back.

**Comment by sgpearse** [comment]
Good call.  Looks like the GRIP API has been discontinued.  They've moved on to a product called ecCodes.

https://confluence.ecmwf.int/display/GRIB/Home
