### ISSUE TITLE
Refactor the Transfer Function (TF) editor

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#1824]
The Transfer Function is buggy and needs to be refactored.

**Comment by clyne** [comment]
Comments from 8/29 GUI design review:

Missing features:

1. logarithmic scaling of opacity function
2. Ability to change data range bounds via the mouse (in addition to current range slider)
3. Save and Load maps to a file
4. Iso value selector for use with isosurface and contour line renderer
5. Ability to support two variables (e.g coloring an isosurface with a second variable)
6. May need "update histo" button depending on performance with high resolution (e.g. >= 1024^3), time-varying data.

Changes:
1. Add ability to add/delete color and opacity knots using the right mouse button to be consistent with old design
2. Make color and opacity knots easier to see when selected
3. Superimpose the opacity curve over the histogram
4. Change the single-line combination of data value and opacity/color selector to use two separate lines: one line for selecting data value, one for color/opacity

**Comment by jvalan** [comment]
I second this change.

**Comment by clyne** [comment]
Ask and ye shall receive. We just completed refactoring of the TF editor :-). I think it’s pretty slick. We might be able to get you an installer with the new capability. Would you be interested in evaluating?

**Comment by jvalan** [comment]
Yes I would be interested, that would be extremely useful.

**Comment by StasJ** [comment]
What OS would you like an installer for?

**Comment by jvalan** [comment]
I am currently running on RedHat Linux.

**Comment by StasJ** [comment]
@jvalan I've built an installer for you. Send us your feedback and let us know if you have any questions.

https://drive.google.com/a/ucar.edu/file/d/1PpXZWcgjqDIXA0V16hRx1BF0DpAUdRI_/view?usp=sharing

**Comment by jvalan** [comment]
Nice! This is a huge help for me, although I may have encountered a bug in the new version. When saving transfer function maps, the file extension .tf3 is supposed to be automatically added to the the saved file. For me, the file gets saved without an extension, and I have to manually add it in afterwards.

**Comment by StasJ** [comment]
@jvalan Thanks for letting us know. We are aware of this; It is a bug in the GUI library we are using and if the library does not fix it, then we will fix it ourselves before the next release.
