### ISSUE TITLE
Isosurface "Color Mapped Variable" tab not available after opening session

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1825]
1. Create an IsoSurface Renderer
2. Disable `Use constant color`
3. Save a session

Note that the `Color Mapped Variable` tab above the TF editor is not greyed out

4. Restart vapor
5. Open the session file

The `Color Mapped Variable` tab above the TF editor is now greyed out
Need to re-enable and re-disable `Use constant color` to fix

**Comment by sgpearse** [comment]
I think this is related to #1733 which was mediated by PR #1753.

**Comment by clyne** [comment]
`Use constant color` no longer exists
