### ISSUE TITLE
Curvilinear Volume Renderer Broken

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1830]
To reproduce:

1) Spin up a session on Casper
2) Import the NetCDF-CF file: 

/glade/collections/cmip/CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Amon/ua/gn/v20190306/ua/ua_Amon_CanESM5_historical_r1i1p1f1_gn_185001-201412.nc

3) Create a volume renderer and enable it.

Note that the histogram registers no values.  If you change the renderer to operate on a regular grid, it does work.
![Screen Shot 2019-08-09 at 3 53 07 PM](https://user-images.githubusercontent.com/9522770/62811133-ccdafe00-babd-11e9-8c6f-45542c39c599.png)

**Comment by StasJ** [comment]
I can confirm this is an issue, however I do not think it is a problem with the volume renderer (My guess, based on the visual artifacts, is that the volume renderer does not work because the grid winding order is incorrect).

It appears that there is something wrong with this dataset (winding order?). As you mentioned, the histogram shows no data, even in the boolean setting. There is no 2D data and none of the 3D renderers work (I tested Wireframe, Slice, and Barbs).

@clyne could you take a look at this to confirm? Also, the issue is unrelated to Casper, so you can test on your Mac.

**Comment by clyne** [comment]
@stasj I'm sending this back to you. There was a problem in the StretchedGrid class: it wasn't handling coordinates that were monotonically *decreasing*. The Z coordinate in this data set is decreasing. I've fixed the issue in StretchedGrid, which also fixes issue #1356, but the curvilinear grid volume renderer is still not working; now it drawing nothing at all. My commits are pushed to the branch issue_1830

**Comment by StasJ** [comment]
@clyne Yes, your commits fixed the data mgr issue however the grid still has a winding order (counter clockwise) different from every other dataset (clockwise) so the ray intersection thinks it is hitting the back face. I attached a screenshot below showing that the ray tracer is intersecting with the back faces believing they are the front faces. 

![scrot](https://user-images.githubusercontent.com/2772687/69465641-e76c7680-0d3e-11ea-8d00-41900efd5696.png)

If I swap the winding order to counter clockwise, the front faces are as expected and the renderer works correctly:

![scrot 2](https://user-images.githubusercontent.com/2772687/69466958-58159200-0d43-11ea-9e3e-a2817226ec3d.png)

![scrot 3](https://user-images.githubusercontent.com/2772687/69466962-5a77ec00-0d43-11ea-9bc6-33ee35c9a691.png)

So we either have to determine the grid cell face winding order for every grid or remove the distinction of front vs back for cell faces. My algorithm initially required knowing the cell face normals however I made some some unrelated changes previously after which it shouldn't be required anymore. I tested a few datasets and it works as expected.

**Comment by StasJ** [comment]
One thing to clarify is that I understand that the cell faces in a structured grid don’t have a winding order. In every other data set that I have encountered there is a consistent layout of the cell vertices which allows me to assume an outside/inside face. With the z axis flipped, this implicit order is swapped.

**Comment by clyne** [comment]
I've added a method to the Grid class, HasCCW, which returns true if the cell face winding order is counter clockwise. This is the default. For this data set the returned value is false. Please see if you can make the needed changes to the volume renderer to flip the normal sign appropriately. Thanks.

**Comment by StasJ** [comment]
I updated the curvilinear renderer to use HasCCW however HasCCW is missing documentation.

**Comment by StasJ** [comment]
Or a more descriptive name such as `HasInvertedCoordinateSystemHandiness`
