### ISSUE TITLE
Flow: Unsteady Flow Crash

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1847]
On OSX, I experience a crash with the following sequence:

Dataset: DUKU
/glade/p/cisl/vast/vapor/data/VDC/vapor-3.0.0/WRF/DUKU/DUKU-3.0.0.nc

1) Create a Flow Renderer
2) Go to timestep 3
3) Enable unsteady flow
4) apply the Uniform/Non-Random rake
5) Change the Z dimensionality of the uniform rake

**Comment by shaomeng** [comment]
Note on 9/10/2019:
This crash seems to be related to the crash that's reported in #1848 . Will investigate later.
