### ISSUE TITLE
Need custom QDoubleValidator

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1855]
The Qt QDoubleValidator is buggy and has a broken interface.

If you set `textbox->setText(QString::fromNumber(x))` where the number of decimals of `x` is greater than the validator decimals, it breaks the validator.

If you call `validator->setRange(a, b)` this resets the number of decimals to zero, `validator->setRange(a, b, validator->decimals())` needs to be called which is confusing and easily missed.

**Comment by clyne** [comment]
@StasJ still relevant?

**Comment by StasJ** [comment]
> @StasJ still relevant?

I guess since all instances where we use this will be wrapped in a Vapor line edit it is not necessary.
