### ISSUE TITLE
Undo/Redo: Crash in OpacityMap::GetDataBounds

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#187]
In all renderers, issuing an undo after modifying the transfer function will crash the application.

To reproduce:
1) Load KatrinaMaster.nc and create a TwoDData renderer
2) Enable it, and modify its transfer function in the Appearance tab
3) Issue an undo command, and Vapor will crash

**Comment by StasJ** [comment]
The vtable for OpacityMap get corrupted upon undo.

**Comment by StasJ** [comment]
Crash only occurs on OSX. Does not crash on Linux.

**Comment by clyne** [comment]
I'm re-assigning this to me. The MappingFrame does not follow the design pattern for users of ParamsBase classes and needs significant changes :-(

**Comment by clyne** [comment]
Fixed
