### ISSUE TITLE
TFWidget: Colorpicker changes pointer to hand permanently

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1871]
To reproduce:
1) With any dataset, select a color control point in the TFWidget
2) Click on the color-box to edit the color control point
3) While the color selection dialog is present, click on the color-box in the TFWidget a second time
4) Click cancel on the color dialog
5) The cursor will be stuck as a hand

**Comment by StasJ** [comment]
Fixed in e853d4d3
