### ISSUE TITLE
TFWidget: Isosurface control point has the wrong data value when out of bounds

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1873]
Editing the isosurface bounds has strange behavior on isovalues that are outside of the transfer function.

To reproduce:

1) Reduce the transfer function data range.
2) Create an isosurface and drag the range so that the isovalue is outside the edge.  The isovalue will then change to be equal to the edge value.
3) Move the range back so the original isovalue is within the range, and the old isovalue will be restored.

I do not believe we want the data range to affect isovalue selections that the users have previously made.

**Comment by StasJ** [comment]
This is intended. The iso value is red to show that it is out of bounds but it is clipped to the edge so you can still select it.
