### ISSUE TITLE
TFWidget: Save/Load .tf3 files

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1875]
2 problems:

1) Saving a transfer function does not add .vs3 as the file extension.

2) When trying to load transfer functions, the dialog is for selecting directories, not files.

**Comment by StasJ** [comment]
1. This is a bug in Qt. Let's see if Qt5 fixes it.
2. I can't reproduce this. Also the code uses `getOpenFileName` so it shouldn't be possible to select a directory.
