### ISSUE TITLE
Flow crashes with Windmill dataset

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1879]
1. Open the Windmill dataset
2. Create a flow renderer
3. Enable the renderer

Vapor will crash

**Comment by shaomeng** [comment]
Stas, can you specify where the Windmill data is in this bug description?

**Comment by StasJ** [comment]
cisl-vapor/data/Source/Windmill

**Comment by shaomeng** [comment]
This is fixed with PR #1885 .

**Comment by StasJ** [comment]
Vapor doesn't crash but nothing happens and there is no warning/error

**Comment by shaomeng** [comment]
This data set has a single variable. The software should default to integrate along a single dimension

**Comment by shaomeng** [comment]
As of 01/09/2020, VAPOR doesn't crash, but remind the user to have at least 2 variables.
 
![windmill](https://user-images.githubusercontent.com/814885/71881176-0e181e00-30ef-11ea-98af-0271e2070f17.png)
