### ISSUE TITLE
No error message when a session's dataset is not found

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1888]
1. Import a NetCDF dataset and save a session
2. Close Vapor
3. Move/rename the dataset
4. Open vapor and open the session

Nothing will happen and no error will be reported.

**Comment by clyne** [comment]
I'm not sure I agree that this is a bug. It should be possible to use different data sets with a session than the one that the session file was saved with. Users may want to, for example, mail a session file to a colleague to us with their data, which may have a different path.

**Comment by StasJ** [comment]
When I first made this bug report I thought the behavior you describe was not working (i.e. if the user opened a session without finding the data the session would not load at all, even if they then import the data) but I was mistaken.

However I think we should still inform the user something along the lines of "This session links to the dataset "..." which was not found. Please open this dataset if it is in a different location". We can make that a feature request.
