### ISSUE TITLE
Renderer image list issues

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#1889]
In the Renderers tab on Linux, when the user has multiple different models located, every time a different render is selected, the list automatically jumps back to the top of the list. Say that I scroll down the list, and I want to enable the ninth and tenth item. I scroll down and I check the two boxes for 9 and 10. Unfortunately because of this bug, I will select number 9, then my second click will register as having selected number "2" back at the top, as the list jumped back to the top, but didn't visually update until moments after I clicked. Clicking anything within this window causes it to jump back to the beginning.

Additionally the numerical order of items in the renderer tab is ordered as 0, 1, 10, 11, 12.... 2, 3, 4, 5, 6, 7, 8, 9, as opposed to 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12..... Vapor defaults to "volume_1" as opposed to volume_01, which would be a minor fix so long as no one tries to load in over 99 renders.

Overall, I would say that these issues greatly impede productivity over time, but only in situations in which multiple rendered datasets are used in conjunction with one another.

To Reproduce this behaviour,
Load up enough volume renders of different datasets to fill up the tab, requiring the scrollbar to be used. Try clicking on and selecting the renders at the bottom of the list after scrolling down.

 - OS and version: Redhat Linux Enterprise version 7
 - Version: Vapor 3.1 and Alpha 3.2

**Comment by clyne** [comment]
I've noticed this on Linux platforms to and it is annoying. Hopefully it behaves better in Qt5, which we should be able to learn pretty soon as the migration work to Qt5 is wrapping up

**Comment by StasJ** [comment]
@clyne In this case the renderer table is deleted and recreated every time an Update is triggered so  Qt5 will not fix the problem.
