### ISSUE TITLE
Ideas on how to automate.

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#1890]
The project that I'm working on goes as follows:
Through linux and a stitched together frankenstien of a bunch of programs I am attempting to make a program/program sequence that will enable meteorologists to easily and painlessly receive 3d models of hurricane storms that are up to date in real time, so they can press a button, and see an animated 3d model in less than fifteen minutes and give their forecast without having to learn how to navigate a 3d space.

Currently I have a program that automatically retrieves storm data and compiles it into formats which VAPOR can read. Now the next step is how do I control VAPOR externally without having to use a mouse or select items. How can I make a loop that loads all of my netcdf files into VAPOR, rotates the renderer, pulls up my presets, and exports images? I was told that there is a form of automation coming to VAPOR, but that is a ways away. So I would like anyone's input on how I can control VAPOR in this manner.

**Comment by clyne** [comment]
We've opened an enhancement request #1894 to provide a scripting interface for VAPOR. Once version 3.2 is released (later this year we hope) VAPOR3 will be more or less feature complete with VAPOR2, and it will be time for the development team to take a step back and think about future enhancements such as this. It would be great to have input from the community to help assess priorities.
