### ISSUE TITLE
Linux installer: allow users select where to install

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#19]
The current behavior is to install wherever the installer is located.
It'd be desirable to allow users input a path to install.

**Comment by StasJ** [comment]
--prefix=dir

Aside: The linux installer is a self extracting tar file. The expected behavior of tar files is to extract into the current directory

**Comment by shaomeng** [comment]
Thanks Stas.

Could you put this information in the prompt after executing the installer, so other users don't have the same confusion?

**Comment by StasJ** [comment]
Technically yes, but not though CMake. It would need to be done manually after the installer is generated. If they run the installer with -h,--help it will print out that option.If it is really necessary I could add a script that does this.
          
            
            On Oct 13 2017, at 5:03 pm, Samuel Li <notifications@github.com> wrote:
            
            
              Thanks Stas.
Could you put this information in the prompt after executing the installer, so other users don't have the same confusion?
