### ISSUE TITLE
Flow renderer crashes upon creation

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1907]
1. Open `/glade/scratch/stasj/OKC_AuxScalar_0.vdc`
1. Create a Flow renderer

Vapor will crash. Tested on OSX

**Comment by shaomeng** [comment]
This crash is cause by certain variables not present in the data folder. Do we have a convention on how to handle this situation? @StasJ @clyne @sgpearse

**Comment by clyne** [comment]
Waiting on #1971

**Comment by shaomeng** [comment]
I hope the issue submitter could follow our convention to put the data set in question in the appropriate directory. 
For this particular data, it's been linked to: `/glade/p/cisl/vast/vapor/Bugs/1907`

**Comment by shaomeng** [comment]
As of 01/07/2019, this data set reports error when opened, before creating any new renderer:

![data_error](https://user-images.githubusercontent.com/814885/71880895-803c3300-30ee-11ea-939e-4c85db82cf9a.png)

**Comment by clyne** [comment]
@shaomeng needs to confirm that there is a problem opening the data set

**Comment by shaomeng** [comment]
Update:

@clyne  this data set opens properly right now, so discard the comment saying that it won't open.

Regarding the reported crash, it doesn't crash anymore and shows a notification window saying that some variables are missing. I think we can close this bug now.
