### ISSUE TITLE
Depth buffers not merged properly after the DVR framebuffer draw

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1913]
This is due to the fact that it is not possible to have depth buffer reads disabled and writes enabled at the same time in OpenGL. This can cause depth buffer problems in the situation where you have an isosurface, dvr, and something else, and all three intersect.

**Comment by clyne** [comment]
How is this bug reproduced? How does it manifest itself in a way the user would notice?

**Comment by StasJ** [comment]
In the scenario described below, notice the slice renderer is see-through:

<img width="579" alt="s" src="https://user-images.githubusercontent.com/2772687/68694975-64297480-0537-11ea-80f1-3c54ebb193aa.png">
