### ISSUE TITLE
Line width for flow renderer

### ISSUE THREAD

**Issue by phawbeck** [NCAR/VAPOR#1918]
Flow renderer does not allow me to adjust line width.

### Describe the solution you'd like.
Line width slider / dropdown.

**Impact**
- [ ] High - User productivity significantly improved
- [x] Medium - User productivity partially improved
- [ ] Low - User productivity trivially improved

**Comment by clyne** [comment]
@stasj what are your thoughts on supporting this in some manner?

**Comment by phawbeck** [comment]
From what we discussed in the meeting and from the duplicate ticket: I would like to be able to adjust the line thickness for streamlines / flowlines. Thickness simply specified by an integer would be sufficient, however, maybe there is some applications where thickness defined by the value of some variable might be useful.
