### ISSUE TITLE
Statistics vs Renderers: Refinement level not the same

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#192]
The statistics utility and any of the renderers show different number of available refinement levels for the same data set.

For example, Katrina data set shows 4 available ref levels (0..3) in a Barb renderer, while 5 (0..4) in the Statistics utility.

**Comment by clyne** [comment]
All variables in the katrina data set should have the same number of refinement levels: 4

> On Nov 1, 2017, at 12:38 PM, Samuel Li <notifications@github.com> wrote:
> 
> The statistics utility and any of the renderers show different number of available refinement levels for the same data set.
> 
> For example, Katrina data set shows 4 available ref levels (0..3) in a Barb renderer, while 5 (0..4) in the Statistics utility.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
@clyne I agree they should be 4. Also I think I tracked down the cause. So, not too worried about this one.
