### ISSUE TITLE
regular grids defined in NetCDF are treated as stretched grids

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#1927]
NetCDF has no means to explicitly describe a Regular grid (one where all cells are the same size). Hence, Regular grids are defined in NetCDF using 1D coordinate variables, with uniform spacing between each value. Currently VAPOR does not examine the values inside 1D coordinate variables and thus assumes that a 1D coordinate variable describes a "stretched" dimension. Thus when accessing variables with 1D coordinate variables from NetCDF these variables are represented using the StretchedGrid class (as opposed to the RegularGrid class). A number of algorithms in VAPOR (e.g. DVR) operate more efficiently on the RegularGrid class. 

Reported by @leighorf

**Comment by leighorf** [comment]
Echoing what I said in the google docs, it seems a pretty straightforward way to check if it's "regular" is to traverse each 1D array, calculating the spacing between adjacent values, and if those values are the same (within epsilon since it's 32 bit floating point data) for each delta in each of the 3D arrays, you could call it a regular grid.

**Comment by clyne** [comment]
The software engineering challenge is that the way the code is currently structured the determination of grid type is made by looking at the metadata only. I.e. the coordinate data values aren’t available to the code that figures out the grid type. So it will take some refactoring to support this.

> On Nov 19, 2019, at 12:55 PM, Leigh Orf <notifications@github.com> wrote:
> 
> Echoing what I said in the google docs, it seems a pretty straightforward way to check if it's "regular" is to traverse each 1D array, calculating the spacing between adjacent values, and if those values are the same (within epsilon since it's 32 bit floating point data) for each delta in each of the 3D arrays, you could call it a regular grid.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu
