### ISSUE TITLE
Wireframe renderer appearance tab incorrect section sizing

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1939]
Open the wireframe renderer appearance tab with a tall window. The `TF Editor` section will be stretched to the entire height. The sidebar sizing policies should be standardized, possibly as part of the VaporWidgets effort.

![scrot](https://user-images.githubusercontent.com/2772687/69373541-4360cd80-0c61-11ea-92ac-ac94f946ab44.png)

**Comment by clyne** [comment]
@StasJ is this issue still relevant?

**Comment by StasJ** [comment]
No, it is fixed
