### ISSUE TITLE
Loading a dataset into Flow caused crash

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#1950]
### Describe the bug
I imported a .nc storm file into VAPOR. Storm files are larger than 360+ megabytes. The storm file contained relative humidity data, and nothing else. In order to import large storm files, I had to strip out all of the other datasets, such as rainfall. I opened the file with a 3d volume renderer, where everything was fine. Then I closed the layers box and and opened the same file, except with a flow renderer. I received no error message about the file, VAPOR just immediately shut down. I re-opened VAPOR and tried to import the file I just used. The file successfully imported. Next, I tried to open the file with a flow renderer. Once more, VAPOR simply closed on me.

I tried attaching the file I used here, but it is too large for github, even compressed it still is 20 mb over the limit.

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [x] Did VAPOR crash?
- [ ] Did you get wrong results?

**Impact**
- [ ] High - User productivity significantly degraded
- [x] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce

I am not sure if this was a file size issue or not.

### Expected behavior
VAPOR closes upon selecting flow renderer.

### Attachments
Too big

### Desktop
 - Linux Redhat Enterprise 7
 - Vapor 3.2.0 alpha

**Comment by shaomeng** [comment]
Hello @jvalan , it'd be helpful to debug with the data file that caused your crash. Can you put the data on some cloud service and then provide a link along with this bug report? 
(One possible service is Firefox Send: https://send.firefox.com/ )

**Comment by jvalan** [comment]
https://send.firefox.com/download/5e789b5b04e32481/#Sj2l9WByM4cJuRO1-MATYA

Thanks, here is the file I used. I'm not certain, but I think that firefox wont let me change the maximum amount of downloads without an account, so be aware that the link here only works once.

**Comment by shaomeng** [comment]
This file now lives on glade:
`/glade/p/cisl/vast/vapor/Bugs/1950`

**Comment by shaomeng** [comment]
This bug and #1907 are caused by the same issue: no 3D variable present in a data set. @sgpearse and @shaomeng  are implementing a fix.

**Comment by clyne** [comment]
Waiting on #1971

**Comment by shaomeng** [comment]
Waiting the resolve of #2058 2058
