### ISSUE TITLE
GPU at 80%, Vapor crashes

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#1955]
I loaded up about seventeen different volume renderers. I only enabled visibility on one at a time so only one data set was visibly rendered at the time. I received a warning that my GPU was at 80%, and vapor crashed shortly afterwards.

I then reopened the same session and began to load in the same files I did before, going over 24 different rendered datasets. This time, however, I did not select or enable any of the datasets, but I still fiddled with the renderer settings on every dataset despite being blind to the change in order to attempt to both recreate the crash, and find ways in which the crash does not happen.

**Comment by StasJ** [comment]
Hi, thank you for reporting this issue. Every volume renderer caches data on the GPU memory. This cache is replaced as needed when you change the volume renderer's variables, however it is not cleared until you delete the renderer. You cannot practically use more than one or two volume renderers at a time and we did not expect users to attempt to use 17 at once. We have found that overloading the GPU's memory and then running complex calculations (volume rendering) can cause the OpenGL driver to crash. Unfortunately, OpenGL does not provide any mechanism to manage this problem.

Currently, the only solution would be to limit the number of volume renderers one can create, or to limit the number of active volume renderers and clear the GPU's memory when a volume renderer is disabled.

**Comment by jvalan** [comment]
Additional information on volume render caches. The cache is cleared when vapor crashes, and if only one volume renderer is active, and the session is saved with only that one renderer active, the other saved renderers won't load up until checked. It is possible to photograph each renderer individually, while chaining saved sessions through crashes.

For this animation, I loaded up a little over 30 volume renderers.

https://send.firefox.com/download/ec6f405965e4d3e4/#vUmPNApfNZIe4h-M8t0BDw
