### ISSUE TITLE
Crash with WRF/2D dataset

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#1956]
1. Open the VDC WRF/2D
2. Create a 2D data renderer
3. Select the variable V10
4. Enable the renderer
5. Set the fidelity to max
6. Move the viewport

Vapor will crash

**Comment by clyne** [comment]
@stasj I'm kicking this one back over to you to look at with valgrind. It may be related to #1949. It crashes in random locations inside of Qt with various memory errors.
