### ISSUE TITLE
Loading Flow Renderer Crashes

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#1960]
### Describe the bug
When using loading any of the following datasets into a flow renderer, vapor crashes instantly.

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [x] Did VAPOR crash?
- [ ] Did you get wrong results?

**Impact**
- [x] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
1. Import NetCDF-cf file
2. Select New in Renderers
3. Select Flow
4. Select Okay
5. Vapor crashes

### Expected behavior
Vapor crashes moments after selecting okay in step 4.

### Attachments

https://send.firefox.com/download/7d28a8da938b0d30/#CTXwDKW9lZ7xNBTiX6qXRg

### Desktop
 - OS and version: Redhat Linux 7
 - Version: Vapor 3.2

**Comment by clyne** [comment]
Check in glade and little glade for data under bugs/bug-number
