### ISSUE TITLE
Pressure Contours not visible?

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#1961]
What am I supposed to be doing to get an image to show up?
![Screenshot from 2019-12-04 18-54-28](https://user-images.githubusercontent.com/56135291/70173150-277e1280-16ca-11ea-98b0-83bd0bd733e1.png)

I'm trying to get a two dimensional image of pressure to appear. The source file has only pressure data in it, and everything else was extracted. Vapor crashes if I use the full file. I am told that it only has one value, but I should at least be seeing something as the opacity slider on the left is displaying something.

### Desktop
 - OS and version: Redhat linux enterprise 7
 - Version: Vapor 3.2 alpha

**Comment by StasJ** [comment]
It works for me. You could try a more recent installer and see if that fixes it for you: https://drive.google.com/open?id=15w1EFK_pu_SCoBBQESc5FW9eP3Hk60Kp

![s](https://user-images.githubusercontent.com/2772687/70274721-e0dff500-1769-11ea-8c76-9fffe33f8c26.png)

**Comment by jvalan** [comment]
Thank you for the new installer, I think it fixed something in that now I have a 3d box instead of a 2d box, but I still can't see anything, nor get anything to appear.
![Screenshot from 2019-12-05 21-13-42](https://user-images.githubusercontent.com/56135291/70275747-b19ba900-17a6-11ea-9b93-4c700d00474e.png)
![Screenshot from 2019-12-05 21-13-17](https://user-images.githubusercontent.com/56135291/70275748-b2343f80-17a6-11ea-8feb-35f0e3a3391c.png)

**Comment by StasJ** [comment]
Dataset in `/little_glade/bugs/1961`

**Comment by StasJ** [comment]
I noticed you are using a height variable. Please try without using a height variable (the height variable offsets the mesh and it could be offset so far you can't see it).
