### ISSUE TITLE
Allow for user-defined colormap range

### ISSUE THREAD

**Issue by phawbeck** [NCAR/VAPOR#1964]
I am trying to fix the colormap range of a volume renderer to values that are the min and max of a 4D dataset. However, I seem to only be able to set the range to the min and max of the **current** frame. When I put in values outside of that range, it gets overwritten by the minimum of the current frame (e.g. if the min of the dataset is -4.0 m/s but the min of the current frame is -2.0 m/s, if I type in -4.0 to the transfer function minimum value box will revert to -2.0).

This also makes it difficult if you have two slices (e.g. XY and YZ) that you want to set to a common color range.

It would be nice to simply be able to set the min and max value to any number and then have a button to set the range to the range of the current frame if desired.

**Impact**
- [ ] High - User productivity significantly improved
- [x] Medium - User productivity partially improved
- [ ] Low - User productivity trivially improved

**Comment by StasJ** [comment]
Hi Pat, thanks for reporting this. We plan to add this feature in the upcoming release.

**Comment by shaomeng** [comment]
The "reset range to default" button doesn't seem to work. I.e., after you set new min and max that are out of the original range, this specific button doesn't bring the range back to the original one.

**Comment by StasJ** [comment]
I just tried and it works for me?

**Comment by shaomeng** [comment]
@StasJ How about the "Appearance" tab of a Flow renderer, using data set `/little_glade/shaomeng/cm1.nc` on Linux? If you still cannot reproduce, I'll open a new ticket.
