### ISSUE TITLE
Flow: Missing Pathlines

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1975]
I'm unable to create any pathlines after following these steps:

1) Load DUKU-3.0.0.nc, or any recent conversion of that WRF dataset
2) Enable Pathlines (unsteady flow)
3) Change the rake-type to random
4) Enable the renderer
5) Advance one timestep.  I believe we should see something here.

I see these results with both old and new guis for the Flow renderer.

**Comment by shaomeng** [comment]
I do see something following the steps described above, on `master` branch.
