### ISSUE TITLE
Barb Renderer not visible

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#1991]
I am attempting to make a Barb render with east-west, north-south and vertical wind speeds, but nothing is showing up. Does Barb renderer even work, I can't get it to work for other datasets, and volume works fine for this file.

![Screenshot from 2019-12-13 15-19-51](https://user-images.githubusercontent.com/56135291/70811891-6e50c400-1dbe-11ea-9e12-f4b872c27e82.png)

File used: https://send.firefox.com/download/065c50f54ae0b1e8/#wJLHvuVtMg8A6gGyIxDFew

Version 3.2.0alphahdf5
Linux Redhat Enterprise 7

**Comment by jvalan** [comment]
Linux version 7 enterprise, vapor version 3.2.0-alpha-hdf5

**Comment by StasJ** [comment]
Hi, I am unable to reproduce your issue, it works for me out of the box. I have attached the most recent version of Vapor, please see if this resolves your issue. If not, I'll see what I can do to help resolve this issue. Also, this new version should allow you to import all of your timesteps together by simply selecting multiple files from the import file selection dialog.

[Vapor 3.2.0-alpha (new version)](https://drive.google.com/open?id=18y2DgnHygXmzGmq0X082qjVfG1OaKmn7)

![barb](https://user-images.githubusercontent.com/2772687/70835128-617da180-1db9-11ea-83b3-352e56bc643a.png)

**Comment by jvalan** [comment]
I'm happy to report that in the new version, the barb renderers are working properly, and the flow renderer no longer causes VAPOR to crash. I'm getting odd looking lines from the flow renderer, but that might be me inputting the wrong datasets.

However, VAPOR still crashes when when I select multiple files on import file selection. It does not tell me that paint failed or anything this time, the program simply closes.

**Comment by jvalan** [comment]
I've been informed that the barb renderer doesn't display barbs, but actually displays vectors.

**Comment by StasJ** [comment]
I'm glad the barb renderer works for you now. Yes, barb renderers always display vectors represented as barbs.

Sorry about the multiple dataset issue. It was fixed however we made a decent amount of changes to that part of the code recently and it appears the bug has reappeared. I've reopened the original report and we will look into it.

**Comment by jvalan** [comment]
Is it possible to render barbs that look like this? Is there a setting I can change?
![aid1443210-v4-728px-Read-Wind-Barbs-Step-3](https://user-images.githubusercontent.com/56135291/70934264-723a4b80-2035-11ea-8514-bae258ae2111.jpg)

**Comment by StasJ** [comment]
This is currently not possible. I added a feature request #2003 and we will see about adding this in the future.

**Comment by clyne** [comment]
Data are in /little_glade/bugs/1991
