### ISSUE TITLE
Flow + Close dataset + Open dataset = Crash

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1996]
To reproduce:

1) Open DUKU's VDC.  Create, and enable a Flow renderer
2) Close DUKU
3) Import the WRF file /glade/p/cisl/vast/vapor/data/Source/WRF/idealized/kalundquist/wrfout_d01_2013-01-01_09_30_00

Vapor will crash.

**Comment by StasJ** [comment]
I think John's recent changes might have fixed this
