### ISSUE TITLE
No longer able to edit Data Value

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#1997]
![Screenshot from 2019-12-16 19-54-17](https://user-images.githubusercontent.com/56135291/70939644-8fc0e280-2040-11ea-8000-3405fe408144.png)

The Data value box highlighted in the picture within the appearance tab is no longer able to be typed in or edited with the keyboard.

To Reproduce
1. Go to appearance tab of the image. (I was using a barb renderer)
2. Attempt to click on and edit the highlighted data value box in the above image.
3. Number does not change regardless of clicks or key presses.

### Desktop
 - OS and version: Redhat Linux Enterprise 7
 - Version: Vapor 3.2.0(new)

**Comment by StasJ** [comment]
You don't have a control point selected. Below the one on the right is selected.

![cp](https://user-images.githubusercontent.com/2772687/70941289-5b7dff80-2009-11ea-8b95-dd286a599273.png)

**Comment by jvalan** [comment]
Oops, My mistake.

**Comment by StasJ** [comment]
No worries. I see why it can be confusing. I'll see if I can make it clearer.
