### ISSUE TITLE
Params extents not honored in DataMgr

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2]
Changing the extents in the Geometry tab of a TwoDData renderer only affects the rendered area by 20% increments.  We can only render 20%, 40%, 60%, 80%, or 100% of the entire domain at a time.  The problem seems to come from dataMgr->_find_bounding_grid().

To reproduce:
1) Load KatrinaMaster.nc
2) Create a new TwoDData renderer and enable it
3) In the Geometry tab, slowly decrease the minimum X extent of the renderer until it re-renders with 80% of the domain.  Continue this to render 60%, 40%, and finally 20% of the domain.

**Comment by clyne** [comment]
Fixed
