### ISSUE TITLE
Flow seeds disappear

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2011]
1. Open DUKU VDC
2. Create/enable a flow renderer
3. Set seed type to random
4. Increase seed count to 10
5. Change Z rake region to encompass top 20% of the dataset

The seeds will disappear as below:

![out](https://user-images.githubusercontent.com/2772687/71034668-2b049700-20d7-11ea-8c3c-ee0028e588fb.gif)

**Comment by shaomeng** [comment]
DUKU has nothing towards the top layers of the domain, see the attached DVR. Thus, this is deemed not a bug. 

![Screenshot from 2019-12-27 14-51-18](https://user-images.githubusercontent.com/814885/71534017-1be0ce80-28b9-11ea-8cf5-700d04adeacb.png)
