### ISSUE TITLE
Wrong Flow Integration Settings GUI is shown

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2012]
1. Open DUKU
2. Create a flow renderer
3. Set Flow Type to Pathlines
4. Delete the renderer
5. Create a flow renderer

The wrong `Flow Integration Settings` GUI is shown. Pathlines are selected by settings are for streamlines.

**Comment by sgpearse** [comment]
Currently fixed on branch 2dFlow.  I'll label this accordingly when that branch merges with master.
