### ISSUE TITLE
BWG colormap not loaded properly

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2013]
1. Create a new renderer
2. Load the builtin colormap Blue-White-Gold

![a](https://user-images.githubusercontent.com/2772687/71036522-1c1fe380-20db-11ea-86a4-940a7037c46e.png)

**Comment by clyne** [comment]
@stasj what is the problem with the loaded colormap? It's not obvious.

**Comment by StasJ** [comment]
The colormap is called Blue-White-Gold yet the screenshot shows Blue-Purple-Pink-Orange-Gold.
