### ISSUE TITLE
VariablesWidget does NOT have a reliable mechanism to return 2D/3D mode

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2017]
The `VariablesWidget` can display 2D or 3D variables. However, it has no reliable mechanisms to report back what mode (2D or 3D) it is operating on. 

More specifically, firstly, `VariablesWidget` has a method `GetDimFlags()`, but this returned flag could be indicating 3D and 2D at the same time.

Secondly @pearse suggested to retrieve a `Box` from `VariablesWidget` and then retrieve the dimensionality of the box. There are three methods of a `Box` class that could potentially return this information: 
1. `GetOrientation()`
2. `GetExtents()`
3. `IsPlanar()`

Unfortunately, all three methods fail to detect 2D operational mode on some data sets, for example, `/little_glade/shaomeng/cm1.nc`

**Comment by clyne** [comment]
Sam, if FlowRenderer is trying to figure out whether it is working on 2D or 3D variables the right way to do that is probably to call RenderParams::GetFieldVariablesName() to get the names of the variables specified by the user, and then use DataMgr::GetDimLens() to query the dimensions of each variable. 

I think the Barb renderer performs this task using the Box, but I’m not sure that is reliable. 

jc


> On Dec 17, 2019, at 3:24 PM, Samuel Li <notifications@github.com> wrote:
> 
> The VariablesWidget can display 2D or 3D variables. However, it has no reliable mechanisms to report back what mode (2D or 3D) it is operating on.
> 
> More specifically, firstly, VariablesWidget has a method GetDimFlags(), but this returned flag could be indicating 3D and 2D at the same time.
> 
> Secondly @pearse suggested to retrieve a Box from VariablesWidget and then retrieve the dimensionality of the box. There are three methods of a Box class that could potentially return this information:
> 
> 	• GetOrientation()
> 	• GetExtents()
> 	• IsPlanar()
> Unfortunately, all three methods fail to detect 2D operational mode on some data sets, for example, /little_glade/shaomeng/cm1.nc
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by clyne** [comment]
Actually you can use DataMgr::GetNumDimensions() to get the number of dimensions: 1, 2, or 3.

> On Dec 17, 2019, at 3:33 PM, John Clyne <clyne@ucar.edu> wrote:
> 
> Sam, if FlowRenderer is trying to figure out whether it is working on 2D or 3D variables the right way to do that is probably to call RenderParams::GetFieldVariablesName() to get the names of the variables specified by the user, and then use DataMgr::GetDimLens() to query the dimensions of each variable. 
> 
> I think the Barb renderer performs this task using the Box, but I’m not sure that is reliable. 
> 
> jc
> 
> 
>> On Dec 17, 2019, at 3:24 PM, Samuel Li <notifications@github.com> wrote:
>> 
>> The VariablesWidget can display 2D or 3D variables. However, it has no reliable mechanisms to report back what mode (2D or 3D) it is operating on.
>> 
>> More specifically, firstly, VariablesWidget has a method GetDimFlags(), but this returned flag could be indicating 3D and 2D at the same time.
>> 
>> Secondly @pearse suggested to retrieve a Box from VariablesWidget and then retrieve the dimensionality of the box. There are three methods of a Box class that could potentially return this information:
>> 
>> 	• GetOrientation()
>> 	• GetExtents()
>> 	• IsPlanar()
>> Unfortunately, all three methods fail to detect 2D operational mode on some data sets, for example, /little_glade/shaomeng/cm1.nc
>> 
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>> 
> 
> John Clyne
> National Center for Atmospheric Research
> 303.497.1236 (w), 303.809.1922 (c)
> clyne@ucar.edu
> 
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
John, your method fails when there's no 2D variable present in the data set. 

Overall, VariableWidget is a GUI widget that's capable of operating in two different modes. There isn't any reason we'll need extra help (from DataMgr etc.) for the widget itself to report back what mode it's operating on.

**Comment by clyne** [comment]
> On Dec 17, 2019, at 4:13 PM, Samuel Li <notifications@github.com> wrote:
> 
> John, your method fails when there's no 2D variable present in the data set.


Fails how? Maybe I don’t understand what you are doing.

> 
> Overall, VariableWidget is a GUI widget that's capable of operating in two different modes. There isn't any reason we'll need extra help (from DataMgr etc.) for the widget itself to report back what mode it's operating on.’

ok. 

> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
@clyne Ok, `DataMgr::GetNumDimensions( varName )` does not fail to return the name of a given variable, but it isn't a good indicator of what mode `VariableWidget` is operating on. 

Specifically, when there's no variable in a certain mode, e.g. no 3D variables in the 3D mode, then `DataMgr::GetNumDimensions( varName )` returns 0 instead of 3. In this case, the `VariableWidget` is still operating in a 3D mode, and this is the piece of information I wanted to use.

**Comment by clyne** [comment]
> On Dec 17, 2019, at 7:11 PM, Samuel Li <notifications@github.com> wrote:
> 
> @clyne Ok, DataMgr::GetNumDimensions( varName ) does not fail to return the name of a given variable, but it isn't a good indicator of what mode VariableWidget is operating on.

No, it is not. The renderer can use it to check the dimensionality of the selected variable (since this information is not available in the Params database).

> 
> Specifically, when there's no variable in a certain mode, e.g. no 3D variables in the 3D mode, then DataMgr::GetNumDimensions( varName ) returns 0 instead of 3. In this case, the VariableWidget is still operating in a 3D mode, and this is the piece of information I wanted to use.

Gotcha. I think. I was confused because I thought you were working on FlowRenderer, not the GUI.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
@clyne There are more GUI elements that need to adjust themselves based on either 2D or 3D is selected by the VariablesWidget, so I took a shot on those GUI elements. Apparently I didn't achieve what I wanted to achieve...

**Comment by shaomeng** [comment]
The solution is to introduce a new entry in the GUIParams database to keep this piece of information. I.e., keep the info weather the `VariablesWidget` operates in 2D or 3D mode.
