### ISSUE TITLE
3.2.0.alpha has shared library problem on casper

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2019]
The 12/17 installer built on garibaldi  (Vapor Release version 3.2.0.alpha.0f428b3 (2019-12-19T00:40:30Z) generates the following message and aborts:

vapor: /lib64/libdbus-1.so.3: no version information available (required by /glade/u/home/clyne/lib/libQt5DBus.so.5)
vapor: relocation error: /glade/u/home/clyne/lib/libQt5DBus.so.5: symbol dbus_message_get_allow_interactive_authorization, version LIBDBUS_1_3 not defined in file libdbus-1.so.3 with link time reference

**Comment by StasJ** [comment]
@clyne the installer on google drive has been updated and now works on capser.
