### ISSUE TITLE
Holes in DUKU Isosurface

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2028]
To reproduce:
1) Load DUKU's VDC (/glade/p/cisl/vast/vapor/data/VDC/vapor-3.0.0/WRF/DUKU/DUKU-3.0.0.nc)
2) Create an isosurface with the variable W
3) Increase the fidelity to the maximum setting

Note: The transfer function bounds appear to be off.  The following screenshot has boolean scaling in the histogram.  I believe we should be seeing histogram values along the entire X axis by default.

<img width="1288" alt="Screen Shot 2019-12-20 at 8 43 05 AM" src="https://user-images.githubusercontent.com/9522770/71266025-c29afd00-2304-11ea-860e-ebb7c2991cc2.png">

**Comment by StasJ** [comment]
The data at this variable is at the very bottom of the dataset and the histogram sampling misses it so it thinks there is no data here. The IsoSurface is correct but the sampling is too low for this case. If you turn up the sampling rate, it gives a correct result as below:

<img width="604" alt="s" src="https://user-images.githubusercontent.com/2772687/71532257-c2c06d00-28af-11ea-96b4-245c764adb18.png">
