### ISSUE TITLE
Colormapped Isosurface values slightly off

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2029]
In the screenshot below, we have an isosurface of U, colored by itself.  I believe this isosurface should have only one single color.

To reproduce:
1) Download the attached session file
2) Rename the file extension to .vs3 (Github does not allow files with just .vs3 as the extension)
2) Load DUKU's VDC (/glade/p/cisl/vast/vapor/data/VDC/vapor-3.0.0/WRF/DUKU/DUKU-3.0.0.nc)

Note: This is using the curvilinear raycaster.  The regular raycaster does not exhibit this behavior.

[issue2029.vs3.txt](https://github.com/NCAR/VAPOR/files/3989037/issue2029.vs3.txt)

<img width="1288" alt="Screen Shot 2019-12-20 at 8 52 47 AM" src="https://user-images.githubusercontent.com/9522770/71266667-1fe37e00-2306-11ea-8d75-c63c44a96589.png">

**Comment by clyne** [comment]
Need to confirm whether this is a bug or just a precision issue.

**Comment by StasJ** [comment]
I believe this is in fact just a precision issue. Also the TF was compressed which would exacerbate this:

<img width="400" alt="s" src="https://user-images.githubusercontent.com/2772687/71450511-bd80e800-2720-11ea-8d00-b1c46d2ef97c.png">
