### ISSUE TITLE
Failed to load MPAS data

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2031]
To reproduce:
1) Start vapor, and import the MPAS file below:

/glade/p/cisl/vast/vapor/data/Source/MPAS/FalkoJudt/30km/diag.2016-08-01_00.00.00.nc

<img width="525" alt="Screen Shot 2019-12-20 at 9 36 20 AM" src="https://user-images.githubusercontent.com/9522770/71269279-3391e300-230c-11ea-8a33-614989e51e48.png">

**Comment by clyne** [comment]
You need to load the grid file that is in the directory as well.



> On Dec 20, 2019, at 9:36 AM, sgpearse <notifications@github.com> wrote:
> 
> To reproduce:
> 
> 	• Start vapor, and import the MPAS file below:
> /glade/p/cisl/vast/vapor/data/Source/MPAS/FalkoJudt/30km/diag.2016-08-01_00.00.00.nc
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu
