### ISSUE TITLE
Annotation: Apply to all colorbars does not work

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2033]
1. Open jsmall
2. Create/Enable a wireframe renderer
3. Enable the annotations
4. Customize the annotation
5. Create/enable a 2D data renderer
6. Enable the 2D data renderer colorbar
7. Select the wireframe
8. Press `Apply to all colorbars`

The 2DData renderer annotation will remain unchanged

**Comment by clyne** [comment]
Duplicate of #406
