### ISSUE TITLE
Buggy DataMgr?

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2042]
Inside of `DataMgr.cpp`, the private method `_getVariable()` doesn't seem to honor the `lock` boolean that was passed into the public method `GetVariable()` when called. This happens in multiple instances, and the following is just one example. (Notice it's hard coded `false`.)

https://github.com/NCAR/VAPOR/blob/77f5941501c078cedfce3dbefc8d08559846150c/lib/vdc/DataMgr.cpp#L1575-L1577

**Comment by clyne** [comment]
@shaomeng DataMgr::_getVariable() is an overloaded method, one with 6 arguments and one with 8. The lock argument is the 5th positional argument in the former and the 7th in the latter. In the code snipped above the lock argument is NOT hard coded to false. It is set by the "lock" variable passed to GetVariable()
