### ISSUE TITLE
3D variables with a dimension with a length of one don't work with vaporgui

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2048]
If a 3D variable has a dimension length of one vaporgui does not appear to be able to set up viewing transformations correctly. This is particularly problematic with VDC data sets which may have variables that are truly 3D at higher refinement levels, but at coarsened refinement levels the variables may collapse to having dimensions of length one. 

To reproduce:

1. Create a data set with a variable that has a dimension length of one along a single axis:

```
% vdccreate -dimension 128x128x4 -vars3d checker check4Master.nc

% raw2vdc -var checker check4Master.nc /little_glade/data/Source/Raw/checker/checker128
```
Note that the full resolution grid does not have any dimensions of length one. However, coarsened versions - which are used to establish viewing transforms - will have a Z dimension of length one.

2. Load the VDC version of the data into vaporgui. Note that no bounding box is displayed. None of the visualizers will work with this data set even if the refinement level is changed such that the Z dimension length is no longer one.

**Comment by shaomeng** [comment]
I have a feeling that this bug can be fixed without too much effort after
we implement the changes to all grids so that they all exhibit 3D
properties.

**Comment by StasJ** [comment]
Clipping "halo" may need to be fixed
