### ISSUE TITLE
Flow crash

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2059]
To reproduce:
1) Load the WRF/2D VDC, create a flow renderer
2) Delete the flow renderer
3) Create a new flow renderer.  Vapor will crash.

**Comment by shaomeng** [comment]
Cannot reproduce with a Leigh Orf Tornado data set. Need more info.

**Comment by StasJ** [comment]
I just reproduced this with the WRF/2D VDC dataset

**Comment by shaomeng** [comment]
Investigation update:
Upon creation of the 2nd flow renderer, the variable `VariableWidget::_rParams` becomes a dangling pointer. Question: what's the correct behavior should be? A new Params object being created? The old Params object not being deleted?

**Comment by shaomeng** [comment]
Investigation update:
This dangling pointer only occurs with data sets that have only 2D variables. I.e., the pointer is properly updated when 3D variables are present. I think there's some logic went wrong when `VariableWidget` handles 2D variables.
