### ISSUE TITLE
Map Distortion

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#2061]
When Stretching out the image rendered map, occasionally the map will experience horizontal bars of corruption. This doesn't always happen, and it isn't consistent as to which coordinates this occurs on. Saving and reloading VAPOR fixes the image.

**Impact**
- [ ] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [x] Low - User productivity trivially degraded

### Desktop
 - OS and version: Linux Redhat Enterprise 7
 - Version: Vapor 3.2.0 alpha.

![map blur](https://user-images.githubusercontent.com/56135291/71926354-0a39d980-318b-11ea-82cb-d1d9b6b0db79.png)

**Comment by shaomeng** [comment]
Hello @jvalan , is there a sequence of actions that lead to this distorted rendering?

**Comment by jvalan** [comment]
It inconsistently happens, and I cannot always replicate it, but it involves:
1. Load up and enable visibility on an image render
2. Change modes from Navigate to region.
3. Stretch image beyond bounding box using orange handles.
4. Sometimes the map will distort.

**Comment by sgpearse** [comment]
Unable to reproduce with Katrina.  @jvalan Please let us know if you have a dataset that can reproduce this.
