### ISSUE TITLE
Rendering Algorithms of Regular and Curvilinear are Reversed

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#2069]
When changing the Rendering Algorithms under Raytracing Patterns from Curvilinear to Regular, I noticed that the renders were mirrored. This Isosurface Renderer is a flipped mirror image of itself when changed from regular to curvilinear and back again.
![Screenshot from 2020-01-09 21-16-49](https://user-images.githubusercontent.com/56135291/72106976-5706e700-3328-11ea-9c77-a61736e07baf.png)
![Screenshot from 2020-01-09 21-17-39](https://user-images.githubusercontent.com/56135291/72106978-58381400-3328-11ea-8015-1dc8978a5346.png)

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [x] Did you get wrong results?

**Impact**
- [x] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### Desktop
 - OS and version: [Linux Redhat Enterprise 7]
 - Version: VAPOR 3.2.0 alpha

**Comment by jvalan** [comment]
file:///home/jvalancy/Desktop/curvilinear.png
Curvilinear is the correct direction
![regular](https://user-images.githubusercontent.com/56135291/72176490-5c226f80-33d6-11ea-998e-bde3f027a5f1.png)
But regular is the wrong direction.

**Comment by jvalan** [comment]
![regular](https://user-images.githubusercontent.com/56135291/72176518-72303000-33d6-11ea-90ae-3a40a1dce450.png)

**Comment by jvalan** [comment]
file://home/jvalancy/Desktop/curvilinear.png

**Comment by jvalan** [comment]
![curvilinear](https://user-images.githubusercontent.com/56135291/72176616-ab68a000-33d6-11ea-9e75-3008dba1033e.png)

**Comment by jvalan** [comment]
Curvilinear is the correct direction
![curvilinear](https://user-images.githubusercontent.com/56135291/72176636-b6bbcb80-33d6-11ea-80da-f29c750f2e5e.png)
Whereas Regular is inverted and in the opposite direction.

![regular](https://user-images.githubusercontent.com/56135291/72176662-c5a27e00-33d6-11ea-9be4-5571de1a79e3.png)

**Comment by jvalan** [comment]
Furthermore, is the curvilinear renderer supposed to pixelate when clicking and dragging the camera?
![Screenshot from 2020-01-10 18-13-22](https://user-images.githubusercontent.com/56135291/72177211-1ff00e80-33d8-11ea-94d3-0702d4168b8f.png)

**Comment by StasJ** [comment]
Hi @jvalan, I suspect your longitudinal coordinates are reversed. If you share the data, I can double check.

As for the pixelation, yes that is expected behavior. Your computer is not fast enough to render the volume in real time as you rotate the scene so Vapor dynamically selects the highest resolution it can render while still providing fluid motion.

**Comment by jvalan** [comment]
I don't see how changing the rendering algorithm from curvilinear to regular would cause the longitudinal coordinates to reverse. This used to not happen, and regular was not inverted. I remember when the curvilinear rendering algorithm was broken, and regular was the only one that could be used, this did not happen, and regular would give me the correct orientation.

[Dorian Vertical Redone.vs3.zip](https://github.com/NCAR/VAPOR/files/4072529/Dorian.Vertical.Redone.vs3.zip)

**Comment by StasJ** [comment]
Take a 1D dataset:
```
coords = [3, 2,  1, 0]
data = [a, b, c, d]
```

The regular renderer does not take coords into account so it renders the data as it appears in the data array: `a, b, c, d`
The curvilinear renderer takes the coords into account so it positions the data based on their coordinates: `d, c, b, a`

If you send me a copy of this data, I can double check.

**Comment by jvalan** [comment]
The session file is attached as a .zip in the post above. Do you need a dataset, or does the session data automatically include it?

**Comment by StasJ** [comment]
I need the dataset. Just a single time step would work.

**Comment by jvalan** [comment]
https://send.firefox.com/download/15e03252fbbb35db/#DD-8y3YVQ8Om59vcKTdtew

Here you go.

**Comment by StasJ** [comment]
I just checked and your lat coord is decreasing. Regular grids do not have coordinate variables so the regular renderer cannot know this. If you use the curvilinear renderer, you will get the correct result.

**Comment by jvalan** [comment]
Okay great to know that I have to use curvilinear to get the correct result, but again, this didn't used to be the case, as when the curvilinear renderer was broken, and I used Regular, it would give me the correct result? Why was this changed when the curvilinear renderer was fixed?

**Comment by StasJ** [comment]
I'm afraid the regular grid renderer never changed in this regard so either your dataset changed or you didn't notice the rendering was flipped.

**Comment by jvalan** [comment]
![DoVvel33](https://user-images.githubusercontent.com/56135291/72558962-a191e180-389b-11ea-9c86-fb2bf9586a50.png)
![DoVvel](https://user-images.githubusercontent.com/56135291/72558988-b5d5de80-389b-11ea-94fc-470e9c6a82c6.gif)
These were made with the Regular renderer before an update flipped them. The screenshot and gif were both taken December 11th, 2019.

Here is the same file being opened now, which still is set to Regular Renderer, yet is inverted.

![flipped regular](https://user-images.githubusercontent.com/56135291/72559330-7956b280-389c-11ea-8126-884cfcebebfe.png)

Compare the similarities of both regular rendered files, and contrast them to one of the curvilinear render

![curvilinear not flipped](https://user-images.githubusercontent.com/56135291/72559407-a1deac80-389c-11ea-8dd9-7fabc6de17d6.png)

Something changed in between now and December 11th, 2019.

**Comment by jvalan** [comment]
Curvilinear renders used to look something like this before they were fixed.
![Curvilinear render old](https://user-images.githubusercontent.com/56135291/72561100-5cbc7980-38a0-11ea-85aa-2a61f1fadd69.png)

**Comment by StasJ** [comment]
I don't know why this changed, however the behavior Vapor is currently exhibiting is correct in this regard. If you want flip the latitude of the regular grid renderer so it looks the same as the curvilinear renderer, you can go to the Geometry tab and scroll to the bottom where you can change Y Scale to -1

**Comment by jvalan** [comment]
This still yields incorrect results.
![sliceflip1](https://user-images.githubusercontent.com/56135291/72828067-d3c48a00-3c73-11ea-8649-27ee45148ba4.png)
Here is the curvilinear renderer, intersecting with a slice render. The data and slice align.
![sliceflip2](https://user-images.githubusercontent.com/56135291/72828282-3ddd2f00-3c74-11ea-9e36-b7c71e00a190.png)
Here is the regular renderer, flipped showing incorrect results,
![sliceflip3](https://user-images.githubusercontent.com/56135291/72828340-54838600-3c74-11ea-8028-67900b2cb5ee.png)
And this is regular with Y scale set to -1. As you can see, the data sill is incorrect despite being flipped, as it is displaced and does not align with the slice.

**Comment by StasJ** [comment]
Yes, the regular and curvilinear grid renderers will not align if your data is curvilinear. You can get them closer by using the renderer transform table. Since your data is curvilinear you should use the curvilinear renderer as that will give the correct result.
