### ISSUE TITLE
Flow GUI wrong Seed Distribution Settings

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2074]
1. Create 2 flow renderers
2. Change the seed distribution type to Random for one of them

Both will now show the Random GUI.

**Comment by sgpearse** [comment]
@clyne @shaomeng @StasJ 

Hey guys, we missed classifying this one yesterday.  Sam's kicking it over to me.  I think this one might be a High.  If you guys agree or disagree, let's mark it so.

**Comment by shaomeng** [comment]
Scott, I think it's a high, and I tested my original fix, it was working.
More specifically, you reported a scenario in which it wasn't working, can
you confirm?
