### ISSUE TITLE
Flow write to file bug

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2079]
1. Open jsmall
2. Create/enable a flow renderer
3. Press write to file
4. Vapor start throwing errors about an invalid file being chosen
5. Press select file

Vapor will freeze and needs to be force-killed.

**Comment by shaomeng** [comment]
I'm not sure if this is a bug, since the default value in the "write to file" field is the home directory of a user. I successfully wrote to a file after changing that default value to a valid file name.

**Comment by shaomeng** [comment]
Cannot reproduce freeze behavior.
