### ISSUE TITLE
GUI inconsistency

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2081]
Isosurface GUI stays in inconsistent state even after press enter. It recovers after dragging the isovalue selector around.

To reproduce:
1. Open. VAPOR, load a data set.
2. Create an Isosurface renderer, enable it.
3. Type a value that's obviously out of bound in the "data value" line edit, and press enter many .
4. The GUI now displays inconsistency between the  "data value" line edit and the iso value control point.
5. Drag the control point, it recovers. 

![iso](https://user-images.githubusercontent.com/814885/72195259-b1f31980-33ce-11ea-9591-dba5435be1a9.png)

**Comment by sgpearse** [comment]
Related to #1872

**Comment by StasJ** [comment]
It does not accept the value. If you touch anything else in vapor it resets it.

**Comment by shaomeng** [comment]
I imagine a user could type in a specific ISO value, for example, I want to see what the surface is at isovalue of 0.75. 

If this use case is truly unsupported, then I'd suggest disable typing in that text box.

**Comment by shaomeng** [comment]
The described behavior still exists.

**Comment by clyne** [comment]
@stasj will replace the offending widget with a "vapor" widget
