### ISSUE TITLE
Statistics: 2nd time open window doesn't fully show.

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2083]
To reproduce:
1. Open VAPOR, load a dataset.
2. Open Statistics window.
3. Close Statistics window.
3. Open Statistics window. Notice that the window isn't properly displayed. 

![stat](https://user-images.githubusercontent.com/814885/72195743-3a72b980-33d1-11ea-80ea-111a32432df5.png)

**Comment by StasJ** [comment]
This is entirely @shaomeng's code. I think it would make more sense if you took a look at this Sam.
