### ISSUE TITLE
Flow: enabling periodic boundaries results in infinite loop

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2087]
The Flow renderer can go into an infinite loop if periodic boundaries
are enabled.

To reproduce:

1. Import the raw Katrina data and create a Flow renderer
2. Change the variable dimension to 2D and enable with U10 and V10 varibles
3. Change the integration direction to backwards, and make the X axis
periodic.

Addendum:

Need to test with a single wrf file: wrfout_d02_2005-08-29_00

**Comment by shaomeng** [comment]
Seems to be a very annoying problem. I think it needs to be investigated/fixed.

**Comment by clyne** [comment]
Still broken

**Comment by shaomeng** [comment]
Cannot reproduce on either Mac or Linux.

**Comment by clyne** [comment]
@clyne re-verify and be specific about data set

**Comment by clyne** [comment]
Works for me raw data and VDC created with 3.2

**Comment by clyne** [comment]
Can't verify until #2177 is fixed
