### ISSUE TITLE
Flow: pathlines broken with 2D data

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2088]
Pathlines do not integrate with 2D data

To reproduce:

1. Load the raw katrina files, create a flow renderer, and set the dimension to 2D
2. Enable the flow renderer. Streamlines will be displayed
3. Change the flow type from streamline to pathline
4. Advance the time steps. Nothing is displayed.

**Comment by shaomeng** [comment]
@clyne John, I've investigated this issue, and it's caused by complications from the changing Z value from time step to time step. More specifically, in a 2D rendering with changing Z values, it becomes more like a 3D rendering. This is a case we haven't thought about...

**Comment by clyne** [comment]
Still broken

**Comment by shaomeng** [comment]
Cannot reproduce on either Mac or Linux.

**Comment by clyne** [comment]
@clyne need to re-verify and specif data set

**Comment by clyne** [comment]
Works for me with raw WRF outputs and VDC 3.2
