### ISSUE TITLE
Flow: pathline performance degrades over time

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2089]
The pathline integration rate gets slower and slower as it advances
through time. For example, the integration rate for the VDC version
Katrina  at the lowest refinement level is about 1 second per frame
for early time steps, and 6  seconds per frame for later time steps.

To reproduce:

1. Load the VDC version of katrina, create and enable a flow renderer
2. Change the flow type to pathline and hit play. Not how long it
takes to integrate early time steps and how long it takes for later
time steps (around time step 50)

**Comment by shaomeng** [comment]
Sam will take a look at why this is happening.
