### ISSUE TITLE
CAM/AdamPhillips wrong data bounds

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2094]
1. Open `CAM/AdamPhillips/v5_rel04_BC5_ne120_t12_pop62`
2. Create/enable a 2D wireframe renderer 

The bounds appear to be incorrect:

![s](https://user-images.githubusercontent.com/2772687/72285880-4218a500-3601-11ea-9175-3738f7cd4ba4.png)

**Comment by clyne** [comment]
@stasj I believe that this is a correct result for this data set. Some of the variables aren't defined past ~80 degrees N. Can you try looking at some of the other variables?

**Comment by StasJ** [comment]
@clyne Yes other variables are defined in the upper region. The reason I brought this up is because from my understanding the bounds are calculated from the currently active variable. If this is correct we can reject this.

**Comment by clyne** [comment]
I believe this variable simply has missing data, but is defined over the same mesh as everything else.

> On Jan 13, 2020, at 1:48 PM, StasJ <notifications@github.com> wrote:
> 
> @clyne Yes other variables are defined in the upper region. The reason I brought this up is because from my understanding the bounds are calculated from the currently active variable. If this is correct we can reject this.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu
