### ISSUE TITLE
Flow: Broken with POP/KISTI

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2100]
1. Import `POP/KISTI`
2. Create/enable a Flow renderer

Vapor will throw error stating that you need to select at least two variables. When you try to select a second variable, multiple error messages pop up stating that you need to select a second variable and the variable selection dropdown is reset to `<no-variable>`.

**Comment by shaomeng** [comment]
@sgpearse The Variable Widget seems to refuse to accept the acceptance of a second selection. Could you take a look? 

![2d](https://user-images.githubusercontent.com/814885/72392259-d14eb700-36ec-11ea-8ac1-6c3a2e5d7c90.gif)
