### ISSUE TITLE
Flow: Vapor freezes permanently with MPAS

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2101]
1. Open MPAS-O
2. Create a flow renderer

Vapor will freeze.

**Comment by shaomeng** [comment]
@StasJ I'd really appreciate if you specify where the data is (e.g. VDC folder or Source folder).

**Comment by shaomeng** [comment]
@sgpearse this one seems to be a duplicate of #2058. Could you take a look?

**Comment by StasJ** [comment]
@shaomeng its not possible to have an MPAS VDC.

**Comment by shaomeng** [comment]
I'd be helpful to specify import a particular data set at a particular
directory, no matter there's a VDC or not.

Btw, what's this file:
data/VDC/vapor-3.2.0.alpha/MPAS/MPAS-O/MPAS-O-3.2.0.alpha.nc

**Comment by sgpearse** [comment]
This seems to have been fixed in a previous merge.  I'm going to mark it "works for me".
