### ISSUE TITLE
Animating Barb Renderer Softlocks Vapor

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#2121]
### Describe the bug
When importing timestamp data into a volume renderer, pressing the play button while recording frames cycles the animation throught each file normally. However, attempting to do the same with a barb renderer causes paint to fail, and the files are still cycled through. This results in VAPOR constantly spamming 'Paint failed" messages, that constatnly reappear when closed, preventing the user from doing anything, even closing VAPOR until the paint failed messages are gone. Given that they constantly appear automatically, it is impossible to stop this.

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [ ] Did you get wrong results?

**Impact**
- [ ] High - User productivity significantly degraded
- [x] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
Steps to reproduce the behavior. For example:
1. Load multiple datasets as one with a time variable.
2. Load dataset into Barb renderer.
3. Press play in the animation tab.
4. VAPOR will endlessly spam paint failed messages.

### Desktop
 - OS and version: Redhat Linux Enterprise 7
 - Version: VAPOR 3.2.0 (latest test build)

**Comment by StasJ** [comment]
Please provide a copy of the dataset with at least two timesteps (or however many it takes to reproduce the problem) and well will look into this. We tried with one of our datasets and we could not reproduce it.

**Comment by jvalan** [comment]
https://send.firefox.com/download/b5e9686acdbdce18/#hOlBYUTg37PbsuAA6O9qLg

I was using the same vertical velocity dataset I used for my other renderers, just to see that if I could, and then move onto Latitudinal and Longitudinal wind speed.

**Comment by sgpearse** [comment]
Hmm I'm unable to reproduce this after the following steps:

1) Import the aforementioned files as NetCDF-CF data
2) Create and enable a barb renderer
3) Animate forwards in time

Tested on OSX 10.14 and CentOS 7

**Comment by StasJ** [comment]
Dataset is at `/glade/p/cisl/vast/vapor/bugs/2121`
