### ISSUE TITLE
Flow does not work with MPAS

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2131]
1. Import source dataset: MPAS/MPAS-O
2. Create/enable a flow renderer
3. Add variables

You will get the following error:
```
Error performing paint event
Update Advection Periodicity failed!
Vector field not available at requested time step!
Variable Dimension Wrong!
------------------
Vapor 3.2.0.85396a7c
OS: Mac OS X 10.14.6
```

**Comment by shaomeng** [comment]
That data seems to contain only 1D variables.

That said, those 1D variables are select-able when the VariableWidget is in 2D mode. This might be a bug from VariableWidget. @sgpearse

**Comment by StasJ** [comment]
@shaomeng those are unstructured 2D variables.
