### ISSUE TITLE
Cannot set Flow Vector Field Multiplier to less that 1e-4

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2134]
We decided that the user needs to be able to input any multiplier.

**Comment by shaomeng** [comment]
This is due to the shortcomings of the GUI widgets.
Internally, it only enforces the value to be greater than zero.

**Comment by sgpearse** [comment]
This is actually a feature, not a bug.

Right-click on the "Vector field multiplier" widget, and increase the decimal precision.
