### ISSUE TITLE
Flow: Katrina not working after POP/KISTI

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2135]
1. Open Katrina
2. Create/enable a Flow renderer

You will see flow rendered

1. Restart Vapor
2. Import source dataset POP/KISTI
3. Create/enable a Flow renderer
4. Select valid variables
5. Create a new session
6. Open Katrina
7. Create/enable a Flow renderer

Nothing will be rendered, even after trying to mess with settings. I reproduced this twice on my Mac

**Comment by sgpearse** [comment]
Possibly related to #2141

**Comment by shaomeng** [comment]
It appears to be a viewpoint problem. That's because after you perform the following, then the flowlines show up again. I'm not sure how to handle this situation. 

1) Close the non-Katrina data set
2) Click reset viewpoint button to reset it.

**Comment by shaomeng** [comment]
Cannot reproduce this bug anymore. Could be fixed between January 2020 and November 2020.
