### ISSUE TITLE
Flow: Write Flowlines to file bug

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2136]
1. Open jsmall
2. Create/enable a Flow renderer
3. Increase scaling so flow is visible
4. Press Write to File
5. Vapor will throw error stating that file is needed
6. Select a valid file (I selected `/Users/stasj/Desktop/asdf.txt`)

Vapor will continue throwing errors until you delete the flow renderer

```
Error performing paint event
Output flow lines wrong!
------------------
Vapor 3.2.0.85396a7c
OS: Mac OS X 10.14.6
```

**Comment by shaomeng** [comment]
I cannot reproduce a "continue throwing errors until you delete the flow renderer" scenario on either Linux or Mac.

**Comment by sgpearse** [comment]
Add a default file, see if that addresses the problem.
