### ISSUE TITLE
Flow cannot have 2D and 3D flow at the same time

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2137]
1. Create 2 Flow renderers
2. Set one of them to 2D

Now both will be 2D

3. Set one to 3D

Now both will be 3D

**Comment by sgpearse** [comment]
This is because we're storing the 2D/3D state of the Flow GUI as a single value GUIStateParams.  I believe that storing this value in each instance FlowParams is the correct fix.  However that also feels outside of the scope of our current release.
