### ISSUE TITLE
Flow: Write flowlines is a no-op

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2138]
To reproduce:
1) Load ROMS/jsmall (little_glade/data/Source/ROMS/jsmall)
2) Create a flow renderer.  On our current installer, no streamlines are drawn
3) Select a destination file and click "Write to file".  The file is written.
3) Click "Write to file" again.  Nothing is written.  

If the file is not written, we should notify the user.

Note: Clicking "Write to file" makes the following params function calls.  These should issue a redraw, which should then write the geometry file.  It seems only the these function calls only issue redraws after the first click of the "Write to file" button.

    _paramsMgr->BeginSaveStateGroup("Write flowline geometry file");
    _params->SetFlowlineOutputFilename( file );
    _params->SetNeedFlowlineOutput( true );
    _paramsMgr->EndSaveStateGroup();

**Comment by clyne** [comment]
duplicate
