### ISSUE TITLE
Contour Renderer crashes upon enabling

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#214]
To reproduce:
1. Open Katrina.nc
2. Add contour renderer
3. Enable contour renderer

Crashes in `RegularGrid::GetValueLinear` when the assertion `assert(i<GetDimensions()[0])` fails.

**Comment by sgpearse** [comment]
FYI - I'm switching this from 'Fixed' to 'works-for-me', because I don't see any pull requests that are associated with this bug.
