### ISSUE TITLE
What kind of storm data works best for flow renderers?

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#2150]
Basically, what datasets paint the clearest picture for flow renderer? I'm using x,y wind speed alongside z vertical velocity, but I'm not getting a picture like the example in the renderer selection. Is there a setting I'm not clicking on, or do certain datasets work better?

**Comment by sgpearse** [comment]
It should work with any dataset with at least 2 variables to calculate advection from.  What you're seeing could be a bug, or it could be a set of bad default settings.

This tutorial video may help you:  https://youtu.be/Zyz30rYD8rU
