### ISSUE TITLE
Slice renderer restored from session bug

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2157]
1. Open `/little_glade/stasj/Lee_Tornado`
2. Create/enable 4 slice renderers

Rotate the scene and notice a high FPS.

3. Save the session 
4. Restart vapor
5. Open the session

The visualizer is unusably slow, i.e. if I try rotating the scene I get about 1 FPS. Deleting the renderers solves this.

**Comment by sgpearse** [comment]
@stasj What kind of file is that?  Session?  NetCDF-CF?  VDC?

**Comment by StasJ** [comment]
It’s a directory

**Comment by shaomeng** [comment]
Cannot verify because of #2184
