### ISSUE TITLE
Flow missing label

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2163]
Flow Region selector seems to have a missing Z label. See the circled area. 

To reproduce:
1. Open VAPOR, load VDC: `/little_glade/data/VDC/vapor-3.2.0.alpha/WRF/Katrina/`
2. Create a flow renderer.
3. Change Variable Dimension to 2D
4. Enable the renderer
4. Go to Seedings tab to observe this missing label.  

![Screen Shot 2020-01-27 at 1 43 44 PM](https://user-images.githubusercontent.com/814885/73212318-3356e580-410b-11ea-9bb3-9edd14b54899.png)

**Comment by sgpearse** [comment]
Hey @shaomeng, I'm not able to reproduce this on master.

Question: Was this bug found on an older installer?  I've noticed that your vector field multiplier has four digits of precision.  It should be 10 by default on the current master branch.

**Comment by shaomeng** [comment]
> Hey @shaomeng, I'm not able to reproduce this on master.
> 
> Question: Was this bug found on an older installer? I've noticed that your vector field multiplier has four digits of precision. It should be 10 by default on the current master branch.

@sgpearse this was using the installer from the last round.

**Comment by shaomeng** [comment]
I cannot reproduce it either. Let's close it and wait to see if it shows up again.
