### ISSUE TITLE
Rewrite ContourRenderer "line cache" storage

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#217]
The current code needs to be rewritten. For example there is a line:

`_lineCache[std::pair<int, int> indexpair] = *(new vector<float*>);`

**Comment by clyne** [comment]
The contour render, in general, needs refactoring. The code needs major cleanup, and should not unnecessarily resampling the grid to support the contouring algorithm: i.e. when the contouring surface aligns with the data the native grid should be used.
