### ISSUE TITLE
Changing colormapped variable breaks flow

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2181]
1. Open the most recent VDC POP/KISTI
2. Create a flow renderer
3. Setup as shown in gif
4. Change the colormap variable

The flow is now incorrect.

![out](https://user-images.githubusercontent.com/2772687/73394444-e275f700-429a-11ea-8001-efe3aba84b5e.gif)

**Comment by shaomeng** [comment]
I can no longer reproduce it with the latest 2D fix. Will close it for now and re-verify the next round.
