### ISSUE TITLE
Flow does not work with MPAS-O

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2182]
1. Import MPAS/MPAS-O
2. Create/Enable a Flow renderer
3. Change settings so something is visible
4. Play with variables selecting different ones

- By comparing with 2DData renderer, flow does not look correct (not sure)
- Eventually when I selected a different variable, vapor crashed.

**Comment by clyne** [comment]
There are no velocity fields in this data set. @stasj you're going to need to provide something more concrete if we're going to fix anything. E.g. which variable caused a crash?.

**Comment by StasJ** [comment]
The crash was non-deterministic so no.
