### ISSUE TITLE
Create a second renderer window seems broken

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2184]
To reproduce: (updated)
1. Open VAPOR, import CDF file: `/little_glade/shaomeng/cm1.nc`
2. Create a slice renderer and enable it.
3. Click `new` renderer button
3. Click `X` on the top left corner to close new renderer window.
3. Now try to open the renderer creation window, but notice that it's broken.

Platform: 
cisl-vapor

![slice](https://user-images.githubusercontent.com/814885/73398036-ebb69200-42a1-11ea-8322-223dda526669.gif)

**Comment by StasJ** [comment]
Cannot reproduce:

![out](https://user-images.githubusercontent.com/2772687/73403591-fcb8d080-42ac-11ea-903d-29fc96b38bc1.gif)

**Comment by sgpearse** [comment]
@shaomeng - Do you happen to recall if you had previously clicked the X on the upper left corner of the new-renderer dialog?

We saw this behavior on other operating systems as well, but supposedly fixed the problem in #1935.

**Comment by shaomeng** [comment]
@sgpearse your tip helps to specify the issue. Now I've updated the description so it can be reproduced.

**Comment by sgpearse** [comment]
Seems to be a bug in our version of Qt (5.12.4)

https://bugzilla.redhat.com/show_bug.cgi?id=1727479
