### ISSUE TITLE
VAPOR's exe file opens new windows as opposed to activating an existing window.

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#2188]
When clicking on VAPOR's executable file, VAPOR opens a new session window as opposed to activating an existing window if one is already open. This allows for multiple sessions to be open at once which can quickly eat up drive memory. This is either a bug or a feature, depending on how you look at it.

I was able to open 83 VAPOR windows before the screens were displayed as solid black. (If I don't try to break things who will?) VAPOR was able to load up 4 different screens with four different sessions of four different sets of data.

**Impact**
- [ ] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [x] Low - User productivity trivially degraded

### Desktop
 - OS and version: Linux Redhat Enterprise 7
 - Version: 3.2.0.85396a7.

**Comment by clyne** [comment]
The ability to open multiple sessions at once is the desired behavior.
