### ISSUE TITLE
Image Capture Crash.

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#2192]
(I was told to write up a new report for this)

When selecting image capture, "Select destination" doesn't appear and VAPOR crashes shortly after.

The frequency of this occurring appears proportional to the amount of changes made to the renderer display.

If I load up a previously saved session with a flow renderer, selecting capture -> image sequence or single image (png). VAPOR will display a message to credit it, and then the image destination window will open as normal.

If I load up a new session, manually create and adjust a flow renderer, move the screen around a bit, edit the region, change the integration steps and vector multiplier, then select capture -> image sequence or single image, VAPOR will display the message for crediting as usual, but the image destination window will not show up. After a brief delay, VAPOR will crash.

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [x] Did VAPOR crash?
- [ ] Did you get wrong results?

**Impact**
- [ ] High - User productivity significantly degraded
- [x] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### Desktop
 - OS and version: Redhat Linux Enterprise 7
 - Version: 3.2.0.85396a7.

**Comment by clyne** [comment]
@stasj please see if you can reproduce and then we will assess priority

**Comment by StasJ** [comment]
Cannot reproduce with current master or current installer.
