### ISSUE TITLE
Isosurface edge does not cut cleanly.

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#2198]
When using the region box sliders to cut a cross section of the renderer, by shrinking the region box on a side, the isosurface renderer does not consistently cut off the image, and erases part of it based on perspective.
Note the eye of the hurricane in this  gif. The storm is cut in half, with the cut going through the eye of the storm. When this image is rotated, however, the cut off "moves", based on perspective and the cut off "moves away" from the eye.

![isoglitch2](https://user-images.githubusercontent.com/56135291/73565897-77731e80-445a-11ea-97cf-1fd9081fd292.gif)

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [ ] Did you get wrong results?

**Impact**
- [ ] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce

1. Make an isosurface render
2. change mode to Region
3. Shrink the region sliders to cut the image in half.
4. Move the camera freely to see the cut inconsistency.

### Desktop
 - OS and version: Linux Redhad Enterprise 7
 - Version: 3.2.0.85396a7.

### Additional context
Add any other context about the problem here. Attach any (zipped) relevant files, such as data, configurations, session files, etc.

**Comment by StasJ** [comment]
@jvalan this is fixed in the new release which will be out by the end of today or early next week most likely.
