### ISSUE TITLE
Slice Renderers look different after reloading session file

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2201]
### Steps: (Updated)
1. Open VAPOR, load CDF compliant data: `/little_glade/shaomeng/cm1.nc`
2. Create a slice renderer. Set the Z location to 3.7 in the Geometry tab. Enable this renderer. 
3. Repeat step 2, with a different Z location value: 6.
3. Repeat step 2, with a different Z location value: 10.
4. Repeat step 2, with a different Z location value: 16.
4. Rotate the scene and observe the 4 planes that are rendered.
3. Save the current state into a session file.
3. Close VAPOR, and then re-open VAPOR, and load the saved session file.
3. Rotate the scene and observe the 4 planes that are rendered. They look different from step 6.

Platform: cisl-vapor
Version: Official 3.2 release. 

Before:
![good](https://user-images.githubusercontent.com/814885/73575094-a1194f00-4434-11ea-9f17-72b946a85b39.gif)

After:
![bad](https://user-images.githubusercontent.com/814885/73575100-a6769980-4434-11ea-83f7-76e9f0badab8.gif)

**Comment by shaomeng** [comment]
@shaomeng  will provide more details on how to reproduce it.

**Comment by clyne** [comment]
Re-assigned to @StasJ
