### ISSUE TITLE
Windows 10 VMWare VM on Mac Catalina Host Machine?

### ISSUE THREAD

**Issue by jweisbaum** [NCAR/VAPOR#2202]
Has anyone been able to successfully run Vapor 3.1.0 on a Windows 10 VM on Mac Catalina using VMWare Fusion? I keep encountering the OpenGL error where it thinks my machine only supports OpenGL 3.0 and then crashes. GLView shows that the vm supports OpenGL 3.3. Running Vapor 3.1.0 on my Mac natively works. I've seen other permutations of this question so sorry if this is a repost, but it didn't look like anyone else was running a Windows VM on a Mac host.  Thanks.

**Comment by StasJ** [comment]
Hi, Vapor heavily utilizes the GPU and VMs generally do not support this well, thus we do not officially support running Vapor on a VM. Vapor will automatically request the highest supported version of OpenGL from the OS so I'm afraid this is outside of our scope.

**Comment by jweisbaum** [comment]
Maybe I filed this in the wrong place. I know this is not a bug and vm support is out of scope, but I guess I was just wondering if anyone in the community has pulled this off. Is there a list serve or a more appropriate forum where I can ask this? Thanks.

**Comment by jweisbaum** [comment]
Also can you confirm whether or not the compatibility open gl profile is required? Thanks.

**Comment by shaomeng** [comment]
> Maybe I filed this in the wrong place. I know this is not a bug and vm support is out of scope, but I guess I was just wondering if anyone in the community has pulled this off. Is there a list serve or a more appropriate forum where I can ask this? Thanks.

No, this is the proper forum for feedback like this. 
There hasn't been a bug report like this, and we're not even aware of a second user who uses VAPOR in a VM, considering that we have release for all three major platforms. Can you let us know what your use case is, and why it is desired to run VAPOR in a VM?

**Comment by shaomeng** [comment]
> Also can you confirm whether or not the compatibility open gl profile is required? Thanks.

I don't think it's required. Can @StasJ confirm?

**Comment by jweisbaum** [comment]
I do offshore sailboat racing and cruising and I'd like to be able to use VAPOR for weather analysis. Using a VM is very useful because I can load it up with my weather utilities and transfer it from computer to computer and the owners of the boat don't have to know or care anything about my environment. 

It turns out that version 3.2.0 DOES work on my VM, so thanks for that! VMs only support the core profile of Open GL so please keep that in mind for future development. Thanks for all your work on this!
