### ISSUE TITLE
Vapor does not contain any version number on macOS

### ISSUE THREAD

**Issue by core-code** [NCAR/VAPOR#2208]
Vapor does not contain any version number information on macOS. each apps is supposed to contain numeric version number information.

<img width="546" alt="Screenshot 2020-02-04 at 21 07 51" src="https://user-images.githubusercontent.com/1261954/73782581-9e9b5a00-4792-11ea-8dd0-9f033b9a9b77.png">
<img width="261" alt="Screenshot 2020-02-04 at 21 07 36" src="https://user-images.githubusercontent.com/1261954/73782583-9e9b5a00-4792-11ea-8aa7-0e86746cc9dd.png">

the problem is that the CFBundleVersion and CFBundleShortVersionString entries in your Info.plist file are missing.

funnily, you do have the CFBundleLongVersionString but this has been deprecated for more than 10 years, and has been completely un-used by macOS for at least a decade.

**Comment by clyne** [comment]
Thanks for your help!
