### ISSUE TITLE
Region box does not move with bounding box during timesteps

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#2217]
This bug still ls not fixed and its page was labelled as fixed and closed.
![region](https://user-images.githubusercontent.com/56135291/74043066-9e80a180-49c0-11ea-82c0-a7325bd3e478.png)

After importing multiple nc data files into one timestamped layer, press play on the animation tab. The rendered image and white bounding box will move, but the region box will stay fixed in its original position, and will cut off the edges. Attempting to make the region box bigger results in the region box simply snapping into the inside of the white box, as region refuses to extend beyond the box. If the white box and region boxes are both completely separate from each other, and the renderer snaps back, an error will occur when VAPOR tries to make all of the dimensions of the region box 0,0,0.

[Dorian Vertical Redone.vs3.zip](https://github.com/NCAR/VAPOR/files/4171909/Dorian.Vertical.Redone.vs3.zip)

### Desktop
 - OS and version: Linux 3.10.0-514.el7.x86_64 #1 (Redhat Enterprise 7)
 - Version: Vapor 3.2.0.51fb2ef

**Comment by clyne** [comment]
duplicate: need support for moving domains
