### ISSUE TITLE
Broken Image Renderer

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2225]
To reproduce:
1) Open Vapor, import the WRF file in /little_glade/bugs/2225
2) Create and enable an image renderer

![Screen Shot 2020-02-10 at 9 06 00 AM](https://user-images.githubusercontent.com/9522770/74167122-01528280-4be5-11ea-8e90-e1b27ecfd0da.png)

**Comment by StasJ** [comment]
Still gives invalid image

**Comment by StasJ** [comment]
Is this the expected image?

![s](https://user-images.githubusercontent.com/2772687/102175115-21358100-3e5c-11eb-8ef4-7cd5556c03f6.png)

**Comment by clyne** [comment]
Correct. The cover a very small region.
