### ISSUE TITLE
Use fix-sized data structures in function interfaces

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2249]
### Description
Use Use fix-sized data structures in function interfaces. Examples include a point in space, a color value, and a bounding box. 

### Possible implementations
1. Use `std::array<float, 3>`, could be aliased to a shorter name: `using vvec3 = std::array<float, 3>;`
    - Pros: baked into C++, ready to be used with many std algorithms.
    - Cons: none as far as what I'm aware of.
2. Use `glm::vec3` and alike.
    - Pros: ready to be used with many glm algorithms. 
    - Cons: shows up in a debugger in a VERY verbose form. I.e., it displays way way more information than simple 3 values.

**Comment by shaomeng** [comment]
This task is dependent on #2250

**Comment by clyne** [comment]
The Grid class has been refactored to use std::array for its API

**Comment by shaomeng** [comment]
I think this task is finished.
