### ISSUE TITLE
Determine data bounds when loading transfer functions without them

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#225]
If a saved transfer function is missing a DataBounds parameter, vapor will not set a proper bounds and will result in a glitch state until the user adjusts the bounds in the gui. Currently, the transfer functions have a default bounds set in them.

**Comment by clyne** [comment]
Followup:

Loading a system provided colormap results in improper data range on the TF. 

To reproduce:
1. Load katrina and enable the 2D renderer with the U10 variable
2. Note the data range on the TF editor. It's about -53 to 35.
3. Load the CoolWarm color map. The TF data value range changes to -6429 to 1067, and there is no way to correct it.
