### ISSUE TITLE
Flow output support lat-long format and geo-friendly time format

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2258]
## Description
Geospatial data use a lat-lon coordinate system for spatial coordinates, and express time as a formatted time string that we refer to in VAPOR as a "time stamp". A formatted time strings look like: 2007-04-01_00:00:00.

Internally VAPOR projects lat-lon coordinates into "meters on the ground" using a map projection, and time stamps into units of seconds. This is necessary to keep units consistent and ensure that things like flow integration work correctly. The conversion of geographical coordinates is performed using the proj4 library and (typically) whatever map projection is contained in the model output file (if no projection is specified VAPOR assumes an equidistant cylindrical projection). The conversion of formatted time strings to seconds is performed using Unidata's UDUnits package (specifically, the ut_decode_time() function.

The flow renderer uses the internal representation of space and time coordinates when reading seed locations from a file, or outputting streamline or pathline coordinates. This makes it challenging for users with geo-referenced spatial data, or data with formatted time strings, to figure out how to specify/interpret coordinates. We should provide the option to input (or output) flow coordinates (eg seed points, integration points) in whatever coordinate system the user's data is in. I.e. transform meters-on-the-ground and time in seconds back to lat-lon and formatted time strings.

**Comment by clyne** [comment]
@shaomeng 

Regarding time: we currently do not record the format of the time stamp stored in the data. We could save this information and make it available, or we could simply offer small number (possibly one) of formatted time stamps for the user to choose from. This would certainly be the simplest approach. The conversion of time from seconds to a formatted time string can be done with the UDUnitsClass::DecodeTime. An example can be found in DataStatus.cpp.

For spatial coordinates the conversion from Projected Coordinate System (PCS) to lat-long can be performed with the Proj4API class. The class must be initialized as follows:

    Proj4API proj4API;
    int rc = proj4API.Initialize(proj4String, "");
    if (rc < 0) return(-1);

where 'proj4String' is the string returned from DataMgr::GetMapProjection()

You can then call one of the overloaded Proj4API::Transform methods to do the actual conversion. Look inside any of the lib/render/Geo*cpp files for example invocations.

**Comment by shaomeng** [comment]
@clyne What's a good data set to test this conversion?

**Comment by clyne** [comment]
Any of the CAM, WRF, ROMS, or MOM data should work fine. The WRF data, e.g. Duku, might be easier to verify that the results look reasonable because the region is localized.

**Comment by shaomeng** [comment]
> Any of the CAM, WRF, ROMS, or MOM data should work fine. The WRF data, e.g. Duku, might be easier to verify that the results look reasonable because the region is localized.

What's a good way to know when to apply this type of conversions, and when to not?

**Comment by clyne** [comment]
> > Any of the CAM, WRF, ROMS, or MOM data should work fine. The WRF data, e.g. Duku, might be easier to verify that the results look reasonable because the region is localized.
> 
> What's a good way to know when to apply this type of conversions, and when to not?

@shaomeng query the data mgr for a map projection string. If not empty there are lat-Lon coordinates
