### ISSUE TITLE
Layered grid doesn't support grids with a dimension length of 1

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2259]
The Grid::ConstNodeIterator's count seems to be nondeterministic, and varies in size when running the testGrid smoke test.

To reproduce:
1) Build VAPOR on the smokeTests branch with TEST_APPS set to ON.
2) issue the following test multiple times, and note the ConstNodeIterator count at the bottom of the output.

<build_directory>/bin/testGrid -dims 1x1x1

**Comment by clyne** [comment]
Note changing node count. Not addressed by PR

**Comment by clyne** [comment]
@sgpearse you are not initializing count before calling TestNodeIterator in gridTools.cpp
