### ISSUE TITLE
Question: What are the minimum hardware and software specifications for Mac

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#2266]
Given the recent virus, I am forced to work on my personal computer, which is a Macbook Pro. I installed the weekly Darwin.dmg file and installed VAPOR, but was unable to open it, with an error message recommending that I check to see the specifications.
My current device is a mid-2015 Macbook Pro running software version 10.13.6 High Sierra.

**Comment by StasJ** [comment]
Vapor should work on that system. Could you specify what the error message you are encountering is and the installer version you are using?

**Comment by jvalan** [comment]
I am told "Vapor cannot be opened because of a problem. Check with the developer to make sure vapor works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.

Click Report to see more detailed information and send a report to Apple."

The installer I used was VAPOR3-3.2.0-Darwin-Weekly.dmg the week of march 30th.

Additionally I have a 2.5 GHz Intel Core i7 processor.

**Comment by StasJ** [comment]
There should be a dropdown with additional information. You could also try running vapor from the command line to get this info. Could you try running the 3.2 release rather than the weekly build?

**Comment by jvalan** [comment]
Alright, the main february 3.2.0 release I am able to boot up, but it seems to have a few issues.
![vapor](https://user-images.githubusercontent.com/56135291/78933746-c7341e80-7a77-11ea-9356-f84e4ac02324.jpeg)
Some of the buttons seem misaligned, such as the renderers, navigation, and settings bar. And the render window itself shrunk to the top of the screen. I kind of wanted to be able to help identify bugs in new releases now that I didn't need to ask for a custom installer.

**Comment by StasJ** [comment]
Hi the graphical bugs you mentioned above exist because the GUI is not fully updated until you open a dataset. Once you import a dataset, these issues should be resolved.
