### ISSUE TITLE
User based windows installer (no Admin privilege)

### ISSUE THREAD

**Issue by MarkUoLeeds** [NCAR/VAPOR#2272]
### Is your feature request related to a problem?
A clear and concise description of the problem. E.g. I'm always frustrated when [...]
Your provided windows installer requires system admin privileges. My system is owned by the university and I only allowed to install through their "store". However, I am able to install per user packages e.g. Anaconda3, MobaXTerm and other s/w that is sensible for user only install.
### Describe the solution you'd like.
Can you make the windows installer not need Admin privilege?

**Impact**
(*Please click check boxes AFTER submitting ticket*)
- [x] High - User productivity significantly improved
- [ ] Medium - User productivity partially improved
- [ ] Low - User productivity trivially improved

### Is your feature request specific to a data set?
Can you use one of our example data sets to demonstrate the desired feature?
* Please provide a data set.  If the data set is small, please zip and upload it as an attachment. If it is large, please provide instructions on how we can contact you to obtain this data.

### Additional context
You are limiting the exposure of this software if i cannot install it on my Windows system

**Comment by StasJ** [comment]
Hi Mark,

Sorry that you are running into this problem. Our installer currently only supports a normal windows install. Our team is currently quarantined and none of us use Windows machines so it would be challenging for us to add support for a single user install at the moment. One thing you could do is if you have another windows machine you could use (or you could use a windows VM on your school machine), you could install vapor there and then copy and paste the installed directory (/Program Files/VAPOR) onto your school machine to a user directory. Then you would have to set the environment variable VAPOR3_HOME to the path of that directory and vapor should work.

**Comment by MarkUoLeeds** [comment]
Hi, your advice has worked to some extent (complains about "banner" on start up). So i will download the katrina sample data and experiment. I hope I changed the correct env var, I am not an expert windows developer, I just have to use it for majority of my work (I prefer working on Unix HPC systems)
Thanks for the help (I too am required to stay at home but for social distancing reasons).
I would like to leave the issue open another 24 hours (or at least until I have confirmed that i can work with this installation 3.2.0)

Mark

**Comment by MarkUoLeeds** [comment]
Hello Again,
so now I have Katrina.zip unzipped as 14 hours of 20050829 but then Vapor failed to import WRF-ARF 
Here is the log of the error message:

Vapor 3.2.0.<debug>
OS: Windows 6.2 (9200)

-------------------
Failed to load data
-------------------
Failure to open data set of type "wrf"
Failed to initialize data importer
Failed to initialize udunits2 library : Can't open installed, default, unit database
UDUnits Error: Can't open installed, default, unit database
UDUnits failed to initialize
Attempting to fall back to system install
Could not find VAPOR installed UDUnits database
------------------
Vapor 3.2.0.<debug>
OS: Windows 6.2 (9200)

It might be I that have to modify more than the PATH for my "faked install".

Mark

**Comment by StasJ** [comment]
Hi Mark,

From the error message it seems to me like `VAPOR3_HOME` is not set. You mention you set `PATH` however you do not need to set that, you need to set `VAPOR3_HOME`. To do this you need to can follow the instructions [here](https://www.computerhope.com/issues/ch000549.htm) but instead of editing the PATH, create a new variable called `VAPOR3_HOME` and set it to the directory in which `vapor.exe` resides (i.e. if you have `C:/home/vapor/vapor.exe` set `VAPOR3_HOME` to `C:/home/vapor`)

**Comment by StasJ** [comment]
I am closing this issue as resolved. Please feel free to reach out if you have additional questions.
