### ISSUE TITLE
jsmall no longer opens

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2273]
If you try opening jsmall (I am using the most recent VDC version on little_glade) you get the following error:

```
Failure to open data set of type "vdc"
Failed to initialize horizontal coordinates
Failed to initialize derived coord variable
Invalid variable "Cs_r"
```

On OSX.

**Comment by clyne** [comment]
This issue has been partially fixed by PR #2277. However, the fix only works for VDC files generated after #2277. Older VDC files will still not open.
