### ISSUE TITLE
Possible bug with OS X El Capitan v10.11.6

### ISSUE THREAD

**Issue by stavrosdafis** [NCAR/VAPOR#2287]
I downloaded the "VAPOR3-3.2.0-Darwin.dmg" installer in my personal Mac and I am not able to run the application. 

Even though the application has been registered to the exceptions of apps downloaded from an unidentified developer, by opening from the shortcut (ctrl+open), I received the following message:
- LSOpenURLsWithRole() failed with error -10810 for the file /Applications/vapor.app.

I changed the permissions of the MacOS folder contents:
- chmod +x /Applications/vapor.app/Contents/MacOS/vapor
or
- chmod -R 777 /Applications/vapor.app/Contents/MacOS/vapor

but received again the aforementioned message about the unidentified developer. The second time, the Vapor icon was jumping in the dock for about a minute and then disappeared. 

Of course, I tried to install the application again and restarted the mac with no success. Please let me know if there is a bug for my OS. 

My system is a MacBook Pro with OS X El Capitan, version: 10.11.6

**Comment by clyne** [comment]
Unfortunately, because of stay at home orders it is difficult for us to test on different operating systems at this time. The problem you noted might be specific to your system. Please see:  http://www.thexlab.com/faqs/error-10810.html

**Comment by stavrosdafis** [comment]
Thank you for your answer. I overcame the -10810 problem by changing the permissions of the folder and this message appeared when I ran vapor.app:

Sorry, "" can not be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.11.6.
logout

Apparently I need to upgrade my OS since Qt does not support version 10.11.6 anymore.

**Comment by clyne** [comment]
Interesting. Are you using the VAPOR 3.2 "stability build" or one of the "nightly builds". We recently upgraded the version of Qt that we are using, but the 3.2 stability build still uses the older version of Qt.

**Comment by stavrosdafis** [comment]
I was not able to find these two versions on Github. I have tried with the "VAPOR3-3.2.0-Darwin-Weekly.dmg" and "VAPOR3-3.2.0-Darwin.dmg". I have not tried to build the code from source if this is what you mean.

**Comment by clyne** [comment]
Those are the versions I was referring to. I mistakenly called the "weekly" a "nightly".  Yes, I would recommend updating your O.S. if you can, with the caveat that this can negatively impact your overall system performance if you have an older machine. There is no guarantee that this will fix your problem, but it makes it much more likely that we can help you if it does not.

**Comment by stavrosdafis** [comment]
Thank you for the information. Indeed, upgrading the OS in an old machine is risky and I am skeptical. I may try installing VAPOR in a Unix system.
