### ISSUE TITLE
Goodbye

### ISSUE THREAD

**Issue by jvalan** [NCAR/VAPOR#2288]
As of April 24th, my contract with NOAA through Colorado State University has ended and I will no longer be reporting bugs, nor enhancements, nor feedback. Stay safe and healthy everyone!

**Comment by clyne** [comment]
Very sorry to hear that. Thank you so much for all of the invaluable feedback you've provided to help make VAPOR a better community tool. I wish you all the best in your future endeavors. Stay healthy!
