### ISSUE TITLE
Vapor does not build on yellowstone

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#230]
`call of overloaded 'isnan(double)' is ambiguous`

**Comment by shaomeng** [comment]
Is that the machine that's gonna be gone in less than 2 month?

**Comment by clyne** [comment]
It may be going away, but we’re not planning on dropping support for RH6 systems at this point.

jc

> On Nov 6, 2017, at 5:50 PM, Samuel Li <notifications@github.com> wrote:
> 
> Is that the machine that's gonna be gone in less than 2 month?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
Looking into the error closely, that's something introduced in c++11. You
might be able to get around it if you load a newer compiler on Yellowstone.
