### ISSUE TITLE
OSX Weekly Build Broken

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2305]
When opening any dataset using the current OSX weekly build it will crash.

**Comment by sgpearse** [comment]
I can't reproduce this on my work machine.  Could be a dataset specific problem.  @stasj what dataset did you load?

Installer version used: 3.2.0.59c3322

**Comment by StasJ** [comment]
I just tested the most recent installer (built on 6/26) and it is working now. The one that was broken for me was the previous installer.
