### ISSUE TITLE
2D Renderer Z scale is wrong

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2324]
It seems the Contour and TwoDData renderers are scaling their height variables too much.

To reproduce:
1) Spin up Vapor, import a katrina file (/glade/p/cisl/vast/vapor/data/wrf/katrina)
2) Create a Contour or TwoDData renderer and apply the HGT height variable.  HGT has a maximum value of ~285 meters, however the rendering will exceed the +z side of the bounding box, which is ~3e6 meters.

![Screen Shot 2020-07-28 at 7 22 15 AM](https://user-images.githubusercontent.com/9522770/88671063-16dc3b80-d0a3-11ea-99b7-59809c72c973.png)
.

**Comment by sgpearse** [comment]
Dataset in question was corrupt.

**Comment by daliagachc** [comment]
hi! how did you find that it was corrupted? im having the same issue

**Comment by clyne** [comment]
@sgpearse can you respond to this?
