### ISSUE TITLE
Does this always get 3?

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#233]
https://github.com/NCAR/VAPOR/blob/d4d9fa403d20a9e9f4c372406d7596b472f3179d/apps/vaporgui/GeometryWidget.cpp#L245

The code above is supposed to get the dimensionality of the active renderer. It is asking the `rParams` the values stored with the `_nDimsTag`. My question is, a RendererParams doesn't even know the `_nDimsTag` tag. Does it always get 3 as the returned value here?

**Comment by clyne** [comment]
Good question. There is something strange going on here. I’ll take a look in the a.m.

> On Nov 6, 2017, at 6:18 PM, Samuel Li <notifications@github.com> wrote:
> 
> https://github.com/NCAR/VAPOR/blob/d4d9fa403d20a9e9f4c372406d7596b472f3179d/apps/vaporgui/GeometryWidget.cpp#L245
> 
> The code above is supposed to get the dimensionality of the active renderer. It is asking the rParams the values stored with the _nDimsTag. My question is, a RendererParams doesn't even know the _nDimsTag tag. Does it always get 3 as the returned value here?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by sgpearse** [comment]
I believe this is the same issue that John and I talked about a few times last week with regards to the VariablesWidget.  We considered adding get/set methods on RenderParams for the number of dimensions, or just leaving things as is.  I forgot the reason that it was not necessarily a suitable RenderParams tag though.

**Comment by shaomeng** [comment]
@sgpearse Are we in agree that this piece of code isn't doing anything? If so, can I go ahead and eliminate this `if` condition, and close this bug? 

Also, do you want to submit a feature request to request a GetDimentionality() function from RendererParams?

**Comment by sgpearse** [comment]
> @sgpearse Are we in agree that this piece of code isn't doing anything?

I'm not sure I believe that to be the case.  It appears to automatically set the TWOD or THREED flag, which controls which GUI components are displayed to the user.

> Also, do you want to submit a feature request to request a GetDimentionality() function from RendererParams?

John and I talked about this on Friday morning and there was a reason (that I do not recall) that this is one option, but we agreed to leave things as-is for now.  This was in regards to the same methodology being used in the VariablesWidget to attain dimensionality.

**Comment by shaomeng** [comment]
Hmm, sorry @sgpearse  for the confusion... I meant does the following line of code always gets 3 for `ndim`?
https://github.com/NCAR/VAPOR/blob/d4d9fa403d20a9e9f4c372406d7596b472f3179d/apps/vaporgui/GeometryWidget.cpp#L245

**Comment by sgpearse** [comment]
That's just a default value.  At the time that was written, we planned on
supporting 3D variables.  It could be changed to a 2, and then changed back
next release.
