### ISSUE TITLE
Expat is needed to compile VAPOR

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2337]
### Describe what needs to be documented.
It should be documented that `libexpat-dev` will be needed to compile VAPOR on Ubuntu.

### Is the documentation missing?
The doc misses this detail. Or, the VAPOR could include the requirement of expat in its 3rd party libraries.

### Is the documentation there but needs improvement?
Yes

*Please provide the url of the documentation.*
https://www.docs.vapor.ucar.edu/downloads.html#installation-instructions

**Comment by sgpearse** [comment]
@shaomeng - Hey, you're right about this and there are currently changes to address the extra libraries needed for CentOS and Ubuntu, in #2306
