### ISSUE TITLE
Weird use of enum in GeometryWidget.

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#234]
https://github.com/NCAR/VAPOR/blob/d4d9fa403d20a9e9f4c372406d7596b472f3179d/apps/vaporgui/GeometryWidget.h#L21-L25

The use of enum is looking weird to me in `GeometryWidget`. This is because there are generally 2 usages of enum, and this code is sitting in between.
More specifically:

1.  Enums are used for *exclusive* properties: 
```
enum Color{ Black, Red, Yellow};
```
Here one item cannot be Black and Red at the same time.

2. Enums are used for *mutually inclusive* properties:
```
enum BoxProperty{ Clickable, Editable, Highlightable };
```
Here one box could be clickable and editable at the same time.

The usage in `GeometryWidget` seems to imply that this widget must be either 2D or 3D just like enum usage 1. At the same time no matter it's 2D or 3D, it could have a VECTOR property, just like enum usage 2. How to use this `Flags` is then very confusing.

**Comment by sgpearse** [comment]
Interesting.  I spent a little bit of time looking for information on this, but I didn't see anything that enumerators have 2 strict use cases.  Is there a style guide that you're referencing?

I'm adding John to the conversation because  the VariablesWidget works in the same regard, but with its enumerator containing {SCALAR, VECTOR, HGT, COLOR}.  I believe that SCALAR and VECTOR are mutually exclusive,  while HGT and COLOR are mutually inclusive.

**Comment by shaomeng** [comment]
There are certain benefits of following the 2 use cases.

With use case 1, you define the color of an item with syntax:
```
item.Color = Color::Yellow;
```
and you'll never give a color to `item` that is not previously defined.

With use case 2, you can manipulate bit values on every property and every combination is valid.

Using Enums sitting in between of case 1 and 2 will result in loss of these benefits.

**Comment by sgpearse** [comment]
I'm feeling that we should talk about this as a group at our next round-table.  We didn't consider this as a requirement when we wrote our first promoted widgets over the summer.

I believe this implies having two sets of flags in each of our promoted widgets; supporting exclusivity and inclusivity.

**Comment by sgpearse** [comment]
Fixed in Pull Request 537
