### ISSUE TITLE
Appearance tab not resizing properly

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2356]
The appearance tab is not resizing itself to fit within the control panel.

Correct:
![Screen Shot 2020-09-04 at 7 41 26 AM](https://user-images.githubusercontent.com/9522770/92245774-0f6a3800-ee82-11ea-94e4-75413f5c7af6.png)

Incorrect (right side is clipped):
![Screen Shot 2020-09-04 at 7 41 17 AM](https://user-images.githubusercontent.com/9522770/92245797-15f8af80-ee82-11ea-8856-0f5cc64c76b1.png)

**Comment by shaomeng** [comment]
The issue now shifts to "Settings" tab.

![resize](https://user-images.githubusercontent.com/814885/101081841-d9fbe600-3567-11eb-9f5f-343c1709d7fb.png)
