### ISSUE TITLE
Allow the user to specify when TMS images are downsampled

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2360]
We currently downsample TMS images when their width or height is > 1024 pixels. This is currently hard-coded.

Sometimes we don't want to downsample the image at all.  Currently, we are unable to render high resolution TMS images of CONUS.

This PR allows the user to specify the threshold at which we downsample TMS images in the Image renderer.

**Comment by clyne** [comment]
@sgpearse, @stasj this PR should have been closed by PR #2358. However, we seem to have lost the GUI that enables TMS resolution selection. At least some other parts of the PR were successfully merged, but the GUI is missing. I'm guessing this might have happened when we merged #2384 ???
