### ISSUE TITLE
Image renderer not available for 3D only data sets

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2366]
The image renderer is not selectable from the list of renderers if the data set does not contain any 2D Variables. 

To reproduce:
1. Load the data set from Glade vapor/Bugs/2366
2. Try to create an Image renderer

**Comment by sgpearse** [comment]
Works with the installer, but vapor dumps core on close when running from source build

**Comment by StasJ** [comment]
> Works with the installer, but vapor dumps core on close when running from source build

I cannot reproduce this.

**Comment by clyne** [comment]
Nor can I. Closing.
