### ISSUE TITLE
"Install Command Line" crashes on Windows 10

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2367]
User Nicholas Boselli has reported the following bug in vapor mailing list:

I have a problem when operating Vapor. I chose to download Vapor 3.2 (stable version) on windows 10 and when I click on the “install command line tools” button under the “Tools” tab, Vapor immediately crashes.

**Comment by StasJ** [comment]
I only have a Windows 8.1 machine and it works as expected. I have no access to a Windows 10 machine if that is the issue.

**Comment by clyne** [comment]
@sgpearse do you have a windows 10 system you can test this on? 

cc @StasJ

**Comment by sgpearse** [comment]
I've tried to reproduce this on three Win10 machines to no avail.

**Comment by clyne** [comment]
Lets close it and call it fixed.
