### ISSUE TITLE
Vapor GUI becomes unreadable after enlarging the window.

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2369]
User Nicholas Boselli reports on vapor mailing list that VAPOR GUI becomes unreadable after enlarging the window.

"I also encounter bugs when I try to enlarge the vapor window and it glitches out making everything unreadable."

**Comment by clyne** [comment]
Sam will reach out to user for more info.

**Comment by shaomeng** [comment]
The user did not have a screenshot nor a sequence to reproduce it. I'll close this bug report for now.
