### ISSUE TITLE
Statistics tool cannot be closed once opened

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2371]
The Statistics window cannot be closed, nor can the VAPOR application, once the statistics tool has been opened. Since the Statistics window cannot be moved, the only recourse is to kill the application. 

To reproduce:
1. Open the app and load any data set
2. Open the Statistics tool. There is no way to close it.

**Comment by shaomeng** [comment]
Plot window seems to exhibit the same issue...

**Comment by clyne** [comment]
Reassigned to @StasJ
