### ISSUE TITLE
multi-variable selector needed

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2400]
The Python editor, Plot tool, Statistics tool, and now flow renderer, all support the selection of 0 to n variables. A multi-variable PWidget that could be used by all of these utilities would be useful. 

Requirements and comments

- It would be good to be configurable to support 2D, 3D, or 2D+3D lists of variables, the latter combining both 2D and 3D lists

- It should be possible to select (or deselect) 0 to N variables. 

- The current statistics and plot tools are pretty clunky; if the user wants to select multiple variables the selector has to be opened and closed for each variable. Removing variables is also a PIA. 

- The Python variable selector is a little more user friendly in that a list of variables is presented with a set of checkboxes so variables can easily be selected/deselected. 

@sgpearse @shaomeng, comments?

**Comment by shaomeng** [comment]
I can think of a desirable but not crucial requirement: 
- Keep the order of returned values as they appeared in the GUI. I.e., when a variable is selected, it's not simply attached to the end of the list of selected values. Rather, it's placed where it appears in the GUI.
