### ISSUE TITLE
Flow broken with ROMS data

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2412]
Streamline advection no longer works with the ROMS "jsmall" data set (and possibly others).

To reproduce:
1. Load Data/ROMS/jsmall
2. Enable Flow with default settings. Nothing is displayed. Changing various parameters (seed locations, direction, integration length) does not seem to help

**Comment by shaomeng** [comment]
I think this is fixed in PR #2385 . Let's close it for now and verify later.
