### ISSUE TITLE
Flow: Streamline data file name is hard to modify

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2419]
The output file for writing streamline data may only be set to existing file names.  Users will want to customize a new output file name.

Case 1:
1. Open Vapor with any dataset and create a Flow Renderer
2. In the Seeding tab, try to modify the default file under the "Write Flowlines to File" section

Case 2:
1. Open Vapor with any dataset and create a Flow Renderer
2. In the Seeding tab, click the "Select" button in the "Write Flowlines to File section
3. The dialog will not accept a new file name, only allowing the selection of preexisting files

**Comment by shaomeng** [comment]
I could reproduce this issue on Ubuntu. But, this is really a missing feature of the file widget. Maybe @StasJ  can make changes to `PFileOpenSelector` to support this use case?
