### ISSUE TITLE
Flow Renderer: Grid of seed points changes depending on <none> variable

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2424]
Changing the number of variables seems to affect the gridded seed distribution.

To reproduce:

1. Load our current DUKU VDC and create a Flow renderer
2. In the Seeding tab, reduce the Integration Steps to 10
3. Enable the renderer and note the 3x3x3 grid of seeds (we should see 5x5x5?)
4. In the Variables tab, set the V and W variables to "none"
5. Note that we now see a 5x3x4 grid of seeds (we should see 5x5x5?).

**Comment by shaomeng** [comment]
Hey Scott, can you do me a favor to shrink the grid box boundary a bit before step 3, and then see if the seed number change behavior is still there? @sgpearse

**Comment by sgpearse** [comment]
@shaomeng sorry I didn't get back to you sooner.  I do still see the 3x3x3 grid of seeds, after reducing the minimum X coordinate of the Box.

**Comment by shaomeng** [comment]
> @shaomeng sorry I didn't get back to you sooner. I do still see the 3x3x3 grid of seeds, after reducing the minimum X coordinate of the Box.

No worries. Can you try *increase* the the minimum X, instead of reducing it? In other words, make minimum X, Y, Z a little larger, and maximum X, Y, Z a little smaller?
