### ISSUE TITLE
Core dump when writing streamline file

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2443]
To reproduce:

1) Spin up Vapor, open DUKU
2) Create and enable a flow renderer
3) Click "Write to file" in the appearance tab
4) Check the variable "P" and click "Write to File"
5) Check the variable "PB" and click "Write to File"
6) Vapor will crash

**Comment by shaomeng** [comment]
@sgpearse I cannot reproduce this crash on cisl-vapor. Maybe there are some missing steps in the sequence of actions?
