### ISSUE TITLE
Default sampling rate for OSPRay unusable for many data sets

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2449]
The default sampling rate for the OSPRay volume renderer is unusable for many data sets. When incorrectly set the application can hang indefinitely.

To reproduce:
1. Load  Data/MPAS/FalkoJudt/30km/diag.2016-08-01_00.00.00.nc (also load he mes file, x1.static.nc
2. Enable the volume renderer. The application will not get past "copying data to OSPRay".

Note: attempting to reduce the computational load by reducing the rendering window to 10x10 and changing the scaling factor to as small as 0.0001 does not seem to help.

**Comment by StasJ** [comment]
This is unfortunately not controllable by us and was already mitigated in #2561
