### ISSUE TITLE
OSPRay renderer is the default

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2451]
The OSPRay renderer is the default renderer for Volume Rendering and isosurfaces, regardless of the data type. OSPRay should only be the default for unstructured grids (e.g. MPAS).

To reproduce:
1. Load any structured grid data set (e.g. Duku).
2. Create a volume renderer. 
3. Look under the appearance tab and OSPRay is the selected rendering algorithm

**Comment by StasJ** [comment]
This is working for me. It may be related to you having an Intel integrated GPU on your mac.

**Comment by clyne** [comment]
ospray should only be default for unstructured data

**Comment by StasJ** [comment]
@clyne This is intentional. We found that the intel drivers had issues with the curvilinear renderer so the regular grid renderer was made the default for intel systems. Once we added support for OSPRay, I made it the default for curvilinear grids on intel GPU machines. What would you like the behavior to be?

**Comment by clyne** [comment]
> @clyne This is intentional. We found that the intel drivers had issues with the curvilinear renderer so the regular grid renderer was made the default for intel systems. Once we added support for OSPRay, I made it the default for curvilinear grids on intel GPU machines. What would you like the behavior to be?

@stasj  OSPRay should only be the default for unstructured grids. For any other grid pick the default should be selected as it was previously.

**Comment by StasJ** [comment]
> > @clyne This is intentional. We found that the intel drivers had issues with the curvilinear renderer so the regular grid renderer was made the default for intel systems. Once we added support for OSPRay, I made it the default for curvilinear grids on intel GPU machines. What would you like the behavior to be?
> 
> @StasJ OSPRay should only be the default for unstructured grids. For any other grid pick the default should be selected as it was previously.

Ok.
