### ISSUE TITLE
Flow output file name does not agree with specified file name

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2454]
The default output file name is "VaporFlow.txt". However, on the Mac the name of the file that is generated is "vaporFlow.txt", not "VaporFlow.txt"

To reproduce:
1. Load Duku.nc
2. Enable the flow renderer
3. Note the "Target file" on the appearance tab. It's VaporFlow.txt.
4. Click "Write to file". The file that gets written is "vaporFlow.txt"

**Comment by shaomeng** [comment]
I cannot reproduce this bug on macOS 10.15. Maybe @sgpearse and @StasJ can help confirm if this behavior exists on their systems?

**Comment by clyne** [comment]
@stasj @clyne please see comment above.

**Comment by StasJ** [comment]
I cannot reproduce the issue.

**Comment by clyne** [comment]
Nor can I. Closing this.
