### ISSUE TITLE
Minimum bound for rake and geometry selector not editable

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2456]
The minimum bound for both the geometry and flow rake selector cannot be edited via the text box. The maximum bound seems to work fine.

To reproduce:
1. Load Duku
2. Enable Flow and set the Z axis number of seeds to 1
3. Try to enter 1000.0 into the minimum bound for the Z rake region. It's not possible. The same is true with the minimum bounds under the geometry subtab

**Comment by StasJ** [comment]
@clyne I am unable to reproduce this

**Comment by clyne** [comment]
It behaves like there is some kind of validation going on that only excepts certain inputs. Is that possible? May have to do a screen share and show you

**Comment by StasJ** [comment]
I followed the steps to reproduce and don't see the behavior you are experiencing. I can do a screen share or you could upload a video. I am currently available if you'd like to screen share.
