### ISSUE TITLE
Flow crash

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2461]
1. Create the dataset in #2307 using `vars2dxy`
2. Create a flow renderer
3. Select `test` for all the vars.
4. Enable

Vapor will crash

**Comment by shaomeng** [comment]
This issue can no longer be reproduced on the master branch as of 11/20/2020. I suggest we close it for now and verify later.

The created data set in question is attached as well.

[issue_2461.tar.gz](https://github.com/NCAR/VAPOR/files/5576344/issue_2461.tar.gz)
