### ISSUE TITLE
Flow crashes with CAM/Gaussian and MOM4/JinHeeYuk/ocean_eta

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2464]
1. Import `CAM/Gaussian` or `MOM4/JinHeeYuk/ocean_eta`
1. Create/enable a Flow renderer
1. Select TS as one of the variables

Vapor will crash

**Comment by shaomeng** [comment]
Seems to be the same issue as reported in #2477. After #2477 being fixed in #2502 , this behavior cannot be reproduced anymore.
