### ISSUE TITLE
camera controls -> Origin doesn't seem to work

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2469]
1. Open VAPOR, create a volume renderer.
2. Go to tab Navigation -> Viewpoint.
3. Change values in Camera Control fields. 
4. Notice that changing values in the first 3 rows will result in a change on the scene, but changing values in the last row (origin) will have no effect on the scene.

**Comment by sgpearse** [comment]
Possibly the same issue as #1231
