### ISSUE TITLE
Disabling Proj4 string deletes Image Renderer

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2475]
To reproduce:

1) Spin up Vapor with DUKU
2) Create an Image Renderer and enable it
3) In the Navigation->Viewpoint tab, uncheck the currently used proj string
4) The Image renderer gets deleted

**Comment by sgpearse** [comment]
Duplicate of #2066

**Comment by clyne** [comment]
If can't fix, could add warning to user.
