### ISSUE TITLE
Volume renderer taking a long time on WRF/rotlatlon/Alan2/d01

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2481]
Volume rendering on the WRF files in /glade/p/cisl/vast/vapor/data/Source/WRF/rotlatlon/Alan2/d01/ takes ~15 minutes on casper.  The grid is curvilinear and 192x96x27 .  Katrina renders near instantly on a 315x309x34 curvilinear grid.

To reproduce on Casper:

1) Import the wrf files in /glade/p/cisl/vast/vapor/data/Source/WRF/rotlatlon/Alan2/d01/
2) Create a volume renderer and enable it.  The rendering will complete in ~15 minutes.

**Comment by clyne** [comment]
@sgpearse which volume rendering algorithm are you using: regular, curvlinear, or ospray?

**Comment by clyne** [comment]
@sgpearse please verify that this is not simply a casper i/o issue

**Comment by sgpearse** [comment]
The rendering is nearly instantaneous now, so it must have been i/o

**Comment by clyne** [comment]
I've noticed lately that  I/O rates can be highly variable on glade (and sometimes unusably long). If you run 'top' and the CPU is in the D or S state you are most likely waiting on I/O.

**Comment by clyne** [comment]
Re-opening this. The rendering completes, but the results are wrong. Compare the Curvilinear grid algorithm with the Regular grid algorithm. I'd upload an image, but am unable at the moment :-(

**Comment by StasJ** [comment]
I cannot reproduce this. The dataset renders correctly in real time with both the regular and curvilinear renderers for me.

**Comment by clyne** [comment]
@StasJ note the comment above. The problem is not the computation time; it's that the "Curvilinear" renderer gives results that look very wrong.

**Comment by StasJ** [comment]
> @StasJ note the comment above. The problem is not the computation time; it's that the "Curvilinear" renderer gives results that look very wrong.

The dataset renders correctly for me.

**Comment by clyne** [comment]
What platform are you testing on?

**Comment by StasJ** [comment]
MacOS with discrete gpu

**Comment by sgpearse** [comment]
Works for me.  Closing.
