### ISSUE TITLE
core dump with OSPRay on WRF HRRR data

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2482]
VAPOR dumps core immediately when the OSPRay renderer is used with the WRF/HRRR data set

To reproduce:
1. Load data/Source/WRF/HRRR/out_surf_2020-08-25_00_00_00
2. Enable a volume renderer with the ospray algorithm selected.

**Comment by sgpearse** [comment]
The following file is a true HRRR file, which may or may not demonstrate this bug:

/Source/WRF/HRRR/wrfout_d01_2020-08-28_20_00_00

**Comment by StasJ** [comment]
> The following file is a true HRRR file, which may or may not demonstrate this bug:
> 
> /Source/WRF/HRRR/wrfout_d01_2020-08-28_20_00_00

This is caused by the 3D grids being a 2D slice so the entire HRRR file is fine but my computer does not have enough RAM to render it.

**Comment by sgpearse** [comment]
> This is caused by the 3D grids being a 2D slice so the entire HRRR file is fine but my computer does not have enough RAM to render it.

There is different file in that directory that is a 2D slice on a 3D grid, prefixed with outsurf.  The one prefixed with 'wrfout' is the full 3D field, but it's a large file so if outsurf used all of your ram, this one will too :\
