### ISSUE TITLE
No 2D Data Rendering with MPAS/FalkoJudt/30km data

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2485]
1. Open VAPOR, import MPAS data: `/little_glade/data/Source/MPAS/FalkoJudt/30km`
2. Create a 2D data render and enable it. Nothing gets rendered. Changing variable selections doesn't seem to help.

**Comment by clyne** [comment]
@shaomeng all of variables named temperature* seem to plot just fine for me. I'm importing the model output file named diag.2016-08-01_00.00.00.nc

**Comment by clyne** [comment]
Works for me. Try any of the variables named temperature*, vorticity*, or relhum*
