### ISSUE TITLE
VAPOR fails to import MPAS-V4.0

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2486]
1. Open VAPOR, import MPAS data: `/little_glade/data/Source/MPAS/MPAS_V4.0`
2. The following message shows up:

```
Failure to open data set of type "mpas"
Failed to initialize data importer
Failed to initialize netCDF data collection for reading
Spatial dimension nCells changed size
------------------
Vapor 3.2.0.dfc7bb5d
OS: Mac OS X 10.15.7
```

**Comment by clyne** [comment]
@shaomeng I can't reproduce this with either the installer from 11/17, or the current master. I note that the sha from your installer doesn't agree with mine. So I'm not sure what's going on there, but I suggest we close the issue and see if it passes verification with the next installer.

**Comment by shaomeng** [comment]
> @shaomeng I can't reproduce this with either the installer from 11/17, or the current master. I note that the sha from your installer doesn't agree with mine. So I'm not sure what's going on there, but I suggest we close the issue and see if it passes verification with the next installer.

Ok, that sounds good to me!

**Comment by shaomeng** [comment]
The problem still exists with extra detail: 
- It imports a single file in the directory mentioned above.
- If select all 4 files in that directory, the error message will appear.

**Comment by shaomeng** [comment]
The problem still exists with extra detail:
    - It successfully imports a single file in the directory mentioned above.
    - If select all 4 files in that directory, the error message will appear.

**Comment by StasJ** [comment]
> The problem still exists with extra detail:
> - It successfully imports a single file in the directory mentioned above.
> - If select all 4 files in that directory, the error message will appear.

The files are not compatible with each other.
