### ISSUE TITLE
Transparency disabled for 2D, wireframe, and barb render

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2489]
The TFE editor for the 2D, wireframe, and barb render no longer provides control for transparency.

To reproduce:
1. Load any data set
2. Enable one of the renderers listed above and try to modify the transparency in the TFE. The transparency/opacity controls are not enabled.

**Comment by clyne** [comment]
renable 2D data renderer. OK to leave barb and wireframe as is

**Comment by shaomeng** [comment]
The described problem still exists for wireframe and barb renderer.

**Comment by clyne** [comment]
The initial bug included wireframe and the barb render. However, per the comment above we decided that only the 2D data renderer should be addressed, and the wireframe and barb renderer left alone. Closing.
