### ISSUE TITLE
Color Palettes: Bundled pallets should not have bounds applied

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#250]
When loading a bundled TransferFunction (tf3) file in Vapor, we should probably not apply any bounds to the new transfer function.  Right now, we're bundling tf3 files that have extents that most likely not apply to most variables.

To reproduce:
1) Load KatrinaMaster.nc, create and enable a TwoDData renderer
2) In the Appearance tab, load the transfer function BlackBody.tf3
3) The TransferFunction's bounds will now be set to those found in the file, not that of the current variable

**Comment by StasJ** [comment]
See also #225
