### ISSUE TITLE
Vapor crashes on close after importing MPAS

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2510]
To reproduce:

1) Spin up Vapor on Casper, and import the following file:
/glade/p/cisl/vast/vapor/data/Source/MPAS/RosimarRiosBerrios/history.2000-05-31_00.00.00.nc
2) Close vapor, and it will dump core

**Comment by clyne** [comment]
It shouldn't crash, but FYI you need to open the grid file as well: x5.tropical_3km_10N.init.nc
