### ISSUE TITLE
image capture drops first frame when animating from command line

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2511]
Matt Rehme reports:

I still got the error of the first timestep not saving an image when running from a command line. Here's an example of what would happen:

# this command would run the 24 timesteps for 03/19
vglrun /glade/u/home/clyne/apps/VAPOR3-3.2.0-Linux/bin/vapor ~/3.Project/Rosimar/vapor/0.1.LoadingTest.vs3 history.2000-03-19_* x5.tropical_3km_10N.init.nc

timestep:                                             image:
history.2000-03-19_00.00.00.nc             no image saved
history.2000-03-19_01.00.00.nc             a0000.png
history.2000-03-19_02.00.00.nc             a0001.png
...                                                       ...
history.2000-03-19_22.00.00.nc             a0021.png
history.2000-03-19_23.00.00.nc             a0022.png
x5.tropical_3km_10N.init.nc                   a0023.png  # saves only a black square because this data set only had the MPAS coordinates

So I get a total of 24 images, as expected, but I should get 25 (and I would throw out the last image from the coordinate file). This happens when running 200+ files as well; the first frame will be missing. It's not a huge issue. I ended up re-running the first file of each group by itself.

**Comment by clyne** [comment]
@stasj reports:

I have already been looking into this, I just didnt have time to write up everything yet. I was unable to access your session file, Matt, since your home directory is not readable by my login but here is what I have so far:

I have tested the -render feature with multiple other datasets, including ones with separate grid files, and everything works correctly. I am, however, running into issues with this dataset. When using vapor normally (I.e. without the -render parameters), trying to load specific time steps with a session file does not work correctly.

I created standalone grid files which can be used to replace the original 300GB grid file. They can be found here. I reduced the size from 300GB to 2GB for the 2D grid and 4GB for the 2D+3D grid files. Their names should describe their purpose. There are separate ones for 2D and 2D+3D grids since it is much faster to load a 2D only grid when you are not using 3D.

In my testing I found that some of the issues are caused by the grid file having its own timestep so there are grids with -notime- in their name which solve those issues but even using those, it does not work correctly. I think John you may want to look into this as I believe this is an issue in the data loader. 

The grid files can be found at /glade/scratch/stasj/init*

Also there is one more thing I have run into that you may want to look into, John, and it is that loading these 2GB 2D grid files takes up 16GB of RAM constantly without any renderers. The files’ variables are compressed, but decompressed they are still only 4GB for 2D.

**Comment by clyne** [comment]
@stasj please try the grid file in /glade/p/cisl/vast/vapor/data/Source/MPAS/RosimarRiosBerrios/x5.tropical_3km_10N.init.nc to see if you're still having trouble. Using this file I'm not seeing the problems that you're running into with the current master branch.

**Comment by StasJ** [comment]
@clyne 

Run:
```
export DIR=/glade/p/cisl/vast/vapor/data/Source/MPAS/RosimarRiosBerrios/
vapor $DIR/history.2000-05-31_00.00.00.nc $DIR/x5.tropical_3km_10N.init.nc
```

Notice there are two timesteps while there should only be one.
Create and enable an image renderer for `rainc`.
Notice that you can switch between the two time steps but it is the same image.
Save session file `session.vs3`.

Run:
```
vapor session.vs3 $DIR/history.2000-05-31_00.00.00.nc $DIR/history.2000-05-31_06.00.00.nc $DIR/x5.tropical_3km_10N.init.nc
```

Now there are still two time steps which is correct but inconsistent with before.
Notice if you try advancing to the second of the two time steps, you get an error message.

Tested on casper.

**Comment by MattRehme** [comment]
Here's the session file:
[0.1.LoadingTest.vs3.zip](https://github.com/NCAR/VAPOR/files/5624267/0.1.LoadingTest.vs3.zip)

**Comment by clyne** [comment]
> @clyne
> 
> Run:
> 
> ```
> export DIR=/glade/p/cisl/vast/vapor/data/Source/MPAS/RosimarRiosBerrios/
> vapor $DIR/history.2000-05-31_00.00.00.nc $DIR/x5.tropical_3km_10N.init.nc
> ```
> 
> Notice there are two timesteps while there should only be one.
> Create and enable a 2D renderer for `rainc`.
> Notice that you can switch between the two time steps but it is the same image.
> Save session file `session.vs3`.
> 
> Run:
> 
> ```
> vapor session.vs3 $DIR/history.2000-05-31_00.00.00.nc $DIR/history.2000-05-31_06.00.00.nc $DIR/x5.tropical_3km_10N.init.nc
> ```
> 
> Now there are still two time steps which is correct but inconsistent with before.
> Notice if you try advancing to the second of the two time steps, you get an error message.
> 
> Tested on casper.

Two things are going on here:

1. The grid file has a time coordinate variable, 'xtime', which is not present in the data files. Removing 'xtime' from x5.tropical_3km_10N.init.nc results in the correct number of time step being displayed, and allows your second step to run correctly.

2. The 'rainc' variable appears to be constant over time (at least it is constant in the two history files you are loading). If you use the 'olrtoa' variable you'll get the expected results.

I don't think that there is anything that we need to fix in VAPOR. The confusion with the lack of a time coordinate in the data files, exacerbated by having a time coordinate in the grid file, is probably not something we can realistically address. I think we should close this ticket.

cc @MattRehme
