### ISSUE TITLE
DVR color map variable controls

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2517]
I found myself confused by the DVR appearance tab when using the ColorMapVariable option.  There are two small changes that I think would improve its usability and prevent what was reported in #2151, where it appeared that selecting built-in colormaps no longer worked.

These small changes are:
1) Disable colormap options on opacity-only transfer functions
2) Move the colormap transfer function below the primary transfer function, instead of below the ray-tracing options.

![Untitled drawing (1)](https://user-images.githubusercontent.com/9522770/100894187-75faf400-3479-11eb-9b9f-7e2882645897.png)

**Comment by clyne** [comment]
We will simply remove the "colorMapVariable" selector from the appearance tab
