### ISSUE TITLE
Navigation->Viewpoint change has no effect

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2525]
To reproduce:
1. Open VAPOR, import jsmall data set.
2. Create a volume renderer and enable it.
3. Go to Navigation->Viewpoint tab
3. Change values in "Translation" section. Notice that there's no effect on the rendering.
3. Change values in "Origin" section. Notice that there's no effect on the rendering.

**Comment by clyne** [comment]
@shaomeng please re-test, verify you are using signficantly large values

**Comment by clyne** [comment]
@shaomeng please verify per above

**Comment by shaomeng** [comment]
> @shaomeng please re-test, verify you are using signficantly large values

It's verified that large values will generate a visible change. Rejecting this bug.
