### ISSUE TITLE
Flow: max value for the integration steps slider can't be changed

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2527]
To reproduce:
1. Load Duku and enable flow.
2. Right click on the Integration Steps slider. Try to change the maximum
value in the pull down menu. It can't be changed.

**Comment by sgpearse** [comment]
@clyne I'm currently unable to reproduce this.

The following screenshot shows a change to the maximum "Integration Steps" from 5000 to 9000, with a right-click.

<img width="1185" alt="Screen Shot 2020-12-08 at 7 38 33 AM" src="https://user-images.githubusercontent.com/9522770/101499798-e8ad1900-392a-11eb-8d58-1b0727edc55e.png">

**Comment by clyne** [comment]
I can't either now. Closing
