### ISSUE TITLE
Flow: Random seeding with bias does not work

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2528]
To reproduce:
1. Load CM1/Orf/24Maycontrol and enable Flow. Streamlines are displayed
2. Change the seed distribution type to Random w/Bias. No streamlines are
drawn.

**Comment by shaomeng** [comment]
This bug is caused by an inconsistency between the GUI widget and the parameter data base. 
More specifically, upon switching to `Random w/ Bias` mode, the GUI widget `RakeBiasVariable` displays a valid variable, while querying `params->GetRakeBiasVariable()` returns an empty string.

**Comment by clyne** [comment]
Assigning to @StasJ
