### ISSUE TITLE
Flow: VDC and native version of data produce very different results

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2535]
The VDC and WRF versions of the same data produce very different streamline fields (see attached)

To reproduce:
1. Load both the VDC and WRF versions of WRF/Harvey
2. Enable Flow for both.
3. For VDC be sure to set the variable Fidelity to "high". The resulting streamline visualizations are very different. 

I suspect this may be related to the way seed positions are selected in "gridded" mode as described in #2526. If the seed distribution mode is changed to random the results look much better, but a are still slightly off.

![VDCvsWRF](https://user-images.githubusercontent.com/6777736/101210749-3bd55200-3633-11eb-9984-0e8d13873c8d.png)

**Comment by shaomeng** [comment]
After giving the same rake regions to both versions of data source, they look more similar but still exhibit visible difference. I tend to think this is due to wavelet boundary effects and the sensitive nature of advection, but open to other theories. 
![two flows](https://user-images.githubusercontent.com/814885/101591699-53516980-39aa-11eb-9357-0b311a3d799b.png)

**Comment by clyne** [comment]
> After giving the same rake regions to both versions of data source, they look more similar but still exhibit visible difference. I tend to think this is due to wavelet boundary effects and the sensitive nature of advection, but open to other theories.
> ![two flows](https://user-images.githubusercontent.com/814885/101591699-53516980-39aa-11eb-9357-0b311a3d799b.png)

@shaomeng these results look plausible. I.e. the minor differences could be explained by the differences between the original and VDC data. Can you clarify what was required to "give the same rake regions to both versions"? I was unable to do this (easily).

**Comment by shaomeng** [comment]
> > After giving the same rake regions to both versions of data source, they look more similar but still exhibit visible difference. I tend to think this is due to wavelet boundary effects and the sensitive nature of advection, but open to other theories.
> > ![two flows](https://user-images.githubusercontent.com/814885/101591699-53516980-39aa-11eb-9357-0b311a3d799b.png)
> 
> @shaomeng these results look plausible. I.e. the minor differences could be explained by the differences between the original and VDC data. Can you clarify what was required to "give the same rake regions to both versions"? I was unable to do this (easily).

@clyne  I opened two instances of VAPOR and created the flow renderer. Then I manually typed in the same values to corresponding rake region boxes before I enabled the renderer. (Figuring out if the typed value was accepted by the text box wasn't very easy...)

**Comment by clyne** [comment]
LGTM!
