### ISSUE TITLE
Vapor hangs with some WRF-Fire data sets

### ISSUE THREAD

**Issue by kasrash** [NCAR/VAPOR#2536]
Hi everybody,

I am trying to visualize some WRF-Fire idealized simulation output using Vapor 3.2. However, when I want to create barb renderer or some other renderers Vapor hangs and I have to force quit it! The WRF output file is relatively small, about 160 mb. and also only Wireframe renderer works correctly.

I am using WRF version 4.2 and Vapor version 3.1 on my MacBook Pro 16 running Catalina.

I appreciate every help, and thank you very much in advance!

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [*] Did VAPOR crash?
- [ ] Did you get wrong results?

**Impact**
- [*] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### Desktop
 - OS and version: macOS Catalina 10.15.5
 - Version: Vapor 3.2

**Comment by clyne** [comment]
Can you try the pre-release of VAPOR 3.3 available from https://github.com/NCAR/VAPOR/releases and let us know if that fixes your problems? Thanks!

**Comment by kasrash** [comment]
I am so sorry for the late response. I tried few things, but didn’t help.
I tried the VAPOR 3.3 pre-release and it didn’t either. Also, I tried converting the wrfout to .vdc format but it didn’t solve the problem. I also tried VAPOR 3.1 and it worked without a problem. However, due to the problem related to XLAT/XLONG which are in meters, it’s unusable.
Again, so sorry for the late response and I hope that you can reopen the issue

**Comment by clyne** [comment]
Is there anyway that you can provide us with a copy of the data?

**Comment by kasrash** [comment]
Sure, would the wrfout file be enough?

**Comment by kasrash** [comment]
I uploaded the wrfout file on my google drive: https://drive.google.com/file/d/1fpPQoulCh7edjYVLOr3ESzCR7ZPuNKJ4/view?usp=sharing

**Comment by clyne** [comment]
OK. We'll take a look at it.

**Comment by clyne** [comment]
This data set is yet another WRF-Fire edge case. In this instance the primary grid coordinate variables (XLONG and XLAT) have valid values, but the staggered grid coordinate variables (XLONG_U, XLAT_U, XLONG_V, XLAT_V) are constant (zero) valued.
