### ISSUE TITLE
OSPRay won't render some MPAS data sets

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2539]
Even with the patched OSPRay library the OSPRay DVR render fails to render MPAS/FalkoJudt/30km data. Setting the sampling scale factor to something really small does not seem to help (e.g. 0.00001)

To reproduce:
1. Load MPAS/FalkoJudt/30km (data and grid file)
2. Create and enable a volume renderer. The renderer never advances past "copy data to OSPRay"

**Comment by StasJ** [comment]
I cannot reproduce. On my mac it takes a *very* long time since it is swapping. On casper with 16 cores and 64GB RAM it works reasonably well.

**Comment by clyne** [comment]
Is the default sampling rate calculated by OSPRay reasonable? I.e. if you set the rate multiplier to 0.01 or 0.1 does the image noticeably degrade, or is it unchanged (indicating oversampling)?

**Comment by StasJ** [comment]
The performance hit is not during rendering but rather while computing the acceleration structures.

**Comment by clyne** [comment]
@stasj do you have an installer for casper that uses the patched OSPRay library that corrects the sampling rate calculation?

**Comment by StasJ** [comment]
@clyne, no I only built one for Mac. I can try building one for Casper however that will not have any impact on this issue. The old version combined with my fix works correctly for this dataset and is not the source of the problem.

**Comment by clyne** [comment]
I'd like to be convinced that we've addressed the sampling issue. On my Mac I ended up terminating the process after about 20 minutes. So I don't think the Mac is an option for resolving this.

**Comment by StasJ** [comment]
I built/tested ospray with the sampling issue fix on casper and the behavior is the same so we can confirm that the sampling issue is resolved with this dataset.

**Comment by clyne** [comment]
Terrific. Can you point me to the installer? thanks

**Comment by StasJ** [comment]
Our centos build machine (cisl-garibaldi) is down and I cannot build an installer on casper. I can prepare a source build for you to use however.

**Comment by clyne** [comment]
Please do provide a version that I can test with.

**Comment by StasJ** [comment]
I prepared a source build here: `/glade/work/stasj/bin`

It should work but if not, you may need to add `/glade/work/stasj/ospray-git/build/install/ospray/lib64` to `LD_LIBRARY_PATH`

I included a source.sh in that directory which does that.

**Comment by clyne** [comment]
Thanks. Everything works as expected. One question: it looks like OSPRay is performing a lot of initialization calculations (e.g. building acceleration structures) every time a data set is loaded. Do these need to be rebuilt if new data are loaded, but the mesh us unchanged?

**Comment by StasJ** [comment]
There are 2 sets of initialization calculations that are done. The first is done on our end to translate/sanitize the data, and the other on OSPRay's end to build the acceleration structures. The calculations on our end could be cached if using the same mesh but this would require some refactoring. On OSPRay's end, I don't know, we would have to do some experimentation to see what happens.

**Comment by clyne** [comment]
Based on what appears in the progress bar, it appears that the majority of time is spent in OSPRay (Copying data to OSPRay). We should consider caching the steps were are doing to sanitize the data, etc. However, that's not going to buy us much. If the OSPRay API supports splitting the processing of the coordinates and the data, that could have a big impact.The first rendering of the FalkoJudt/30km data takes over two minutes on casper with 16 cores, most of that time spent "copying data to OSPRay". Subsequent renderings take only about  a second. How about exploring what is possible on the OSPRay side? If we can eliminate the mesh handling it would make a huge improvement on how useful the capability is.

**Comment by StasJ** [comment]
> Based on what appears in the progress bar, it appears that the majority of time is spent in OSPRay (Copying data to OSPRay). We should consider caching the steps were are doing to sanitize the data, etc. However, that's not going to buy us much. If the OSPRay API supports splitting the processing of the coordinates and the data, that could have a big impact.The first rendering of the FalkoJudt/30km data takes over two minutes on casper with 16 cores, most of that time spent "copying data to OSPRay". Subsequent renderings take only about a second. How about exploring what is possible on the OSPRay side? If we can eliminate the mesh handling it would make a huge improvement on how useful the capability is.

I agree. I did some testing where I change only the value data between two commits and OSPRay recomputes everything.

**Comment by clyne** [comment]
@stasj please open a ticket with Intel to add this functionality (avoiding unnecessary initialization when mesh doesn't change)
