### ISSUE TITLE
Pathlines not correct in 24MayControl?

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2542]
The pathlines generated with the steps below do not seem correct to me.  Alternatively, see the attached session file, used on Casper.

1) Import the CF files in /glade/p/cisl/vast/vapor/data/Source/CM1/Orf/24Maycontrol/
2) Create a Pathline flow renderer with the default variables
3) Set the gridded rake to be 1x1x1
4) Set the Pathline Length to 1
5) Set the Injection Interval to 1
6) Enable the renderer and animate through time.  I believe we should be seeing pathlines injected every timestep.  All I see is the screenshot below, at every timestep.

Update from Sam: this bug is really about: does multiple seed injections always start from time step 0, or from multiple time steps? 

<img width="1712" alt="Screen Shot 2020-12-07 at 9 03 01 AM" src="https://user-images.githubusercontent.com/9522770/101374147-0e72e900-386b-11eb-85a4-bff7c123fd94.png">

**Comment by sgpearse** [comment]
May be a duplicate of #2465

**Comment by clyne** [comment]
@shaomeng please verify that seeds are released at different time steps, not all the same time step, when injection interval is not 0

**Comment by shaomeng** [comment]
@sgpearse I have confirmed that multiple seed injections do use the time stamps of the according time steps. For example, a seed injected at time step 3 will have the time stamp of time step 3, but not the time stamp of time step 0. Do you think this confirmation resolves this bug?

**Comment by sgpearse** [comment]
It was an issue with the dataset which has a difference in units (m vs km) between the domain and the vector field variables.
