### ISSUE TITLE
IsoSurface hangs on MPAS data

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2547]
### Describe the bug
Attempting to render an isosurface causes the machine to hang on some MPAS data sets. Examples of such data sets include:
`MPAS/MPAS-O`
`MPAS/MPAS_V4.0`

**Comment by clyne** [comment]
@stasj please create a bug report if one doesn't exist and link it here.

**Comment by StasJ** [comment]
Issue open with OSPRay

https://github.com/ospray/ospray/issues/343

**Comment by clyne** [comment]
@stasj please disable osrpray isosurfaces
