### ISSUE TITLE
Barb: Length scale shows `inf`

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#256]
As the screenshot shows, there's an `inf`.
![screenshot from 2017-11-07 15-52-51](https://user-images.githubusercontent.com/814885/32522356-34f1cc90-c3d4-11e7-8cbf-10f85614bf03.png)

This bug is a little hard to reproduce: it requires adjusting the length scale slider for some times before it comes up. Unfortunately, I haven't come up with a deterministic approach to reproduce it.

Instead, I've saved the session file when this was occurring. The dataset is Katrina.
PS, simply loading the session file does not trigger the `inf`s though. I'm hoping this session file could provide a little information.
PS2, rename this attached session file to get rid of the `.txt` subfix.

[Barb_inf.vs3.txt](https://github.com/NCAR/VAPOR/files/1451980/Barb_inf.vs3.txt)

**Comment by sgpearse** [comment]
I'm not able to reproduce this yet, but I'm happy to revisit it if we can trigger it.
