### ISSUE TITLE
Flow: velocity multiplier seems no longer working

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2563]
This bug might be introduced by  #2552 ... More investigation is needed.

**Comment by shaomeng** [comment]
Given a domain extent and a velocity field, the logic to determine a `deltaT` is that a particle will need to travel around 500 steps to cover this domain. Note that in the logic described above, this given velocity field could be multiplied by a factor or not. 

The change merged in #2552 results in different `deltaT` value being calculated depending on a velocity multiplier set by the user, but it won't change the rough number of steps a particle covers the domain, thus it appears that the velocity multiplier doesn't have any effect as this bug report indicates. 

I propose we reverse changes made in #2552 . What do you think @clyne  ?

**Comment by clyne** [comment]
@shaomeng I'm not sure that I understand. The effect of the velocity multiplier should be as if the original data were scaled by the multiplier before they are accessed by the flow renderer.

**Comment by shaomeng** [comment]
Upon discussion, this turns out isn't a bug. Closing it!
