### ISSUE TITLE
Pathline length: maximum should be num_of_TS - 1. 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2581]
Given the definition of displayed pathline length, which is how many time steps to display before the current time step, that number should max out at `num_of_TS-1`. The current implementation has that number at `num_of_TS`.

To use an example, when there are 2 time steps, the longest possible pathline is 1.

**Comment by StasJ** [comment]
This contradicts your previous bug report #2505 (look at step 6) fixed here: #2513

**Comment by StasJ** [comment]
The maximum was `num_of_TS - 1` and the previous bug report claims the maximum should be `num_of_TS` instead

**Comment by shaomeng** [comment]
@StasJ  you're right that my fix re-introduced the previous bug. 

Let me ask the question in a different way. Given `N` available time steps, I want the widget to 
1) have a range of (1, N-1), and
2) keep in sync with the params class. 
What's the recommended configuration to give to the widget so goals above can be achieved ?

**Comment by shaomeng** [comment]
> This contradicts your previous bug report #2505 (look at step 6) fixed here: #2513

Step 6 should be "number of time step minus 1". Sorry for any confusion.

**Comment by shaomeng** [comment]
> @StasJ you're right that my fix re-introduced the previous bug.
> 
> Let me ask the question in a different way. Given `N` available time steps, I want the widget to
> 
>     1. have a range of (~1~ 0, N-1), and
> 
>     2. keep in sync with the params class.
>        What's the recommended configuration to give to the widget so goals above can be achieved ?

I think I figured out how to do it. Please review the latest PR if there is any concern.
