### ISSUE TITLE
vaporpychecker dumps core

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2604]
vaporpychecker is currently broken on our CentOS installer.  Note: The python engine seems to still be functional.

[vapor2@localhost jan26]$ ./VAPOR3-3.3.0-Linux/bin/vaporpychecker 
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f5658018780 (most recent call first):
Aborted (core dumped)

**Comment by sgpearse** [comment]
Need to reverify

**Comment by sgpearse** [comment]
It's still there :\

**Comment by StasJ** [comment]
Works for me on both Casper and on a fresh CentOS install.
