### ISSUE TITLE
Add support for bookmarking

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2607]
Allow the user to "book mark" the current state of the application in a manner similar to web browser bookmarks. The user could then quickly toggle between different states. This might be particularly helpful when, for example, editing a colormap. The book mark browser could contain a snapshot of the visualizer window along with optional text

**Comment by sgpearse** [comment]
@clyne - just throwing thoughts out there.  One of the 3D applications I use shows their undo/redo queue as a dropdown menu, letting you roll backwards or forwards in history by multiple steps.  This is shown in the screenshot below.  Would this kind of mechanism help with what you describe?

We could embed an image as a tool-tip at each undo/redo item in the dropdown, showing the current rendering.

![undoRedoQueue](https://user-images.githubusercontent.com/9522770/106160946-9ecefb00-6143-11eb-9923-47cf54f3d52d.png)

**Comment by clyne** [comment]
I think the presentation of the information is close to what I was thinking, but I think having the user manually bookmark pages of interest is probably more valuable than having an automated system. The latter I think would generate an overwhelming list. Then again, to use the browser analogy browsers support both an automated and manual state saving: history and bookmarks. Both could be useful in VAPOR.
