### ISSUE TITLE
MainForm.cpp: _firstSession not doing anything

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#261]
I initially added the member boolean `_firstSession` to record if the main window is 1st time open, and thus not pop up the "session not saved" dialog when a user immediately opens a new session or create a new session.

However, it doesn't seem to be preventing that message window pop up. 

Now I intend to remove this variable, and spend some time to figure out why `_stateChangeFlag` is reporting true upon VAPOR fires up.

**Comment by clyne** [comment]
Can't reproduce. Need more info
