### ISSUE TITLE
clang-format strips whitespace from empty lines

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2627]
If we have the following code:

```
struct {
    int a;
    
    int b;
}
```

I believe the normal whitespace should be:

```
struct {
....int a;
....
....int b;
}
```

Clang format changes it to:

```
struct {
....int a;

....int b;
}
```

This is not configurable as an option in the formatter.

**Comment by shaomeng** [comment]
I kind of like what clang-format does. In my practice, when I notice that I have spaces in an empty line, or at the end of a non-empty line, I'd actually delete it by myself.
