### ISSUE TITLE
Default renderers for WRF users/developers

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2630]
WRF developers have stated that Vapor can be intimidating.  Other tools like NCView plot data automatically, whereas Vapor presents a more complicated set of steps before actually seeing something.  Having one or two default renderers would help coax users into our UI model more easily.

Potential solutions:
1) Automatically have an Image renderer for datasets containing a proj string
2) Extend the Image renderer's default region by 200% on the X and Y axes
3) Automatically create a slice renderer as a default

**Comment by clyne** [comment]
We might want to make the default renderer 2D. The things we should consider are performance and the likelihood of producing a meaningful plot. Note some data sets are 2D (3D) only. 

It should be possible to disable this feature, which could become problematic with large data. Also, the feature should be disabled if the user loads a session file.

**Comment by sgpearse** [comment]
This would introduce a lot of edge cases that we would be chasing around.  Not worth the effort.
