### ISSUE TITLE
Open Session: cannot create new renderers afterwards...

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#264]
To reproduce:

1. Invoke VAPOR without any parameters.
2. Open Katrina dataset.
3. Open the attached session file. (remove the .txt subfix)
4. Now it's impossible to add new renderers! Note that Katrina is still loaded, as we can see it from the "Close VDC" menu.

[Barb_colormapping.vs3.txt](https://github.com/NCAR/VAPOR/files/1452049/Barb_colormapping.vs3.txt)

**Comment by clyne** [comment]
It should be possible to open any renderers after loading a new session. Loading a new session unloads any data. You'll need to re-load data into the new session.
