### ISSUE TITLE
Clearer name: Number of Barbs in X

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2643]
The barb renderer has labels named "X Barbs," "Y Barbs" etc. These names are kind of confusing. I suggest to use a clearer name, for example, "Num of Barbs in X."

<img width="779" alt="Screen Shot 2021-03-16 at 12 55 50 PM" src="https://user-images.githubusercontent.com/814885/111364586-0ccd7400-8657-11eb-8195-c2211b7a1264.png">

**Comment by clyne** [comment]
It might be good to look at the terminology used by Matplotlib quiver plots and try to be consistent.

**Comment by clyne** [comment]
Relates to #2644

**Comment by shaomeng** [comment]
I decide that it's ultra low priority so close it.
