### ISSUE TITLE
Performance of Barbs unusable with larger data

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2645]
### Describe the bug
The Barb renderer is unusable with larger data. It appears to be performing unnecessary calculations with every update, including scene navigation.

### To Reproduce
1. Load PALM/cbl_KIT_ug00_dx10_masked_M01.000.0119.split.nc from glade
2. Enable the barb renderer
3. Try to change the viewpoint. It's impossible to do this interactively.

**Comment by shaomeng** [comment]
This one is so bad that I think it deserves a "High."

**Comment by clyne** [comment]
@stasj we skipped triaging this a couple of days ago. If you've wrapped up TODOs for the release could you please assess whether this is something reasonable to know off for 3.4? It's a pretty significant bug.
