### ISSUE TITLE
ImageRenderer: Current image file display

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#265]
I believe we should be displaying the current filename of our Image renderer without its directory path.

To reproduce:
1) Spin up Vapor with KatrinaMaster.nc
2) Create an Image renderer
3) In the Appearance tab, it's a little bit hard to ascertain our current image file

**Comment by clyne** [comment]
Related to #1509

**Comment by shaomeng** [comment]
why not path names? 

(I often have multiple directories holding different versions of the same file. Without the path name, I won't be able to tell which version am I using.)
