### ISSUE TITLE
Crash opening data set after a previous data set failed to open

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2651]
After following the steps from #1888:

1) Import a NetCDF dataset and save a session
2) Close Vapor
3) Move/rename the dataset
4) Open vapor and open the session

We get an error message, which fixes #1888.

However, now try to import a wrf file and vapor will crash.

**Comment by StasJ** [comment]
This is not related to #1888

**Comment by sgpearse** [comment]
These bugs are related to a use case that we were not supporting.
