### ISSUE TITLE
Window size feature should apply to visualization window, not entire application

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2656]
There is a setting on the Preferences menu to set (and lock) the window size. This is particularly useful for people who want to capture a number of outputs images, often over numerous session, and want the images to be a consistent size. However, the size specification applies to the overall application window, not the renderer window, limiting the usability of the feature.

**Comment by StasJ** [comment]
@clyne That is why we have the "Custom Output Size" option under Viewpoint. I don't know what the point of the original option you are referring to is for, we could just remove it.

**Comment by clyne** [comment]
We should probably discuss whether it makes sense to have both of these? The FrameBuffer control is clearly much more useful, but not sure we should do away with the viewpoint preference. 

cc: @sgpearse , @shaomeng

**Comment by shaomeng** [comment]
yeah, it seems redundant to me. I'd vote to remove the options under global preference menu, and keep the one that's under viewpoint.

**Comment by sgpearse** [comment]
Removing it is fine with me.
