### ISSUE TITLE
Red box not able to be dragged bigger? 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2659]
It might just be a secrete operation that I'm not aware of, but once the red box shrinks, it feels impossible to extend it bigger by dragging the red dot. 

https://user-images.githubusercontent.com/814885/111854802-dc036e00-88e6-11eb-832c-06ed7f5b9429.mov

**Comment by sgpearse** [comment]
Which button are you using?  Left click moves the region.  Right click adjusts its size.  This gets trickier if you're using a trackpad.

**Comment by shaomeng** [comment]
> Which button are you using? Left click moves the region. Right click adjusts its size. This gets trickier if you're using a trackpad.

Oh, thanks for the reminder; I was using a trackpad. I feel this is a usability issue, because as we know, even on mac, resizing a window and moving a window around are both pretty common operations using the trackpad.

**Comment by clyne** [comment]
This is a good point, and we may want to think about how we can improve support for Mac users with track pads. Thumbwheels ? :-)

**Comment by sgpearse** [comment]
Closing and will revisit all things visualizer and manipulator oriented in new tickets.
