### ISSUE TITLE
Flow: variable output not consistent 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2661]
### Describe the bug
Flow variable value output is not consistent after deleting and recreating the renderer.

### To Reproduce
Steps to reproduce the behavior. For example:
1. Open VAPOR, import data `PALM/cbl_KIT_ug00_dx10_masked_M01.000.0119.split.nc`
2. Create a flow renderer, enable it using default parameters
3. Output flowlines with `u` variable selected.
4. Make a backup of the output file
5. Delete the renderer, re-create it, and re-output flowlines wiht `u` variable selected
6. Compare the new output file and the previous one, notice that `u` values are not the same.

**Comment by sgpearse** [comment]
On Casper, I get the following error when enabling the flow renderer with default values (step 2)

Error performing paint event
Update deltaT failed!
Vector field not available at requested time step!
Not able to get a grid!
Failed to read variable "w" at time step (0), and
refinement level (-1) and level-of-detail (-1)
Failed to read region from variable/timestep/level/lod (w, 0, -1, -1)
Failed to allocate requested memory
------------------
Vapor 3.4.0.0e7b352
OS: Linux 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020
Distro:
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch

**Comment by clyne** [comment]
This is the expected behavior. You have to increase the cache size (previously the data were being corrupted). Admittedly, we should consider a more informative message.

**Comment by sgpearse** [comment]
Interesting.  My cache is set to 8GB and the file is 7GB.  I'm not sure what the advection code is allocating though.  Is there a rule of thumb to follow with cache size for flow renderer (ie field variable size on disk x3 x1.50)? 

If this is the expected behavior, let's reject this.
