### ISSUE TITLE
The VAPOR cache size is unintuitive and should be made unlimited by default

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2678]
Similar argument to the default number of CPU cores.

**Comment by clyne** [comment]
The problem with making it unlimited is that in environments that place limits on memory (e.g. Casper) this will lead to process termination if the application grabs too much memory. Without a user-settable limit the user has no way to control this, and it may be particularly problematic for data with lots of time steps; VAPOR will attempt to cache every single time step that it loads . 

Another option that might improve the situation would be a more explicit error message that directs the user to increase the cache size if possible. Another thought would be to be treat the cap as a soft limit and always try to allocate enough memory to hold three variables (for flow) + coordinates.

Other thoughts ?

**Comment by shaomeng** [comment]
This specific ticket was suggesting to set unlimited as the default, while
users could still set a specific value in those environments.

If we start over I'd suggest that VAPOR doesn't overlap with the OS to try
to manage memory. But that's not what this ticket tries to suggest.
