### ISSUE TITLE
Memory allocation error - cache not being cleared

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2686]
vaporgui will run out of memory under some normal use situations when adequate memory should be available.

To reproduce:
1. Set the cache size to 1000 and restart the application for the change to take effect.
2. Load the TG data set (unfortunately we are not auto-generating a VDC data set, so you'll have to create one from scratch)
3. Create a slice renderer
4. Change the variable resolution to 512^3 and enable
5. Adjust the geometry a few times. You'll get a paint error and a message about failing to allocate memory

The problem is that the DataMgrUtils::GetGrids() method does not provide a "lock" flag (as is provided by the DataMgr:GetVariable() method that GetGrids() calls). Thus, the user of DataMgrUtils::GetGrids() must explicitly call DataMgrUtils::UnlockGrids() to free the grid(s) when done with the Grid instance. This is not being done consistently throughout the application (e.g. in Histo.cpp).

**Comment by shaomeng** [comment]
A short term solution is to go examine those grid consumers and make sure the correct functions are called. 

A long term solution, and IMO a more proper solution, and also a less bug-prone solution, and also a solution that's more complying with normal software engineering practices, is to not try to enforce a such limit within the application itself.

**Comment by StasJ** [comment]
I fixed the memory leak and checked every occurrence of `GetGrids` to make sure it unlocks the grids. Just some things to note:
- The `lock` parameter is not mentioned in the documentation for any of the `GetVariable` or `GetGrids` methods
- The default value for the `lock` parameter is false for all of the `GetVariable` methods
- The default value for the `lock` parameter is true for all of the `GetGrids` methods and this is hidden from the interface
- It should be possible to have the destructor of `Grid` automatically reduce its reference count, solving this issue

**Comment by clyne** [comment]
Stas,

I’ve approved your quick fix and merged. Thanks. I ‘ve also opened a separate issue to refactor the code per below and other issues I noted as well. 

https://github.com/NCAR/VAPOR/issues/2694

cheers - jc


> On Apr 5, 2021, at 2:40 AM, StasJ ***@***.***> wrote:
> 
> 
> I fixed the memory leak and checked every occurrence of GetGrids to make sure it unlocks the grids. Just some things to note:
> 
> 	• The lock parameter is not mentioned in the documentation for any of the GetVariable or GetGrids methods
> 	• The default value for the lock parameter is false for all of the GetVariable methods
> 	• The default value for the lock parameter is true for all of the GetGrids methods and this is hidden from the interface
> 	• It should be possible to have the destructor of Grid automatically reduce its reference count, solving this issue
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
***@***.***
