### ISSUE TITLE
Barb color seems inconsistant 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2688]
To reproduce:
1. Open VAPOR, load data `PALM/cbl_KIT_ug00_dx10_masked_M01.000.0119.split.nc`
2. Create a barb renderer, enable it. 
3. Go to "Appearance" tab, check off the option "Use Constant Color."
4. At this point, the barbs look like this:
![Screenshot from 2021-04-01 19-42-06](https://user-images.githubusercontent.com/814885/113371060-97ce8f80-9322-11eb-8456-0f004dd4a26b.png)

5. Go to "Variables" tab, select `2D` in Variable Dimension.
6. Select `3D` in Variable Dimension.
7. At this point, the barbs look like the following, and clearly different from its previous rendering
![Screenshot from 2021-04-01 19-45-49](https://user-images.githubusercontent.com/814885/113371146-e11edf00-9322-11eb-9859-6d699117ab7b.png)

**Comment by clyne** [comment]
Unchecking "use constant color" seems to be a no-op until some other event takes place. I've observed that simply changing the selected color variable will trigger the desired color-by-variable.
