### ISSUE TITLE
Ineffective Memory Management

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2697]
### Describe the bug
Isosurface renderer seems to consume an infinity amount of memory on Linux (cisl-vapor and Casper), but not on MacOS.

To Reproduce:
1. Open VAPOR, set the cache size to be 16GB. Restart VAPOR.
2. Load data `Source/ROMS/Kauffman/b.n20.B1850CN.f09_g16.09.roms.ha.0001-04` and its corresponding grid file: `NEP4_grid.nc`
3. Notice that these two files total at 220MB, thus I decide that a 16GB cache size is a *safe* limit.
4. Open `top` or any system resource monitor to observe the memory consumption of VAPOR.
4. Create an isosurface renderer. Enable it with all default settings. 
5. Notice that the memory consumption of VAPOR goes way beyond 16GB, causing the system not responding, all without a successful rendering.

**Comment by StasJ** [comment]
Cannot reproduce

<img width="373" alt="top" src="https://user-images.githubusercontent.com/2772687/114129821-91a95780-98bc-11eb-8b25-2f054e003364.png">

**Comment by clyne** [comment]
@shaomeng will split this issue into a bug report and a separate ticket addressing refactoring needs.

**Comment by shaomeng** [comment]
No longer applicable.
