### ISSUE TITLE
Missing building from source documentation

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2709]
Our "building VAPOR from source" documentation seems to have vanished. There is a note here:

https://vapor.readthedocs.io/en/readthedocs/downloads.html#installationinstructions

that says "Building From Source <buildFromSource> section below", but there is nothing about source installation in the document. 

We need to augment our build instructions with the changes we've made to our cmake config to support OpenMP as described here:

https://docs.google.com/document/d/1nsaarW3jaZVAJFIHsERZ7MWMlms57LbErdcLgjtAkTo/edit?usp=sharing

**Comment by sgpearse** [comment]
@clyne @shaomeng - I believe that GCC/LLVM currently have native support for OpenMP, so these instructions are not longer needed.  The only thing that still needs mentioning is that we don't support Windows builds with OpenMP.  Anything I'm missing or wrong about on this?

**Comment by shaomeng** [comment]
> @clyne @shaomeng - I believe that GCC/LLVM currently have native support for OpenMP, 

I believe this statement is true, but the problem is that MacOS ships with a modified version of LLVM that doesn't support OpenMP. I'm not sure how this mismatch should be addressed.

**Comment by sgpearse** [comment]
> the problem is that MacOS ships with a modified version of LLVM that doesn't support OpenMP

Ok, it sounds like this still needs to be documented with our MacPorts installation info then.

**Comment by clyne** [comment]
According to #2860 MacOS Clang13 includes OpenMP support, but I don't think Clang13 is widely available on Macs yet.

**Comment by NihanthCW** [comment]
@sgpearse is this issue still relevant?

**Comment by sgpearse** [comment]
@NihanthCW No, it's not.  I'll close.
