### ISSUE TITLE
Camera controls do not update the scene

### ISSUE THREAD

**Issue by daliagachc** [NCAR/VAPOR#2715]
### Describe the bug
When I type values in any of the "camera control" fields nothing happens. I would expect that the view would update accordingly. 

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [ ] Did you get wrong results?

**Impact**
- [ ] High - User productivity significantly degraded
- [x] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
Steps to reproduce the behavior. For example:
1. Open a file 
2. type value in the camera control fields 
3. nothing happens 

*Additionally, please attach a session file to this ticket to easily reproduce (use File->Save Session).*

### Expected behavior
I would expect the visualizer view to be updated 

### Desktop
 - OS and version: Macos Mojave 
 - Version: [e.g. Vapor 3.4]

**Comment by clyne** [comment]
duplicates #865 and #2233
