### ISSUE TITLE
Color bar shows constant value and color on non-constant variables

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2723]
Steps to reproduce:
1. Open the following session file on Casper. The data file will be loaded automatically.
2. Notice that the flow lines show different colors, however, the color bar has only one color and one value.
3. Examine the color mapping variable using the histogram. Notice that this variable has a non-constant data field.

[CircularRibbonFlare.vs3.tar.gz](https://github.com/NCAR/VAPOR/files/6461193/CircularRibbonFlare.vs3.tar.gz)

**Comment by clyne** [comment]
Comments from Matthias:![Emission_Circ_Ribbon_Flare_top_vz](https://user-images.githubusercontent.com/6777736/117886270-2ad8de80-b26c-11eb-8ba2-496518421d19.png)
Hi John,

I'm working on the attached figure with vapor. The annotation in the lower left should correspond
to the red-blue field lines (colormapped the vertical velocity), but it just shows a constant value (of 1) and constant color. I'm not sure what I'm doing wrong here.

**Comment by sgpearse** [comment]
Session file no longer seems to work.

<img width="1599" alt="Screen Shot 2021-07-12 at 5 39 07 PM" src="https://user-images.githubusercontent.com/9522770/125368776-4168e800-e338-11eb-9a26-131bebb3949c.png">
