### ISSUE TITLE
Contours: Allow for rendering 3D variables

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2728]
Our contour renderer only works with 2D variables.  Users have expressed the need for having them in 3D too: i.e. draw contours on a slice from a 3D volume

**Comment by clyne** [comment]
Related to #2637

**Comment by clyne** [comment]
The plane manipulator that was implemented to support #2637 is somewhat cumbersome to use. I looked at what both VISiT and ParaView are doing and found their approach to be not terribly satisfying either (though ParaView supports mouse interactions that make manipulating the plane much easier). There are two problems with our current implementation. First, while specifying the orientation as rotations about the primary axis does the job, it assumes that there is some default orientation about which these transformations apply. Specifying the orientation via a normal is less ambiguous and, IMHO, more natural for describing the orientation of a plane. This is what both ViSIT and ParaView do. 

The more problematic issue is the "Slice Origin"; it provides more degrees of freedom than are necessary, which makes it confusing to use. For example, if the plane is perpendicular to the Z axis, changing the Y and X coordinates is a no-op. I find it pretty challenging to position a non-axis-aligned plane where I want it. A simpler, more intuitive approach might be to specify a displacement along the plane normal.  The displacement could be from either the origin or the center of the domain. I think this would give the flexility to arbitrarily position the plane in a way that is far more intuitive. 

@StasJ , @sgpearse, thoughts?

**Comment by StasJ** [comment]
> The plane manipulator that was implemented to support #2637 is somewhat cumbersome to use. I looked at what both VISiT and ParaView are doing and found their approach to be not terribly satisfying either (though ParaView supports mouse interactions that make manipulating the plane much easier). There are two problems with our current implementation. First, while specifying the orientation as rotations about the primary axis does the job, it assumes that there is some default orientation about which these transformations apply. Specifying the orientation via a normal is less ambiguous and, IMHO, more natural for describing the orientation of a plane. This is what both ViSIT and ParaView do.
> 
> The more problematic issue is the "Slice Origin"; it provides more degrees of freedom than are necessary, which makes it confusing to use. For example, if the plane is perpendicular to the Z axis, changing the Y and X coordinates is a no-op. I find it pretty challenging to position a non-axis-aligned plane where I want it. A simpler, more intuitive approach might be to specify a displacement along the plane normal. The displacement could be from either the origin or the center of the domain. I think this would give the flexility to arbitrarily position the plane in a way that is far more intuitive.
> 
> @StasJ , @sgpearse, thoughts?

I agree that a displacement along the plane normal would be a more intuitive control scheme. Additionally I believe a common use case would be to look at multiple slices along the plane normal which is difficult to do with the XYZ sliders.

**Comment by clyne** [comment]
@StasJ perhaps you can try that approach with the contour renderer and we can A/B with the slice renderer interface...

**Comment by sgpearse** [comment]
> There are two problems with our current implementation. First, while specifying the orientation as rotations about the primary axis does the job, it assumes that there is some default orientation about which these transformations apply. Specifying the orientation via a normal is less ambiguous and, IMHO, more natural for describing the orientation of a plane. This is what both ViSIT and ParaView do.

I'd like to try it, but I'm wondering how specifying a normal is less ambiguous to a layman.  Plane normals are familiar to graphics programers, but are they a familiar concept to meteorologists?  I don't know, but I do think that 3 axis rotation could be a more basic way to describe the same thing.  If we go down this route, I think it would be helpful to render an arrow indicating the direction of the normal.

> I find it pretty challenging to position a non-axis-aligned plane where I want it.

I'd like to understand the challenge you're facing.  I haven't had any problems, but then again I'm the guy who wrote the thing.

> A simpler, more intuitive approach might be to specify a displacement along the plane normal. The displacement could be from either the origin or the center of the domain. I think this would give the flexility to arbitrarily position the plane in a way that is far more intuitive.

This would reduce the 3 parameter origin controls into a single displacement controller, which is good.

There will likely be edge cases to sort out here.  I'm not sure what will happen if the slice's origin is defined outside of the domain bounds.  Specifying a _displacement_ can put the origin outside the domain but the current origin controls cannot.  Off the top of my head, this might require changes to the sampling logic.
