### ISSUE TITLE
Test and build platforms need to be configured to enable OpenMP

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2739]
Currently, our test and build platforms are not set up to compile VAPOR with OpenMP enabled.

**Comment by sgpearse** [comment]
@clyne A few questions:

1) Do we want to enable our USE_OMP flag for our release builds?  It's currently defaulted to OFF.
2) Do we want to enable it for both debug and release CI tests, on Ubuntu and CentOS?  Or, do we want to have a new set of tests where we build with it?  Right now we test for compilation and warnings in release and debug mode.  Would the following set of compilation/warning tests fit our bill?

Test compilation/warnings on:
- Ubuntu/CentOS
- Debug/Release-mode
- USE_OMP ON, and OFF

**Comment by clyne** [comment]
Yes, I believe we want to enable USE_OMP for all platforms that we are able (Mac OS X and Linux). Note for Mac this will require installing the LLVM clang compiler ourselves. The Apple version of the clang compiler does NOT support OpenMP.

We should do our Circle CI testing with USE_OMP  enabled, both for debug and release mode. I don't see any reason to also test with OpenMP disabled at this time. 


CC'ing @shaomeng and @stasj for their input.

**Comment by shaomeng** [comment]
From a test completeness perspective, as long as the build configuration supports *both* enable and disable modes, *both* modes should be tested.

**Comment by StasJ** [comment]
I agree with John that there isn't much reason to test with OpenMP disabled since we are planning to ship all builds with it enabled.

**Comment by clyne** [comment]
We won't be able to enable OpenMP support on Windows. So @shaomeng is probably right; we should build&test with and without OpenMP support.

**Comment by clyne** [comment]
Copy-n-paste email thread on this topic below:

Interesting, do we have a macos circle CI set up?
 
Yes, circle is building the installers on all platforms.

Thanks for the doc.  It helps a lot.

A couple questions:

1) Should we add omp to our third party libraries for OSX?
2) If we're distributing our installers with OpenMP, should we make the settings in Sam's document the default in CMakeLists.txt?
3) Before following sam's instructions, I was getting the error below which is due to the use of c++14 features.  Are we still on c++11 with the omp changes?

In file included from /Users/pearse/VAPOR/apps/vaporgui/AnimationController.h:3:
In file included from /usr/local/VAPOR-Deps/2019-Aug/Qt/5.13.2/clang_64/lib/QtCore.framework/Headers/QTimer:1:
In file included from /usr/local/VAPOR-Deps/2019-Aug/Qt/5.13.2/clang_64/lib/QtCore.framework/Headers/qtimer.h:43:
/usr/local/include/QtCore/qglobal.h:675:26: error: no template named 'enable_if_t' in namespace 'std'; did you mean 'enable_if'?
         typename = std::enable_if_t<std::is_arithmetic_v<T> && std::is_arithmetic_v<U> &&
                    ~~~~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:538:63: note: 'enable_if' declared here
template <bool, class _Tp = void> struct _LIBCPP_TEMPLATE_VIS enable_if {};

On Thu, Jul 1, 2021 at 9:26 AM Samuel Li <shaomeng@ucar.edu> wrote:
Interesting, do we have a macos circle CI set up? 

On my laptop, I use homebrew:
https://docs.google.com/document/d/1nsaarW3jaZVAJFIHsERZ7MWMlms57LbErdcLgjtAkTo/edit#heading=h.p2vqktlbuajw

On Thu, Jul 1, 2021 at 8:49 AM John Clyne <clyne@ucar.edu> wrote:
Good question. I use Mac Ports to manage 3rd party packages on my Mac and simply installed 'clang-11’ with ’sudo port install clang-11’. If you end up with multiple versions of clang installed you can manage those (select the default version) with something like "port select clang  clang-11”. 

I’m pretty sure you can also install clang from Homebrew, which may be what Sam and or Stas use.

Lastly, all of the testing I’ve done has been with clang-11, which I think is the most current version of clang available on Mac Ports, but may not be the most current version that exists. I don’t see any reason to not use clang-11, but Sam and Stas may have input.

**Comment by clyne** [comment]
I don't see any reason/benefit for compiling our 3rd party libs with OpenMP. To the best of my knowledge none of them have OpenMP support that would benefit us, and they seem to work fine as is.

Re the CMakeList.txt file: my inclination is to not burden the external community with OpenMP. Building without OpenMP support should work fine, albeit their code will be slower. So I'd be inclined for the default build environment to use the bundled Apple compiler without OpenMP. Thus we would have to customize the env. for our OpenMP builds.  What do others think?

Re c++14: I don't see any reason for us to not move to C++14. However, that might be best addressed separately, possibly after this release. I think we should take whatever path is simplest.

**Comment by sgpearse** [comment]
> I don't see any reason/benefit for compiling our 3rd party libs with OpenMP. To the best of my knowledge none of them have OpenMP support that would benefit us, and they seem to work fine as is.

I agree - but do we want to include it in our third party library tarball?  I don't think so, unless we want to make the OMP settings default in CMakeLists.txt.

> Re the CMakeList.txt file: my inclination is to not burden the external community with OpenMP. Building without OpenMP support should work fine, albeit their code will be slower. So I'd be inclined for the default build environment to use the bundled Apple compiler without OpenMP. Thus we would have to customize the env. for our OpenMP builds. What do others think?

I hear you, but this will make accepting external code harder.  The contributor will run their tests and submit changes, and we will need to re-test a different beast with OMP enabled.  Maybe automation can make this a non-issue.  Or, maybe others feel this isn't a big deal.

> Re c++14: I don't see any reason for us to not move to C++14. However, that might be best addressed separately, possibly after this release. I think we should take whatever path is simplest.

I agree 100%.

**Comment by clyne** [comment]
> > I don't see any reason/benefit for compiling our 3rd party libs with OpenMP. To the best of my knowledge none of them have OpenMP support that would benefit us, and they seem to work fine as is.
> 
> I agree - but do we want to include it in our third party library tarball? I don't think so, unless we want to make the OMP settings default in CMakeLists.txt.

I'm not sure I know what you mean by "include it in our third party library tarball". I already stated that I don't see any reason to touch our 3rd party libs, which, to the best of my knowledge, were compiled a couple of years ago.

> 
> > Re the CMakeList.txt file: my inclination is to not burden the external community with OpenMP. Building without OpenMP support should work fine, albeit their code will be slower. So I'd be inclined for the default build environment to use the bundled Apple compiler without OpenMP. Thus we would have to customize the env. for our OpenMP builds. What do others think?
> 
> I hear you, but this will make accepting external code harder. The contributor will run their tests and submit changes, and we will need to re-test a different beast with OMP enabled. Maybe automation can make this a non-issue. Or, maybe others feel this isn't a big deal.

I believe @shaomeng opined that we should run our tests with and without OMP enabled. That makes sense to me (though earlier I said the opposite, but Sam persuaded me). This should simply entail a change of the OMP_Enable flag (or whatever it is called). 

> 
> > Re c++14: I don't see any reason for us to not move to C++14. However, that might be best addressed separately, possibly after this release. I think we should take whatever path is simplest.
> 
> I agree 100%.

**Comment by sgpearse** [comment]
> I'm not sure I know what you mean by "include it in our third party library tarball". I already stated that I don't see any reason to touch our 3rd party libs, which, to the best of my knowledge, were compiled a couple of years ago.

I'm referring to [these bundles](https://drive.google.com/drive/u/0/folders/0B0dQMtxB89M0Q2F2U3ZaQ2dVeWs?resourcekey=0-KjrYiMNi3FG-JnLKuDFupw) that we distribute to people who want to compile Vapor from source.  Some of these libraries were compiled by ourselves, but some are pre-compiled binaries.  Last release, we added pre-compiled Ospray libraries and I'm wondering if we should do the same for OMP.  

There are also some libraries in our tarballs that users need to install manually.  On Ubuntu, users need to manually install expat, glib, and dbus.  Should OMP be included in the tarball, or should developers install it themselves?  

I'd lean towards including it in the tarball because 1) it makes everyone's build systems consistent, and 2) it makes it easier for people to contribute to Vapor.  But I also think that this is something that can wait until 3.6.

**Comment by clyne** [comment]
> > I'm not sure I know what you mean by "include it in our third party library tarball". I already stated that I don't see any reason to touch our 3rd party libs, which, to the best of my knowledge, were compiled a couple of years ago.
> 
> I'm referring to [these bundles](https://drive.google.com/drive/u/0/folders/0B0dQMtxB89M0Q2F2U3ZaQ2dVeWs?resourcekey=0-KjrYiMNi3FG-JnLKuDFupw) that we distribute to people who want to compile Vapor from source. Some of these libraries were compiled by ourselves, but some are pre-compiled binaries. Last release, we added pre-compiled Ospray libraries and I'm wondering if we should do the same for OMP.

Again, there is no reason to recompile a library that VAPOR depends on in order to add OMP support. VAPOR can be compiled WITH OpenMP, and all of the libraries that VAPOR depends on can be compiled WITHOUT OpenMP. Mixing the two is no problem, and I don't see that anything would be gained by trying to make them consistent.

> 
> There are also some libraries in our tarballs that users need to install manually. On Ubuntu, users need to manually install expat, glib, and dbus. Should OMP be included in the tarball, or should developers install it themselves?

I don't understand what you mean by "should OMP be included in the tarball". OpenMP is library that is provided by the compiler. We can't (shouldn't) distribute OMP. If someone wants to compile something with OpenMP they need a compiler environment that supports it.

> 
> I'd lean towards including it in the tarball because 1) it makes everyone's build systems consistent, and 2) it makes it easier for people to contribute to Vapor. But I also think that this is something that can wait until 3.6.

**Comment by sgpearse** [comment]
> I don't understand what you mean by "should OMP be included in the tarball". OpenMP is library that is provided by the compiler. We can't (shouldn't) distribute OMP. If someone wants to compile something with OpenMP they need a compiler environment that supports it.

Thanks, this answers my question.  I wasn't suggesting re-compiling our 3rd party libraries.  I was asking if we should add the files below to the third-party tar.xz archives we distribute.  The answer is no.

    lib/libomp.dylib
    include/ompt.h
    include/omp.h
    include/omp-tools.h

**Comment by clyne** [comment]
Now I see the disconnect. However, this raises another issue: the runtime library, libomp.{dylib,so} will almost certainly need to be bundled with our installer. Hoping this is not opening a can of worms. @StasJ, need your input on this.

**Comment by StasJ** [comment]
> Now I see the disconnect. However, this raises another issue: the runtime library, libomp.{dylib,so} will almost certainly need to be bundled with our installer. Hoping this is not opening a can of worms. @StasJ, need your input on this.

I am working on it. I'll open a PR once its ready.

**Comment by clyne** [comment]
Thanks, @StasJ

**Comment by clyne** [comment]
@clyne needs to look at performance issues reported by @stasj in #2770

**Comment by clyne** [comment]
@stasj I can't reproduce the performance problems you reported in #2770 when running locally on either my Mac or CISL-VAPOR (Ubuntu). Benchmarking threaded code on the CircleCI systems may not be very meaningful....

**Comment by StasJ** [comment]
> @StasJ I can't reproduce the performance problems you reported in #2770 when running locally on either my Mac or CISL-VAPOR (Ubuntu). Benchmarking threaded code on the CircleCI systems may not be very meaningful....

I don't know, I just noticed that the timing results in `VAPOR/test_apps/smokeTests/testResults/` had increased.

**Comment by clyne** [comment]
If we can't reproduce a performance problem outside of CircleCI I am inclined to not worry about it.
