### ISSUE TITLE
strange visualizer window in Vapor3.4 

### ISSUE THREAD

**Issue by seanboulder** [NCAR/VAPOR#2751]
I just installed Vapor 3.4 on MacOS Big Sur. When I open Vapor, the visualizer window is transparent. After importing a WRF-ARW file, a black visualizer window with only 1/4 size appears on the lower-left corner. Any fix? Thanks very much.

![image](https://user-images.githubusercontent.com/52478641/121583522-5df2c700-c9fe-11eb-8955-13a20c116cb2.png)

![image](https://user-images.githubusercontent.com/52478641/121583905-de192c80-c9fe-11eb-989b-d4da4a61bc2a.png)

**Comment by sgpearse** [comment]
@seanboulder The transparent visualizer is something we've looked at before, but your report may put more emphasis on getting this fixed.  Note for team: #2488 reports the same issue.

The visualizer taking up 1/4 of your window is new to me though .  Can you provide us with the verison of Vapor you're using, the OS you're using, and/or a sample file and a session file?  We'll try to reproduce it and the better we can replicate what you see, the more likely we'll be able to fix it.

Thanks for reporting this.

**Comment by seanboulder** [comment]
@sgpearse @clyne 
Vapor Version: 3.4.0.117aeef18
Macbook Pro 2020, Big Sur 11.4
Sample WRF data: https://drive.google.com/file/d/1wgOp2hwhjRmO8s0FXxgBFG4vuSdmxWv5/view?usp=sharing
I also reported the same problem on vapor.discourse.group

I tried Vapor 3.3, it doesn't have this small window problem. 

Many thanks.

**Comment by clyne** [comment]
I've confirmed that this works fine with the attached data set on Catalina (Mac OSX 10.15.7). I guessing this is a Big Sur problem. We'll have to see if we can run down a 11.x Mac.

**Comment by sgpearse** [comment]
Also being reported by ViggoHanst [on our forum](https://vapor.discourse.group/t/only-one-quarter-of-canvas-filled-on-macbook-pro/103). :\

**Comment by sgpearse** [comment]
[As well as by user yochen.](https://vapor.discourse.group/t/strange-visualizer-window-in-vapor3-4/98)

**Comment by wgustafson** [comment]
I am also seeing this issue on Big Sur with the window only being quarter filled. I am also seeing a different issue that I think is related, which is why I'm posting this here. I am unable to drag the red handles to adjust the plotted region. When I try to drag the handle, the visualized box rotates instead. I am guessing this is because the code thinks the handle is somewhere else on the screen based on the full window instead of the quarter window that is displayed--just a guess though.

**Comment by shaomeng** [comment]
I'm able to verify this reported bug using the 3.4 installer.

If I open VAPOR from a local build and import the attached WRF file, VAPOR will crash with this message on screen:

```
shaomeng@cisl-watson VAPOR-git/build % ./bin/vapor.app/Contents/MacOS/vapor
qt.qpa.window: <QNSWindow: 0x7f86c91bb100; contentView=<QNSView: 0x7f86c91ba940; QCocoaWindow(0x7f86c91ba820, window=QWidgetWindow(0x7f86c91b8540, name="QGLWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
num threads = 16
num threads = 16
num threads = 16
num threads = 16
num threads = 16
num threads = 16
num threads = 16
num threads = 16
num threads = 16
num threads = 16
num threads = 16
num threads = 16
num threads = 16
num threads = 16
num threads = 16
num threads = 16
zsh: bus error  ./bin/vapor.app/Contents/MacOS/vapor
```

**Comment by clyne** [comment]
@shaomeng do you have the resources to troubleshoot and repair?

**Comment by shaomeng** [comment]
No, I don't have experience with OpenGL in QT, nor how VAPOR initializes an
OpenGL environment etc.

**Comment by clyne** [comment]
Suggestions on how we resolve this then? @stasj is probably the one that needs to look at it, but I don't believe he has access to a Mac OSX 11.x system...

**Comment by shaomeng** [comment]
Given that VAPOR 3.3 runs well on Big Sur (which I have verified to be true) while VAPOR 3.4 doesn't, I think it's more likely a VAPOR problem rather than a macos problem: something changed in vapor wrt OpenGL from VAPOR 3.3 to 3.4. I can help with testing, but I'd agree that it'd make things a lot easier if Stas has a Big Sur machine.

**Comment by StasJ** [comment]
If that is the case then I have no idea what could be the culprit. I thought it would be the QOpenGLWidget however that has not changed since Vapor 3.1

**Comment by clyne** [comment]
Do we have another Mac that would could update to 11.x that @stasj can lay hands on? @sgpearse what about our test systems?

**Comment by clyne** [comment]
@sgpearse will have one of our loaner macs updated to 11.x and hand the system over to @stasj for troubleshooting this problem.
