### ISSUE TITLE
Height offset wrong in high-altitude, high-resolution WRF simulation

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2755]
To reproduce:
1) Create a personal copy of the data in /glade/p/cisl/vast/vapor/Bugs/2755, which contains a session and a wrfout file
   1a) Alternatively download [this zip file](https://drive.google.com/file/d/15Ew5TJo3jNFdMiWKcifD9acEbfZEC4w6/view?usp=sharing)
2) Edit the session file to point to your copy of the wrfout file, and open the session
3) Observe that the 2D renderer of HGT is roughly at an elevation of 7000 meters
4) Now look at the transfer function to see that the HGT variable's range is between 3076 and 5030 meters

The HGT rendering should be aligning with the missing value region at the bottom of the slice.

![Screen Shot 2021-06-22 at 12 06 31 PM](https://user-images.githubusercontent.com/9522770/122977545-c6bd3600-d352-11eb-9eed-0a825eaf95b9.png)

**Comment by clyne** [comment]
@sgpearse please relocate data the glade bugs directory
