### ISSUE TITLE
Smoke tests crash with OpenMP

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2772]
Running our smoke tests with OMP enabled results in a memory error.

This can be seen on OSX, and our CircleCI tests that run on Ubuntu.

**Comment by clyne** [comment]
@sgpearse can you include the error message and any other information to help reproduce the problem locally?

**Comment by sgpearse** [comment]
This is non-deterministic and will occasionally pass.  Two of the errors I've seen in lldb are listed below.

To reproduce on OSX:
1) on main, issue the following cmake command from the VAPOR/build directory
> cmake -DCPACK_BINARY_DRAGNDROP=ON -DCMAKE_BUILD_TYPE:String=Release -DDIST_INSTALLER:string=ON -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_FLAGS=-I/usr/local/opt/llvm/include -DCMAKE_EXE_LINKER_FLAGS=-L/usr/local/opt/llvm/lib -DUSE_OMP=ON -DBUILD_TEST_APPS=ON -Wl,-rpath,/usr/local/opt/llvm/lib ..

2) from the build directory, issue the following:
> lldb bin/testGrid
> run -dims 8x8x8

Error 1:
> testGrid(28189,0x70000865e000) malloc: Double free of object 0x101315d60
testGrid(28189,0x700008e61000) malloc: *** error for object 0x101315df0: pointer being freed was not allocated
testGrid(28189,0x700009e67000) malloc: *** error for object 0x101315df0: pointer being freed was not allocated
testGrid(28189,0x70000564c000) malloc: Double free of object 0x101315d60
testGrid(28189,0x70000a66a000) malloc: Double free of object 0x101315d60
Process 28189 stopped
>* thread #7, stop reason = EXC_BAD_ACCESS (code=1, address=0x30d)
    frame #0: 0x00000001001280e1 libvdc.dylib`VAPoR::Grid::GetValueAtIndex(std::__1::array<unsigned long, 3ul> const&) const + 33
libvdc.dylib`VAPoR::Grid::GetValueAtIndex:
->  0x1001280e1 <+33>: movss  (%rax), %xmm0             ; xmm0 = mem[0],zero,zero,zero
    0x1001280e5 <+37>: addq   $0x8, %rsp
    0x1001280e9 <+41>: popq   %rbx
    0x1001280ea <+42>: popq   %rbp

Error 2:
>testGrid(28209,0x70000651f000) malloc: *** error for object 0x101704a40: pointer being freed was not allocated
testGrid(28209,0x70000651f000) malloc: *** set a breakpoint in malloc_error_break to debug
Process 28209 stopped
>* thread #12, stop reason = signal SIGABRT
    frame #0: 0x00007fff6d48f33a libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff6d48f33a <+10>: jae    0x7fff6d48f344            ; <+20>
    0x7fff6d48f33c <+12>: movq   %rax, %rdi
    0x7fff6d48f33f <+15>: jmp    0x7fff6d489629            ; cerror_nocancel
    0x7fff6d48f344 <+20>: retq

**Comment by clyne** [comment]
@sgpearse I can't reproduce this. What version of clang are you running? Also, could you please compile with -g and rerun so there is more info?

**Comment by sgpearse** [comment]
> What version of clang are you running? Also, could you please compile with -g and rerun so there is more info?

clang version 12.0.0
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

I remember you mentioned that you're using v11.  I also installed with brew instead of ports.

> Also, could you please compile with -g and rerun so there is more info?

Sure, give me a moment.  I'll also try to reproduce this on cisl-vapor, which might help if we both see the problem on one system.

**Comment by sgpearse** [comment]
@clyne I'm no longer able to reproduce this on main.

I am however able to reproduce it when checking out commit 20af529eae7450cf6b84a2c957afe45df84c4f06.  @shaomeng had a PR that was merged this morning which I _believe_ fixed the issue.  I'm not totally sure why or how.

Either way, I can't reproduce it after 8c01dcedfcb5bca15b1f40133c6215c42a082efd was merged.

**Comment by clyne** [comment]
I'd say let's close it unless the problem returns :-)
