### ISSUE TITLE
Switch clang formatting from pre-push to pre-commit hook

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2777]
Currently we apply a GitHub pre-push hook with each PR that performs formatting with clang-format. For whatever reason this has proven to be unreliable, often resulting in complaints about code that was not edited requiring formatting. We should consider using a pre-commit for this task, which is the more common practice.

**Comment by shaomeng** [comment]
Imagine the following scenario:

1) The developer is editing a source file in vim (or any editor) in terminal window #1.
2) He/she builds VAPOR and tests functionalities in terminal window #2 while the editing session remains active in window #1. 
3) When he/she completes developing and testing of a module/class/function, he/she commits the changes before moving on to the next module/class/function.

Q: what will happen to the editor session in terminal window #1 ?

**Comment by sgpearse** [comment]
@shaomeng You'll need to refresh the file.  If you're using vi/vim, `:e!` will do the trick.
