### ISSUE TITLE
CircleCI is triggered by branches and commits that are not even in a PR

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2780]
### Describe the bug
It seems whenever a new branch with commits gets pushed to Github, CircleCI is triggered, even though the pushed branch is simply experimenting and doesn't belong to any PR. This is a waste of cycles and drains CircleCI credits. 

<img width="684" alt="Screen Shot 2021-07-08 at 12 54 31 AM" src="https://user-images.githubusercontent.com/814885/124876650-7c110000-df87-11eb-9eef-848c06c515f4.png">

**Comment by sgpearse** [comment]
We haven't had any recent complaints from the NCAR administrators about our CircleCI usage.  If we do have more, we should look at strategies to reduce clock time, but for now we seem ok.
