### ISSUE TITLE
cisl-garibaldi can no longer serve as a CentOS7 dev machine

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2781]
cisl-garibaldi runs CentOS7, which has the default compiler of gcc 4.8.

For unknown reasons, the default compiler on cisl-garibaldi becomes gcc-9.3, which isn't the default compiler version of CentOS7.

For this reason, cisl-garibaldi can no longer serve as a CentOS7 dev machine.

**Comment by sgpearse** [comment]
Question: Will Vapor compile with gcc 4.8?

**Comment by shaomeng** [comment]
not applicable anymore.
