### ISSUE TITLE
Contour: Min and Spacing widgets usage weird

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#279]
Under the Appearance tab of Contour, the "Contour Minimum" and "Spacing" widgets are only for showing the values, but not for user interactivity. 

However, they are using the slider bar + text box widget, which is used for user interactivity across the application. This inconsistent use of  slider bar + text box widget causes confusion...
![screenshot from 2017-11-07 22-50-10](https://user-images.githubusercontent.com/814885/32533543-8080bc9a-c40e-11e7-8503-1264de83e5a6.png)

**Comment by sgpearse** [comment]
If you uncheck "Lock properties to TF bounds" they become enabled.  The default behavior is for the contours to adhere to what's shown in the transfer function.  If you'd like to extend the isovalues beyond that range, you can uncheck the box and control them with the Contour Minimum and Spacing sliders.

**Comment by shaomeng** [comment]
Update on 4/4/2018:
It seems the interface has changed, so this issue is no longer valid. I'm going to close it.
