### ISSUE TITLE
Top time step control doesn't honor max time step settings

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2799]
To reproduce:
1. Open VAPOR, load 18 time steps from the WRF->Katrina data set.
2. Create a wireframe renderer
3. Go to Scene->Animation panel, set the "Animation Last Timestep" control to be 10.
4. Notice that within Scene->Animation panel, all knobs honor the new setting, i.e., no knob can go beyond time step 10.
5. Notice that the top time step panel does not honor this setting: i.e., if you type 15, it accepts 15 (as the screenshot shows).

![image](https://user-images.githubusercontent.com/814885/125376530-6feebf00-e348-11eb-88c7-4237a3134fe9.png)

**Comment by StasJ** [comment]
I believe this is the correct behavior. The animation control panel is for controlling the animation playback. The timestep input in the top bar is for setting the current timestep. Those are separate functionalities. If you play the animation from the top bar, it will respect the parameters in the animation control panel.
