### ISSUE TITLE
Contour: TF Function Editor not having any effect

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#280]
The vertical bars of TF Function Editor of Contour Renderer are movable, but not having any effect. 
To reproduce:

1. Open VAPOR, load Katrina.
2. Create a Contour Renderer, select MU variable.
3. Under the Appearance subtab, there are 7 vertical bars by default, and they are movable by mouse.
4. Weird thing is, moving these bars have no effect on the rendered contours.

**Comment by sgpearse** [comment]
I agree, the contour indicator lines should be immovable.
