### ISSUE TITLE
DVR problem on ROMS data

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2800]
The DVR is giving different results based on which side of the domain we are viewing from, in the ROMS/Kauffman dataset.

To reproduce:
1) On casper, open the session file /glade/p/cisl/vast/vapor/Bugs/2800.vs3
2) Note that the DVR is different when viewing through the YZ plane, versus the XY plane.

![Screen Shot 2021-07-13 at 9 35 44 AM](https://user-images.githubusercontent.com/9522770/125481762-f1f8f369-f4d3-40af-bea4-bd829408c127.png)

![Screen Shot 2021-07-13 at 9 36 41 AM](https://user-images.githubusercontent.com/9522770/125481728-fd2382e4-89e5-4618-8602-6148449c39e4.png)

**Comment by shaomeng** [comment]
Note: the data set used is ROMS/Kauffman.

**Comment by sgpearse** [comment]
Unfortunately, I see the following with the DVR on ROMS/Kauffman:

Home viewpoint:

![Screen Shot 2021-07-26 at 8 54 32 AM](https://user-images.githubusercontent.com/9522770/127010845-3c6d8498-90ad-421a-9d89-03bfa4b2e0b9.png)

Rotate about the X axis:

![Screen Shot 2021-07-26 at 8 55 17 AM](https://user-images.githubusercontent.com/9522770/127010880-a7dbecd5-a276-4d83-bd04-72cab2001306.png)

**Comment by clyne** [comment]
That may simply be because the ROMS data are uber thin along the Z axis and are missed entirely by the sampling.

**Comment by sgpearse** [comment]
The ROMS data seem to be passing.  Since this is CAM, I'm going to make a new report.

**Comment by sgpearse** [comment]
Reopening, since we're backing out the DVR fix for now.

**Comment by sgpearse** [comment]
@stasj - If this cannot be conceivably fixed, we can postpone it.  

Request: please add any comments as to why.

**Comment by StasJ** [comment]
> @StasJ - If this cannot be conceivably fixed, we can postpone it.
> 
> Request: please add any comments as to why.

This was fixed however the DVR code is extremity fragile due to bugs in the GLSL compilers and the fix had to be rolled back.
