### ISSUE TITLE
Flow renderer crashes with MPAS-O

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2802]
1. Open MPAS-O
2. Create a flow renderer
3. Play with variable settings, i.e. change selected variables and change between 2d/3d. Enable/disable renderer.

Vapor will crash.

**Comment by shaomeng** [comment]
Hi Stas, I cannot reproduce it based on the current description. Can you be more specific on steps to crash it?

**Comment by sgpearse** [comment]
@stasj will give it another shot.

**Comment by StasJ** [comment]
I can no longer reproduce this after @clyne's iterator fix.
