### ISSUE TITLE
Windows installer?

### ISSUE THREAD

**Issue by WUR-BrianV** [NCAR/VAPOR#2806]
Hi all,

I am looking to use VAPOR on my Windows computer to make 3D plots of WRF-Fire output. With the standard download, there was a bug with loading in idealised WRF-Fire data (VAPOR crashed). This was resolved some time ago and I was told to download the new weekly built when it would come. Unfortuantely, I couldn't as I cannot find an installer for Windows on there.

My question is whether one for Windows can be made available so that I can use the fixed version of VAPOR to visualize my WRF-Fire output.

Best,
Brian

**Comment by sgpearse** [comment]
Hi Brian, we have a windows installer for our latest release, linked below.

https://github.com/NCAR/VAPOR/releases/tag/3.4.0

**Comment by WUR-BrianV** [comment]
Hi,

That version is what I already had on my computer. It is regarding this issue:
https://vapor.discourse.group/t/issue-importing-wrf-fire-ideal-run-file/76/10

Best,
Brian

**Comment by sgpearse** [comment]
Got it.  Our windows build is currently broken we might be able to get you something by the end of the day.  Stay tuned.

**Comment by sgpearse** [comment]
Hi Brian, sorry this took longer than expected.  Please try the installer at the link below:

https://drive.google.com/file/d/1v96st4ZFnKIGGzh-Y3cpUe-qTxWAFV_P/view?usp=sharing

**Comment by WUR-BrianV** [comment]
Hi again,

Thanks a lot for the Windows installer. I am happy to say that the installer worked and that loading and plotting WRF-Fire output was succesful. Thanks a lot!

Best,
Brian
