### ISSUE TITLE
BOV: not supporting implicit multiple time steps

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2821]
To reproduce: 
1) Open VAPOR.
2) Import 2 BOV files representing 2 time steps: 
`/glade/p/cisl/vast/vapor/Bugs/BOV_Bugs/bug7.bov` and `/glade/p/cisl/vast/vapor/Bugs/BOV_Bugs/bug8.bov`.
3) Create a renderer. Notice that VAPOR shows there's only one time step.

**Comment by clyne** [comment]
@shaomeng there is no time specified in these files, so I'm guessing they are both given the same default user time. Perhaps an error should be issued, but otherwise the behavior seems reasonable to me (unless there is something in the BOV spec that says time-varying data can be specified this way).

**Comment by shaomeng** [comment]
When a user time is not provided, I'd think the default user time should NOT be a fixed value, but rather be the file index.

In anyway event, the only mention of the time attribute in Scott BOV specification is that "time is optional." I'd be OK if Scott provides more detailed specification on what is treated as single vs. multiple time steps.

**Comment by clyne** [comment]
It would reasonable to simply flag a missing TIME variable with multiple files as an error

**Comment by sgpearse** [comment]
Make TIME a required field.

**Comment by sgpearse** [comment]
> Make TIME a required field.

After looking at this, I think it's best to update the documentation instead.

If we make TIME a required field, the user can _still_ have multiple BOV files with the same time value for a variable.  Duplicate BOV files get skipped in this case.

The documentation does state that TIME is given a default value, but I'll make it clearer that if duplicate timestep/variable pairs are given, they will be skipped.

**Comment by sgpearse** [comment]
We will not support BOV files that do not contain a TIME variable.
