### ISSUE TITLE
Contour: Color mapping cannot go back to "Map to Var"

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#283]
1. Under Appearance tab, the default option of "Color Mapping" is "Map to Var." It works great.
2. One can change the value to "Constant." It still works great. 
3. If one selects "Map to Var" again, sorry, you cannot go back!

**Comment by clyne** [comment]
Scott, I'm assigning this back to you after our discuss as you are already working on the TFWidget.

**Comment by clyne** [comment]
Reopening. It is no longer possible to select constant color
