### ISSUE TITLE
OpenMP causing crash

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2839]
I've been looking at #2831 (Bookmark crashes) and #2825 (VAPOR disappears upon closing notice board) and it appears Vapor can't find librender when built with OMP.  It turns out that this kind of crash can also happen when closing the Preferences menu.

Additionally, running Vapor from source with OpenMP in both Debug and Release modes will crash on startup.  Debugging the crashes in the Notice Board, Preferences Menu, and our Bookmarks cannot be done until Vapor can successfully launch.

  Here are the traces for these two configurations:

**Running from a source build, with Debug mode and OMP:**
```    (base) cisl-farmington:build pearse$ make && make installer
    (base) cisl-farmington:build pearse$ lldb bin/vapor.app/Contents/MacOS/vapor
    (lldb) target create "bin/vapor.app/Contents/MacOS/vapor"
    Current executable set to '/Users/pearse/VAPOR/build/bin/vapor.app/Contents/MacOS/vapor' (x86_64).
    (lldb) run
    Process 88600 launched: '/Users/pearse/VAPOR/build/bin/vapor.app/Contents/MacOS/vapor' (x86_64)
    dyld: Library not loaded: @rpath/librender.dylib
      Referenced from: /Users/pearse/VAPOR/build/bin/vapor.app/Contents/MacOS/vapor
      Reason: image not found
    Process 88600 stopped
    * thread #1, stop reason = signal SIGABRT
        frame #0: 0x0000000100b19ede dyld`__abort_with_payload + 10
    dyld`__abort_with_payload:
    ->  0x100b19ede <+10>: jae    0x100b19ee8               ; <+20>
        0x100b19ee0 <+12>: movq   %rax, %rdi
        0x100b19ee3 <+15>: jmp    0x100b18408               ; cerror_nocancel
        0x100b19ee8 <+20>: retq
    (lldb) bt
    * thread #1, stop reason = signal SIGABRT
      * frame #0: 0x0000000100b19ede dyld`__abort_with_payload + 10
        frame #1: 0x0000000100b4355d dyld`abort_with_payload_wrapper_internal + 80
        frame #2: 0x0000000100b4358f dyld`abort_with_payload + 9
        frame #3: 0x0000000100b40bf4 dyld`dyld::halt(char const*) + 463
        frame #4: 0x0000000100acbef8 dyld`dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 7497
        frame #5: 0x0000000100ac5227 dyld`dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*) + 453
        frame #6: 0x0000000100ac5025 dyld`_dyld_start + 37
```

**Running from a source build, with Release mode and OMP:**
```(base) cisl-farmington:build pearse$ bin/vapor.app/Contents/MacOS/vapor
dyld: Library not loaded: @rpath/librender.dylib
  Referenced from: /Users/pearse/VAPOR/build/bin/vapor.app/Contents/MacOS/vapor
  Reason: image not found
Abort trap: 6
```

The following table shows the tested configurations on my OSX development laptop.  Note- the noticeboard is not shown with debug builds.

|                       | Notice           | Preferences      | Bookmarks        |
| --------------------- | ---------------- | ---------------- | ---------------- |
| Debug Source          | NA               | pass             | pass             |
| Debug Installer       | NA               | pass             | pass             |
| Release Source        | pass             | pass             | pass             |
| Release Installer     | pass             | pass             | pass             |
| Debug OMP Source      | crash on startup | crash on startup | crash on startup |
| Debug OMP Installer   | NA               | crash            | crash            |
| Release OMP Source    | crash on startup | crash on startup | crash on startup |
| Release OMP Installer | crash            | crash            | crash            |

**Comment by clyne** [comment]
If I compile with the stock clang compiler on my 11.4 system the notifier window will not show. Other problems reported above are not observed.

**Comment by clyne** [comment]
@sgpearse I marked this as high and made it a 3.5 milestone. Hopefully the changes we discussed today will address this problem

**Comment by sgpearse** [comment]
Fixed by using MacPorts' version of llvm, as described in [this document](https://docs.google.com/document/d/1nsaarW3jaZVAJFIHsERZ7MWMlms57LbErdcLgjtAkTo/edit#heading=h.p2vqktlbuajw).
