### ISSUE TITLE
Show the number of cores OpenMP has available to it

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#2840]
It would be helpful to users and developers if vapor showed the number of OpenMP cores available. Perhaps putting this information in About VAPOR?

**Comment by clyne** [comment]
Reopening because @StasJ reports that only one thread is shown on casper with an 8-core VNC session. Stas,
 check the setting of the OMP_NUM_THREADS env. variable. For some reason in my multi-cores session it is set to 1

**Comment by StasJ** [comment]
> Reopening because @StasJ reports that only one thread is shown on casper with an 8-core VNC session. Stas,
> check the setting of the OMP_NUM_THREADS env. variable. For some reason in my multi-cores session it is set to 1

@clyne you are correct, `OMP_NUM_THREADS` was set to 1. This was not set by me, it seems odd that OMP multithreading would be disabled by default on Casper?

**Comment by clyne** [comment]
I think this `OMP_NUM_THREADS` setting was either an oversight, or they have reason that is not readily obvious. I'll reach out to CSG. Can we close this issue and mark it as passed?

**Comment by StasJ** [comment]
Yes, after unsetting the environment variable it works as expected.
