### ISSUE TITLE
BOV file cannot be passed in as a command line parameter

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2842]
To reproduce:
1. In a terminal window, invoke VAPOR in this way: `./bin/vapor /little_glade/data/Source/BOV/2D.bov`
2. VAPOR will say "cannot determine dataset format" as the following screenshot shows. 

Platform: cisl-vapor. 

![image](https://user-images.githubusercontent.com/814885/128062093-12f90e29-c048-40db-957b-d110dc8a45f5.png)

**Comment by clyne** [comment]
Works for me. Can you provide more information, like which data set you are using?

**Comment by shaomeng** [comment]
> Works for me. Can you provide more information, like which data set you are using?
Sure. I've updated the report with more detailed information.

**Comment by sgpearse** [comment]
@sgpearse will create an an enhancement that requires vapor to provide a DC API to test initialization of datasets fed in by the command line.

@clyne will clean up the enhancement and elaborate.

**Comment by clyne** [comment]
Done. See #2844. Closing this issue.
