### ISSUE TITLE
MacOS Clang 13 now ships with OpenMP

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2860]
Given that the latest Clang compiler (and libraries) on MacOS now supports OpenMP, it's time for us to remove the convoluted logic in cmake that handles OpenMP on MacOS. 

Note: this change is brought on by XCode 13 and Clang 13.

**Comment by clyne** [comment]
That's good news! We'll want to test first :-)

**Comment by clyne** [comment]
@shaomeng are you sure about this? Checkout the output below:

```
cisl-benona[608] cc --version
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
cisl-benona[609] touch foo.c
cisl-benona[610] cc -c -fopenmp foo.c
clang: error: unsupported option '-fopenmp'
```

**Comment by shaomeng** [comment]
> 

Hmm, it's correct that Apple Clang doesn't seem to have OMP support. I don't know how I decided earlier that the support was brought in. Let's ignore this issue, and I'm going to close it.
