### ISSUE TITLE
Close VDC: crash 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#287]
To Reproduce:

1. Open Vapor, load Katrina, load DUKU, both ones use the VDC files.
2. Create a barb renderer using Duku. Enable this renderer.
3. Close Duku from the Close VDC menu.
4. Vapor crashes.

**Comment by sgpearse** [comment]
This report was duplicated in bug #305 

Debug info:

4 0x000000010f68bb86 RenderEventRouter::GetActiveParams() const + 1110 (RenderEventRouter.cpp:44)
5 0x000000010f68c5d4 RenderEventRouter::updateTab() + 212 (RenderEventRouter.cpp:305)
6 0x000000010f88f78f VizWinMgr::UpdateRouters() + 2063 (VizWinMgr.cpp:632)
7 0x000000010f893223 VizWinMgr::ReinitRouters() + 1443 (VizWinMgr.cpp:594)
8 0x000000010f87610c MainForm::closeData(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >) + 8796 (MainForm.cpp:1298)
9 0x000000010f8df12e MainForm::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 1230 (moc_MainForm_JNMC47IE5BQP7T.cpp:131)
