### ISSUE TITLE
Separate binary executables to different folders

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2871]
As of 10/5/21, there are 30 binary executables generated in the `bin` directory with a mix of useful binaries, debug binaries, and automatic testing binaries, manual testing binaries, and irrelevant binaries. They can be put in separate directories so the functionality of each directory is clearer.

**Comment by clyne** [comment]
I've submitted a PR #2872 to remove the obviously obsolete test drivers. The remaining test drivers in the test_apps directory fall into two categories:

1. Test drivers in the smokeTests subdirectory are invoked by the python scripts contained therein during our CI automated tests. These drivers would be good candidates for memory analysis with valgrind. The python scripts demonstrate invocation syntax. 
2. The remainder of the test drivers might be more appropriately named 'debug' drivers; they are used to troubleshoot problems in specific components and are constantly modified to meet a specific troubleshooting task. Some of these could, however, be fodder for future test drivers.

Assigning this back over to @shaomeng to create a 'debug' (or other) directory if desired.
