### ISSUE TITLE
New Sessions: crash

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#289]
Two consecutive New Sessions operation results in a Vapor crash.

**Comment by sgpearse** [comment]
This also occurs with non-consecutive new sessions:

To reproduce:

1) Spin up Vapor
2) File -> Import -> WRF-ARW, pick any WRF file
3) File -> New Session
4) File -> Import -> WRF-ARW, pick any WRF file
5) File -> New Session, crash
