### ISSUE TITLE
Python is initialized, but not finalized.

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2891]
In VAPOR, multiple execution paths can lead to python initialization, which calls the `Py_Initialize()` function provided by python API.
 
https://github.com/NCAR/VAPOR/blob/b8cfee1a8523264a70c25a8f20197e0fbfb9c1e6/lib/render/MyPython.cpp#L112

However, there doesn't seem to have any [`Py_Finalize()`](https://docs.python.org/3/c-api/init.html#c.Py_Finalize) in the code base, which is responsible to various clean up work, including freeing memory allocated by python. It should be paired up with `Py_Initialize()`.

I haven't discovered any observable malfunction of VAPOR that is caused by missing `Py_Finalize()`, but there are dozens of errors similar to `Invalid read of size 4` reported by valgrind that I suspect is caused by missing `Py_Finalize()`. One example is pasted below.

```
  216 ==4859== Invalid read of size 4
  217 ==4859==    at 0x57434D6: address_in_range (obmalloc.c:1218)
  218 ==4859==    by 0x57434D6: _PyObject_Free (obmalloc.c:1486)
  219 ==4859==    by 0x572C202: dictresize (dictobject.c:1314)
  220 ==4859==    by 0x572DA52: insertion_resize (dictobject.c:1103)
  221 ==4859==    by 0x572DA52: insertdict (dictobject.c:1149)
  222 ==4859==    by 0x572DA52: PyDict_SetItem (dictobject.c:1576)
  223 ==4859==    by 0x5757146: add_operators (typeobject.c:7220)
  224 ==4859==    by 0x5757146: PyType_Ready (typeobject.c:5005)
  225 ==4859==    by 0x574100B: _Py_ReadyTypes (object.c:1599)
  226 ==4859==    by 0x57FD411: _Py_InitializeEx_Private (pylifecycle.c:363)
  227 ==4859==    by 0x4A51956: Wasp::MyPython::Initialize() (MyPython.cpp:112)
  228 ==4859==    by 0x4A69B9E: VAPoR::PyEngine::Initialize() (PyEngine.cpp:224)
  229 ==4859==    by 0x4A7D14B: VAPoR::CalcEngineMgr::_sync() (CalcEngineMgr.cpp:160)
  230 ==4859==    by 0x49D333F: VAPoR::CalcEngineMgr::ReinitFromState() (CalcEngineMgr.h:51)
  231 ==4859==    by 0x49CD8E0: VAPoR::ControlExec::openDataHelper(bool) (ControlExecutive.cpp:449)
  232 ==4859==    by 0x49CE17B: VAPoR::ControlExec::OpenData(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char      > > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_str      ing<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (ControlExecutive.cpp:500)
  233 ==4859==  Address 0x1f1b1020 is 224 bytes inside an unallocated block of size 288 in arena "client"

```

**Comment by clyne** [comment]
At the time that the Python engine was developed it was not possible to call Py_Finalize; it would break the application. Newer versions of Python could potentially fix this. However, note that Py_Finalize invokes the termination routines for loaded modules. Thus testing Py_Finalize requires testing all Python modules that might be loaded. Since the user may load any modules they want it is not possible to know which modules might be loaded. 

N.B. a related problem with Py_Initialize is that it can only be called once per process.

**Comment by shaomeng** [comment]
Got it, thanks for clarifying!

**Comment by sgpearse** [comment]
Revisit after Python API has been merged.

**Comment by clyne** [comment]
We may not fix this one if the Python library is still broken.
