### ISSUE TITLE
Attempting to import specific dataset causes crash

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2908]
Attempting to import `/glade/p/cisl/vast/vapor/Bugs/2886` as NetCDF-CF will cause vapor to crash.

**Comment by clyne** [comment]
@stasj, Works for me on my Mac. It's a big data set. ARe you running out of memory?

**Comment by clyne** [comment]
N.B. data need to be imported as NetCDF CF, not UGRID
