### ISSUE TITLE
Save Session: missing renderer

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#291]
I created a ImageRenderer and then saved a session file. When I open the session file, the ImageRenderer is missing. 

The saved session file is attached.
[Image.vs3.txt](https://github.com/NCAR/VAPOR/files/1452883/Image.vs3.txt)

**Comment by clyne** [comment]
This bug is fixed. However, it required making changes to what is saved in the session file. The attached session file will still not load, but if a new session file is created with an Image renderer in it it will work.
