### ISSUE TITLE
Need better documentation on how to bypass MacOS security alerts

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2916]
Currently, after a fresh install of VAPOR on macOS, trying to open it will trigger a chain of alerts similar to this one:

<img width="372" alt="Screen Shot 2021-11-27 at 6 47 52 PM" src="https://user-images.githubusercontent.com/814885/143678223-37dd8f4a-5336-4c4b-bfaf-18ecb9d96d8f.png">

The sheer number of such alerts makes it almost impossible to allow them one by one. I remember that there was a command line command that applies to a folder and all the files in the folder are all marked "secure." However, we don't have that command anywhere in the documentation. 

Note: the same issue affects developers using the 3rd party library downloaded from Google Drive too.

**Comment by shaomeng** [comment]
the warning still exists.

**Comment by sgpearse** [comment]
No longer exists.
