### ISSUE TITLE
OSX build broken when using USE_OMP

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2919]
To reproduce:
1) Configure Vapor's build to set USE_OMP to ON.  Use default settings otherwise.
2) Build Vapor with make and the following warning gets emitted repeatedly in the renderer library, following by a build error in our Qt third party library.

`clang: warning: argument unused during compilation: '-Xclang -fopenmp' [-Wunused-command-line-argument]`

**Comment by sgpearse** [comment]
Unfortunately, upgdating macports after the upgrade to OSX 11.6 does not seem to fix the problem.  Instructions followed are below.

https://trac.macports.org/wiki/Migration

**Comment by clyne** [comment]
The default c++ compiler for Mac is /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++, which does not support OpenMP. You need to change the C and C++ compilers:

CMAKE_CXX_COMPILER:STRING=/opt/local/bin/clang++
CMAKE_C_COMPILER:STRING=/opt/local/bin/clang

**Comment by sgpearse** [comment]
Thanks John, that was the missing piece.  main is currently building and running on our test machine.

I've modified [our documentation](/opt/local/bin/clang) to hopefully make this clearer.  

@shaomeng, there were instructions in this document for installing openMP with homebrew.  I removed those instructions because of the snafu we had with mixing up port and brew installations.
