### ISSUE TITLE
OpenSSL errors on CentOS

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2976]
Multiple CentOS users report OpenSSL warnings and errors when running Vapor 3.5.

[Report 1](https://vapor.discourse.group/t/vapor-crashes-when-reading-files-with-openssl-error/141/12)
[Report 2](https://vapor.discourse.group/t/ssl-error-isosurface-and-volume-rendering-never-finishes/154/2)
[Report 3](https://github.com/NCAR/VAPOR/issues/2961)

User @gyorgy-fekete reports the following:

> I found out that my Centos box (not HERA) had OpenSSL 1.0.2k
> I got 1.1.1c (not even the latest one) from openssl.org/source and built myself a new one.
> That seems to have fixed the "qt.network.ssl: QSslSocket: cannot resolve OPENSSL_init_ssl" ... issue! (wooHoo!)

We may want to consider doing a manual update of OpenSSL on our CI build systems when generating installers.

**Comment by gyorgy-fekete** [comment]
Oh, and one more thing.
I found out that if you have an activated conda environment, then PATH may also redirect to a different openssl.
```
(base) [gfekete@NESCC bin]$ which openssl
~/anaconda3/bin/openssl
(base) [gfekete@NESCC bin]$ conda deactivate
[gfekete@NESCC bin]$ which openssl
/usr/local/ssl/bin/openssl
```
Another potential "gotcha!" 

If you build one from sources, I recommend to not overwrite /usr/bin, but configure with somewhere other than a normal place. Here is how I did mine
```
--prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib
```
FYI, Cheers,
George

**Comment by sgpearse** [comment]
I've confirmed on Casper that Vapor's version checker hangs due to the OpenSSL incompatibility.

To reproduce:
1) On Casper, launch Edit->Preferences->Check For Updates
2) The check will hang, with the following output in the console

> qt.network.ssl: Incompatible version of OpenSSL
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed

**Comment by sgpearse** [comment]
This isn't something that we can fix by distributing an updated version of openssl.  Users will need to upgrade the library on their own system.
