### ISSUE TITLE
Slice renderer red region outside extents

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2977]
1. Follow the steps as in #2918 
2. Replace the volume renderer with a slice renderer for `vortmag`
3. Change the extents

<img width="363" alt="ss" src="https://user-images.githubusercontent.com/2772687/150861393-dfb165c6-8942-4adb-8eaf-d20d91178153.png">

**Comment by sgpearse** [comment]
@stasj - Is this on main, or on branch 2969v4 (the current slice PR branch, #2974)?

**Comment by StasJ** [comment]
> @StasJ - Is this on main, or on branch 2969v4 (the current slice PR branch, #2974)?

This was tested with the current release installers

**Comment by sgpearse** [comment]
Got it - thanks.

**Comment by sgpearse** [comment]
Fixed with PR #2974
