### ISSUE TITLE
2DRenderer has an incorrect height offset

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2988]
The 2DRenderer seems to be scaled too much in the following session file.

`/glade/p/cisl/vast/vapor/Bugs/2998/2998.vs3
`
Note the difference in height between the enabled 2DRenderer, and its corresponding WireFrame renderer.

![Screen Shot 2022-02-01 at 8 08 25 PM](https://user-images.githubusercontent.com/9522770/152087256-19792546-5743-4275-ad63-cbca48421b5c.png)

To reproduce:
1) On Casper, load the session file /glade/p/cisl/vast/vapor/Bugs/2998/2998.vs3

Alternatively, import the NetCDF-CF file below and play with 2d and 3d renderers.

`/glade/scratch/pearse/marshall/coen/212.nc`

**Comment by sgpearse** [comment]
@clyne I'm wondering if this is a 2D/3D grid regression.  Thoughts?

**Comment by clyne** [comment]
I don't think so. It looks like the Origin in the transform is not consistent between the wireframe renderer and the 2D data renderer. You can manually change them and get consistent results. If this workaround doesn't address your problem you may need to engage @StasJ

**Comment by sgpearse** [comment]
I see the mismatch in the Origin value for the two renderers.  Unfortunately matching them doesn't fix the problem.  

But I can at least translate the renderers to make them visually align, which gets me past my problem for now.
