### ISSUE TITLE
Image renderer incorrect with wrf-fire data

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2991]
To reproduce:
1) Import [this wrf file](https://drive.google.com/file/d/1zM0pYnrBTnbXQyFA8BydACQjVT1yZBik/view?usp=sharing)
2) Create an image renderer

Vapor will hang.

**Comment by sgpearse** [comment]
Note this WRF file is missing P and PB which are needed to define the vertical coordinate.  Vapor cannot read this file, but it should error out instead of hanging.

**Comment by clyne** [comment]
Works for me.

**Comment by StasJ** [comment]
Does not hang but gives incorrect result

<img width="794" alt="ss" src="https://user-images.githubusercontent.com/2772687/155489677-8164381d-4fc6-4ca0-a1dd-db07694500e8.png">

**Comment by clyne** [comment]
I changed the title to better reflect the current problem.

**Comment by sgpearse** [comment]
This is a boundary issue in WRF-Fire where 0 values are applied at the border.
