### ISSUE TITLE
MapperFunction gets corrupted upon undo/redo

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3]
The MapperFunction sometimes gets corrupted after issuing an Undo command.  This is a non-deterministic bug, and exists for both the TwoD and Barb renderers.  Corrupt MapperFunctions appear as in the screenshot below.  Data bounds seem correct, but the histogram and colorbar are not.  The console emits glErrors from the file ShaderProgram.cpp when this happens.

To reproduce:
1) Load any dataset, create a new TwoD or Barb renderer
2) Adjust an opacity control point, then undo the change.  The MapperFunction may get corrupted.  If not, restart the application and try again.

<img width="436" alt="screen shot 2017-07-06 at 2 11 39 pm" src="https://user-images.githubusercontent.com/9522770/27930773-135801fc-6255-11e7-9de9-19028e64ceec.png">

**Comment by clyne** [comment]
I'm re-assigning this to me. The MappingFrame does not follow the design pattern for users of ParamsBase classes
