### ISSUE TITLE
cf2vdc fails with various data sets

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3010]
A regression has been introduced in cf2vdc and it is now failing to convert numerous model outputs, including CAM and MOM4

To reproduce:
1. Create a vdc file:
`cfvdccreate /glade/p/cisl/vast/vapor/data/Source/CAM/AdamPhillips/F2000C5_new120_025/FV_768x1152.bilinear.F2000C5_new120_025.cam.h0.2004-01.nc FV.vdc`
2. Populate with cf2vdc:
`cf2vdc /glade/p/cisl/vast/vapor/data/Source/CAM/AdamPhillips/F2000C5_new120_025/FV_768x1152.bilinear.F2000C5_new120_025.cam.h0.2004-01.nc FV.vdc`

The process will terminate with:

Copying variable TROP_P
  Time step 0
Error accessing netCDF file "/Users/clyne/tmp/f2_data/data/mask_lon_lat/mask_lon_lat.nc", nc_open() : No such file or directory -- file (/Users/distiller/project/lib/wasp/NetCDFCpp.cpp), line(51)

**Comment by StasJ** [comment]
This may not be a bug but running the above generates a 24GB VDC dataset while the source dataset is only 11GB
