### ISSUE TITLE
Slice renderer misses data at top of domain with VDC

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3015]
The slice renderer (and contour renderer) fail to capture data in VDC files near the top of the domain.

To reproduce:
1. Load the VDC file /glade/p/cisl/vast/vapor/data/VDC/vapor-3.5.0/CAM/AdamPhillips/F2000C5_new120_025/F2000C5_new120_025-3.5.0.nc
2. Create a slice renderer and change the variable fidelity to high
3. Move the component of the slice origin to anything greater than ~900. Nothing is displayed (there are several layers over 900, and the highest is 992).

Note that the volume render is able to capture this data as can be verified by again setting the fidelity to high, and moving the minimum Z extent to a value over 900.

N.B. the correct path to use should be glade/p/cisl/vast/vapor/data/VDC/vapor-3.6.0, not glade/p/cisl/vast/vapor/data/VDC/vapor-3.5.0

The attached image shows a volume rendering with the min Z extent 950, and max 992

![FV_dvr](https://user-images.githubusercontent.com/6777736/153725532-a2ebae5b-b9aa-49ec-b026-735ac5ed5936.png)

**Comment by sgpearse** [comment]
@clyne #3027 is reporting that source builds of Vapor throw an error when loading this dataset.  I'm trying to back out recent commits in case this is a recent regression.

**Comment by sgpearse** [comment]
@clyne - I can load the data when I manually create a VDC.  The dataset below still throws the error listed in #3027.

`/glade/p/cisl/vast/vapor/data/VDC/vapor-3.5.0/CAM/AdamPhillips/F2000C5_new120_025/F2000C5_new120_025-3.5.0.nc`

**Comment by clyne** [comment]
My bad. The current 3.5 VDC data set on glade is broken. The fix for it is in main and the next time @stasj regenerates our VDC data this problem will be fixed. However, we've bumped the version to 3.6, so the correct data will be found in /glade/p/cisl/vast/vapor/data/VDC/vapor-3.6.0. I will update the issue to reflect that.

**Comment by clyne** [comment]
We will revisit after #2029 is fixed (and new bug with placement of bounding box and scaled data).

**Comment by clyne** [comment]
With the fix for #3032 IMHO this usability issues is not as severe as it was before; it becomes somewhat obvious to me that the plane as moved outside of the red region box (of course it is helpful if you know what the red region box represents). However, the green plane bounding region is only shown for the contour renderer, not the slice renderer. @sgpearse is there a reason the plane bounding was omitted for the slice renderer?

**Comment by sgpearse** [comment]
> @sgpearse is there a reason the plane bounding was omitted for the slice renderer?

Yes - It wasn't a requirement when the Slice Renderer was introduced.  The degraded slice seemed good enough at the time.  It should be a 1 liner to add right now.

**Comment by clyne** [comment]
cool. I'd say let's add it for consistency sake if nothing else.
