### ISSUE TITLE
vdccreate should accept formatted time strings

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3022]
vdccreate allows the user to specify time coordinates via an ASCII text file with the '-tcoords' command line option. The format of the time coordinate file should be expanded to allow formatted time strings commonly used in earth sciences, and understood by the UDUNITS library (and supported by the NetCDF CF conventions). For example, UDUNITS supports specifications of the form:

<unit > since YYYY-MM-DD hh:mm:ss

**Comment by sgpearse** [comment]
I tried to use "km" for the spatial units but they register as meters.  The time coordinate did work though.  Commands and files are below.

`vdccreate -dimension 256x256x256 -ncvars3d test -xcoords ~/xcoords.txt -ycoords ~/ycoords.txt -zcoords ~/zcoords.txt -tcoords ~/tcoords.txt test.vdc`

`raw2vdc -type double -varname test test.vdc ~/Data/bovFiles/256d.bin`

These should range from 0 to 255,000:
![Screen Shot 2022-09-22 at 8 28 30 AM](https://user-images.githubusercontent.com/9522770/191774420-a9e738e2-6778-40a5-ad78-478d6b9ed5c7.png)

[256d.bin.zip](https://github.com/NCAR/VAPOR/files/9626768/256d.bin.zip)
[tcoords.txt](https://github.com/NCAR/VAPOR/files/9626758/tcoords.txt)
[zcoords.txt](https://github.com/NCAR/VAPOR/files/9626759/zcoords.txt)
[ycoords.txt](https://github.com/NCAR/VAPOR/files/9626760/ycoords.txt)
[xcoords.txt](https://github.com/NCAR/VAPOR/files/9626761/xcoords.txt)
