### ISSUE TITLE
Transfer renderers across datasets

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3057]
Use case:
1) Create a session with a set of renderers on computer 1
2) Save the session and copy it to computer 2, which has a different filesystem
3) Try to open the session on computer 2, and Vapor will fail to load the data

It would be useful to create a session on my local machine with a single data file.  Once I've configured my renderers, that same session could reference large datasets on Casper.  This would also help collaborating with scientists since we could share sessions across different filesystems.

**Comment by clyne** [comment]
I believe there are other similar issues that are open.

We really need to identify the common use cases with mixing different data sets with a session file and make sure VAPOR does the right thing when the data sets are the same, or very different.

**Comment by clyne** [comment]
@sgpearse we're not sure what to do here. Can you weigh in on whether to make this a 3.7 milestone?

**Comment by sgpearse** [comment]
@sgpearse will revisit

**Comment by sgpearse** [comment]
Vapor asks to open the data after failing to load, and will open that data according to the referenced session, so this is moot.
