### ISSUE TITLE
Advection diagnostics printed in DEBUG build

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3068]
@shaomeng - The Flow Renderer currently prints a lot of diagnostic information when building in DEBUG mode.  This makes it hard to debug other parts of the code.  Can we use a macro in Advection.cpp and FlowRenderer.cpp for these diagnostics instead of NDEBUG, which is set by CMake?

**Comment by shaomeng** [comment]
Hey @sgpearse , would you see if  #3071 addresses your concern?

**Comment by sgpearse** [comment]
@shaomeng That fixes it.  Thanks!
