### ISSUE TITLE
Upgrade our 3rd party libs

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3072]
@sgpearse, @shaomeng, @StasJ, is this something we should do before the next release?

**Comment by sgpearse** [comment]
Probably if QT fixes its OSX slider bug, or if Ospray sees a new release?

**Comment by shaomeng** [comment]
I'd vote for a 3rd party upgrade given that the current 3rd party libs are almost 3 years old. (Since Aug 2019)

**Comment by clyne** [comment]
Assigning this since we seem to be doing it.

**Comment by clyne** [comment]
Fixes #2816

**Comment by clyne** [comment]
closed by #3110
