### ISSUE TITLE
Flow renderer crashes on NetCDF data

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3087]
To reproduce:
1) Import the three NetCDF files in /glade/p/cisl/vast/vapor/Bugs/3087
2) Create  flow renderer and select Bx as the X field variable
3) Enable the renderer, vapor will crash

**Comment by shaomeng** [comment]
After examination, the root of this crash is a `nan` produced by the following code:
https://github.com/NCAR/VAPOR/blob/2d025c095f6aa5872575e00f20b275c618e72a06/lib/vdc/RegularGrid.cpp#L85-L86

I think maybe @clyne can take a look at why a `nan` was produced?

**Comment by clyne** [comment]
@shaomeng re-assigning this back to you. The input to ClampCoord(), `coords`, contains NaNs that are generated somewhere in VaporField.cpp.
