### ISSUE TITLE
Open Session: Warning dialog when loading session for first time

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#309]
When a user opens Vapor then tries to open a session, they're prompted with a message that their session will be lost.  We should probably omit this if we're in Vapor's initial state.

To reproduce:
1) Spin up Vapor
2) File -> Open Session
3) Dialog will appear warning about losing your settings

**Comment by StasJ** [comment]
You may have accidentally touched the visualizer window first
