### ISSUE TITLE
Particle Renderer: Crash on 1,000,000 particles

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3102]
To reproduce:
1) Download and run [1Mparticles.py.zip](https://github.com/NCAR/VAPOR/files/8642097/1Mparticles.py.zip), a modified version of VAPOR/share/examples/generateExampleDCP.py.  This creates a single time step file with 1M particles.
2) Import the DCP file, then create and enable a particle renderer (stride=1).  Vapor will crash.  Stride=2 will not crash.

The crash occurs in LegacyGL.cpp:86.
`    glDrawArrays(_mode, 0, _vertices.size());`

While the glyph code in #3093 does not use LegacyGL, it also crashes with a call to the same function.

This does not appear to be a memory issue.  GPU memory footprint of the current particle renderer (no glyphs) at different strides:

![Screen Shot 2022-05-06 at 10 10 33 AM](https://user-images.githubusercontent.com/9522770/167171189-99c91c0b-1986-4a04-8e14-62811a587262.png)

**Comment by sgpearse** [comment]
@shaomeng will test on cisl-vapor to see if this is widespread.  We will mark as medium pending Sam's findings.

**Comment by shaomeng** [comment]
> @shaomeng will test on cisl-vapor to see if this is widespread. We will mark as medium pending Sam's findings.

I tested it on cisl-vapor and there's no crash. I guess we'll live with an occasional crash?

**Comment by NihanthCW** [comment]
@StasJ I assume the particle renderer update must have fixed this.?

**Comment by StasJ** [comment]
Yes, I confirmed this is fixed.
