### ISSUE TITLE
Flow: Random Seeds with Bias: need bigger number

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3115]
From user kgalsgaard in [this post](https://vapor.discourse.group/t/flow-tracer-behavior-color-coding-random-setup/192)

" When selecting a seed distribution for the stating points, using the random setup with bias, the number of starting points are limited to 500 – for the project I am working on this is on the low side – especially when the gridded setup allows up to 2500 starting points."

**Comment by sgpearse** [comment]
At the least, we should allow the user to define the maximum.

As a convenience, it would be nice to have a cancellation button.  But will multithreaded OpenMP allow for interruption?
