### ISSUE TITLE
Flow: Random Seeds with Bias: finer controls

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3116]
From user [kgalsgaard](https://vapor.discourse.group/u/kgalsgaard) in [this post](https://vapor.discourse.group/t/flow-tracer-behavior-color-coding-random-setup/192)

"Also for the bias value, it only accepts integer values. For my case the step between 0 and 1 is to large and already there focuses the starting points to much on the very strong field. Could this slider be turned into a float?"

**Comment by clyne** [comment]
@StasJ can you explain why this was reopened?

**Comment by StasJ** [comment]
> @StasJ can you explain why this was reopened?

![ss](https://user-images.githubusercontent.com/2772687/192086194-7aa54bf5-009a-40c2-8267-42e90c10c30e.gif)

**Comment by shaomeng** [comment]
I'd consider this as "fixed" because the step size is now 1/100 of the old step size. This particular user can try values between 0 to 100 which will give him step sizes between 0 and 1 in the old software.

**Comment by StasJ** [comment]
Changing the internal interpretation of this value will break existing session files. We may also find ourselves in the same situation again when someone has a different dataset with at a 1/100 scale.

**Comment by shaomeng** [comment]
There have been several versions of VAPOR being released since 2022, and there doesn't seem to have an issue since, so I'd close this issue, unless @StasJ thinks otherwise.
