### ISSUE TITLE
Conda installation documentation needed

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3119]
A comprehensive conda install guide is needed, similar to [this](https://geocat-comp.readthedocs.io/en/latest/installation.html#installing-geocat-comp-via-conda-in-a-new-environment). 

@stasj is there a reason a wrapper, `install_vapor.sh`, is needed to perform the conda install?

**Comment by StasJ** [comment]
> @StasJ is there a reason a wrapper, install_vapor.sh, is needed to perform the conda install?

Since this is an in-review beta version of vapor, it has not been uploaded to Conda's servers. So the installer is needed because it contains the vapor api.

**Comment by sgpearse** [comment]
Will address once PR is merged.

**Comment by sgpearse** [comment]
Fixed a long time ago.
