### ISSUE TITLE
VAPOR Python examples should reference canonical test data sets distributed with VAPOR

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3122]
The current examples that use data from files (e.g. dataset_example.py and katrina_example.py) don't use data sets that are available to users from our web site. These examples should be modified so users can easily run them (i.e. they should make use of our canonical user example data).

Even better, we should pilfer the GeoCAT's `geocat.datafiles` module, which uses `pooch` to automatically fetch and cache example data sets. I.e. users don't have to perform a manual step of downloading data files and then edit the example script to point to them.

**Comment by StasJ** [comment]
All of the examples except for the Katrina one use a dataset that is generated by the python API so it is available to users. I believe we used to distribute Katrina? In any event, the Katrina example was included because it has a more interesting volume rendering however the generated dataset should suffice for documentation purposes.

**Comment by clyne** [comment]
The `katrina_example.py` example script may use our Katrina data set, but it doesn't do so in a way that facilitates a user, not deeply familiar with our repository, being able to run the script. E.g. the script simply references:

`'/Users/stasj/data/Katrina/min_wrfout_d02_2005-08-29_01'`

but makes no mention that this data set can be download from the VAPOR  site, and where it can be found. We can (should) make it easier for the user to run the example.

**Comment by StasJ** [comment]
The example no longer depends on the Katrina dataset and uses the included example dataset.
