### ISSUE TITLE
VAPOR Python examples in Jupyter Notebook gallery form

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3123]
All (most?) of the example scripts should be converted to Jupyter Notebooks, rendered as a documentation page from our website, and available as downloads in both Python and Jupyter Notebook form as is done [here](https://geocat-examples.readthedocs.io/en/latest/).

**Comment by sgpearse** [comment]
@clyne - I'm hitting a roadblock here.  `sphinx-gallery` is currently not rendering images for the python api scripts, and  I believe that this is because of the use of openGL contexts.

**Comment by sgpearse** [comment]
Fixed with [VaporDocumentationWebsite PR #4](https://github.com/NCAR/VaporDocumentationWebsite/pull/4)
