### ISSUE TITLE
VAPOR doesn't properly handle dimensions of length one. 

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3134]
To reproduce:
1) Build on main and cd into /glade/p/cisl/vast/vapor/Bugs/3134
2) Issue the following VDC conversion on Casper

`cfvdccreate snapshots_00030005.nc nw2_0.25deg_N15_baseline_hmix5_interpolated.nc quarter.vdc`
`cf2vdc -numts 1 snapshots_00030005.nc nw2_0.25deg_N15_baseline_hmix5_interpolated.nc quarter.vdc`

3) Open the file in Vapor and the following error will be issued.  Vapor will crash after interacting with the visualizer.

`Failed to get camera parameters`

Note: This error does not occur when importing the aforementioned files as NetCDF-CF.

**Comment by clyne** [comment]
This error is occurring because the "snapshots" data set's z dimension length is 15, which, after undergoing a VDC wavelet transform, is coarsened to 1. VAPOR is not handling the degenerate case.
