### ISSUE TITLE
User quick start guide for Python API

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3137]
We need a quick start guide to walk people though getting the Python API installed, and running simple use cases

**Comment by sgpearse** [comment]
This ticket spans two different issues that I'm splitting up, so I've changed the title of this from
> Quick start guide for Python API

to

> **User** quick start guide for Python API

This issue now regards our general user base, the **Users**.

However we have developer [documentation](https://docs.google.com/document/d/1RvbnJ_LbWvlUZzgjeutLQKwJV_M0blEHFSxsgSB7wRQ/edit#heading=h.jdi94x911txd) in the works that shows how to install the API on a local channel.  This needs to be added to the contributor's guide along with instructions for building the API's .tar.bz2 package through enabling CONDA_BUILD in CMake.  Issue #3148 reflects this requirement.

**Comment by NihanthCW** [comment]
Building python API on Mac: cppyy issue added for reference. 
See issue below
https://github.com/NCAR/VAPOR/issues/3114#issuecomment-1191779583

**Comment by NihanthCW** [comment]
Addressed through [pythia cookbook](https://projectpythia.org/vapor-python-cookbook/README.html)
