### ISSUE TITLE
More extensive documentation of Params needed

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3138]
The Python API generates documentation for all functions automatically from the Params classes. While it is awesome to be able to reuse documentation for  two purposes (GUI and Python API), unfortunately many of the Params class methods are not adequately documented. For example, the documentation for FlowParams. SetRenderGlyphType, which takes an int argument, simply says:

`When rendering samples, determines whether samples are rendered as circles or arrows.`

This is fine in the context of the GUI because the integer options are mapped to strings by Qt, but this documentation provides no help at all for someone trying to use the Python API. A more egregious example is FlowParams. SetSeedGenMode(). There is no documentation for this parameter at all, and thus little hope for a Python user to figure out what valid inputs might be, or how this function changes the behavior of a flow rendering. 

N.B. we were able to get a way with being lax about much of the Parameter documentation for the GUI because the results of manipulating a slider, thumb wheel, etc. were often obvious. This is not the case with a programmatic interface.

**Comment by sgpearse** [comment]
This needs to be split among developers and their contributed code.  Not necessarily needed for 3.7's release.

Will revisit after python_api gets merged.

**Comment by sgpearse** [comment]
@clyne or @stasj, after getting the API running with [these steps](https://docs.google.com/document/d/1RvbnJ_LbWvlUZzgjeutLQKwJV_M0blEHFSxsgSB7wRQ/edit#heading=h.jdi94x911txd), where can I find the documentation that's referencing our Doxygen comments?

**Comment by StasJ** [comment]
The documentation exists as python docstrings.

**Comment by sgpearse** [comment]
@stasj but where do I find them?  How do I validate that the newly documented params are being translated to docstrings?

**Comment by StasJ** [comment]
You call help() on a python object to see its documentation.
