### ISSUE TITLE
Windows crash on UGRID data

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3139]
To reproduce:
1) On windows, load our example [UGRID dataset](https://vapor.readthedocs.io/en/readthedocs/downloads/downloads.html#sample-data).

On my machine, Vapor will crash.  User mbotto has reported the following error:

```
Failure to open data set of type "ugrid"
Failed to initialize data importer
Failed to initialize netCDF data collection for reading
NetCDFSimple::Initialize(---/smallGrid.nc)
nc_get_att_long(327680, 1, _FillValue) : NetCDF: Numeric conversion not representable
------------------
Vapor 3.6.0.<debug>
OS: Windows 6.2 (9200)
```

**Comment by clyne** [comment]
@sgpearse can you try loading only the grid specification file, smallGrid.nc, and report what happens? Also, have  you tried this with the updated netcdf libraries in #3110?
