### ISSUE TITLE
Ensure vapor_python package is compatible with commonly used scientific python ecosystem packages

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3141]
Currently our Conda third party dependencies are locked to the same versions (or at least very close) to our manually built libraries. We may need to relax these requirements to improve compatibility with other packages.

We should strive for making vapor_python work with the latest stable versions of xarray, pandas, matplotlib, and probably a few other packages that are commonly used for geoscience analysis and vis.

**Comment by sgpearse** [comment]
@sgpearse 2 years can be a fuzzy time window for libraries, and major releases.  Check out meta.yaml for current dependency list.
