### ISSUE TITLE
Create a conda-forge recipe for vapor_python

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3143]
Most scientific python packages are installed with conda from the [conda-forge](https://conda-forge.org/) channel (or an alternate channel). This allows users to install packages by simply executing:

`conda install <package_name>
`
Additionally, there is a lot of infrastructure around the Jupyter + GitHub environment for automatically installing package dependencies via a conda channel. For example, Jupyter Books can be easily rendered with GitHub workflows if package dependencies can be satisfied with a conda installation from a web accessible channel. 

We should create a "recipe" for building and distributing vapor_python on conda forge (preferably) or some other web-accessible channel.

**Comment by StasJ** [comment]
Vapor can be installed with `conda create -n vapor_env -c conda-forge -c ncar-vapor vapor`
