### ISSUE TITLE
Statistics: Statistic values lost upon parameter change

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#315]
Previously, we would retain the calculations in the Statistics tool until 'Update Statistics' was pressed, or 'Auto-update' was checked.  The numbers would turn red to indicate a change in parameters.  We are currently changing all values to ?? upon a parameter change

To reproduce:
1) Spin up Vapor, load KatrinaMaster.nc
2) Tools -> Statistics
3) Add variable T, then press 'Update Statistics'
4) Change any parameter, and the statistic values will be lost

**Comment by shaomeng** [comment]
Hmm, I intentionally designed it to only display valid statistics. E.g., changing the spatial extents make every value invalid.

That said, operations that don't affect existing statistics don't lose these existing statistics. E.g., add a new variable or new calculation.

**Comment by shaomeng** [comment]
As I explained in the previous comment, I intentionally made it so, and eliminated a "red text" representation, which isn't well defined. 

For my brain, something in red grabs my attention but has no indication that this red object is *invalid*. While if something has question marks on, it needs to be resolved. 

What do you think? @sgpearse @clyne @StasJ
