### ISSUE TITLE
How does the build system find Python

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3154]
@stasj how does the build system (cmake) determine which Python environment to use? Specifically, I'm running cmake from an active 3.9 conda environment and cmake is reporting:

` Python Found
 Python_VERSION = '2.7.16'
 Python_NumPy_VERSION = '1.8.0rc1'
 Python_LIBRARIES =
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dyl
 ib' OK
 Python_INCLUDE_DIRS =
 '/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7'
 OK
 Python_SITELIB = '/Library/Python/2.7/site-packages' OK
 Python_NumPy_INCLUDE_DIRS =
 '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/nu
 mpy/core/include' OK
 Python Found: '2.7.16'
 (/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dyl
 ib)
 CMake Warning at apps/pythonapi/examples/CMakeLists.txt:49 (message):
   jupytext not found

 CMake Warning at apps/pythonapi/examples/CMakeLists.txt:50 (message):
   Skipping generation of jupyter notebooks`

So it looks like it is finding Mac's bundled version of Python.

**Comment by StasJ** [comment]
If you run the normal build of vapor, it will use the bundled python. If you enable the BUILD_PYTHON flag, it leaves it up to CMake's built in python finding routine.

**Comment by clyne** [comment]
Is there a way to tell cmake what to use? In particular, I'd like it to use my current conda environment. Cmake doesn't seem to be picking that up from my search path.Thanks.

**Comment by StasJ** [comment]
It works for me with my Conda environment. You could try setting `Python_ROOT_DIR` (https://cmake.org/cmake/help/latest/module/FindPython.html#hints) but its possible something is not configured in the way Cmake expects it.

**Comment by clyne** [comment]
@stasj according to this [thread](https://gitlab.kitware.com/cmake/cmake/-/issues/21322) cmake version 3.17 or greater is needed to support anaconda builds. I set 

`cmake_minimum_required (VERSION 3.17)
`

And now the build is using the correct Python installation. Can we change the cmake version minimum to 3.17?

Next question: How is the package installed after it is built?

**Comment by StasJ** [comment]
> @StasJ according to this [thread](https://gitlab.kitware.com/cmake/cmake/-/issues/21322) cmake version 3.17 or greater is needed to support anaconda builds. I set
> 
> `cmake_minimum_required (VERSION 3.17) `
> 
> And now the build is using the correct Python installation. Can we change the cmake version minimum to 3.17?

I opened a PR to that effect.

> Next question: How is the package installed after it is built?

Building with Conda-build generates a tar.bz2 file which can be installed with Conda. If the package is built manually it does not generate an installer. It will run from source however you could also install it manually.

**Comment by clyne** [comment]
> Building with Conda-build generates a tar.bz2 file which can be installed with Conda. If the package is built manually it does not generate an installer. It will run from source however you could also install it manually

Hmm. I'm not finding a tar.bz2 file after doing 'make all'

**Comment by sgpearse** [comment]
@clyne This will be more officially documented soon, but you can find notes in [this doc](https://docs.google.com/document/d/11Tim67ISrWPebs2xRhxeH2DtjDOM2UOE_rQAnd1O6aE/edit).  If you've built in VAPOR/build before, you'll need to delete VAPOR/build/CMakeCache.txt.

```
cd VAPOR/conda
conda install conda-build
conda build .
```

The tar.bz2 file should be in ~/anaconda3/conda-bld/linux-64/

**Comment by clyne** [comment]
@sgpearse or @stasj, are their two ways to build vapor_python, one with cmake, and one with conda? I was attempting to build with cmake. @sgpearse instructions suggest building with conda. The latter seems to take a really long time. What is the difference in the end result?

**Comment by sgpearse** [comment]
Yes, it does take a long time.  But I'm not aware of a way to do it with cmake.

**Comment by StasJ** [comment]
> @sgpearse or @StasJ, are their two ways to build vapor_python, one with cmake, and one with conda? I was attempting to build with cmake. @sgpearse instructions suggest building with conda. The latter seems to take a really long time. What is the difference in the end result?

In order to build a Conda package, you need to use Conda-build. Conda-build works on top of our CMake build. It does indeed take a really long time. Also you need to re-run the whole thing for even a minor change which makes it very convenient to debug.

**Comment by clyne** [comment]
Back to the cmake build. I'm now able to build the module from cmake, and I can import it by first setting the PYTHONPATH environment variable to build/python. e.g.

```
PYTHONPATH=/Users/clyne/src/vapor/build/python
export PYTHONPATH
```
However, the first time that I tried to run the `annotation_example.py` example I was told cppyy could not be found. After installing it with `conda install cppyy` I now get:

Python 3.8.6 (/Users/clyne/tmp/miniconda/envs/xarray)
OpenGL 4.1 INTEL-16.5.2
Traceback (most recent call last):
  File "annotation_example.py", line 9, in <module>
    from vapor import session, renderer, dataset, camera, utils
  File "/Users/clyne/src/vapor/build/python/vapor/session.py", line 2, in <module>
    from .renderer import Renderer
  File "/Users/clyne/src/vapor/build/python/vapor/renderer.py", line 2, in <module>
    from .params import *
  File "/Users/clyne/src/vapor/build/python/vapor/params.py", line 2, in <module>
    from .smartwrapper import *
  File "/Users/clyne/src/vapor/build/python/vapor/smartwrapper.py", line 3, in <module>
    from . import cppyyDoxygenWrapper
  File "/Users/clyne/src/vapor/build/python/vapor/cppyyDoxygenWrapper.py", line 6, in <module>
    class CPPYYDoxygenWrapperMeta(type):
  File "/Users/clyne/src/vapor/build/python/vapor/cppyyDoxygenWrapper.py", line 10, in CPPYYDoxygenWrapperMeta
    @functools.cache
AttributeError: module 'functools' has no attribute 'cache'


Thoughts on how to proceed, @StasJ

**Comment by StasJ** [comment]
> Back to the cmake build. I'm now able to build the module from cmake, and I can import it by first setting the PYTHONPATH environment variable to build/python. e.g.
> 
> ```
> PYTHONPATH=/Users/clyne/src/vapor/build/python
> export PYTHONPATH
> ```
> 
> However, the first time that I tried to run the `annotation_example.py` example I was told cppyy could not be found. After installing it with `conda install cppyy` I now get:
> 
> Python 3.8.6 (/Users/clyne/tmp/miniconda/envs/xarray) OpenGL 4.1 INTEL-16.5.2 Traceback (most recent call last): File "annotation_example.py", line 9, in from vapor import session, renderer, dataset, camera, utils File "/Users/clyne/src/vapor/build/python/vapor/session.py", line 2, in from .renderer import Renderer File "/Users/clyne/src/vapor/build/python/vapor/renderer.py", line 2, in from .params import * File "/Users/clyne/src/vapor/build/python/vapor/params.py", line 2, in from .smartwrapper import * File "/Users/clyne/src/vapor/build/python/vapor/smartwrapper.py", line 3, in from . import cppyyDoxygenWrapper File "/Users/clyne/src/vapor/build/python/vapor/cppyyDoxygenWrapper.py", line 6, in class CPPYYDoxygenWrapperMeta(type): File "/Users/clyne/src/vapor/build/python/vapor/cppyyDoxygenWrapper.py", line 10, in CPPYYDoxygenWrapperMeta @functools.cache AttributeError: module 'functools' has no attribute 'cache'
> 
> Thoughts on how to proceed, @StasJ

Vapor’s python library requires python 3.9. functools.cache is part of the standard library

**Comment by clyne** [comment]
Thanks. This is working now. Something else to include in our "building from source" documentation.

cc: @sgpearse

**Comment by clyne** [comment]
@stasj after building successfully with cmake I'm able to import vapor but I get a warning:

Vapor 3.6.1
Python 3.9.13 (/Users/clyne/tmp/miniconda/envs/xarray)
OpenGL 4.1 INTEL-16.5.2
WARNING DOxygen not found

Any idea how to resolve the DOxygen problem? I'm assuming that this is necessary to see the new documentation that @sgpearse has added? 

(xarray) bash-5.1$ conda list | grep doxygen
doxygen                   1.9.3                h51faa4e_1    conda-forge

**Comment by StasJ** [comment]
Did you build the documentation with `make doc`?

**Comment by clyne** [comment]
That did it. Thanks. There are number of things in this thread that will need to make their way into the "building from source" documentation.

**Comment by NihanthCW** [comment]
@sgpearse @ifranda @StasJ I believe the documentation is [updated](https://ncar.github.io/VaporDocumentationWebsite/contributingToVapor/codeContributions.html) now right?

**Comment by sgpearse** [comment]
@NihanthCW Not the Doxygen part.  @stasj, does running `make doc` from VAPOR\build need to be added after step 3 in our procedure for [Building the conda image](https://ncar.github.io/VaporDocumentationWebsite/contributingToVapor/codeContributions.html#building-the-conda-image)?

**Comment by StasJ** [comment]
> @NihanthCW Not the Doxygen part. @StasJ, does running `make doc` from VAPOR\build need to be added after step 3 in our procedure for [Building the conda image](https://ncar.github.io/VaporDocumentationWebsite/contributingToVapor/codeContributions.html#building-the-conda-image)?

No, this is handled in step 4.

**Comment by sgpearse** [comment]
Ok, I'll close this one then.
