### ISSUE TITLE
Notifier seems to be broken

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3156]
I've created a new notice ([__tutorial-notice.json](https://github.com/NCAR/VAPOR-Website/blob/master/notices/__tutorial-notice.json)) that does not seem to register when vapor starts up.  For a sanity check, I've also reinstated the old notice ([__test.json](https://github.com/NCAR/VAPOR-Website/blob/master/notices/__test.json)) that we used for the user survey last year.  [This JSON validator](https://jsonlint.com/) indicates that the files are valid.  The dates have been changed in both notice files, and they can be found at the link below:

https://github.com/NCAR/VAPOR-Website/tree/master/notices

PS - The __example-notice.json has a line that states the following:

`    "_comment-1": "This is an example notice. It will be ingored by Vapor",`

It's not clear why this notice is ignored.  Is there syntax that vapor ignores, is it being ignored because it's outside of the specified date range, or something else?

**Comment by StasJ** [comment]
The notice board stopped working because you renamed the repo it was querying. We can either rename the repo back to the original name, or create a new repo to replace the old one. Vapor can be updated to refer to the renamed repo, however, this change would not reach users until the next release.

**Comment by sgpearse** [comment]
Got it.  Renamed the repo to VAPOR-SupportPage.
