### ISSUE TITLE
OSX build broken on CircleCI

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3158]
Weekly install is no longer being published due to failure on OSX.

https://app.circleci.com/pipelines/github/NCAR/VAPOR/5813/workflows/ae15eff8-8f45-4ff8-84c9-cb1698c157af/jobs/13821

**Comment by clyne** [comment]
@sgpearse won't we need to have this fixed to release? Shouldn't it thus be a 3.7 milestone?

**Comment by sgpearse** [comment]
Yep.  I'll go ahead and add it.  Working on it now.

**Comment by clyne** [comment]
I think this is a Apple clang vs real clang issue and is related to #3179, which is assigned to @StasJ
