### ISSUE TITLE
Height mapped variables on 2D grids

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3162]
As discussed in #3155, Vapor applies height variables to 2 dimensional renderers as an offset from the bottom of the data domain.  

I believe the behavior we want is for 2D height mapped grid points to be rendered at the coordinate of the height variable.  IE - If a dataset has a minimum Z extent of 1500m, the Z coordinate of the height-mapped mesh should be HGT, not be HGT+1500.

If there's a use case for using HGT+Zmin, allowing the user to switch between the two modes would be helpful.

**Comment by clyne** [comment]
@sgpearse based on a limited examination of different model outputs, you are probably correct: the more typical use case is to have a height field specifying elevation (or depth), not a displacement.
