### ISSUE TITLE
Missing values that are NaNs are not supported

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3167]
It is possible to use NaNs as a missing value. Hence, Grid::GetMissingValue() may return a NaN. Much of the code in VAPOR that handles missing values checks for the existence of missing values in the data with something like:

`if (g->GetMissingValue() == g->GetValue())`

However, in C/C++ comparing a NaN to a NaN with an equality operator always results in False. Thus special case handling should be added throughout the code base to deal with NaN missing values. E.g.

`if ((g->GetMissingValue() == g->GetValue())) || (std::isnan(g->GetMissingValue())  && std::isnan(g->GetValue()))`

See the test data set used in #3087

**Comment by shaomeng** [comment]
Might be simpler to just introduce a new public method to a grid class: 
```C++
bool Grid::IsMissing(float val);
bool Grid::IsMissing(double val);
```
