### ISSUE TITLE
Python broken on Linux installers

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3177]
To reproduce:
1) Build and install an installer on main on Ubuntu or CentOS
2) Launch the installed vaporpychecker to get the following error:

Note: This can be reproduced with our OSX 3.6.0 installer as well.

> (vapor) [vapor2@localhost build]$ bin/vaporpychecker
> Redirecting Python IO
> System search path:
> Location of site module: PyRun_SimpleString() : VAPOR_PY: Traceback (most recent call last):
>   File "<string>", line 6, in <module>
> NameError: name 'os' is not defined

**Comment by clyne** [comment]
The introduction of the Python API (which we typically refer to as vapor_python) leads to some confusion when discussing  VAPOR GUI's internal Python calculation engine. I believe this issue refers to problems with the latter, and is independent of vapor_python, correct? @stas does the success or failure of `vaporpychecker` tell us anything about vapor_python?

@sgpearse vaporpychecker fails, but have you tried to run the internal calculation engine?

**Comment by StasJ** [comment]
[casper06 bin]$./vaporpychecker 
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002b31d8aebc80 (most recent call first):
Aborted
