### ISSUE TITLE
Windows build currently broken

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3178]
PR #3152 takes some steps towards building on windows with BUILD_PYTHON=ON, but when it's off our build still fails due to ~osgl~ glad linker problems.

**Comment by StasJ** [comment]
@sgpearse The windows build fails with issues unrelated to OSGL even in the branch from #3152. Could you please point me to the branch where windows is failing due to OSGL linker problems so I don't have to fix the other issues a second time?

**Comment by sgpearse** [comment]
Right - I know what you mean.  The branch I've been working on is _[winPythonAPI2](https://github.com/NCAR/VAPOR/tree/winPythonAPI2)_, which is referenced in PR #3152.  Not sure if all of the changes in that PR are valid though.
