### ISSUE TITLE
MPAS/ThomasSchwitalla TwoDData Incorrect

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#3193]
Var: t2m

![MPAS-ThomasSchwitalla-TwoDData](https://user-images.githubusercontent.com/2772687/186506876-83ab4e5a-5fe3-436a-88b8-13037855f69e.png)

**Comment by clyne** [comment]
Works for me. Closing. Note, this data set is composed of three files:

QVAPOR_MPAS.nc - contains a 3D field (QVAPOR)
ter_3km.nc - contains a 2D field (t2m)
x1.65536002.grid.nc  - the static grid file

Only the grid file (x1.65536002.grid.nc) and ter_3km.nc need to be loaded to render the 2D field, "t2m".
