### ISSUE TITLE
MOM4-JinHeeYuk-ocean_salt IsoSurface and volume blank

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#3205]
![MOM4-JinHeeYuk-ocean_salt-IsoSurface](https://user-images.githubusercontent.com/2772687/187134290-b00add03-fdf2-4b24-9a69-edf06efffc22.png)
[MOM4-JinHeeYuk-ocean_salt-IsoSurface.png.log](https://github.com/NCAR/VAPOR/files/9441951/MOM4-JinHeeYuk-ocean_salt-IsoSurface.png.log)
[MOM4-JinHeeYuk-ocean_salt-IsoSurface.png.vs3.zip](https://github.com/NCAR/VAPOR/files/9441952/MOM4-JinHeeYuk-ocean_salt-IsoSurface.png.vs3.zip)
![MOM4-JinHeeYuk-ocean_salt-Volume](https://user-images.githubusercontent.com/2772687/187134293-82f5a0b0-063c-41a0-9b02-fc7fcfbc8d31.png)
[MOM4-JinHeeYuk-ocean_salt-Volume.png.log](https://github.com/NCAR/VAPOR/files/9441953/MOM4-JinHeeYuk-ocean_salt-Volume.png.log)
[MOM4-JinHeeYuk-ocean_salt-Volume.png.vs3.zip](https://github.com/NCAR/VAPOR/files/9441954/MOM4-JinHeeYuk-ocean_salt-Volume.png.vs3.zip)

**Comment by clyne** [comment]
I'm getting an OpenGL error on my Mac:

```
Error performing paint event
OpenGL error : Error #1281
```
Assigning to @StasJ 

Note, if I try to use the Curvilinear volume renderer I get:

```
GPU hang occurred, CoreAnalytics returned false
GPU hang occurred, CoreAnalytics returned false
Abort
```
