### ISSUE TITLE
flow_example.ipynb generates numerous blank images

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3210]
The flow_example.ipynb  notebook produces a number of blank images where nothing is rendered. Presumably this is not the intended behavior. In particular, cells 8, 9, and 11 generate blank images.

**Comment by shaomeng** [comment]
Could be related to #3215.

**Comment by sgpearse** [comment]
@stasj will take another look now that the flow bug has been fixed.

**Comment by StasJ** [comment]
This has been fixed by the flow bug fix.
