### ISSUE TITLE
Particle Lighting seems weird.

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3214]
The particle lighting seems weird, if not wrong. The test data is this one (/glade/p/cisl/vast/vapor/data/Source/DCP) and the following screenshots explains what's weird.

Note: the reference lighting effect pictures are from this website: https://www.cs.toronto.edu/~jacobson/phong-demo/.

##  Specular lighting seems weird
To illustrate the effect of specular lighting, let's turn off every other lighting and turn specular lighting to its full level, as the following screenshot shows. 
<img width="1366" alt="Screen Shot 2022-08-31 at 11 50 34 AM" src="https://user-images.githubusercontent.com/814885/187745884-43bdf80f-0ef0-471f-8c2e-3d36eb3915b2.png">
However, this looks more like ambient lighting. A proper specular lighting on a sphere would look something like this:
<img width="608" alt="Screen Shot 2022-08-31 at 11 52 16 AM" src="https://user-images.githubusercontent.com/814885/187746209-f9726689-5bdd-420e-be49-9f6c2aeac0fb.png">

## Shineness is not strong enough. 
Let's try to use the strongest shineness, as the following screenshot shows. However, each sphere is barely shining. 
<img width="1366" alt="Screen Shot 2022-08-31 at 11 57 01 AM" src="https://user-images.githubusercontent.com/814885/187747015-60c4db14-817c-49db-9e8d-330451425e90.png">

A properly lighted sphere, however, would give very obvious shining effect, as the following screenshot shows.  
<img width="610" alt="Screen Shot 2022-08-31 at 11 58 22 AM" src="https://user-images.githubusercontent.com/814885/187747269-b80e98e1-39e0-46ae-9832-bbbef949fe6b.png">

**Comment by shaomeng** [comment]
We agreed on 2 baselines regarding lighting:
1. Particles and flow renderers should use the same lighting model
2. Whatever lighting model is chosen, we should provide a correct implementation of it.

**Comment by sgpearse** [comment]
No slider should go to zero shininess should go to ~100.
