### ISSUE TITLE
Image Capture: TIF files not correct

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#322]
The captured TIF (2nd attached image) files are not the same as JPGs (1st attached image), and the TIFs are obviously wrong. 
![pic](https://user-images.githubusercontent.com/814885/32568226-d109d748-c47a-11e7-9417-39c101cfe14a.jpg)

![pic tif](https://user-images.githubusercontent.com/814885/32568234-d6f03dd2-c47a-11e7-8f5f-aeb3cb6cabcc.png)

**Comment by StasJ** [comment]
Fix: disable

**Comment by shaomeng** [comment]
Refactor needed: implement a png exporter to take place of the tif exporter.
