### ISSUE TITLE
Geotiff image reader broken and results in core dump

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3220]
Attempting to open one of our bundled GeoTIFF images results in a core dump inside of libgeotiff.

To reproduce:
1. Open DUKU.nc
2. Create an Image renderer and enable it.
3. Change the image file from the default to worldFilled.tif

Other bundled geotiff files produce the same result.

**Comment by sgpearse** [comment]
@clyne Which platform is this on?  OSX?

**Comment by clyne** [comment]
Yes, OSX 11.6

**Comment by sgpearse** [comment]
I think you may be building from source, without the new third party libraries. 
 If so, this was reported in #3174 and passed our last round of bug fix tests.  If that's the case, [here's a link](https://drive.google.com/file/d/1Q-IXlP_OgZSXsWKmT-smyrW9xnR-dUfg/view?usp=sharing) to the new version.

**Comment by clyne** [comment]
@sgpearse something is not right here. The version of libgeotiff in the link you provided (as well as what I have installed on my machine) appears to be version 1.5.1. I'm speculating that is the version based on this macro in the geotiff.h header file:

`geotiff.h:#define LIBGEOTIFF_VERSION 1510`

However, if I download version 1.7.1 of geotiff from  [here](https://github.com/OSGeo/libgeotiff/releases) the LIBGEOTIFF_VERSION is defined as:

`#define LIBGEOTIFF_VERSION 1710`

Contrary to this [comment](https://github.com/NCAR/VAPOR/issues/3174#issue-1334943867),  it does NOT look like are building against geotiff v1.7.1

**Comment by sgpearse** [comment]
You seem to be right.  I'm wondering how this didn't turn up when testing the installers built on CircleCI.  Either way, I'm updating the libraries now and will let you know when they're uploaded.  Thanks for catching this.
