### ISSUE TITLE
Allow user to load and save current camera settings as a file

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3230]
If we are working on multiple datasets that have the same domain and we want to use the same camera position among them, we need to manually enter 16 values into Vapor.  

Currently I'm have a dataset like this that is run at four different resolutions. 
 Each time I need to change the camera perspective, I change it on one session then manually enter the 16 camera values into the other three sessions.  This means 48 manual entries per camera change, which is tedious prone to error.

**Comment by shaomeng** [comment]
Can someone, maybe @sgpearse , specify how this is fixed? I.e., this is a new button somewhere, or there's a new menu option, and what do those buttons or menu options do? 

Basically, if I'm to verify that this is really fixed, I need to know what I do and what I can expect from my actions.

**Comment by sgpearse** [comment]
yes, sorry about the confusion.  This feature is in the Scene->Viewpoint->Camera Controls section.  There are two buttons that allow you to save and load camera perspectives.

**Comment by shaomeng** [comment]
Question, when saving a file using the dialog window shown below, would the user expect the saved file to be "MyCamera.vc3", or to be "MyCamera" ? The current behavior is that  "MyCamera" got saved to disk. 

![image](https://user-images.githubusercontent.com/814885/205181054-52343898-7e49-4b44-b5f6-4846f88ee2aa.png)

**Comment by shaomeng** [comment]
> @shaomeng this is a Qt bug in Linux. .vs3 gets appended on OSX and Windows. From what I've read, people have mixed success with this and some end up resorting to manually adding it. Should be an easy fix though.

I think either behavior is fine, as long as it's consistent across our supported operating systems.

**Comment by sgpearse** [comment]
Fixed in #3231
