### ISSUE TITLE
Free GPU Ram

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3236]
We've added new GPU memory warnings that are issuing a "Paint failed" error for a dataset* on our Ubuntu test tower.  Previously, this dataset was doing successful volume renderings, as far as I could discern.  I suspect that previously, the volume renderings were incorrect but we were not reporting it.

Question: We currently throw an error and render nothing.  Do we want to fall back on an incorrect approximation if the GPU runs out of ram, or render nothing, or render alongside with a warning?

* Dataset in question is leigh's ~4GB ZFP dataset referenced in #3088.

**Comment by StasJ** [comment]
What is the error?

**Comment by clyne** [comment]
This is a large data set, 1476^2 x 496. I don't know what kind of GPU is on the test tower, but my impression is that it is pretty dated (i.e. ancient). I'm able to render this data set on my laptop, which has a pretty wimpy, but more current, integrated Intel Iris Plus Graphics. Are you sure this is a regression on the tower? Not sure that we should worry about it if the behavior is reasonable on more current hw.

**Comment by clyne** [comment]
A possible future enhancement might be down down sample the data when they are too large for the graphics hw.

**Comment by sgpearse** [comment]
Just followups:

@stasj 

```
Error performing paint event
Not enough GPU RAM free (3686MB free, need at least 4122MB)

Redirecting Python IO
```


@clyne 

It's an AMD card that's ~5 years old.  Details below.

https://en.wikipedia.org/wiki/Radeon_500_series

```
(base) vapor2@vapor2:~/Downloads/sep21$ sudo lshw -C display
[sudo] password for vapor2: 
  *-display                 
       description: VGA compatible controller
       product: Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:03:00.0
       version: c7
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:39 memory:e0000000-efffffff memory:f0000000-f01fffff ioport:e000(size=256) memory:f7e00000-f7e3ffff memory:c0000-dffff
```

**Comment by sgpearse** [comment]
> Are you sure this is a regression on the tower?

I haven't gotten through the other platform tests yet.  This dateset is not a part of the platform tests however.  I'll test this on CentOS, OSX and Windows in addition to the other platform tests tomorrow.

**Comment by sgpearse** [comment]
Same error is occurring on CISL-ACWORTH (OSX patform test machine).

<img width="698" alt="Screen Shot 2022-09-22 at 8 49 43 AM" src="https://user-images.githubusercontent.com/9522770/191780183-28c81698-c033-4464-aa0a-8aa93022087b.png">

**Comment by clyne** [comment]
The reported behavior seems reasonable. You're trying to volume render a large data set on older, less capable GPUs. you are are getting an informative error message, and the system is recovering from the error (not crashing, able to resume normal operation).

**Comment by sgpearse** [comment]
My only concern was that on Ubuntu we render absolutely nothing at all, whereas previously we would still render _something_.  

However the other platforms do seem to be drawing the volume, and allow the user to continue normally.  I'd prefer just telling users to upgrade hardware instead of chasing this discrepancy down on Ubuntu, so I'll close this.
