### ISSUE TITLE
WRF-rotlatlon-Alan1-d01 image renderer broken

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#3238]
1. Open WRF/rotlatlon-Alan2-d01
2. Create/enable an image renderer

![WRF-rotlatlon-Alan2-d01-Image](https://user-images.githubusercontent.com/2772687/191631963-5f35c483-c51e-4b3e-92b3-7be3f00902c6.png)

Session: [WRF-rotlatlon-Alan1-d01-Image.png.vs3.zip](https://github.com/NCAR/VAPOR/files/9621139/WRF-rotlatlon-Alan1-d01-Image.png.vs3.zip)

**Comment by clyne** [comment]
@StasJ is this a duplicate of #3201? Note, the issue title refers to "Alan1", but the description refers to "Alan2". These are two different data sets. The bug reported in #3201 only occurs with Alan2.

**Comment by StasJ** [comment]
> @StasJ is this a duplicate of #3201? Note, the issue title refers to "Alan1", but the description refers to "Alan2". These are two different data sets. The bug reported in #3201 only occurs with Alan2.

I thought there already was an open issue for this but when I typed "rotlatlon" into the github issue search nothing came up. I just tried again and the old issues came up so idk what was going on there. Closing this one as a duplicate.
