### ISSUE TITLE
Crash in UnstructuredGrid3D

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3243]
To reproduce:
1) Load DCP data and create/enable a particle renderer
2) Enable "Show direction"
3) Reduce the Y maximum extent to less than half of the domain
4) Vapor will crash

Note: This is issue was present in 3.6.0 as well.  Checkout commit _bbf18a5_ and follow the above steps with the old particle renderer to reproduce.

```
Process 61981 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x41)
    frame #0: 0x000000010302dcc3 libvdc.dylib`VAPoR::UnstructuredGrid3D::ConstCoordItrU3D::next(this=0x000000015d810ff0) at UnstructuredGrid3D.cpp:223:18
   220
   221 	    _coords[0] = *_xCoordItr;
   222 	    _coords[1] = *_yCoordItr;
-> 223 	    _coords[2] = *_zCoordItr;
   224 	}
   225
   226
Target 0: (vapor) stopped.
```

**Comment by StasJ** [comment]
This is a regression and does not occur in the original particle renderer.

**Comment by sgpearse** [comment]
Just to be clear - This regression was introduced in 3.6.0.  It was not present in 3.5.0, where DCP was added.
