### ISSUE TITLE
Particles disappear when "Enable 3D Geometry" Disabled

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#3244]
1. Load DCP data and create/enable a particle renderer
1. Enable "Show direction"
1. Select appearance tab
2. Uncheck "Enable 3D Geometry"

**Comment by sgpearse** [comment]
@stasj are you referring to the gui controls disappearing or the rendered particles themselves?  

I can reproduce the former, but not the ladder.  PR #3247 addresses the GUI issue if that's the problem you're referring to.

**Comment by StasJ** [comment]
I guess they don't disappear, they just become tiny. Their size should not change with regards to whether they are rendered as 3d objects or 2d glyphs. Yes, the GUI does in fact disappear though.

**Comment by sgpearse** [comment]
> Their size should not change with regards to whether they are rendered as 3d objects or 2d glyphs.

Hmm I'm not sure that I agree and I think there's some confusion with the terminology used in the Particle renderer.  When the `Enable 3D geometry` parameter is disabled, we are rendering with the legacy code that used gl primitives.  When it's enabled, we use the shaders.

The legacy particle renderer has no control over the radius (although it does have controls for length).  We should always see a change in size when switching between modes, unless the shader's radius is very small.

Do you think there might be a different term than `Enable 3D geometry` that would be more intuitive?

**Comment by StasJ** [comment]
Responded here: https://github.com/NCAR/VAPOR/issues/3247#issuecomment-1259110223

**Comment by shaomeng** [comment]
The checkbox in question, "Enable 3D Geometry", is no longer there. When closing the bug, it needs to be specified whether the original bug is fixed by internal logic improvement, or a GUI rearrangement, or simply removing the checkbox in question.

**Comment by sgpearse** [comment]
@shaomeng The "Enable 3D Geometry" checkbox has been replaced with the "Enable Lighting" checkbox for consistency with the flow renderer.

**Comment by shaomeng** [comment]
> @shaomeng The "Enable 3D Geometry" checkbox has been replaced with the "Enable Lighting" checkbox for consistency with the flow renderer.

Subtle name change big problem solved [👍](https://emojiguide.com/people-body/thumbs-up/)
