### ISSUE TITLE
Particle Length Scale changes direction rather than length. 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3253]
Use the session file located at `/glade/p/cisl/vast/vapor/Bugs/3253/particle-length-scale.vs3` and the bug behavior is illustrated below:

when changing the "Length Scale" slider, no length is changed. Rather, it appears the direction of a few sticks are changed, for example, the one in orange color. 

https://user-images.githubusercontent.com/814885/193118361-cf3a910a-d648-4d44-b4e1-d1b3f9b64e59.mp4

**Comment by sgpearse** [comment]
Pushing back to 3.8 since it's relevant to something that's already broken, #3250 and #3243.

**Comment by shaomeng** [comment]
The same behavior still occurs, just on another tube. To trigger it, load the same session file, and then adjust the "Length Scale" slider to positions between 8.0 and 8.2. The jumping tube is on the right side of the scene.
