### ISSUE TITLE
Transfer Function opacity slider is a no-op

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#327]
1. Open a dataset
2. Add and enable a renderer
3. Move opacity slider to the right of transfer function and nothing happens

**Comment by StasJ** [comment]
Fix: Disable

**Comment by sgpearse** [comment]
This is working for the TwoD renderer, but does not seem to work for Barbs or Contours on the current OSX (Nov 25) installer.

**Comment by StasJ** [comment]
@sgpearse The opacity slider works as intended but transparency is not implemented for these renderers. I will close this and open a new issue.
