### ISSUE TITLE
loading a NETCDF file with Python API prints an error

### ISSUE THREAD

**Issue by NihanthCW** [NCAR/VAPOR#3274]
### Describe the bug
https://vapor.discourse.group/t/netcdf-and-python-api/230
Hi Vapor Team,
Thanks for the new updates! I’m having some issues loading NetCDF data with the Python API; data that works just fine with the Vapor GUI. I’m getting what looks like a compliance issue (see Output below) but if the file is non-compliant, it shouldn’t work in the GUI either. Any ideas?

Input:

import vapor
from vapor import session,renderer,dataset,camera
import numpy as np
import matplotlib.pyplot as plt

ses = session.Session()
data = ses.OpenDataset(dataset.MPAS, ["/Volumes/3TB-Data/cx/rolled_1280.nc"])
Output:

Missing required dimension "Time"
Failed to initialize data importer
Failure to open data set of type "mpas"

**Helpful additional information**
- [ ] Did you get wrong results?

### To Reproduce
Link to the data: https://vapor.discourse.group/t/netcdf-and-python-api/230

### Additional context
Add any other context about the problem here. Attach any (zipped) relevant files, such as data, configurations, session files, etc.
https://drive.google.com/drive/folders/1CvsuS16ClBBonjoJAv_Y4_iGo3dswPxf?usp=sharing

**Comment by NihanthCW** [comment]
This is from a user (discourse comment).

**Comment by StasJ** [comment]
The user is attempting to load CF data as MPAS.

data = ses.OpenDataset(**dataset.MPAS**, ["/Volumes/3TB-Data/cx/rolled_1280.nc"])

which the error explains:

`Failure to open data set of type "mpas"
`

**Comment by NihanthCW** [comment]
I see... 
@shaomeng :Since you've already responded to her before, could you update her [here](https://vapor.discourse.group/t/netcdf-and-python-api/230)?
You could point her to some vapor python API reference on loading datasets (if any) or mention the correct way to load the dataset. 
Thanks @StasJ @shaomeng

**Comment by shaomeng** [comment]
Sure, I replied to the user. However, I wasn't able to find Python API documentation on how to correctly import a CF data file. If @StasJ knows the correct command, could you let the user know on the forum? 

Btw, I didn't find Python API documentation on VAPOR documentation website https://vapor.readthedocs.io/en/readthedocs/ . Is it me not finding it, or is the python documentation really missing?

**Comment by NihanthCW** [comment]
Thanks @shaomeng ! I don't think we have an external API reference and I agree that we ought to have this. Let's discuss this in the upcoming meeting.

**Comment by sgpearse** [comment]
Rejecting due to user error.  **dataset.CF** needs to be used instead of **dataset.MPAS**.
