### ISSUE TITLE
Wanting to render isentropic potential vorticity surfaces on VAPOR 3.7

### ISSUE THREAD

**Issue by winash12** [NCAR/VAPOR#3284]
### Describe what needs to be documented.
I have seen this https://www.youtube.com/watch?v=eVYOc8XN3mg video and I have PV data on isentropic surfaces(260 to 420K) in intervals of 15K. The data is a function of latitude and longitude and is interpolated from NCAR reanalysis isobaric data. But the video uses PV at heights above MSL. Do I need to again interpolate from isentropic to constant height surface to make videos such as shown in the external link or is it possible to display them using isentropic surfaces ? 

I would also like a map of the world or a region above the surface as is shown in that video.

**Comment by winash12** [comment]
> If I understand your problem correctly, your data's vertical coordinate is entropy, not height in meters, which Vapor requires. If so, you will unfortunately need to interpolate the Z coordinate to meters.
It is actually temperature not entropy. It is called potential temperature. Like 322 K or 360K etc. The vertical coordinate is monotonically increasing.

**Comment by sgpearse** [comment]
> The vertical coordinate is monotonically increasing.

So I think you should be set as long as you can interpolate to meters.  I'll close this ticket but feel free to re-open if there's another issue.
