### ISSUE TITLE
Region/Navigate tool bar not visible. Context menu for toolbars empty

### ISSUE THREAD

**Issue by Padanian** [NCAR/VAPOR#3285]
### Describe the bug
The region/navigate toolbar is not visible/is unavailable under Windows

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [x] Did you get wrong results?

**Impact**
- [x] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
Steps to reproduce the behavior. For example:
1. Open Vapor under Windows
2. Right click on menu bar, see empty checkbox caption

### Expected behavior
A region/navigate toolbar shall be visible

### Attachments
Screenshot

### Desktop
 - OS and version: Windows 11 21H2
 - Version: [Vapor 3.7]

### Additional context

![image](https://user-images.githubusercontent.com/7769348/204479297-c7724d11-44f9-4bc1-b747-d3a59ee1ca05.png)

**Comment by sgpearse** [comment]
@Padanian The flow renderer has more tabs than other renderers and you need to scroll to the right.  Check out the screenshot below.  IMO, the Integration Tab is not used enough to warrant its own tab and should be put somewhere else.

![Screen Shot 2022-11-29 at 8 46 58 AM](https://user-images.githubusercontent.com/9522770/204576138-1d7c9b0a-50ae-4f2e-a07f-2d8e8c8c9fb2.png)

**Comment by Padanian** [comment]
Yeah, I realized it myself after opening the issue. Closing, thanks.
