### ISSUE TITLE
Data fidelity, only "HIGH" available in all panes

### ISSUE THREAD

**Issue by Padanian** [NCAR/VAPOR#3286]
### Describe the bug
No other data fidelity can be selected other than HIGH

**Helpful additional information**
- [ ] Did VAPOR crash?
- [x] Did you get wrong results?

**Impact**
- [ ] High - User productivity significantly degraded
- [x] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
Steps to reproduce the behavior. For example:
1. Enable one renderer of choice
2. Click on data fidelity combobox

### Expected behavior
Low and medium data fidelity should be selectable

### Desktop
 - OS and version: [Windows 11 21H2]
 - Version: [Vapor 3.7]

### Additional context
Add any other context about the problem here. Attach any (zipped) relevant files, such as data, configurations, session files, etc.
![image](https://user-images.githubusercontent.com/7769348/204483291-c7655726-671a-468d-963f-d3545629d015.png)

**Comment by sgpearse** [comment]
This happens with imported data.  Are you seeing this with wavelet-compressed VDC?

**Comment by Padanian** [comment]
Ah. So you're telling me that WRF data have a fixed fidelity.
