### ISSUE TITLE
Deleting a Python variable plotted in a renderer causes Vapor to crash

### ISSUE THREAD

**Issue by Padanian** [NCAR/VAPOR#3293]
### Describe the bug
When an active renderer is showing a user-derived variable, and the variable is deleted in the Python derived variable form, the renderer crashes to shell

**Helpful additional information**
- [X] Did VAPOR crash?

**Impact**
- [X] High - User productivity significantly degraded

### To Reproduce
Steps to reproduce the behavior. For example:
1. Go to Python derived variables
2. Create a derived variable
3. Create a renderer and plot the variable according to type
4. Enable the renderer
5. Open Python derived variables and delete variable
6. Vapor crashes to shell

### Expected behavior
I expect Vapor to warn the user the variable is used and can't be deleted, or the renderer to be disabled until a new variable is set.

### Desktop
 - OS and version: [Windows 11 21H2]
 - Version: [Vapor 3.7]

**Comment by StasJ** [comment]
Note: This issue is specific to the TwoDDataRenderer
