### ISSUE TITLE
File selector cannot select multiple files on Casper

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3294]
### Describe the bug
Usually, when importing multiple files into VAPOR, one would select multiple files in the file window. However, on Casper, a single left click on a file opens it, eliminating the user option to select multiple files.  

### Expected behavior
I expect a single click to select a file but not open it.

### Desktop
Casper

**Comment by sgpearse** [comment]
@shaomeng I've noticed this on the KDE desktop on Casper and other applications behave the same way.  If you're not using KDE, do you know if other apps do the same thing?

**Comment by shaomeng** [comment]
> @shaomeng I've noticed this on the KDE desktop on Casper and other applications behave the same way. If you're not using KDE, do you know if other apps do the same thing?

I tested KDE environment and Evince (document viewer). Evince is able to correctly select and open multiple files.

**Comment by sgpearse** [comment]
@pearse will contact the consultants about this issue and find out why we must use the KDE desktop, while the default desktop does not exhibit this behavior.

**Comment by sgpearse** [comment]
KDE is currently the default desktop on Casper, but users can specify `--desktop=gnome-session` with vncmgr, which does not exhibit this problem.

**Comment by NihanthCW** [comment]
#3576 #3580
