### ISSUE TITLE
consolidate Quick Start Guides

### ISSUE THREAD

**Issue by NihanthCW** [NCAR/VAPOR#3295]
### Describe what needs to be documented.
Review the documentation on the [VAPOR page here](https://vapor.readthedocs.io/en/readthedocs/quickStartGuide.html) 
Ensure that users don't get confused with the instructions for the python API and the GUI.

Include API documentation on ReadTheDocs that shows help() output.

### Is the documentation there but needs improvement?
Yes
*Please provide the url of the documentation.*
https://vapor.readthedocs.io/en/readthedocs/quickStartGuide.html 

### Additional context
Add any other context or screenshots about the desired documentation.

**Comment by shaomeng** [comment]
Piggy back on documentation improvements, the Python API page is empty right now.
https://vapor.readthedocs.io/en/readthedocs/usage/pythonAPI/README.html?highlight=python%20api

**Comment by shaomeng** [comment]
Qfter I download these two zip files (supposed to contain examples) from this page: https://vapor.readthedocs.io/en/readthedocs/usage/pythonAPI/index.html?highlight=python%20api , the downloaded zip files are empty.

**Comment by NihanthCW** [comment]
no longer relevant
