### ISSUE TITLE
Scaling one dimension doesn't scale the domain box as well

### ISSUE THREAD

**Issue by Wolpes11** [NCAR/VAPOR#3298]
Hi,
actually I don't know if it's a bug or it's me that I'm doing something wrong.

I want to rescale one dimension in a 3D Volume plot. Under "Transformation -> Scale", I rescale Z to be twice the original dimension, but the transformation doesn't apply to the domain frame. So I have a 3D surface plot having one dimension doubled and the reference frame which cannot contain the whole plot.

Hope I sufficiently explained what's my issue.

Thanks in advance.

**Comment by sgpearse** [comment]
Yes, that makes sense.  Each renderer has its own transform.  Additionally, each loaded dataset has a transform.  The Z scaling that is applied to your Volume renderer will not be applied to other instances.

The transform for the entire dataset can be found under Scene->Viewpoint->Transform.  Hope that helps.

**Comment by Wolpes11** [comment]
That's great! Thank you so much.

Regards,
