### ISSUE TITLE
Jupyter widgets and interactive visualizer no longer working

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3303]
To reproduce:
1) On casper
```
conda create --name bug
conda install python=3.9
conda install -c conda-forge -c ncar-vapor vapor
cd $CONDA_PREFIX/lib/python3.9/site-packages/vapor/example_notebooks
jupyter notebook
```
2) run visualizer_widget_example.ipynb and the visualizers will not be interactive until their cells are re-run, and the slider will not change the isovalue

**Comment by StasJ** [comment]
Works for me:

![casper](https://user-images.githubusercontent.com/2772687/208827604-57f6243b-9f7d-4376-a3d7-e07a18a289c6.gif)

**Comment by sgpearse** [comment]
@stasj It looks like you're running vapor 3.7.1.  The current version is 3.8.

**Comment by StasJ** [comment]
@sgpearse The only difference between the two is the version bump but if you insist:

![casper](https://user-images.githubusercontent.com/2772687/208969015-41c3ea8c-115d-4401-9dac-f9050207acae.gif)

**Comment by shaomeng** [comment]
Maybe worth it to see how the widgets behave on Casper following the CISL recommended Python environment (https://arc.ucar.edu/articles/373).

**Comment by sgpearse** [comment]
Hard to reproduce.  We will revisit this if users encounter the problem.
