### ISSUE TITLE
Documentation is wrong about the vector field multiplier

### ISSUE THREAD

**Issue by leighorf** [NCAR/VAPOR#3304]
In the documentation, the following is stated:

Vector field multiplier: Allows the user to multiply their vector field values by a scalar. This is useful in the situation
where the data domain and the vector field are in different units. For example, if the data domain is in units of km, and
the vector field is in units of m/s, the user may **multiply their vector field by 1000** so that all units are congruent with
each other.

This should read "**multiply their vector field by 0.001**"

I had some very weird results until I figured this out.

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [ X] Did you get wrong results?

**Impact**
- [X ] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce

I have a model with a domain in km and velocity data in m/s just like the "for example" above, but 1000 should be 1/1000! To reproduce, just follow the advice above!

**Comment by NihanthCW** [comment]
Thank you for bringing this to our attention, Leigh. We'll fix that asap.
