### ISSUE TITLE
ZFP compressed NetCDF files do NOT open with VAPOR 3.7.0

### ISSUE THREAD

**Issue by leighorf** [NCAR/VAPOR#3306]
### Describe the bug
NetCDF4 files using ZFP compression throw a "NetCDF: Unimplemented Filter" error when trying to access properly encoded ZFP compressed CF compliant NetCDF4/HDF5 files.

I am much of the impetus behind this welcome code change of having VAPOR natively read NetCDF4 files that are ZFP compressed. However on the Mac M1 version, it just doesn't work. I tried mucking with HDF5_PLUGIN_PATH (thinking that perhaps it had to be set) but to no avail.
[vaporlog.txt](https://github.com/NCAR/VAPOR/files/10320536/vaporlog.txt)

**Comment by shaomeng** [comment]
A little more info: an example zfp compressed netcdf file here is one:

https://www.dropbox.com/sh/e1c6j8ygob0cuua/AAB32o6tKBfrLcxTEz6RxaWra?dl=0

The CentOS version of VAPOR 3.7.0 opened this file fine.

**Comment by sgpearse** [comment]
@leighorf I can reproduce this on OSX Monterrey but not Big Sur.  I have a fix in the works that I think can make it into 3.8, which we are releasing very soon.  If this fix does not get incorporated, I can make you a custom installer.

In the meantime, you mentioned HDF5_PLUGIN_PATH does not work for you.  However I'm currently having success with the following workaround.  Does the following launch command for vapor still present the error?

```
export HDF5_PLUGIN_PATH=/Applications/vapor.app/Contents/share/plugins
/Applications/vapor.app/Contents/MacOS/vapor
```
