### ISSUE TITLE
Journal article should be cited. 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3311]
In the [VAPOR citation page](https://vapor.readthedocs.io/en/readthedocs/licenseAndCitation.html), there's no mention of the journal article on VAPOR. However, the [journal article](https://www.mdpi.com/2073-4433/10/9/488) should be requested to be cited.

**Comment by sgpearse** [comment]
@NihanthCW and @clyne  - Do we want our users to cite our Zenodo DOI, the MDPI article, or both?  If both, how do we suggest users cite two different DOI's?

**Comment by NihanthCW** [comment]
Hmm, this is an interesting question. I like what GeoCat has on [their page](https://geocat.ucar.edu/pages/citation.html). We could do something similar explaining when to cite each version. Thoughts?

One drawback: we might be diluting the citations to the paper.

**Comment by clyne** [comment]
I don't think that it is unreasonable to ask users to cite a journal article AND a DOI with the specific version. That would prevent dilution of citations. Plus I've found that Google Scholar does a good job of tracking citations for journal articles. I've not found similar tools for software DOIs, but admittedly I was pretty lazy in my search :-)

**Comment by shaomeng** [comment]
Agreed. While the journal article is tracked by Google with very *detailed* citation record, for example [the list of publications who cited VAPOR](https://scholar.google.com/scholar?cites=9064842922077460956&as_sdt=4005&sciodt=0,6&hl=en), there isn't a solid place that tells you simply how many citations the DOI received.

**Comment by NihanthCW** [comment]
@shaomeng I added a citations page mentioning the article and the software. https://www.vapor.ucar.edu/pages/vaporCitationPage.html

**Comment by shaomeng** [comment]
That looks good Nihanth, thanks!
