### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by pick2510** [NCAR/VAPOR#3321]
Dear VAPOR Team,
I wanted to build a native Apple Silicon version of VAPOR and noticed there is a lack of information how to build VAPOR from source. I had a look into your CI for checking how you build the releases. There I saw you download the necessary dependencies from a Google Drive. 

Would it be possible to publish your way of building the dependencies? Maybe you even have a scripted build system for the complete workflow.

**Comment by sgpearse** [comment]
Sure, you can find instructions at the link below.  Please let us know if you find any inconsistencies or errors.

https://vapor.readthedocs.io/en/readthedocs/contributing.html#building-vapor-from-source

**Comment by pick2510** [comment]
Thanks a lot. I didn‘t find it in the documentation.
I now managed to build a a fully native Apple Silicon version with your August-2019 source and some updated source packages. I qualitatively compared the performance of a more complex rendering task with the standard Intel binary and it‘s definitely way faster and snappier, especially for CPU heavy things like flows.
If there is any interest from your side, I can share my compilation procedurey

**Comment by sgpearse** [comment]
That's great.  Did you rebuild the third party libraries, or just Vapor?  Please do share your proceedure.

**Comment by pick2510** [comment]
It‘s full a recompilation with all dependencies and OpenMP support. I had to update packages like Python and HDF5 to recent versions to be able to compile on Apple Silicon.
I will share my steps when I am at work again tomorrow.

**Comment by sgpearse** [comment]
Great, thanks again and I'm looking forward to seeing your steps.

**Comment by pick2510** [comment]
I am having a bit a hard time to package it. QT5 from homebrew doesn't work properly since it uses a different freetype version. I will now build QT5 from source as well. 
So the current state: The build is working and I can package it with CPack. But it won't work on other macs since rpath management doesn't work yet.

**Comment by pick2510** [comment]
I think I managed to build a portable version. There are some problems with it:

1. I have to use macdeployqt for correctly handling dependencies. If I use the OSX_PostBuild.py script to manage rpath on the ThirdParty libs the resulting vapor will crash when loading some QT pluging. I still have no idea why. So packaging is:
- make 
- make installer
- cd _CPack_Packages/Darwin/DragNDrop/VAPOR3-3.8.0-Darwin/ALL_IN_ONE
- macdeployqt vapor.app
Then you have fully portable version.
2. This deployment leads to two folders, lib and Frameworks in the app. Frameworks contains then most of the needed libraries but lib will need to have the shared libraries of vapor itself.
3. The result is a bigger vapor.app.

So as a first step I suggest you test my build:
https://polybox.ethz.ch/index.php/s/FCyAaoYGrc5sSGO

Maybe you have some benchmark cases at hand. 
We can then maybe dive further into building and packaging.

**Comment by pick2510** [comment]
I now managed to build it completely with the CMake buildsystem without any other deployment tool. 😃
I updated the build under https://polybox.ethz.ch/index.php/s/FCyAaoYGrc5sSGO

Here is my workflow:

As a base, I used your source distribution available under: 
https://drive.google.com/open?id=1sWIV-Y66aFuDkC2oDnceIIUJDDH4puKI

The following packages were updated:
Python-3.9.16
HDF5 1.14
udunits 2.28

The following packages were added:
zlib 1.2.13 (for minizip)
libpng 1.6.37 (to prevent using system libpng)

In addition, I had to compile qt5 by hand since homebrew qt5 has lots of dependencies to other homebrew packages.
I used the one file version here: 
https://download.qt.io/archive/qt/5.15/5.15.8/single/qt-everywhere-opensource-src-5.15.8.tar.xz

**Compiling QT5**
```bash
export MACOSX_DEPLOYMENT_TARGET=11.0
export PREF=/User/strebdom/BUILD_VAPOR/QT5
./configure -prefix $PREF
make -j 15
# wait for a long time. ;-)
make install
```

**Compiling other dependencies**
```
brew install xz openssl zlib glm llvm libomp

export MACOSX_DEPLOYMENT_TARGET=11.0
export PREF=/User/strebdom/BUILD_VAPOR/THIRD_PARTY_LIBS/

# libpng
cd libpng-1.6.37
CC=clang CXX=clang++ ./configure --prefix=$PREF
make install -j 15

# Minizip from zlib
cd zlib-1.2.13/contrib/minizip
autoreconf -i
CC=clang CXX=clang++ ./configure --prefix=$PREF
make install -j 15

# assimp
cd assimp-4.1.0
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$PREF -DCMAKE_EXE_LINKER_FLAGS=$PREF/lib -DCMAKE_BUILD_TYPE=Release ..
make install -j 15

# szip  
cd szip-2.1.1
CC=clang CXX=clang++ ./configure --prefix=$PREF 
make install -j 15

# HDF5
cd hdf5-1.14.0
CC=clang CXX=clang++ ./configure --prefix=$PREF --with-szlib=$PREF
make install -j 15

# NetCDF
cd netcdf-c-4.7.0 
LDFLAGS=-L$PREF/lib/ CPPFLAGS=-I$PREF/include/ CC=clang CXX=clang++ ./configure --prefix=$PREF --disable-dap
make install -j 15

# Udunits  
cd udunits-2.2.28
CC=clang CXX=clang++ ./configure --prefix=$PREF
make install -j 15

# freetype
cd freetype-2.10.1
LIBPNG_CFLAGS="-I$PREF/include" LIBPNG_LIBS="-L$PREF/lib -lpng16”  CC=clang CXX=clang++ ./configure --prefix=$PREF --with-harfbuzz=no
make install -j 15

# jpeg
cd jpeg9c
CC=clang CXX=clang++ ./configure --prefix=$PREF
make install -j 15

# libtiff
cd tiff-4.0.10
 LDFLAGS=-L$PREF/lib/ CPPFLAGS=-I$PREF/include/ CC=clang CXX=clang++ ./configure --prefix=$PREF
make install -j 15

# sqlite
cd sqlite-autoconf-3290000
CC=clang CXX=clang++ ./configure --prefix=$PREF

# libproj
cd proj-6.1.1
mkdir build 
cd build
 cmake -DEXE_SQLITE3=$PREF/bin/sqlite3 -DSQLITE3_INCLUDE_DIR=$PREF/include -DSQLITE3_LIBRARY=$PREF/lib/libsqlite3.dylib -DCMAKE_INSTALL_PREFIX=$PREF -DPROJ_COMPILER_NAME=clang++ ..
 unzip ../../proj-datumgrid-1.8.zip -d data/
make install -j 15

# libgeotiff
cd libgeotiff-1.5.1
LDFLAGS=-L$PREF/lib/ CPPFLAGS=-I$PREF/include/ CC=clang CXX=clang++ ./configure --prefix=$PREF --with-zlib=yes --with-jpeg=yes
make install -j 15

# glew
I just set GLEW_DEST to $PREF.
make install

# Python
cd Python-3.9.16
CPPFLAGS="-I$PREF/include -I$(brew --prefix zlib)/include -I$(brew --prefix openssl)/include" LDFLAGS="-L$PREF/lib -L$(brew --prefix zlib)/lib  -L$(brew --prefix openssl)/lib" CC=clang CXX=clang++ ./configure  --with-openssl=/opt/homebrew/opt/openssl prefix=$PREF --enable-shared --with-ensurepip=install --with-suffix=.vapor --enable-optimizations
# Somehow pip didn't get installed. I then used https://bootstrap.pypa.io/get-pip.py with python3.vapor to install it.
$PREF/bin/python3.vapor get.pip.py
$PREF/bin/pip  install --upgrade --target $PREF/lib/python3.9/site-packages numpy scipy matplotlib
# I had to make a symlink from $PREF/include/python3.9 to $PREF/include/python3.9m since CMake wants to have Python include path there.
ln -s python3.9 python3.9m
```
Then the most recent problem was not all rpath were updated with the current configuration of OSX_PostBuild.py. I had to run it twice with changeFileID=False and changeFileID=True until all rpaths were changed. Also libGLEW was not detected with the script. I had to remove the os.access(filename, os.X_OK) condition. I will send a pull request later.
Check with otool -L that all rpaths are correctly set and no $PREF path is still active

Next is to edit you site.NCAR (or ../site.local?) with the appropriate paths. 

Then building vapor is not difficult anymore:
```bash
cd ~/git/Vapor/builtutils
unzip GTE.zip
cd ...
mkdir build
cd build
cmake -DCMAKE_C_COMPILER="/opt/homebrew/opt/llvm/bin/clang" -DCMAKE_CXX_COMPILER="/opt/homebrew/opt/llvm/bin/clang++" -DCMAKE_C_FLAGS="-I/Users/strebdom/git/VAPOR/buildutils -I/opt/homebrew/include" -DCMAKE_CXX_FLAGS="-I/Users/strebdom/git/VAPOR/buildutils -I/opt/homebrew/include" -DCMAKE_BUILD_TYPE="RELEASE" -DBUILD_OSP="OFF" -DUSE_OMP="ON" -DDIST_INSTALLER="ON" ..
make -j 15
make installer
```
This should then lead to your shiny new Apple silicon VAPOR version.

I hope I didn't forget anything. If something doesn't work, please let me know.

**Comment by pick2510** [comment]
To just try out a build:
https://polybox.ethz.ch/index.php/s/FCyAaoYGrc5sSGO

**Comment by sgpearse** [comment]
Thanks for doing this @pick2510.  These notes will help us with our next release.  Cheers!
