### ISSUE TITLE
Flow: Pathlines seem to never stop advecting

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3325]
![flow](https://user-images.githubusercontent.com/9522770/216748337-0cb6642a-f09c-4c88-8f18-ecf3af707035.gif)

Pathlines seem to get "stuck" during their advection, leading to increasing rendering times as more pathlines are injected into the scene.

To reproduce:
1. Download the attached .zip file that contains a BOV files, a binary data file, and a session file.
2. Load the session file and point it to the attached data.  Failing that, load the data and create a flow renderer as follows:
    - Pathlines
    - X, Y, and Z Field Variables = a
    - Pathline Length = 1
    - Injection Interval = 1
    - X, Y, and Z axis seeds = 10
5. Enable image capture and run the time series

The images on my computer and Casper are generated quickly at first but then slow down.  It only takes 5 time steps for the pathlines to completely exit the domain.  Rendering time should theoretically plateau after 5 time steps.

Many renderings captured in the first minute at the beginning of the time series:
![Screen Shot 2023-02-02 at 11 04 00 AM](https://user-images.githubusercontent.com/9522770/216406485-69641340-67c7-4dc3-9e5b-ed8ae1fcfbac.png)

One capture per 2 minutes near timestep 100:
![Screen Shot 2023-02-02 at 11 04 53 AM](https://user-images.githubusercontent.com/9522770/216406793-751d2380-cc71-4362-b666-fcea57434256.png)

[flowBug3325.zip](https://github.com/NCAR/VAPOR/files/10572883/flowBug3325.zip)

**Comment by sgpearse** [comment]
@shaomeng flowBug3325.zip, attached in the PR body, will have a session file that loads the included files to load as BOV data.  Once you load the session, you should be able to load the 100 .txt files wherever they are stored on your computer.

**Comment by shaomeng** [comment]
Hi @sgpearse , I failed to reproduce the increased rendering time, if that's the bug. In my case, all 100 images are generated within 1 minute, so all of them have the same timestamp. See attached screenshot. 

![Screenshot from 2023-02-08 12-25-28](https://user-images.githubusercontent.com/814885/217631676-7bb8e68d-79c3-47f9-80a2-7ab7dc12ea57.png)

**Comment by sgpearse** [comment]
Strange.  I wonder if this is system dependent?  I can't guess why it would be, but I see it on OSX and Casper haven't tested Ubuntu. I added a video clip to this PR description showing the pathlines getting "stuck".

I'll try to make a simpler session for that dataset on Casper file that reproduces this.

**Comment by sgpearse** [comment]
@shaomeng I can reproduce it on casper with the test dataset.  Try the session file at /glade/p/cisl/vast/vapor/Bugs/3325/3325.vs3.

My only guess as to why you're not seeing it is that there might be another issue with loading session files that point to BOV data.  Are all of the parameters in your test as follows?

- Pathlines
- X, Y, and Z Field Variables = a
- Pathline Length = 1
- Injection Interval = 1
- X, Y, and Z axis seeds = 10

**Comment by shaomeng** [comment]
> @shaomeng I can reproduce it on casper with the test dataset. Try the session file at /glade/p/cisl/vast/vapor/Bugs/3325/3325.vs3.


Is there a set of instructions of building VAPOR on caspoer? I'll need a debug build to hunt the issue.

**Comment by sgpearse** [comment]
> Is there a set of instructions of building VAPOR on caspoer? I'll need a debug build to hunt the issue.

I've written [some instructions](https://docs.google.com/document/d/1N0aAVU-scAtPzkGUche9RvTf-NVjFwLjnW33D7T4oYw/edit?usp=sharing) in our Developer Documentation google drive folder.  You can also see them below:

```
git clone https://github.com/NCAR/VAPOR.git
cd VAPOR
git checkout origin/casper3.8.1 -- site_files/site.NCAR
mkdir build
cd build
cmake ..
make -j4
```

**Comment by shaomeng** [comment]
@sgpearse , the 3rd line of your instruction fails on Casper.:
```
shaomeng@casper-login1:VAPOR-git> git checkout origin/casper3.8.1 -- site_files/site.NCAR
fatal: invalid reference: origin/casper3.8.1
```

**Comment by sgpearse** [comment]
Sorry, forgot to push the branch.  It should work now.

**Comment by shaomeng** [comment]
@sgpearse  Thanks for the instructions, but I still don't have luck building it on Casper. Following your steps, I have a linker error at the last linking step, thus unable to build VAPOR on Casper.
```
[100%] Linking CXX executable ../../bin/vapor
../../lib/librender.so: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
../../lib/librender.so: undefined reference to `_TIFFfree@LIBTIFF_4.0'
../../lib/librender.so: undefined reference to `TIFFGetField@LIBTIFF_4.0'
../../lib/librender.so: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
../../lib/librender.so: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
../../lib/librender.so: undefined reference to `TIFFWriteRawStrip@LIBTIFF_4.0'
../../lib/librender.so: undefined reference to `TIFFReadRGBAImage@LIBTIFF_4.0'
../../lib/librender.so: undefined reference to `TIFFSetField@LIBTIFF_4.0'
../../lib/librender.so: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
../../lib/librender.so: undefined reference to `_TIFFmalloc@LIBTIFF_4.0'
../../lib/librender.so: undefined reference to `TIFFSetDirectory@LIBTIFF_4.0'
../../lib/librender.so: undefined reference to `TIFFReadScanline@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/vapor] Error 1
make[1]: *** [apps/vaporgui/CMakeFiles/vapor.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by shaomeng** [comment]
@sgpearse Never mind, I used a different compiler version (GNU 6.4.0) and it proceeded with success !

**Comment by sgpearse** [comment]
Great!  I'm glad to hear it.  I'm eager to move past CentOS version 7 because of this kind of thing.
