### ISSUE TITLE
AppSettings: Does not seem to be implemented

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#333]
None of the AppSettings seem to work.

https://github.com/NCAR/VAPOR/issues/299
https://github.com/NCAR/VAPOR/issues/298
https://github.com/NCAR/VAPOR/issues/297
https://github.com/NCAR/VAPOR/issues/296
https://github.com/NCAR/VAPOR/issues/321

**Comment by StasJ** [comment]
Fix: disable app settings tab

**Comment by clyne** [comment]
I created a new feature request to implement AppSettings
