### ISSUE TITLE
XArray axes are swapped compared to Vapor convention

### ISSUE THREAD

**Issue by acellison** [NCAR/VAPOR#3333]
The method `PythonDataset.AddXArrayData` incorrectly assumes the data ordering convention z slowest, y medium, x fastest.  One constructs an `xarray.DataArray` with the following:
    `xarray.DataArray(f, dims=('x', 'y', 'z'), coords={'x': x, 'y': y, 'z': z})`
Upon construction it is required that `f` has shape `(len(x), len(y), len(z))`, which translates to z being the fastest axis.  Vapor then garbles this data assuming x the fastest.  From dataset.py the line
    `dc.AddDataVar(var, np.float32(arr.data))`
can be potentially fixed with:
    `dc.AddDataVar(var, np.array(np.swapaxes(arr.data, 0, -1), dtype=np.float32, order='C'))`

**Helpful additional information**
- [ ] Did VAPOR crash?
- [x] Did you get wrong results?

**Impact**
- [ ] High - User productivity significantly degraded
- [x] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
See attached Jupyter notebook with demo code exhibiting the behavior.

### Expected behavior
The utility function `PythonDataset.AddXArrayData` should swap the first and final axes of the `xarray.DataArray.data` member to interoperate with Vapor conventions.
 
### Attachments
[xarray_to_vapor_bug.ipynb.zip](https://github.com/NCAR/VAPOR/files/10748096/xarray_to_vapor_bug.ipynb.zip)

### Desktop
 - OS and version: macOS 12.5.1
 - Version: Vapor 3.8.0

**Comment by StasJ** [comment]
Hi @acellison, thank you for your feedback. To my best knowledge, the standard convention for `order='C'` data is Z,Y,X where X is the fastest varying.  Your data is reversed from this ordering which is why you are seeing incorrect results. If I am incorrect in my assumption and you can point me to documentation stating your data layout is the convention for XArray, I will gladly revise our API to reflect that. In the mean time, I have updated our documentation with a note to alleviate future confusion on the matter.

**Comment by acellison** [comment]
XArray's `DataArray` axes ordering matches the order you specify in the dims arguments.  When I specify the axes order `dims=("y", "x")`, which implies the data is ordered x fastest, and use different number of points in each direction, the data gets garbled in when loaded into Vapor.

**Comment by StasJ** [comment]
The dims specified in xarray are just arbitrary labels so, while I understand what you are saying, that would be require using heuristics to guess and restructure the data based on arbitrary strings.

**Comment by acellison** [comment]
Yes as above, `dim_n` is the fastest dimension.  In dataset.py Vapor iterates over the dimensions but assumes `dim_0` is the fastest.  Have you tried my attached Jupyter notebook that exhibits the failure?  Or are there unit tests in vapor that demonstrate the code working for axes with different sizes?

**Comment by StasJ** [comment]
The XArray DataArray documentation does not state any correlation between the dims parameter and the varying speed. In fact, under the DataArray documentation examples, the first example has dim_0 as the fastest dimension which is consistent with Vapor.

**Comment by acellison** [comment]
I think DataArray is agnostic of the ordering - you can pass in a numpy array with order='C' (row major) or order='F' (column major).  Passing an order='F' ndarray to Vapor through the DataArray interface yields this exception: 
```
TypeError: void VAPoR::DCRAM::AddDataVar(const VAPoR::DC::DataVar& var, const float* buf) =>
    TypeError: could not convert argument 2 (could not convert argument to buffer or nullptr)
```
Can you provide an example with different size axes so I can see how to order my data, preferably with non-random data so we can tell it gets rendered properly?  Or can you show what I'm doing wrong in my Jupyter notebook attached to the bug?

**Comment by acellison** [comment]
The first example here https://docs.xarray.dev/en/stable/generated/xarray.DataArray.html has `x, y, time` as the axes.  The temperature, created with `temperature = 15 + 8 * np.random.randn(2, 2, 3)` has flags
```
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
```
From numpy's documentation https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html we have:
     "Row-major (C-style) or column-major (Fortran-style) order."
This means the fastest, "row major" dimension is `time`, which is the final dimension of the ndarray.

**Comment by StasJ** [comment]
Hi @acellison, sorry for the delay. I initially misunderstood your issue, however, it has been resolved and in Vapor's latest release the notebook you attached now has Vapor's and matplotlib's output matching.
