### ISSUE TITLE
3D grids in XArray are not supported

### ISSUE THREAD

**Issue by acellison** [NCAR/VAPOR#3334]
3D grids in XArray are not supported in Vapor when the grid is a set of x,y,z coordinates all of shape (nx,ny,nz).  When we create an `XArray.DataArray` instance with this type of grid and pass it on to Vapor we get the error "Unrecognized grid type for variable".  On the other hand, this grid type is supported in 2D - see the comment and attached demo in #3333, where we create a tilted 2D coordinate system.

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [x] Did you get wrong results?

**Impact**
- [x] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
See attached Jupyter notebook with demo code exhibiting the behavior.

### Expected behavior
Vapor should allow 3D grids for non-uniform coordinates via its XArray interface.

### Attachments
[xarray_to_vapor_structured_3d_grid_bug.ipynb.zip](https://github.com/NCAR/VAPOR/files/10758341/xarray_to_vapor_structured_3d_grid_bug.ipynb.zip)

### Desktop
 - OS and version: macOS 12.5.1
 - Version: Vapor 3.8.0

**Comment by StasJ** [comment]
Hi @acellison, the 3D grid you are generating is unsupported by Vapor. Vapor is specialized visualization software targeted at earth sciences data and as such only supports grids found in that field. XArray, on the other hand is a more generic library that supports a broader variety of data. Below is an example of how to create 2D and 3D curvilinear grids supported by vapor akin to ones found commonly in earth sciences data using XArray.


```
def gen2d(w,h,f):
    """Generate a 2D grid of size (w,h) by evaluating f(x,y) for every x,y coordinate"""
    ay = []
    for y in range(0,h):
        ax = []
        for x in range(0,w):
            ax += [f(x,y)]
        ay += [ax]
    return ay


def gen3d(w,h,d,f):
    """Generate a 3D grid of size (w,h,d) by evaluating f(x,y,z) for every x,y,z coordinate"""
    az = []
    for z in range(0,d):
        ay = []
        for y in range(0,h):
            ax = []
            for x in range(0,w):
                ax += [f(x,y,z)]
            ay += [ax]
        az += [ay]
    return az


w = h = d = 8
curveVar = xr.DataArray(
    gen2d(8,8,lambda x,y: y*8+x),
    dims=("x", "y"),
    coords={
        "x_coord": xr.DataArray(gen2d(8,8,lambda x,y: x), dims=("x", "y")),
        "y_coord": xr.DataArray(gen2d(8,8,lambda x,y: y), dims=("x", "y"))
    })

data.AddXArrayData("variable_2d", curveVar)


curveVar = xr.DataArray(
    gen3d(w,h,d,lambda x,y,z: z*w*h + y*w + x),
    dims=("x", "y", "z"),
    coords={
        "x_coord": xr.DataArray(gen2d(w,h,lambda x,y: x), dims=("x", "y")),
        "y_coord": xr.DataArray(gen2d(w,h,lambda x,y: y), dims=("x", "y")),
        "z_coord": xr.DataArray(gen3d(w,h,d,lambda x,y,z: z), dims=("x", "y", "z")),
    })

data.AddXArrayData("variable_3d", curveVar)
```
