### ISSUE TITLE
Bad documentation page

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3335]
When I search "VAPOR data format" the following link shows up as the 1st result. However, it's a dead link.

https://vapor.readthedocs.io/en/readthedocs/data/vdc.html

**Comment by shaomeng** [comment]
So is the following link:  https://vapor.readthedocs.io/en/readthedocs/data/dcp.html

**Comment by shaomeng** [comment]
The working webpage hosting the documentation seems to be hosted under @sgpearse's personal space. This is less than ideal...  https://sgpearse.github.io/VAPOR-Sphinx/gettingDataIntoVapor.html#vapor-data-collection-vdc

**Comment by sgpearse** [comment]
You're understandably confused here Sam.  The website was restructured recently and Google's web crawlers will take some time to re-index the new structure of our docs.  This is outside of our control.

The data formatting documentation is at the top level of our table of contents:

https://vapor.readthedocs.io/en/readthedocs/dataFormatRequirements.html
