### ISSUE TITLE
Installation under arm

### ISSUE THREAD

**Issue by xiaopangjun666** [NCAR/VAPOR#3342]
Hi author, I recently tried to install vapor under arm platform using clang compiler, but I could never find ospray dependency when executing cmake command, but I did install ospray, here is the cmake command and the error screenshot：
cmake -DCMAKE_PREFIX_PATH=/usr/local/VAPOR-Deps/ospray-2.10.0 -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ..
![image](https://user-images.githubusercontent.com/48478201/221774827-e51bce5c-607b-45b3-b00b-ccfc002f4d40.png)
![image](https://user-images.githubusercontent.com/48478201/221774993-f6c6be2e-cc88-415e-b07e-90467434b4c9.png)
What puzzles me is that I checked lib/render/CMakeLists.txt:147 (find_library) which is supposed to find the static library file of opsray, and the static library file also exists in the lib64 folder under the installation location of opsray, but it can't be found.Could you give me some advice? Thank you very much!

**Comment by xiaopangjun666** [comment]
@datvance @opoplawski @shaomeng @core-code

**Comment by sgpearse** [comment]
Ospray is an intel library so I don't think it's going to work on ARM.  Try adding -DBUILD_OSP=OFF to your cmake command, which will omit it from your build.

**Comment by sgpearse** [comment]
@xiaopangjun666 - Please let us know if you have any other qustions.
