### ISSUE TITLE
Python API direct parameter access not working

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3345]
@stasJ - I don't think I'm experiencing user error but I'm not 100% positive.

To reproduce, run run /glade/p/cisl/vast/vapor/Bugs/3345/3345.py.  This generates initial.tiff which is correct, and zero.tiff which does not seem to have accepted the 0 value for the _constantOpacityTag.

3345.py for reference:
```
from vapor import session, renderer

path = "/glade/p/cisl/vast/vapor/data/Bugs/3345/"

ses = session.Session()
ses.Load(path + "3345.vs3")

image = ses.GetRenderers()[0]

v = image._params.GetValueDouble("_constantOpacityTag",0.0)
print("initial " + str(v))
ses.Render(path + "initial.tiff")

image._params.SetValueDouble("_constantOpacityTag","Set opacity value",0)
v = image._params.GetValueDouble("_constantOpacityTag",0.0)
print("zero " + str(v))
ses.Render(path + "zero.tiff")
```

**Comment by StasJ** [comment]
“_constantOpacityTag” is the variable name, not the tag name.

**Comment by sgpearse** [comment]
`image._params.SetValueDouble("_constantOpacityTag","Set opacity value",0)`

should be 

`image._params.SetValueDouble(RenderParams::_constantOpacityTag,"Set opacity value",0)`
