### ISSUE TITLE
Installer for Fedora operating system

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3348]
Currently, none of our linux installers can be used on a Fedora system. Leigh Orf indicated that in the past Ubuntu installers can be used on Fedora, but not anymore. Is it necessary to provide a Fedora installer?

**Comment by sgpearse** [comment]
@leighorf - Have you tried both the Ubuntu22 and 18 installers?  What version of Fedora are you using?

**Comment by leighorf** [comment]
I just tried the Ubuntu22 installer and it worked!! I am on Fedora 37. I am always within a few days of the latest kernel (I keep current with my weekly reboots!). So, this works w/out issue, I believe the older Ubuntu version was the one that failed.
