### ISSUE TITLE
Void / broken links for Python documentation ... https://www.vapor.ucar.edu/pages/pythonDocumentation.html

### ISSUE THREAD

**Issue by richlysakowski** [NCAR/VAPOR#3354]
Examples and Class Reference links are void: 
[Python Documentation](https://www.vapor.ucar.edu/pages/pythonDocumentation.html)

Links have been void for a while... Is there any plan to provide this? 

[Examples](https://vapor.readthedocs.io/en/readthedocs/pythonAPIReference/examples.html#)    
    Examples
    Coming soon.

[Class Reference](https://vapor.readthedocs.io/en/readthedocs/pythonAPIReference/classReference.html)
    Class Reference
    Coming soon.

**Comment by NihanthCW** [comment]
@richlysakowski Thanks for reaching out. Yes, the links will be updated within the next two weeks with our next release.

Meanwhile, you can access some example jupyter notebooks and python scripts provided with the package. You can find [instructions on how to access them here](https://www.vapor.ucar.edu/pages/vaporPythonDownloads.html)

Class references can be accessed through help
For instance for help on animation class:
`import vapor`
`from vapor import animation`
`help(animation)`

Please let us know if you have any further questions. We also welcome any other feedback on how we can improve documentation. Thank you!

**Comment by sgpearse** [comment]
Fixed.
