### ISSUE TITLE
Python documentation missing

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3366]
### Describe the bug
1. From the VAPOR official website, go to the documentation page: https://www.vapor.ucar.edu/pages/DocumentationPage.html
2. Click on python documentation, it's missing...

**Comment by NihanthCW** [comment]
@NihanthCW new url: https://ncar.github.io/VaporDocumentationWebsite/

**Comment by NihanthCW** [comment]
@shaomeng Should be fixed now.
