### ISSUE TITLE
dead kernel with Python API

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3367]
I keep running into "dead kernel" problems when trying out example python notebooks. Not sure if it's a VAPOR problem, or if I did something wrong, or if it's an Apple M1 issue. Anyway, here's the problem:

1. Install mini conda on an Apple M1 machine.
2. Follow steps here (https://www.vapor.ucar.edu/pages/vaporPythonDownloads.html) to create a new conda environment, and install vapor in the new environment.
3. Start a jupyter notebook inside of this environment. Navigate to the VAPOR folder that contains example notebooks (`~/miniconda3/envs/vapor_python/lib/python3.9/site-packages/vapor/example_notebooks`).
4. Open any example notebook, and try to run it. After 1 minute or 2, every notebook reports dead kernel, as the screenshot shows. It appears that the kernel will remain dead and not respond afterwards.

Note: the example notebooks work on Casper, so this is probably an Apple M1 issue. 

<img width="1305" alt="Screenshot 2023-03-27 at 5 10 48 PM" src="https://user-images.githubusercontent.com/814885/228087401-f4e8e840-2ceb-457b-a6c2-51c9b02fc1d5.png">

**Comment by StasJ** [comment]
You are using the 3.8.0 release, not the current pre-release. This issue was addressed last week (Issue #3359 and PR #3358).

**Comment by shaomeng** [comment]
I see. Is there a way to test the per-release?

**Comment by NihanthCW** [comment]
Update: Will verify after the release

**Comment by NihanthCW** [comment]
As per [comment](https://github.com/NCAR/VAPOR/issues/3367#issuecomment-1486041985) above
