### ISSUE TITLE
Verify documentation links

### ISSUE THREAD

**Issue by NihanthCW** [NCAR/VAPOR#3368]
### Describe what needs to be documented.
- There are numerous links that show up in a google search that still point to old documentation pages. Ensure there aren't any stray documentation links pointing to readthedocs pages that might confuse users. 
- Example: https://vapor.readthedocs.io/en/readthedocs/ 

### Is the documentation missing?
No

### Is the documentation there but needs improvement?

*Please provide the url of the documentation.*
Yes

**Comment by NihanthCW** [comment]
@sgpearse will explore options.

**Comment by NihanthCW** [comment]
I think this is working great Scott! Thank you. 
We can add a project 3.8.3

**Comment by StasJ** [comment]
Still among top results
- https://readthe ----- docs.org/projects/vapor/
- https://www.yum ----- pu.com/en/document/view/6709839/getting-started-with-vapor-and-wrf-vapor-ucar

(Links are intentionally broken to prevent this post from boosting their relevance)

**Comment by sgpearse** [comment]
@stasj - https://www.vapor.ucar.edu is the top search result for me.  Do you know of anything else we can do about this?

**Comment by StasJ** [comment]
> @StasJ - https://www.vapor.ucar.edu is the top search result for me. Do you know of anything else we can do about this?

It is as well for me but the others are in the top 5.

**Comment by sgpearse** [comment]
I'm rather certain that this is a web-crawler issue and suspect there's personalized Search Engine Optimization voodoo.  The 404'd readthedocs pages are ~20 results from the top for me.  In other words, I don't think there's anything more we can do here.
