### ISSUE TITLE
Pathline render bug

### ISSUE THREAD

**Issue by leighorf** [NCAR/VAPOR#3372]
### Describe the bug

It is best shown:
https://youtu.be/PUIZ4ZbNPAA

In short, all pathline renderings have missing surfaces

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [x] Did you get wrong results?

It's a rendering bug/artifact, VAPOR did not crash, it just looks bad.

**Impact**
- [ ] High - User productivity significantly degraded
- [ X] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
Steps to reproduce the behavior. For example:

Render some pathlines... for me, this always happens.

### Desktop
 - OS and version: Fedora 37, up to date
 - Version: 3.8.2

**Comment by sgpearse** [comment]
@leighorf - What graphics card are you using and can you provide a sample of your data?

**Comment by shaomeng** [comment]
Hey @leighorf , could you share a subset of your data so we can try to reproduce and investigate?

**Comment by shaomeng** [comment]
To be more specific, in this screenshot, what should be tubes are missing half the triangles. I'll assign @StasJ  to look at this together with me. Also, @leighorf , is it possible for you to provide a few data files that triggers this bug?

![image](https://github.com/NCAR/VAPOR/assets/814885/d4260995-10c2-4b7c-9bae-51face2ed3c6)

**Comment by leighorf** [comment]
Well, now I can't reproduce it either. I upgraded to Fedora 38 today, that may have done it? I get nice predictable behavior now. I am going to close this issue.
