### ISSUE TITLE
Downloadable item unclear

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3381]
There are many downloadable items released. Some are obvious from their names, e.g., the ones with OS names. Some are unclear, e.g., the ones with different hash numbers. 

I suggest that we either document what these downloadables mean and which one to choose for different purposes, or remove the ones with different hash numbers.

**Comment by sgpearse** [comment]
@sgpearse will remove the python API installers from the 3.8.1 release.  Our team will then rely only on conda for user distributable packages.

**Comment by shaomeng** [comment]
No longer applicable.
