### ISSUE TITLE
Particle render auto-region issue

### ISSUE THREAD

**Issue by davidedelvento** [NCAR/VAPOR#3388]
I am not sure if this is operator error or actual bug, sorry if it's the first.

I am trying to do a particle render for a dataset in which the particles are initially close and then diffuse at increasing distances. What happens is that the rendering changes the bounding box at each time step and it is basically unusable. Something similar (actually worse) happens if you replace the random initial positions in the example generating DCP to all zeros.

It seems to me that at each time step the Geometry->Region values for the bounding box are changed in a way that would make sense for that specific time step, but it doesn't for the whole rendering (especially considering that it does not automatically move the camera accordingly, but even if it did it could still be too choppy).

I can't figure out if it's possible to manually set a region that would work for all the time steps (trying to do so in the  Geometry->Region  GUI is not possible in that the values have maxima that one cannot override).

Perhaps a possible workaround would be to define 8 dummy particles at the edge of the desired bounding box (assuming that no other particle gets out), but I have not tried that. It would have the downside that one has to change the whole dataset just for changing that bounding box, which is not ideal.

Am I missing something or otherwise using the tool incorrectly?

**Comment by sgpearse** [comment]
Hi Davide, good to hear from you again and glad you're using Vapor.

I think this is related to an old enhancement that we never got around to, #433.  Now that you've brought it back up I think we'll put some more priority into this.  We will discuss this in our meeting tomorrow and update this ticket accordingly.

Thanks for the feedback!

**Comment by davidedelvento** [comment]
Thank you for the very quick response, Scott, and nice to hear from you too.

Yes, #433 would probably solve my problem, but in my case something much easier will do: I can live with a fixed domain, if there were a way to specify it. If my understanding is not too off, that may be allowed by a GUI option to fix the region for the whole animation (without changing it at each time step) and allowing to select limits outside of the (current) max/min values.

Thanks again

**Comment by sgpearse** [comment]
Thanks again for reaching out on this Davide.  This problem turns out to be more complicated than I originally thought, and we need to put some thought into the problem.  I'm not aware of an easy workaround either, sorry.  I'll let you know if we come up with one.  Meanwhile you should be notified when there are updates on this thread.

**Comment by davidedelvento** [comment]
For people who may be reading this and having a similar problem, here is my workaround.

I've just added 8 particles to all time steps of my dataset. I placed those 8 particles at the vertices  of my intended bounding box. I can make those particles stay in the same place for all time steps (which is what I want at the moment) or move them around with time. This is straightforward if I want my bounding box to be *larger* than the default which contains all the other particles in the dataset (which again is what I want at the moment). On the other hand, I would also need to remove the particles outside of the bounding box if I want to make it *smaller* (which I may want to do later, and is a bit more complicated to do, but not the end of the world).

> This problem turns out to be more complicated than I originally thought

Perhaps you can add a simple "filter" to the DCP files with a simple GUI where users can select parameters. The "filter" will add/remove particles similarly to what I describe above and everything should work. I understand if you don't want to do that, because I admit it'd be a hack and you may want to do it "the right way" instead. And perhaps the infrastructure to add such a filter might be more complicated than "the right way". If that is the case, maybe just a simple comment or a few line of code in the python example which generated the DCP could be "good enough" for people with such a burning need while you guys figure out what you actually need to do.

As far as I am concerned, you may now close this issue, but I'm fine if you want to keep it open to track such future work.

Thanks again.

**Comment by sgpearse** [comment]
Interesting workaround.  That indeed would work.

This problem goes beyond the particle renderer and into Vapor's Box class, which is fundamental to all renderers.  We're deliberating on what a good fix is.  #433 has been open since 2017 which is a testament to this being non-trivial.

We'll keep this ticket open for documenting the use cases that pertain to this issue.  Thanks again for pointing it out and for the workaround.

**Comment by NihanthCW** [comment]
@StasJ @sgpearse @sgpearse folks this has been addressed through #3425 , right?

**Comment by StasJ** [comment]
> @StasJ @sgpearse @sgpearse folks this has been addressed through #3425 , right?

Yes, mostly. The only remaining element is the domain will not automatically grow along with the particle domain. You can manually set the domain to be large enough to contain all timesteps and Vapor will now preserve that region, and move it together with the particle domain.
