### ISSUE TITLE
Warn users when a new session is opened while working in an current active session 

### ISSUE THREAD

**Issue by NihanthCW** [NCAR/VAPOR#3391]
### Is your feature request related to a problem?
I see that VAPOR auto saves the current session. However, I would expect the software to warn the me when I attempt to open a new session while already working in an existing session. 

### Describe the solution you'd like.
I accidentally opened a new session and VAPOR opened one without any prompts. Unfortunately, the auto save did not capture all my changes. A simple warning pop-up when someone opens a new session would have prevented this. 

**Impact**
(*Please click check boxes AFTER submitting ticket*)
- [X] High - User productivity significantly improved
- [ ] Medium - User productivity partially improved
- [ ] Low - User productivity trivially improved

**Comment by StasJ** [comment]
Vapor already does this but it is disabled for debug builds.

<img width="448" alt="ss" src="https://github.com/NCAR/VAPOR/assets/2772687/084833f1-8487-473a-aa22-38a2630c90e4">

**Comment by NihanthCW** [comment]
Yes! I see it. I was using the application built from source previously. Thanks!

**Comment by NihanthCW** [comment]
Yes! I see it. I was using the application built from source previously. Thanks!
