### ISSUE TITLE
Being able to share a session file with someone such that they can apply it to their own data

### ISSUE THREAD

**Issue by leighorf** [NCAR/VAPOR#3400]
Session files appear tied to input data files in a way such that a session file cannot be applied to another dataset. Feature request: The ability to apply a session file to an existing dataset (such as by opening the session file after NetCDF data has been imported into vapor), and/or the ability to, when opening a session file, getting a prompt that asks whether they want to open the data specified within the session file, or to open another set of files. The idea is that all the opacity curves, homemade colormaps etc. could be applied to another dataset, but not requiring the original data.

**Comment by Padanian** [comment]
+1

**Comment by sgpearse** [comment]
Duplicate of #3399
