### ISSUE TITLE
Bundle libomp with MacOS 3rd party libraries

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3418]
To build Vapor on MacOS with support for OpenMP, developers need to acquire libomp from macports.  Using brew or other means breaks the build.  Ideally, this library would be included in our 3rd party library bundle.

**Comment by shaomeng** [comment]
It's possible to build libomp by ourselves and bundle with MacOS 3rd party libraries, but CMake will have a hard time finding it using the current `find_package` directive in CMakeLists.txt.

One solution is to abandon the use of `find_package` directive in CMakeLists.txt, but that'll introduce a  branch in CMakeLists.txt to have different approaches to find openmp on different platforms. It's less consistency.

Balance those considerations, I think it's still the best to use libomp from llvm.

**Comment by sgpearse** [comment]
> Balance those considerations, I think it's still the best to use libomp from llvm.

@shaomeng - do you mean the LLVM distribution that's provided by macports, which we are currently using?

**Comment by shaomeng** [comment]
> > Balance those considerations, I think it's still the best to use libomp from llvm.
> 
> @shaomeng - do you mean the LLVM distribution that's provided by macports, which we are currently using?

Yes, this is what I meant.
