### ISSUE TITLE
Jupyter kernel dies when it can't find data

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3429]
When we load a session that has missing data in Vapor's GUI we get an error message indicating the problem, but when loading the session in the API, the kernel dies without indicating what's wrong.

To reproduce, run the following script along with the attached session file that shouldn't find the targeted dataset.
```
from vapor import session
ses = session.Session()
ses.Load("/Users/<username>/Downloads/atpescA.vs3")
ses.Render("test.png")
```
[atpescA.vs3.zip](https://github.com/NCAR/VAPOR/files/12344935/atpescA.vs3.zip)

**Comment by NihanthCW** [comment]
@sgpearse I don't think #3429 is merged/ included in 3.9.
