### ISSUE TITLE
What is the best practice when working with multiple VDC files at a time

### ISSUE THREAD

**Issue by ogressel** [NCAR/VAPOR#3446]
### Describe what needs to be documented.
When working with multiple VDC files at a time, what is possible (and what should be avoided) in terms of colliding variable names between the files. Can this be solved by specifying distinct dataset paths/names/labels in the vdccreate tool? 

### Is the documentation missing?
Honestly could not find anything on this. When I load two VDC files that both have a variable called "rho", VAPOR produces a segfault (v3.8.1 on Ubuntu 22.04).

**Comment by sgpearse** [comment]
@ogressel - When you have multiple VDC datasets, you should load them separately.  After that, you will be able to create new renderers that target one VDC dataset or another.  The renderer's target dataset can be picked in the New Renderer dialog.

That said, Vapor should not be crashing.  I'll add the Bug label to this ticket.  Please correct me if these are not the steps that are leading to the crash and add any other information that you think would b e helpful.

To reproduce:
1) Load two VDC datasets simultaneously.  These datasets may need to have like-named variables.

**Comment by sgpearse** [comment]
@sgpearse will add a note in the documentation that datasets need to be loaded on an individual basis

**Comment by sgpearse** [comment]
Fixed.
