### ISSUE TITLE
`conda index` being deprecated

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3447]
When running the python API platform tests on ubuntu, I'm unable to index my channel according to [our instructions](https://ncar.github.io/VaporDocumentationWebsite/contributingToVapor/codeContributions.html#building-vapor-s-python-api-from-source) due to a deprecation error.  Conda is at version 23.7.3.

(3.9.0.aug29) vapor@vapor-Precision-Tower-5810:~$ conda index channel           
/home/vapor/miniconda3/envs/3.9.0.aug29/bin/conda-index:11: DeprecationWarning: conda_build.cli.main_index.main is deprecated and will be removed in 4.0.0. Use `conda index` instead.                                  
  sys.exit(main())

![image](https://github.com/NCAR/VAPOR/assets/9522770/b6bbdbed-0d07-4f54-a957-c69b81b2f77b)

**Comment by sgpearse** [comment]
The issue exists with mamba as well.

![image](https://github.com/NCAR/VAPOR/assets/9522770/641d1f50-2396-4ea1-921c-268f36839285)

**Comment by sgpearse** [comment]
On a fresh Ubuntu 22 installation:

![image](https://github.com/NCAR/VAPOR/assets/9522770/4789fbff-179a-4d26-9eba-ff75df82d66b)

**Comment by StasJ** [comment]
I could not reproduce this. I used a fresh conda install and made sure to have the latest version of conda-build.

In any event, this is a Conda issue unrelated to Vapor.

**Comment by sgpearse** [comment]
https://github.com/conda/conda-build/issues/4993
