### ISSUE TITLE
Mamba index does not work on Casper

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3452]
Using a fresh Mamba installation on Casper and also following instructions [here](https://ncar.github.io/VaporDocumentationWebsite/contributingToVapor/codeContributions.html#installing-the-conda-image), Step 3 issues error.

![image](https://github.com/NCAR/VAPOR/assets/814885/ade9c732-ada0-471d-8c47-22d52a420f13)

**Comment by sgpearse** [comment]
@shaomeng - Ubuntu20/22 are giving a different error, but I've managed to get around it by backing out my conda-build version to 3.24.0.  Can you give this a try?

`mamba install conda-build=3.24`

PS - It looks like you're in your base environment.  You should consider creating a new one for each round of tests we do.

**Comment by shaomeng** [comment]
Close it since "will not fix".
