### ISSUE TITLE
Fix incorrect citation info on Zenodo

### ISSUE THREAD

**Issue by NihanthCW** [NCAR/VAPOR#3454]
Citation information on[ Zenodo VAPOR page](https://zenodo.org/record/7779648) is incorrect.

**Comment by sgpearse** [comment]
Need to fix share as / cite as

![Screen Shot 2023-09-05 at 11 53 18 AM](https://github.com/NCAR/VAPOR/assets/9522770/7d389fc9-cce4-4c90-ad21-e9f7ae4e5b62)
