### ISSUE TITLE
Vapor 3.9.0 macOS ARM download doesn't contain an arm version

### ISSUE THREAD

**Issue by suschizu** [NCAR/VAPOR#3461]
### Describe the bug
the download https://github.com/NCAR/VAPOR/releases/download/v3.9.0/VAPOR3-3.9.0-DarwinARM64.dmg does not contain an ARM version - only another intel build

<img width="263" alt="Screenshot 2023-09-08 at 17 54 47" src="https://github.com/NCAR/VAPOR/assets/16004333/ddb29e9a-7348-4fed-a343-3fdb1b56dbd1">

**Impact**
- [x] Low - User productivity trivially degraded

### To Reproduce

`file [path/to/binary] > Mach-O 64-bit executable x86_64`

### Desktop
 - Ventura 13.5.2
 - Version: [e.g. Vapor 3.9.0]

**Comment by sgpearse** [comment]
Hi, you are correct.  We are currently working on getting Vapor's MacOS arm64 version codesigned, so users will still need to run Vapor through Rosetta.  The only difference between the arm64 and x86 versions is that Ospray is omitted from arm64 due to it crashing.

**Comment by suschizu** [comment]
thanks for the fast answer!

**Comment by sgpearse** [comment]
@suschizu - PS, if you'd like a native M1 build, you can find one [at this link](https://drive.google.com/file/d/1DrlegKfuFxubkED0NEDlRFE8ZudGZph5/view?usp=drive_link).  Note that after you install it, Apple will report the application as damaged.  You will need to run the following command to get past Gatekeeper's safeguard:

`sudo xattr -rds com.apple.quarantine /Applications/vapor.app`
