### ISSUE TITLE
Add seed bias variables for x, y, and z axes, and add "Random Seed" feature from Vapor2

### ISSUE THREAD

**Issue by vema1818** [NCAR/VAPOR#3472]
(Striking out to separate two issues - See #3473)
~~I am facing the following issue in VAPOR3.9~~

~~**raw2vdc: /usr/local/exelis8.5.1/idl85//bin/bin.linux.x86_64/libcurl.so.4: no version information available (required by /home/vema/VAPOR39/lib/libproj.so.19)**~~

~~which is not arising with VAPOR3.4 . Here I am putting raw binary data created by IDL into VDC file. Both Ubuntu 20.** 22.** versions, this issue is arising.~~

In VAPOR2 version, the seed points are biased by upto three variables. Also, there is an option to vary random number generator so that the seeds represents well with the desired magnetic structure. I wish to preserve these two features in the new VAPOR3.9 version.

**Comment by sgpearse** [comment]
Thanks for reporting this, but I'm unable to reproduce it on my Ubuntu20/22 machines.  Could you provide the full commands you're issuing (including vdccreate) and their output, and perhaps a sample file so I can try to do exactly what you're doing?

> In VAPOR2 version, the seed points are biased by upto three variables

Yes, you are correct.  Could you please write an "Enhancement" ticket for this?  When our users file this kind of ticket (rather than a Vapor developer) they are more likely to get implemented.

> Also, there is an option to vary random number generator so that the seeds represents well with the desired magnetic structure. I wish to preserve these two features in the new VAPOR3.9 version.

I am not familiar with this feature from Vapor2.  Could you elaborate?  I thought "Random Rake" was purely a randomized distribution.  If a screenshare would help, let me know.

**Comment by vema1818** [comment]
Thank you Pearse for reading my issue and commenting it.

> Thanks for reporting this, but I'm unable to reproduce it on my Ubuntu20/22 machines. Could you provide the full commands you're issuing (including vdccreate) and their output, and perhaps a sample file so I can try to do exactly what you're doing?

This could be specific to my system. The problem can related to libcurl.so.4 which is soft linked to higher version in the later versions in Ubuntu 22.04. A dirty solution for this is that I use VAPOR3.4 version for writing master .vdc file and then VAPOR3.9 version for visualisation. 

> 
> > In VAPOR2 version, the seed points are biased by upto three variables
> 
> Yes, you are correct. Could you please write an "Enhancement" ticket for this? When our users file this kind of ticket (rather than a Vapor developer) they are more likely to get implemented.
> 
> > Also, there is an option to vary random number generator so that the seeds represents well with the desired magnetic structure. I wish to preserve these two features in the new VAPOR3.9 version.
> 
> I am not familiar with this feature from Vapor2. Could you elaborate? I thought "Random Rake" was purely a randomized distribution. If a screenshare would help, let me know.
Kindly see the attached rendering screenshot on VAPOR2.6 to understand the issue. Seed dist. field can be biased upto variables. And therese was a provision to vary random seed to  until there was a desired magnetic structure. This kind of magnetic structure is typical in solar active regions, and such a rendering for twisted field is on high demand in solar magnetic field . Please see a detailed analysis in [P. Vemareddy, 2019, ApJ, 872, 182](https://iopscience.iop.org/article/10.3847/1538-4357/ab0200/pdf)

**Comment by vema1818** [comment]
<img width="1160" alt="Screen Shot 2023-09-27 at 11 19 57 PM" src="https://github.com/NCAR/VAPOR/assets/54621569/41c5df99-2985-4f01-95c2-1c44f411a7c7">

**Comment by sgpearse** [comment]
@vema1818 - I'm going to break this post up into a bug report at #3473 for the raw2vdc issue, and change this ticket to an enhancement so we can solve these problems separately.

**Comment by vema1818** [comment]
@sgpearse ok then. Please consider the suggested inclusions of random seed in the further developments.

**Comment by vema1818** [comment]
Hi @shaomeng , thanks for reading my issue. At a single instant of time, one can check the most suitable magnetic structure by  applying bias to random number generator. In addition, the random number generator can be varied by hand instead of a default value (zero I think).  Once this exercise is done, the same seed points be tracked in time as per evolution. 

In the current version of the vapor, number of bias variables are reduced to one, and no option to vary random number seed. Why it was so I have no clue. Hopefully I am clear now. You can download vapor 2.8 version and check these.

**Comment by shaomeng** [comment]
Hi @vema1818 I see what you mean. I think it's pretty trivial to add a manual selection of random number generator seed. 

If I understand correctly, the "number of bias variables" is a very different issue from the random number seed generator, is it right? If so, could you explain a bit more what does it mean to have 3 bias variables? I can understand how one variable influences the seeds---the strong the variable is at a spatial subvolume, the more likely trajectory seeds are placed in this subvolume. How can 3 variables influence the seeds simultaneously?

**Comment by vema1818** [comment]
@shaomeng, one variable bias may be useful if one is satisfied with it. How the three variable bias is implemented I have no idea, but in my previous applications, I found it very useful. For example, in the published paper, I use three variable bias (jtot, bx, by) then a suitable structure was found. If one dont want three variables, they can be kept to the same variable, similar to existing option.

On top of three variable bias, changing the random seed, one can arrive at most suitable distribution of seed points. All these options are quite useful enabling the user to look around all available options to visualise the most suitable magnetic configuration. Don't you see now that how vapor 2.8 (or earlier versions) is developed with a multiple options. 

What I want to say is that the present config of vapor regarding seeds selection is narrowed down to very fewer options. 

May be you can see the source code of VAPOR 2.8 in order to get to know on their implementation.

**Comment by vema1818** [comment]
@shaomeng, in order to explain more why I (solar physics in particular) need three bias variables and with an option of variable random seed, I have to explain more on the observational aspects of solar magnetic fields and the surrounding plasma emission which I think beyond the scope of your domain. But please understand the need of more flexible options available.

**Comment by vema1818** [comment]
@shaomeng thank you. The requirement of three variables mostly comes from people studying the solar magnetic fields. One variable bias can have probabilistic seed points at one region, like that representation of seed points from different regions could be due to different derived variable. A combination of all of these variables better resembles in the cases I studied. I have no problem if the developer doubts the usage, still I can use VAPOR 2.8 version until I find an alternative solution. But just remember these two requirements (random seed option & three variables), you may realise soon or later their importance. 

By the way, #3480 enhancement is due to me only. You can discuss this points with some known solar researchers. We can discuss it more on live with an example case I have.

**Comment by clyne** [comment]
@vema1818 if multiple bias variables were specified in VAPOR2, their magnitude was calculated and used to generate seed points based on the value of the bias. The reason the ability to specify multiple bias variables was removed in VAPOR3 is because the identical behavior can be obtained by simply computing a derived variable representing the field magnitude using VAPOR3's built in Python calculation engine.

**Comment by sgpearse** [comment]
@vema1818 - We will be tracking this issue on issue #3480
