### ISSUE TITLE
Potential issue with raw2vdc on Ubuntu

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3473]
Posted by @vema1818 on this thread.  I'm breaking his post into a bug report (here) and an enhancement request at #3472.

> I am facing the following issue in VAPOR3.9
> 
> raw2vdc: /usr/local/exelis8.5.1/idl85//bin/bin.linux.x86_64/libcurl.so.4: no version information available (required by /home/vema/VAPOR39/lib/libproj.so.19)
> 
> which is not arising with VAPOR3.4 . Here I am putting raw binary data created by IDL into VDC file. Both Ubuntu 20.** 22.** versions, this issue is arising.

Reply by @sgpearse:

> Thanks for reporting this, but I'm unable to reproduce it on my Ubuntu20/22 machines. Could you provide the full commands you're issuing (including vdccreate) and their output, and perhaps a sample file so I can try to do exactly what you're doing?

Reply from @vema1818:

> This could be specific to my system. The problem can related to libcurl.so.4 which is soft linked to higher version in the later versions in Ubuntu 22.04. A dirty solution for this is that I use VAPOR3.4 version for writing master .vdc file and then VAPOR3.9 version for visualisation.

**Comment by vema1818** [comment]
@sgpearse Let me be clear what I did. First I wrote the binary files in IDL for each variable through

     openw, lun, 'bx.bin', /get_lun        (with / without /stdio option both gives the error)
     writeu, lun, bx   
     close,lun

then try to run the raw2vdc 
   raw2vdc -ts 1 -varname bx bb_master.vdc bx.bin

then you get the error as
   raw2vdc: /usr/local/exelis8.5.1/idl85//bin/bin.linux.x86_64/libcurl.so.4: no version information 
   available (required by /home/vema/VAPOR39/lib/libproj.so.19)

this error is not arising not  with VAPOR 3.4. It appears for me that there must be some information that goes into binary file created by IDL, which is not syncing with build version of VAPOR3.9 . 

With these details, one can reproduce the error.

**Comment by sgpearse** [comment]
Thank you @vema1818.  Is there a way you could provide bx.bin, and also the terminal output of the command `ldd raw2vdc`?

**Comment by vema1818** [comment]
> Thank you @vema1818. Is there a way you could provide bx.bin, and also the terminal output of the command `ldd raw2vdc`?

Please download the [bx.bin](https://www.iiap.res.in/people/personnel/vemareddy/bx.bin) [by.bin](https://www.iiap.res.in/people/personnel/vemareddy/by.bin) [bz.bin](https://www.iiap.res.in/people/personnel/vemareddy/bz.bin)  and please use the following commands

vdccreate -numts 1 -dimension 192x192x120 -extents -13.9:-13.9:0.0:13.9:13.9:17.5 -vars3d bx:by:bz bb_master.vdc
raw2vdc -ts 1 -varname bx bb_master.vdc bx.bin
raw2vdc -ts 1 -varname bx bb_master.vdc by.bin
raw2vdc -ts 1 -varname bx bb_master.vdc bz.bin

and the output of ldd raw2vdc is as follows 

        linux-vdso.so.1 (0x00007ffd383d2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa7b9a00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa7b9cdb000)

Hopefully this may help to identify the issue

**Comment by sgpearse** [comment]
Works now with AppImage.
