### ISSUE TITLE
Flow random number generator seed selector

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3480]
In flow renderer with randomly generated seeds, there's a *seed* for the random number generator used internally. (Note not to be confused with the seed of a flow line.) The same seed will result in the same random numbers, no matter how many times one attempts to generate random numbers. Some users, however, find it useful to have a manual selector to specify the random number generator seed, as requested [here](https://github.com/NCAR/VAPOR/issues/3472)

**Comment by sgpearse** [comment]
@vema1818 - Could you please confirm that this is the desired behavior discussed in #3472?  Thank you!

**Comment by vema1818** [comment]
> @vema1818 - Could you please confirm that this is the desired behavior discussed in #3472? Thank you!

Yes, Is it solved? 
Also, I wish to bring to your notice on coloring field lines based on variable at bottom boundary. Means, the entire field line is of one color on a colorbar scaled by the variable at a plane say z=0. How to do this? Anyway to do it?
