### ISSUE TITLE
Failed to install 'vapor' using conda

### ISSUE THREAD

**Issue by littlebig-balala** [NCAR/VAPOR#3497]
I am encountering an issue while trying to install the vapor library. The error message I receive is ‘Solving environment: failed with initial frozen solve. Retrying with flexible solve.’ I have seen suggestions on forums to use mamba for installation, but I still encounter the error ‘Could not solve for environment specs. The following package could not be installed - vapor does not exist (perhaps a typo or a missing channel).’ I have experienced this issue on both Ubuntu and Windows 10 environments. Could you please provide guidance on how to properly install this library? Thank you.
![image](https://github.com/NCAR/VAPOR/assets/53027914/5aa0039f-ff11-4058-b8a8-f3efb40683ca)

**Comment by sgpearse** [comment]
You could try using WSL.  If it works for you, please let us know!
