### ISSUE TITLE
Barb: color mapping with TSLB variable crashes

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#35]
To reproduce:
1. Load KatrniaMaster.nc
2. Create a Barb renderer
3. Switch to Appearance tab, select TSLB from the color mapping menu.
4. Vapor crashes.

**Comment by sgpearse** [comment]
All operations on TSLB seem to fail during calls to DataMgr::GetVariable().  This includes rendering in the contour renderer, plots, and generating statistics.

It may be helpful to note that this is the only variable in KatrinaMaster.nc using the coordinate variable 'soil_layers_stag'.  All others use 'bottom_top' for their vertical coordinate.

**Comment by sgpearse** [comment]
Since we've scaled back our requirements to only support 2D variables, and TSLB is a 3D variable, I'm going to close this.

Please let me know if you see it occur again.
