### ISSUE TITLE
Data Set interference? 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3509]
It appears that the following two data sets interfere with each other:
1.  `CAM/Gaussian`
2. `WRF/Katrina`

### Good behavior:
1. Load `CAM/Gaussian` 
2. Create and enable an Image Renderer.
3. The Image Renderer shows the entire globe.

### Bad behavior:
1. Load `WRF/Katrina`
2. Load `CAM/Gaussian` 
2. Create and enable an Image Renderer **based on `CAM/Gaussian`** 
3. The Image Renderer shows bad rendering, as the screenshot illustrates.
![Screenshot from 2023-12-20 14-06-06](https://github.com/NCAR/VAPOR/assets/814885/c190c416-b346-4607-a7d5-f8dcfdc3cbdc)

**Comment by NihanthCW** [comment]
This is intended behavior.
