### ISSUE TITLE
Installer for Centos 9

### ISSUE THREAD

**Issue by akrherz** [NCAR/VAPOR#3515]
I was hoping that the ubuntu-22 installer would work on Centos 9 (stream), but it failed to provide all needed libraries.  Could you kindly consider making a release build for Centos 9?

**Comment by NihanthCW** [comment]
Hello @akrherz, we'll discuss this in our meeting next week. We do need to determine how to handle linux installers since we've been getting requests for other distributions as well. If this is relatively easy, we might be able to create an installer for CentOS in the interim. I'll keep you posted. Thanks!

**Comment by sgpearse** [comment]
@akrherz Please watch #3518, which should allow you to build VAPOR on any Linux platform.

**Comment by sgpearse** [comment]
Also related to #3519

**Comment by sgpearse** [comment]
@akrherz - Could you try the installer linked below on your CentOS system?

https://output.circle-artifacts.com/output/job/9f32477b-787f-454e-8b0f-9f04364082e8/artifacts/0/tmp/workspace/installers/VAPOR-3.9.2-x86_64.AppImage

**Comment by akrherz** [comment]
> @akrherz - Could you try the installer linked below on your CentOS system?

Thanks.  This appears to be an executable that runs VAPOR and not an installer?  It does appear to run on centos 9 though.

**Comment by sgpearse** [comment]
It's called an AppImage bundle.  You should be able to run it from anywhere, even a USB stick.  Drag-and-drop is basically installation.  Glad to hear it's working.  Please let us know if you hit any snags!
