### ISSUE TITLE
DCP dataset containing a single particle crashes vapor

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#3526]
[particles_000.nc.zip](https://github.com/NCAR/VAPOR/files/14042872/particles_000.nc.zip)

**Comment by shaomeng** [comment]
There's no more crash, but not a single particle displayed too. Not sure if it's a bug or not, so I re-open the ticket to have the issue discussed.

**Comment by StasJ** [comment]
I believe the issue you raise is due to how vapor handles 0-volume datasets and is not specific to particles.

**Comment by shaomeng** [comment]
> I believe the issue you raise is due to how vapor handles 0-volume datasets and is not specific to particles.

It makes sense. I'm going to close the issue again.
