### ISSUE TITLE
Track renderer regions does not properly adjust the region if the dataset extents get larger without moving

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#3527]
This might be the case in a particle dataset

**Comment by StasJ** [comment]
Test:
1. Import both timesteps in `Bugs/3527` on glade
2. Add/enable a particle renderer
3. The particle renderer domain should continue encompass the entire data domain when changing timesteps.

**Comment by shaomeng** [comment]
VAPOR crashes when following the steps above to advance time steps.

**Comment by StasJ** [comment]
Do you have any additional steps to reproduce the crash? It works for me.

**Comment by shaomeng** [comment]
> Do you have any additional steps to reproduce the crash? It works for me.

Hmm, really no additional steps. To be clear, it renders particles at step 0 when the particle renderer is enabled. It crashes upon clicking on the "next step" button. Could @sgpearse @NihanthCW  see if they can reproduce the issue?

**Comment by sgpearse** [comment]
I am reproducing the crash on casper when following the steps above :(

**Comment by StasJ** [comment]
I tested the appimage installer and it does crash on casper. I also tested the old-style installer (https://app.circleci.com/pipelines/github/NCAR/VAPOR/7362/workflows/d68ca9a2-ec1d-4f95-9cde-8b41664c4b46/jobs/18309) generated for the last 3.9.2 code commit (991dcb0b1ac75190f2212031ae01030ba45c03f3) on casper and it does not crash. Either way, investigating this further probably will depend on #3551
