### ISSUE TITLE
3rd party libraries on Casper

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3551]
The third party libraries got deleted with the removal of /glade/p.  We need to regenerate them.

**Comment by shaomeng** [comment]
they are kept in `/glade/campaign/cisl/vast/vapor/third-party/current` 

you will need to issue two commands before compiling:
`module --force unload ncarenv`
`export LD_LIBRARY_PATH=${THIRD_PARTY_DIR}:$LD_LIBRARY_PATH`
where `THIRD_PARTY_DIR` is `/glade/campaign/cisl/vast/vapor/third-party/current`
