### ISSUE TITLE
Vapor build instructions on Ubuntu 22 not working

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#3564]
Following the provided instructions and using the Ubuntu 22 third party libraries linked in the documentation, on a clean Ubuntu 22 system vapor will build but fail to run

<img width="777" alt="s" src="https://github.com/NCAR/VAPOR/assets/2772687/4813568a-cf4e-4838-9e6d-8b902ba68237">

**Comment by StasJ** [comment]
This appears to be limited to VMs

**Comment by sgpearse** [comment]
Closing, since we have updated the libraries and the issue does not present itself on our test systems.
