### ISSUE TITLE
file selector issues on SUSE (Casper)

### ISSUE THREAD

**Issue by NihanthCW** [NCAR/VAPOR#3576]
related to #3294 

Selecting multiple files/ selecting any files on casper is very finicky. Being a critical part of the workflow this is a major painpoint for our users. Also one wrong click and they'd need to wait a minute or two for large datasets before they can retry.

To reproduce (On Casper):
- Open VAPOR
- Import any dataset
- Select multiple files/ any file. Single click acts as a double click. 

This issue does not occur on other platforms.

**Comment by sgpearse** [comment]
Unfortunately Qt uses the operating system's file dialogs, and this is is how SUSE chooses to operate.  We had the same problem with CentOS on casper, as per #3294.

**Comment by NihanthCW** [comment]
I see... I am hesitant with the workaround primarily due to how prevalent the issue is how it impacts everyone using VAPOR on casper.
Is there another workaround besides using the keyboard? Any system settings that could be changed to get the desired behavior?

**Comment by sgpearse** [comment]
Actually I do see an option for this under:

System Settings → Workspace Behaviour → General Behaviour - Clicking files or folders…

I was able to persist these settings across two different VNC sessions so this looks like the better workaround.

**Comment by NihanthCW** [comment]
In lieu of #3580

**Comment by sgpearse** [comment]
Rejecting since it's an OS setting on Casper that goes beyond Vapor's scope.
