### ISSUE TITLE
Volume Renderer memory error on Casper

### ISSUE THREAD

**Issue by NihanthCW** [NCAR/VAPOR#3596]
Volume Renderers not working on Casper. OsPray seems to be the only option on Casper.

- When I download the installer manually and run VAPOR, I don't run into any problems.
- However, when I try to module load vapor (same version v3.9.2) and create a volume renderer, I get the GL out of memory error

**Error log**
Error performing paint event
OpenGL Error: GL_OUT_OF_MEMORY (#1285)

Redirecting Python IO
Your device appears to either not have hardware graphics support, or not have graphics drivers configured correctly for your device.
Rendering performance may be significantly diminished, or in the case of some renderers, may not function at all.

Vapor 3.9.2.<debug>
OS: Linux 5.14.21-150400.24.46-default #1 SMP PREEMPT_DYNAMIC Thu Feb 9 08:38:18 UTC 2023 (2d95137)
Distro:
LSB Version:	n/a

**Comment by sgpearse** [comment]
Related to spack formula

**Comment by NihanthCW** [comment]
@StasJ This issue is resolved now. However, I am unclear which specific action helped resolve it. Could you please link / provide a one liner on what fixed this and close it? Thanks!

**Comment by StasJ** [comment]
That would be a question for Scott/Brian as it has to do with the SPACK build and vapor’s official installation on Casper, it is not something that was fixed in this repo. I was not looped into that conversation so I don’t know what changes were made.

**Comment by NihanthCW** [comment]
Tagging @sgpearse

**Comment by NihanthCW** [comment]
Updated [casper documentation](https://ncar-hpc-docs.readthedocs.io/en/latest/compute-systems/casper/remote-desktops/#example-vnc-session)
