### ISSUE TITLE
Image sequence capture produces low-quality images.

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3597]
Currently, when the user rotates the scene, the volume renderer uses a "fast mode" that produces renderings of low quality. This is typically a good idea, but it does also produce a sequence of images at low qualities when the user captures it. In such a use case (i.e., capture a sequence of images), almost always the user wants all images to have a high quality too.

**Comment by sgpearse** [comment]
Related to #3317 and #2230
