### ISSUE TITLE
Keyframing in Python

### ISSUE THREAD

**Issue by ifranda** [NCAR/VAPOR#3616]
Keyframing scripts in python can get pretty lengthy, especially when using more than 2 key frames. I'm not sure if this is something we're already thinking about, but it wouldn't be too difficult to add helper functions to our Python API to streamline this. 

Here's one way we could set it up:

`def animate_keyframes(session_paths, steps):`
session_paths is a list of paths to saved session files with the desired camera angles for each key frame.
steps is a list of the number of interpolated frames between each key frame.

![image](https://github.com/NCAR/VAPOR/assets/134353359/51d57b1e-4d49-4368-9f7d-a4c7f9cd6d4c)

Users can use the GUI to save their camera angles as key frames, then use Python to render an animation.

**Comment by ifranda** [comment]
Related to #3597, #3317, and #2230.

This could be a quick fix until we work on keyframing in the GUI.

**Comment by NihanthCW** [comment]
Related to the python Utilities module.

**Comment by ifranda** [comment]
Example usecase:

```
ses = session.Session()
data = ses.OpenDataset(dataset.WRF, ["data/wrfout_d02_2005-08-29_02.nc"])
iso = data.NewRenderer(renderer.VolumeIsoRenderer)

# The camera position of each keyframe
positions = [
    [-1190444.44426004, 1882360.85954653, 770176.40842364], # Keyframe 1
    [-1172384.15238047, 2813172.26639064, 355291.41877028], # Keyframe 2
    [-968784.32993129, 3056725.58106798, -34317.16158186] # ...
]

# The camera target for each keyframe
targets = [
    [-420811.28125, 2737271.75, 5699.78515597], # Keyframe 1
    [-420811.28125, 2737271.75, 15699.78515597], # ...
    [-420811.28125, 2737271.75, 15699.78515597]
]

# The up vector for each keyframe
ups = [
    [0.41853764, 0.35630071, 0.83538976],
    [ 0.39861183, -0.08972356, 0.91272027],
    [-0.08058301, 0.02890014, 0.99632884]
]

# Save keyframes
sessions = []
for i, position, target, up in zip(range(1, len(positions)+1), positions, targets, ups):
    ses.GetCamera().LookAt(position, target, up)
    keyframe = f"keyframe{i}.vs3"
    sessions.append(keyframe)
    ses.Save(keyframe)


from vapor.utils import keyframing
anim = keyframing.animate_camera_keyframes(sessions)
anim.Show()
```

In practice, it is easier to save the keyframes by using the jupyter widget instead of specifying the camera angles manually
