### ISSUE TITLE
Volume Renderer taking >32GB memory on a 0.4GB data file

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3618]
WRF file `/glade/campaign/collections/rda/data/ds559.0/wy2022/202110/wrf2d_d01_2021-10-01_00:00:00.nc` is ~0.4GB on disk. Its 3D variables are at a resolution of  `1367x1015x4`. After importing it to VAPOR and enabling a volume renderer, CISL-VAPOR (Ubuntu 22.04, 32GB memory) hangs because of VAPOR consuming all the memory.

There seems to be serious memory issues in VAPOR. Even if a machine equipped with more memory is able to successfully render this data set, the ratio between data/memory size prohibits volume rendering a moderately big file.

**Comment by NihanthCW** [comment]
Question: Is Ospray enabled?

**Comment by shaomeng** [comment]
> Question: Is Ospray enabled?

This behavior was observed using the "Curvilinear" renderer, not the Ospray renderer.

**Comment by StasJ** [comment]
I tested this on my mac and vapor used about 1.3GB of RAM to volume render this file. It was running very slow, however, and this is due to the shape of the cells. Here is a part of a single row of cells:
![s](https://github.com/NCAR/VAPOR/assets/2772687/6a7115f1-c0ee-4c48-899b-01180e02aff4)

**Comment by StasJ** [comment]
This dataset also appears to be incorrectly marked as curvilinear and can be rendered in real-time using the Regular volume rendering algorithm.

**Comment by NihanthCW** [comment]
@StasJ @shaomeng If this is resolved/ is an issue with the specific use case, we can close this issue.

**Comment by shaomeng** [comment]
> @StasJ @shaomeng If this is resolved/ is an issue with the specific use case, we can close this issue.

You know what, VAPOR (3.9.2 installer) doesn't show any 3D variables on Casper and MacOS, so I cannot verify the reported issue on these 2 platforms. Seems weird to me and seems there's something else going on in VAPOR, but this particular issue is at a "not verifiable" state for me.

@StasJ , you seem to be able to create a volume renderer based on this file on MacOS. Did you use the 3.9.2 installer, or a custom build?

**Comment by StasJ** [comment]
It works when building from source.
