### ISSUE TITLE
pythonAPI fails to install on M1

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3649]
Using conda 24.5.0, I get the following error when using the test installer generated on July 31 (used in both Aug1 and Aug5 installer spreadsheets):

```
(base) cisl-ridgeland:~ pearse$ conda activate 3.9.3aug5
(3.9.3aug5) cisl-ridgeland:~ pearse$ conda index ~/channel/
(3.9.3aug5) cisl-ridgeland:~ pearse$ conda install -c file://Users/pearse/channel/ vapor
Channels:
 - file://users/pearse/channel
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides cppyy 2.2.* needed by vapor-3.9.3-hcb8d3e5_0

Could not solve for environment specs
The following package could not be installed
└─ vapor is not installable because it requires
   └─ cppyy 2.2.* , which does not exist (perhaps a missing channel).

(3.9.3aug5) cisl-ridgeland:~ pearse$
```

**Comment by ifranda** [comment]
Hmmm that's odd! @StasJ mentioned that the the linux installer I built was in debug mode, is the same thing happening here? Here is what it looks like on my M1, the only difference I can see is that I have the ncar-vapor channel:

![image](https://github.com/user-attachments/assets/4224492a-8cff-4f61-97cc-8a527faaf172)

**Comment by sgpearse** [comment]
Thanks Ian, adding conda-forge did the trick.

I'm going to make a ticket in for our documentation to add this step to the "Installing the conda image" portion since this step is in the "Building the conda image" portion, which not everybody is necessarily doing.  Something like the following, before step #5:

```
If you have not done so already, ensure that you have added the conda-forge channel:
conda config --add channels conda-forge
```
