### ISSUE TITLE
VAPOR notarization/verification on MacOS ?

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#3651]
The testing installer of VAPOR 3.9.3 for MacOS_x86 is still showing a "developer cannot be verified" message. I thought this message should be gone, since we have implemented the Apple notarization thing?
<img width="311" alt="Screen Shot 2024-08-07 at 4 04 01 PM" src="https://github.com/user-attachments/assets/0058a1e2-fe62-42c4-9762-e72d7c48ac1e">

The application is not able to start due to this behavior. 
The System Info is attached here:

<img width="698" alt="Screen Shot 2024-08-07 at 4 52 20 PM" src="https://github.com/user-attachments/assets/0c176128-304f-469a-8877-26317842d0a0">

Update: after right-click VAPOR from the application folder, VAPOR starts. However, it cannot load a data set successfully because of many messages like the screenshot below. Note that it complains `*.so` files, which are supposed to be Linux files. Also, it says the files are downloaded on June 6th, while I downloaded and reinstalled VAPOR (remove old VAPOR, install new VAPOR) on 8/8/2024.

<img width="372" alt="Screen Shot 2024-08-08 at 9 03 11 PM" src="https://github.com/user-attachments/assets/e6677807-0f3f-46de-b70b-04405957b8a2">

**Comment by sgpearse** [comment]
@shaomeng Regarding your first point, yes this is correct.  Next up for 3.9.4 is notorizing macOS x86 which requires reconfiguring our libraries and build system.

Regarding your second point, is this on an x86 system or appleSilicon through rosetta?

**Comment by shaomeng** [comment]
> 
> Regarding your second point, is this on an x86 system or appleSilicon through rosetta?
x86 macbook with the x86 installer.

**Comment by sgpearse** [comment]
@shaomeng Could you tag this thread with which x86 operating system you're using?

**Comment by shaomeng** [comment]
@sgpearse reports that this is a duplicate as #3641 , thus closing.
