### ISSUE TITLE
What is a Hello renderer

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#37]
I'm not sure what a Hello renderer is. Maybe we want to give it a better name...

**Comment by shaomeng** [comment]
We want to remove this renderer before we ship.

**Comment by shaomeng** [comment]
I cannot figure out where to hide this renderer. @clyne is jumping in...

**Comment by clyne** [comment]
The fix for this issue has introduced a regression: it is no longer possible to create some renderers.

To reproduce:
1. Load any data set
2. Try to create a TwoDData renderer. An image renderer is created instead.

**Comment by shaomeng** [comment]
Closed after pr #139
