### ISSUE TITLE
Settings/AppSettings needs to be implemented

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#389]
The Settings/AppSettings is currently greyed out and needs to be reviewed for functionality and implemented.

**Comment by sgpearse** [comment]
Needs more review.  Most could probably be removed.

**Comment by shaomeng** [comment]
Thoughts on the JPEG quality knob:
-- We should use PNG format so no more JPEG quality settings needed.
-- PNG also has a file size benefit: it's usually smaller than JPEG in our cases.
-- We can bring in a libpng and get rid of libjpeg, so hopefully the same number of 3rd party libraries.

**Comment by sgpearse** [comment]
Need to determine what to keep and what to pitch.
