### ISSUE TITLE
TFE: constant color option not available

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#396]
The constant color option is not longer displayed on any of the renderers. It should be possible to select constant coloring for the Barbs and contour renderers.

To reproduce:
1. Load any data set and enable a Barb or Contour renderer
2. Select the appearance tab. There is no option for constant coloring.

**Comment by sgpearse** [comment]
We will do option 2!

Make a constant color checkbox in the Apperance tab.  Move the const color selector to the appearance tab (off by default).  Keep the color-mapped variable selector in the variables tab.
