### ISSUE TITLE
assert always fails at RangeController.cpp

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#4]
Line 221 or RangeController.cpp
(https://github.com/NCAR/VAPOR/blob/master/apps/vaporgui/RangeController.cpp#L221)
will always fail.

Suggestion:
Give "position" a default value to silence this warning.

**Comment by sgpearse** [comment]
Hey guys, RangeController is being deprecated in 3.X.

**Comment by shaomeng** [comment]
It seems the file is touched and the line referred to at the original post is gone. I'm then going to close this issue.
