### ISSUE TITLE
contours: can't set desired contour values

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#405]
It is sometimes not possible to get the desired contour values. The Contour editor (TFE) will not let contour lines go outside of the range of data making some selections impossible. Setting the  space between lines may not be possible

To reproduce:
1. Load DUKU.nc and enable the contour renderer with the U10 variable.
2. Uncheck the "Lock properties to ..". 
3. Set the contour line count to 20.
4. Try setting the spacing to 2.0. The application won't let you, presumably because some of the resulting lines would go outside of the data range.

**Comment by sgpearse** [comment]
Spacing should reduce the count if the maximum contour exceeds the range of the data.
