### ISSUE TITLE
statistics: sample count doesn't count samples over time

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#407]
The sample count in the Statistics tool does not appear to be accumulating samples over time. It probably should

To reproduce
1. Load any data set with multiple time steps (e.g. katrina) and launch the Stats tool. 
2. Add any variable and click Update. Make note of the count.
3. Increase the maximum time step and update. The count does not chage

**Comment by shaomeng** [comment]
Hi John,

I played with the GUI and cannot reproduce this problem. I also looked at the code and it seems the code is taking into account multiple time slices. Could you verify that it is actually occurring? 

Thanks,
Sam

**Comment by clyne** [comment]
Works for me. I'm closing this.
