### ISSUE TITLE
Statistics: Default bounding box

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#411]
The default bounding box for the Statistics tool should probably enclose the entire domain.  From what I've tested so far, the X and Y axes are slightly trimmed in their minimum and maximum extents, and the Z axis maximum is substantially trimmed.

To reproduce:
1) Open Vapor with KatrinaMaster.nc
2) Open the Statistics tool
3) Add variable P.  The Geometry widget's defaults will not enclose the entire domain.

**Comment by shaomeng** [comment]
Hmm, Statistics doesn't really command GeometryWidgets where to place the sliders; it responds to whatever GeometryWidgets reports back.
Maybe @sgpearse can provide some hints on how to make them work better?

**Comment by shaomeng** [comment]
Update on 4/4/2018:
I still think the information flow is a one way from GeometryWidgets to Statistics... So I'm adding @sgpearse to the asignees list.
P.s., I'm also OK to not fix this one, since this issue is too minor...

**Comment by sgpearse** [comment]
This bug is still present.  I'd like to bump it to medium priority.  I think the extents of our Statistics tool should default to the maximum extents, like what we get back from DataStatus::GetActiveExtents().  I believe this is the same behavior exhibited by our renderers.

![screen shot 2018-04-25 at 2 48 37 pm](https://user-images.githubusercontent.com/9522770/39272041-05a1f6ec-4898-11e8-9fef-58891e33dd45.png)

**Comment by sgpearse** [comment]
The issue seems to pertain to 3D variables.  Since we're not listing them as options for the Statistics tool anymore, this problem cannot be encountered currently.
