### ISSUE TITLE
Statistics: Timestep Selection

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#414]
I believe that Statistics is missing a timestep in the min/max selector for time.

To reproduce:
1) Run Vapor with KatrinaMaster.nc
2) Note that KatrinaMaster.nc holds 10 timesteps, 0 to 9
3) Open Statistics, the timestep selectors max out at 8

**Comment by shaomeng** [comment]
Submitted a PR to work around it in the Statistics tool, but there's further an improvement needed for DataMgr, as described in issue #429 .

**Comment by shaomeng** [comment]
should be fixed by PR #435
