### ISSUE TITLE
multiple visualizers confuses render controlers

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#423]
When multiple visualizers are created the Render tabs get confused.

To reproduce:
1. Load DUKU.nc
2. Create and enable a Barb renderer
3. Create a second visualizer window 
4. In the second visualizer window create a Contour renderer
5. Click in the first visualizer window (right side of screen, labeled "Visualizer 0"). The Barb renderer becomes active as it should, but the Variable selector for the Barb renderer is showing only a single variable. It should show 2 or 3 variables.

Note also that killing the visualizer windows does not seem to terminate the renderers associated with them. It should.

**Comment by sgpearse** [comment]
@clyne, I have a partial fix for this, but I believe there's a bug in the ControlExec's RenderLookup() function that is preventing a complete fix.

If you check out the branch issue_423_multipleVisualizerBug, there is a function in MainForm.cpp called setWinActive(), which updates the GUI with a default Renderer, depending on which Visualizer is active.  

MainForm::setWinActive() makes a call to _controlExec->RenderLookup() to retrieve information for the update.  However the "rendererType" field seems to be returning an empty string.

My current work-around is to re-assign the "rendererType" to be equal to "rendererName" (line 739).  However this will not have the correct behavior for multiple renderers of the same type within a single visualizer.

I've done some cursory digging and it's not clear why ControlExec::RenderLookup() is returning an empty string for the "rendererType"
