### ISSUE TITLE
Does non-time-varying variable have number of time steps 0 or 1?

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#434]
The following code indicates that if a variable is not time varying, it will have 0 time steps. I'm not sure if this is a convention across the entire code base (instead of 1)? 
https://github.com/NCAR/VAPOR/blob/b30705c006d6e9c094ac1847420af9876849ed22/include/vapor/NetCDFCollection.h#L736

**Comment by clyne** [comment]
It should be 1
