### ISSUE TITLE
Undo does not return correct params

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#438]
To reproduce, a debugger is required. 

1. Checkout branch `issue_415` and compile with `-g` option.
2. Invoke vapor within a debugger. In my case `gdb ./bin/vapor`.
3. Set a breakpoint: `b Statistics.cpp:105`.
4. Run VAPOR, load a data set. (I used Duku.) Open Statistics tool.
5. Add 2 variables: `ALBEDO` and `E`. Issue "continue" to gdb when the program hits breakpoints.
6. Click "Undo" from the Menu. Issue "continue" when hitting breakpoints. Notice that there's only `ALBEDO` left in the statistics window.
7. Click "Undo" again. The program hits breakpoints. Now examine the variables from gdb:

  - Check what variables are held by `statsParams`, which is the current copy of the `StatisticsParameters`: `print statsParams->GetAuxVariableNames()`.
  - It shows a vector of size 1, with its content being a string ALBEDO, the same as the variable left on the screen.
  - I could keep clicking the "Undo" button but this ALBEDO string is not going away.
  - I believe the correct behavior here should be an empty array.

@clyne maybe you can let me know if my reasoning is correct. I assume I'm getting the pointers following the good practices.

**Comment by clyne** [comment]
Sam, I committed a change to this branch that I believe fixes the problem. Let me know if not

**Comment by shaomeng** [comment]
Hi John,

I confirm this bug is fixed. 

Meanwhile I discovered another undo/redo related bug: #441. I've assigned that one to you.

I'll close this bug.

**Comment by clyne** [comment]
Sam, I accepted your pull request. However, I noticed afterward that the StatisticParams class files had been moved into the library (e.g. lib/params and include/vapor). These should really reside in the apps/vaporgui directory as they are not part of the render library. 

thanks - jc

> On Nov 21, 2017, at 12:05 PM, Samuel Li <notifications@github.com> wrote:
> 
> Hi John,
> 
> I confirm this bug is fixed.
> 
> Meanwhile I discovered another undo/redo related bug: #441. I've assigned that one to you.
> 
> I'll close this bug.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
Hi John,

I could bring them back. But aren't we treating StatisticsParams as RendererParams, ,since that's the base class of StatisticsParams?
