### ISSUE TITLE
Redo: breaks "Close VDC" menu items

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#441]
Follow the steps below, and the "Close VDC" menu will miss opened data sets.

1. Open VAPOR, load Katrina.
2. Open Statistics tool. Add a variable. Then "Undo," the variable table clears.
3. Open another data set, say Duku, with Statistics window open.
4. Notice that under the "Close VDC" menu both Katrina and Duku are available.
5. Click "Redo" with the Statistics window open. Notice that one variable goes back to the variable table.
6. Take a look at the "Close VDC" menu. The Duku data set is missing.

**Comment by clyne** [comment]
Note: This bug was fixed by making it possible to perform a redo only *immediately* following an undo. This it is no longer possible to reproduce the problem.
