### ISSUE TITLE
Renderer deletion causes crash

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#450]
To reproduce: 
1. Open Vapor, import WRF data: `/little_glade/data/WRF/headwaters/wrfout_d01_2053-03-20_00:00:00`.
2. Create an ImageRenderer, enabled it.
3. Close the current dataset.
4. Import WRF again: `/little_glade/data/WRF/headwaters/wrfout_d01_2053-03-21_00:00:00`.
5. Create an ImageRenderer and a TwoDDataRenderer, enable both.
6. Notice that the TwoDData Rendere is highlighted with a blue background. If not, select it to have blue background.
7. Click "Delete" button. Notice that the TwoDData Rendere is still in the Renderer box.
8. Click on the TwoDDataRenderer, VAPOR crashes.

**Comment by StasJ** [comment]
I followed these instructions except I clicked on the TwoDData renderer before deleting it in step 7, causing vapor to crash.

**Comment by sgpearse** [comment]
The RenderHolder has several quirks that I'm going to try to iron out along with this.
