### ISSUE TITLE
MOM4 data sets not able to load:

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#456]
The following MOM4 data sets are not able to import to VAPOR with the NetCDF-CF option.
(Vapor throws an error message.)
```
/little_glade/data/MOM4/19990101/19990101.ocean_month.nc 
/little_glade/data/MOM4/iom1/ocean_layer/20010101.ocean_layer.nc
/little_glade/data/MOM4/iom1/ocean_momth/20010101.ocean_month.nc
```
The following MOM4 data sets are not able to import to VAPOR with the NetCDF-CF option.
(Vapor crashes.)
```
/little_glade/data/MOM4/iom1/ocean_trans/20010101.ocean_trans.nc
/little_glade/data/MOM4/om3/ocean_residency_month/19900101.ocean_residency_month.nc
/little_glade/data/MOM4/om3/ocean_residency_snap/19900101.ocean_residency_snap.nc
```

**Comment by clyne** [comment]
Unable to convert vertical coordinate expressed in dbars to meters.

**Comment by shaomeng** [comment]
4/3/2018: Could someone in Boulder verify if this is still a bug?
