### ISSUE TITLE
POP data sets not able to load

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#457]
The following POP data sets are not able to load as NetCDF-CF files: they cause vapor to crash.
```
/little_glade/data/POP/0059/2D.t.t0.1_42l_nccs01.0059.nc
/little_glade/data/POP/0059/grid.3600x2400x42.no_caspian_or_black.nc
/little_glade/data/POP/0059/SALT.t.t0.1_42l_nccs01.0059.nc
```
(I didn't test the rest files in the `/little_glade/data/POP/0059/` folder.

**Comment by clyne** [comment]
These files are pre POP version 2.x, and do not contain coordinate variables (i.e. the don't follow the CF conventions).

See feature request #361

**Comment by shaomeng** [comment]
4/3/2018: Could someone in Boulder verify if this is still a bug?
