### ISSUE TITLE
TwoDData renderer results looking weird on a particular data set

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#459]
The TwoDData renderer renders the following image on the data set:
```
/little_glade/data/POP/BryanASP/tenth_degree/daily/hybrid_v5_rel04_BC5_ne120_t12_pop62.pop.h.nday1.0045-01-01.nc
```
It seems a little weird to me because of the super clear boundary between color blocks.
It could also be whatever the read data shows though.

![screenshot from 2017-11-22 13-26-00](https://user-images.githubusercontent.com/814885/33148341-be40c70c-cf88-11e7-9849-30fbff9854e9.png)

**Comment by shaomeng** [comment]
Similar renderings happen to the following data set:
```
/little_glade/data/POP/BryanASP/tenth_degree/monthly/hybrid_v5_rel04_BC5_ne120_t12_pop62.pop.h.0045-01.nc
```

**Comment by clyne** [comment]
This data set was produced from a version of POP that has a bug in it, resulting in many of the lat and lon coordinate values incorrectly being set to -1.
