### ISSUE TITLE
OSX: Save Session As has no text entry field

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#474]
When performing a "Save Session As..." there seems to be no text entry field to name your session file.  This is observed on OSX.

To reproduce:
1) Spin up Vapor with KatrinaMaster.nc
2) Create a new Barb renderer.
3) File->Save Session As...
4) The file dialog will not have a text field to name your session file

**Comment by StasJ** [comment]
Save Session As opens an "open" dialog.
