### ISSUE TITLE
Crash upon rendering multiple datasets

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#49]
To reproduce:

1) Import the following CF file:
    /glade/p/VAST/VAPOR/Data/CoupledWrfRoms/kiost_roms_nwp12_avg_y1982-002.nc
2) Import the following WRF file:
    /glade/p/VAST/VAPOR/Data/CoupledWrfRoms/wrfout_d01_1982-01-31_10_00_00
3) Create a 2D renderer instance on the WRF file and enable it
4) Create a barb renderer instance on the ROMS file, Vapor will crash

**Comment by clyne** [comment]
Fixed
