### ISSUE TITLE
Image capture and image capture sequence are broken

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#50]
Image capture isn't working

To reproduce:
1. Load any data set and enable any visualizer
2. Capture an image. Examine the resulting image. It is not the image displayed on the screen

**Comment by shaomeng** [comment]
This bug seems gone. I'm gonna close it, and @clyne is welcome to verify it.

**Comment by clyne** [comment]
I'm reopening this. The image is only correct (on Macs) if the application has been re-sized *before* capturing an image.
