### ISSUE TITLE
Fidelity Widget does not populate radio buttons

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#526]
Platform: Mac OS

To reproduce: 
1. Open vapor with the Katrina data set: 
```
./bin/vapor.app/Contents/MacOS/vapor ~/Data/KatrniaMaster.nc
```
2. Create an Image renderer. 
3. The fidelity widget does not populate radio buttons, as the attached screenshot shows.

![screenshot 2017-12-21 15 33 43](https://user-images.githubusercontent.com/814885/34277770-6fba10d2-e664-11e7-96b4-8255a0cb4056.png)

**Comment by sgpearse** [comment]
I believe that this is the correct behavior.  If you take a look at the screenshot, there is no variable selected, hence no fidelity controls.

**Comment by shaomeng** [comment]
I'm not so sure, since the following screenshot shows that it has radio buttons with "0" selected as the variable. Maybe the issue is better described as "inconsistent GUI" ?

![screenshot 2018-01-09 12 06 07](https://user-images.githubusercontent.com/814885/34738269-c14feee6-f535-11e7-9aa0-52c400118b79.png)

**Comment by shaomeng** [comment]
The problem seems not resolved, see screenshot.

![screenshot 2018-01-24 16 36 11](https://user-images.githubusercontent.com/814885/35362950-d1564eb6-0124-11e8-8c4c-7b32e0a903a4.png)

**Comment by shaomeng** [comment]
This issue seems to be fixed by Scott.
