### ISSUE TITLE
Widget should not keep copies of these pointers

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#527]
According our newest program structure, any widget should not keep copies of the following pointers.

https://github.com/NCAR/VAPOR/blob/e8166d4d51889d3ef521c5709793415d6d9a4e82/apps/vaporgui/VariablesWidget.h#L128-L132

**Comment by shaomeng** [comment]
Similar to issue #200

**Comment by clyne** [comment]
Needs discussion in broader context of all event routers

**Comment by sgpearse** [comment]
It turns out that the VariablesWidget does use all three of these objects.  Since this requires a broader discussion about the architecture of the Update() method, I'm going to un-assign myself for now.

**Comment by shaomeng** [comment]
No longer applicable.
