### ISSUE TITLE
Improvement to the GeometryWidget -- Time Dimension

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#529]
The current GeometryWidget provides controls of the extents of X, Y, and Z dimensions.

It'd be a reasonable improvement to also provide controls of the Time dimension, which can be shown or hidden.

An example use case: Statistics utility.

**Comment by shaomeng** [comment]
Hi @sgpearse ,

John and I discussed a few possible changes to the GeometryWidget aiming to reuse as much code as possible. I opened two tickets for them, this issue #529 and another issue #530 . I hope my description makes sense, and you agree with the proposed changed.

If you think it makes sense to apply the changes, could you take a lead in making them happen? I tried but the complexity of the widgets stopped me from making good progress... I've created a branch issue_529 for it.

Please let me/us know any questions you might have.

Thanks,
Sam

**Comment by sgpearse** [comment]
Question:

What parameters are we setting when we have a min/max timestep selector?  RenderParams has a SetCurrentTimestep() option, but nothing for a minimum or maximum setting.

Do we add min/max timestep parameters to RenderParams, or implement the timestep selector as a one-off for the Statistics and Plot tools?
