### ISSUE TITLE
Improvement to the GeometryWidget -- Single Point mode

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#530]
The current GeometryWidget provides two controls for each dimension: one for the min value and one for the max value.

It's good for GeometryWidget to also provide another operational mode, namely single point mode. 
Under the single point mode, it exposes only one control for each dimension.

Example use case: single point selection in Plot utility.

**Comment by sgpearse** [comment]
If you check out the branch issue_530, you'll see that the geometry now takes a new flag on Reinit(), named DisplayFlags.  You'll want to pass GeometryWidget::SINGLEPOINT to the second argument on Reinit() to get the desired feature to replace the MINMAX default.

Was there a refactorizaiton needed as well?  I did some cleaning while implementing this, but I'm not sure if you're referring to something specific with the Refactor-needed tag.
