### ISSUE TITLE
Naming of Get/SetSpaceTimeMode()

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#547]
Rename the following functions:

    bool GetSpaceTimeMode();
    void SetSpaceMode();
    void SetTimeMode();

to something like:

bool GetSpaceMode()
bool GetTimeMode()
...

https://github.com/NCAR/VAPOR/blob/4772ea18277bf8be2c4b163ade84bd73ef022ebd/apps/vaporgui/PlotParams.new.h#L45

**Comment by shaomeng** [comment]
fixed.
