### ISSUE TITLE
Vapor crashes every time I try to import a wrfout file

### ISSUE THREAD

**Issue by wf835334** [NCAR/VAPOR#548]
Vapor keeps crashing every time I try to import a WRF dataset into the GUI. I'm running the 2.6 version on Windows 10

**Comment by shaomeng** [comment]
@wf835334 
Could you give us an example of the WRF data you were trying to input?

**Comment by clyne** [comment]
Old VDC files are not compatible with the recent changes. The GUI now issues a warning instead of crashing.
