### ISSUE TITLE
Settings: changes needed

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#569]
The new Settings tab needs some help. There are a few issues that make its behavior problematics:

1. Parameters are saved both in the session file *and* a .vapor3_settings file. Its not clear how they interact

2. Some of parameters only take effect after a restart. The current mechanism for notifying the user of this does not make this clear (changing text to yellow and adding a Qt tooltip that may or may not be seen)

3. There is no way to restore the system defaults, and thus get back reasonable values.

**Comment by sgpearse** [comment]
I'm not sure I understand issue 1.  2 and 3 should be fixed now though.

**Comment by sgpearse** [comment]
I'm going to close this since I think all of the issues have been addressed.

Regarding item #1, there should be no session file modifications done from the Settings tab.
