### ISSUE TITLE
Master branch cannot compile

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#586]
The master branch cannot compile with the following error. I've also attached my CMakeCache file. 

Platform: macOS 10.13.4

<img width="810" alt="screenshot 2018-04-03 22 22 25" src="https://user-images.githubusercontent.com/814885/38256537-1f83c0da-3791-11e8-88f6-319b5f1c8e3e.png">

[CMakeCache.txt](https://github.com/NCAR/VAPOR/files/1872105/CMakeCache.txt)

**Comment by StasJ** [comment]
That's my bad. I'll fix it

**Comment by shaomeng** [comment]
Confirm it is fixed.
