### ISSUE TITLE
Add support for scaling transform

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#60]
Users specified scene scaling is not currently supported (only translation is available). Though in 3.0.0.beta we are only required (contractually) to support 2D data, the contour and barb renderer can support 3D variables. Moreover, even for 2D renderers the lack of scaling means that displacing a plane (e.g. 2DData, Image) by a height field is effectively a no-op for most ESS data sets

**Comment by clyne** [comment]
Stas, let's talk about what needs to be done here.

**Comment by clyne** [comment]
Add entry to transform table for "origin" about which to do scaling and rotation.

This needs to be done in GeometryWidget as well as Navigation/Viewpoint tab.

Need to modify
+ transform paramsbase class
+ Transform Widget (in vaporgui/applications0
+ OpenGL render code

**Comment by sgpearse** [comment]
Scaling from the Navigation->Viewpoint tab seems to perform a different operation than scaling individual renderers.  I believe that the origin is not being set to the same values.

To reproduce:
1) Spin up Vapor with KatrinaMaster.nc
2) Create a TwoDData instance, apply height variable HGT
3) In the Geometry tab, scale the Z axis by 100.  Confirm that this is the desired effect.
4) In the Navigation->Viewpoint tab, scale the scene by 100.  The renderer will drop down outside of the domain box.  Note that the origin is ~10km here, while it's ~0 for the TwoDData renderer.

**Comment by clyne** [comment]
This is working. Picking the default origin is tricky. Each renderer picks one based on the default variable selected. For twoD this is a 2D variable, so the component of the origin is 0. The data set transforms select the origin by looking at all active variables, which includes 3D variables. Hence, here the default of the Z component is not 0.
