### ISSUE TITLE
Calculating Image Renderer height is very slow

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#617]
1. Open Katrina
2. Add image renderer
3. Select USFilled.tiff as the image
4. Set height variable to HGT
5. Enable

This will take 3-6 seconds to compute. The TwoDData renderer does the same in a fraction of a second.

**Comment by clyne** [comment]
Adding a comment that Jeremy Sauer and Patrick Hawbecker are running into this.

**Comment by clyne** [comment]
The performance issue appears to be due to the use of Grid::GetValue(), which still accepts STL vectors as arguments. Most of the other Grid accessors have been refactored to use raw pointers.
