### ISSUE TITLE
Unreasonable setting value restrictions

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#620]
I found the following setting value restrictions *unreasonable*:

1. https://github.com/NCAR/VAPOR/blob/1432d5aab8269f59d6263654887e52ebb2d30570/apps/vaporgui/SettingsEventRouter.cpp#L66-L68
Why 0 thread is allowed? Why aren't more than 8 threads allowed? 

2. https://github.com/NCAR/VAPOR/blob/1432d5aab8269f59d6263654887e52ebb2d30570/apps/vaporgui/SettingsEventRouter.cpp#L70-L72
Why 0MB cache allowed? Why don't allow more than 100GB cache? 

3. https://github.com/NCAR/VAPOR/blob/1432d5aab8269f59d6263654887e52ebb2d30570/apps/vaporgui/SettingsEventRouter.cpp#L74-L80
Why 0 is allowed as window dimensions? What will happen if a user enters 0?

**Comment by sgpearse** [comment]
make maxInt values for all maxima
