### ISSUE TITLE
Settings: Dataset Projections table unable to read

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#621]
To reproduce:
1. Open VAPOR, load Katrina dataset.
2. Create an Image Renderer, and enable it. 
3. Go to Navigation->Viewpoint settings. The Dataset Projections table is too short and is not able to read, as the screenshot shows.

![screenshot from 2018-04-13 14-42-05](https://user-images.githubusercontent.com/814885/38757176-4fa409ba-3f29-11e8-90fd-94c1cdd3f0c6.png)

**Comment by shaomeng** [comment]
I'd say it's improved, but not "fixed."

![screenshot 2018-04-24 17 58 46](https://user-images.githubusercontent.com/814885/39219669-3d84fdfc-47e9-11e8-8981-aec950a5c83b.png)

**Comment by clyne** [comment]
Can't reproduce this on the Mac. Is it a Linux (or Ubuntu) only problem?

**Comment by shaomeng** [comment]
Most likely. Lucky you on a Mac!

**Comment by shaomeng** [comment]
The table is still in "fixed size" so situations like the following screenshot could still happen. But given it's not a common use case, we're lowing its priority to "low."

![screenshot 2018-05-02 11 32 36](https://user-images.githubusercontent.com/814885/39539562-2e2d3b34-4dfd-11e8-8ea5-325d31218c48.png)
