### ISSUE TITLE
Inconsistent behavior of duplicate renderers

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#622]
This issue is regarding to how a duplicate renderer should behave. 
More specifically, after creating a duplicate renderer, `dup_renderer`, from the original renderer, `orig_renderer`, should `dup_renderer` keep track of all the setting changes made to `orig_renderer` and update itself? 

Currently, the behavior of `dup_renderer` is inconsistent: it keeps some changes from `orig_renderer` but not every change.

Example:
1. Open VAPOR, load Katrina.
2. Create an Image renderer. Make a duplication.
3. Change Height Variable and Fidelity of `orig_renderer`, and also play a few time steps forward.
4. Click the `dup_renderer`, and examine its settings. 
5. Height Variable and Fidelity changes of `orig_renderer` are *NOT* carried to `dup_renderer`, while the time step is updated to be the same as `orig_renderer`.

**Comment by clyne** [comment]
This is the intended behavior. The time step is a global setting.
