### ISSUE TITLE
File: can't load session files

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#639]
vaporgui will not longer load session files.

To reproduce:
1. Load katrina and enable the 2D renderer
2. Save the session file
3. Exit vaporgui
4. restart vaporgui and try to load the session file (File/Open Session). An error message is generated

**Comment by shaomeng** [comment]
Update on 4/24/2018:
Step 2 throws an error, thus not able to verify.

**Comment by clyne** [comment]
Works for me. Can you give more detail on the steps you are performing?

**Comment by shaomeng** [comment]
I strictly repeated the steps listed on this bug report...

**Comment by clyne** [comment]
@shaomeng I can't reproduce this. Can you verify that is still a problem and what platform you are testing on?

**Comment by shaomeng** [comment]
@clyne This was happening on the installers from last round, but not the current master branch. I'm gonna close it until we find it come back again...
