### ISSUE TITLE
Settings: Autosave file dialog should verify that a regular file with appropriate extension

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#643]
The Autosave file location dialog allows the user to change the session file path to an arbitrary path. It should require a file ending with a ".vs3" suffix because the file filter for reading session files requires this extension.

**Comment by shaomeng** [comment]
A regression is introduced... I'm re-opening this issue.

**Comment by clyne** [comment]
Sam, please provide a precise step-by-step process that demonstrates the problem you're seeing. It seems to work fine for me.

**Comment by shaomeng** [comment]
John, I'm actually curious how it works fine for you. 
Here are the steps to repeat it:
1. Open Katrina, go to "Settings" tab.
2. Change the default session file from `VaporAutoSave.vs3` to `VaporAutoSave.v3`.
4. A new `VaporAutoSave.v3` file appears on the disk.

**Comment by clyne** [comment]
This bug still exists. I'm reopening it. The steps provided by Sam still result in a file with an invalid extension

**Comment by shaomeng** [comment]
Aha, I think I fixed the `Save Session File` button, but didn't fix `Auto Save Session File`. Let me re-fix...
