### ISSUE TITLE
Settings: window size line edit turns yellow

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#644]
The Qt line edit widget for the Settings/Startup Settings Width and Height sometimes turns yellow when a value is entered.

To reproduce:
1. Load any data set
2. Under Settings / Startup Settings change the "Lock window dimensions" width to 800 and hit return. The background color for the line edit turns yellow

**Comment by shaomeng** [comment]
Err, I didn't understand it either, but then @sgpearse told me that yellow means these changes only take effect after restart.

This is an example of "color coding a text box is a bad idea," as I described in the common of issue #315
