### ISSUE TITLE
Settings: Inconsistent behavior of 1st and 2nd time clicking on the "Restore Default" button.

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#690]
To Reproduce:
1. Open VAPOR, go to Settings tab.
2. Edit "Session file path" text box to something else. Don't press ENTER after finishing.
3. Click "Restore Defaults" button. Notice that the text box goes back. **This is behavior 1**. 
4. Edit "Session file path" text box again to something else. Don't press ENTER after finishing.
5. Click "Restore Defaults" button again. Notice that the text box goes back. **This is behavior 2**.
6. Behavior 1 and 2 are inconsistent.

The following screen capture demonstrates this issue.

![apr-20-2018 11-52-54](https://user-images.githubusercontent.com/814885/39066376-17f74022-4492-11e8-8db0-5688eaf3e68c.gif)

**Comment by sgpearse** [comment]
This appears to be an issue with Update.  After we replace our SettingsParams instance with the saved default, update does not trigger.  If we move the scene after pressing RestoreDefaults, the changes will then be applied in the GUI.

**Comment by clyne** [comment]
You can always force an update within the event router by simply calling it's public update() method. Typically there are enough Qt events to trigger updates after every change, but it's somewhat non-deterministic.
