### ISSUE TITLE
Default Search Paths: GUI does not update with user-selected path

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#729]
To reproduce:
1) spin up vapor with any dataset
2) In Settings->Default Search Paths, pick a directory via the Select button, for either the "Session file path" or the "Data set path".  The QLineEdits that correspond to these selections will not register the change until an Update is triggered through another params mechanism.

**Comment by shaomeng** [comment]
This bug is no longer there, thus closing it.
