### ISSUE TITLE
Contour lines not correct for 3D data

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#73]
Contour lines generated by vapor3 are very different from vapor2. Moreover, the histograms are very different as well.

To reproduce:
1. Load the Duku.nc data set
2. Create and enable a contour instance using the variable "P". Compare the histogram displayed with that of vapor2. 
3. Change the minimum contour value to 0, and set spacing to 100. Use the same settings for vapor2. Compare the contour lines for both.

**Comment by shaomeng** [comment]
@clyne I couldn't find a Duku.nc in the VAPOR/Data directory in glade. Could you send me a pointer of that?

**Comment by StasJ** [comment]
VAPOR/Data/WRF/DUKU

**Comment by clyne** [comment]
/glade/p/VAST/VAPOR/Data/WRF/DUKU/wrfout_d02_2007-04-01_00:00:00.nc

> On Oct 17, 2017, at 12:07 PM, Samuel Li <notifications@github.com> wrote:
> 
> @clyne I couldn't find a Duku.nc in the VAPOR/Data directory in glade. Could you send me a pointer of that?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
I'm not convinced that the bug is with VAPOR3, since VAPOR3 shows the same histogram as the histograms in VAPOR2 Iso and DVR tabs.
This means, VAPOR2's Contour and and Iso tabs show different histograms...
@clyne needs to weigh in how to proceed!

**Comment by clyne** [comment]
Fixed
