### ISSUE TITLE
Save Sessions crash

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#732]
Open VAPOR, load Katrina. Create a renderer, enable it. Select "Save Session," vapor crashes.

**Comment by clyne** [comment]
Sam, please be more specific in describing how to reproduce a problem. “do something” is not helpful. What specific action results in a crash?

> On Apr 25, 2018, at 4:17 PM, Samuel Li <notifications@github.com> wrote:
> 
> Open VAPOR, load Katrina. Do something. Select "Save Session," vapor crashes.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
John, I've updated the description, so instead of "do something," it currently is "create a renderer, and enable it."

Sometimes, I feel giving a specific direction is misleading, when every direction leads to a fail. For example, if I said "deleting a pointer pointing to an int array without allocating memory will lead to a segfault", one might think that deleting a pointer pointing to a *float* array is fine...
