### ISSUE TITLE
Single Image Capture Broken

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#735]
To reproduce:
1) Import one of Katrina's WRF files
2) Create a 2D renderer, enable it, and select V10 for its variable
3) Open the Appearance tab, which contains the Transfer Function
4) Capture single image.  

Note: Do not select .jpg for the extension.  I'm not sure if this problem is specific to jpg or png files, but I currently see it with .pngs.

The transfer function's histogram will go blank, and the captured image will be corrupt.
![coolwarm](https://user-images.githubusercontent.com/9522770/39276175-3edac436-48a5-11e8-855d-e80a74702ae2.png)

**Comment by shaomeng** [comment]
If you don't select an eligible suffix, it will give you a .png.

**Comment by shaomeng** [comment]
Could you verify if this corrupt is specific to .png, or all image formats?

**Comment by shaomeng** [comment]
Update: it's broken for any image format, and not only to .png files. Someone with more OpenGL experience to look at it?

**Comment by shaomeng** [comment]
This issue is fixed, so I'm gonna close it.
