### ISSUE TITLE
TFE: auto update of histogram not working

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#737]
There are two problems with the "automatically update histogram" feature.

To reproduce:
1. Load the VDC version of Duku
2. Create and enable a barb tab with U10 and V10 vector variables, and PFSC as the color map variable.
3. Select the appearance tab

Problem 1:
1. Make sure "auto update histo" is not checked
2. Change the variable fidelity. The histogram does not update until "update histogram" is clicked. This is correct behavior
3. Now enable "auto update histo". Change the variable fidelity again. The histogram does not automatically update as it should

Problem 2:
1. Uncheck "auto update histo"
2. Advance the time step. The histogram updates itself. It should not because "auto update histo" is not enabled.

**Comment by sgpearse** [comment]
This seems to be fixed with the PR from June 7, but it wasn't closed.
