### ISSUE TITLE
Copy region from renderer: too many renderers show up. 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#740]
To reproduce: 
1. Open VAPOR, load Katrina. 
2. Create an Image Renderer. Enable it. Note this is the only renderer created.
3. Go to Navigation -> Annotation. Click on "Copy region from renderer." **Two** renderers show up! 
![screenshot 2018-04-25 16 42 55](https://user-images.githubusercontent.com/814885/39276857-2f3b31b6-48a8-11e8-8cf4-d2c72648b1f9.png)

**Comment by sgpearse** [comment]
I cannot reproduce this on OSX or Ubuntu :\

**Comment by shaomeng** [comment]
This bug seems to be gone on 5/1/2018, so I'm going to close it.

**Comment by shaomeng** [comment]
Update: The steps to reproduce: 
1. Open VAPOR, load Katrina. 
2. Import WRF data: `/little_glade/data/Source/WRF/jangmi/wrfout_d02_2008-09-26_13_00_00`
3. Create a barb renderer. **Note that this is the only renderer exists.**
4. Go to Navigation->Annotation->Copy Region from renderer. **Note that two renderers show up.**
