### ISSUE TITLE
VDC: kdtree cache needs refactoring

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#767]
The cache for the KDTree needs a better policy for purging. Currently the cache can grow excessively large.

**Comment by shaomeng** [comment]
Is this due to the new KDtree implementation I introduced earlier, or the KDTree wrapper that we use?

**Comment by clyne** [comment]
Neither. The problem is the cache that maintains multiple Kd trees.


> On May 1, 2018, at 4:51 PM, Samuel Li <notifications@github.com> wrote:
> 
> Is this due to the new KDtree implementation I introduced earlier, or the KDTree wrapper that we use?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by clyne** [comment]
This was fixed back in May and never closed.
