### ISSUE TITLE
Contours: LOD seems to have no effect

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#779]
To reproduce:
1) Load Katrina, create a new Contour Renderer with variable T2 and enable it
2) Adjust the LOD and the contours appear to be unchanged 

![contourlodbug](https://user-images.githubusercontent.com/9522770/39585976-34eec6f2-4eb3-11e8-88e0-841cd3f48c44.gif)

**Comment by clyne** [comment]
This is working. You're just not going to see much (any) difference at really coarse grid resolutions
