### ISSUE TITLE
Contour: Geometry Controls

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#780]
Bug #778, regarding a diagonal discontinuity in the Contour Renderer, seems to be exacerbated by changes made with the geometry widget.

To reproduce:
1) Load Katrina, create a Contour Renderer with T2 at maximum fidelity
2) Increase the Contour Count to 50, and reduce the Spacing that they all fit within the histogram bounds
3) Reduce the X extents using the Geometry Widget

![screen shot 2018-05-03 at 9 30 38 am](https://user-images.githubusercontent.com/9522770/39586603-a871aea4-4eb4-11e8-8b82-2862b70909a8.png)

**Comment by StasJ** [comment]
The contour renderer is getting an invalid grid from the data manager. The grey lines are the grid cells:

![screen shot 2018-05-03 at 2 28 21 pm](https://user-images.githubusercontent.com/2772687/39601161-4e4bd2cc-4ede-11e8-8bb6-e891771f9cd1.png)

![screen shot 2018-05-03 at 2 28 28 pm](https://user-images.githubusercontent.com/2772687/39601168-521aea3c-4ede-11e8-8db2-10d507e9fb03.png)
