### ISSUE TITLE
Session files: multiple data sets not handled correct

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#787]
A saved session file with multiple data sets cannot be used to reload the data sets with their previous state

To reproduce:
0. Make sure "auto scaling" is disabled
1. Import the WRF data set from Data/CoupledWrfRoms
2. Enable 2D data and change the variable to something other than the default (e.g. U10)
3. Import the ROMS data set from Data/CoupledWrfRoms. When prompted, select "new session"
4. Enable 2D data from the *roms* data set and change the variable to something other than default (e.g. ubar). Note both 2D renderings are drawn on top of each other and you may not see both. It doesn't matter.
4a. Rotate the scene to change the viewpoint
5. Save the session and exit the application
6. Restart the application and open the previously saved session file
7. Import the WRF file. Note that it is loaded with the state from the session file (the selected variable is present). **However, the GUI failed to prompt whether the data should be loaded into a "new" or existing data set.**
8. Import the ROMS data set. Note this time the app promts whether to use a "new" data set state, or an existing one. **However, the choice of existing state is the WRF data set, not the ROMS data set**. If "new" data is selected the data set is NOT loaded into new state, but loaded into the ROMS state (confirm be looking at the selected variable).

**Comment by clyne** [comment]
There is a regression and the second data set can no longer be displayed. It appears that the bounding box for the second data set is not correct. Assigning to @StasJ

**Comment by StasJ** [comment]
@clyne I followed your steps and it seems to be working for me

![out5](https://user-images.githubusercontent.com/2772687/50671152-602edc80-0f8d-11e9-930e-34018d416174.gif)

**Comment by StasJ** [comment]
I tried this in release mode too and I still cannot reproduce
