### ISSUE TITLE
Annotation: replace text entry boxes with slider+text

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#791]
Several of the frames on the Annotation tab take numerical values. However, the Time Annotation and Orientation frames use only text entry boxes (QtLineEdits). There is enough realestate to replace these with Sam's slide+text combo. This would be particularly helpful where the range of reasonable values is not knowable (e.g. coordinates for orientation arrows, or time annotation coordinates).

**Comment by clyne** [comment]
@clyne verify this is still relevant

**Comment by sgpearse** [comment]
Fixed.
