### ISSUE TITLE
Vapor seems unable to launch on Windows 10

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#794]
To reproduce:

1) Install the binary VAPOR3-3.3.0-win64.exe that was made on May 2, located [here](https://drive.google.com/open?id=1cx80b9-076KuPX-L1DBY7TSnpyWa0cjF)
2) Run the application
3) A window will briefly appear then close

**Comment by StasJ** [comment]
Thats odd. The installer from the previous round of testing was working though?

**Comment by StasJ** [comment]
![scrot](https://user-images.githubusercontent.com/2772687/39780145-99a0b498-52c8-11e8-9e33-9e414235d850.png)
