### ISSUE TITLE
Error: Failed to get camera parameters

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#796]
Vapor cannot generate any renderers with the dataset /WRF/headwaters/headwaters-3.0.0.nc.  We get the dialog:

An error has occured
Failed to get camera parameters

To reproduce:
1) Spin up vapor, load /WRF/headwaters/headwaters-3.0.0.nc
2) You will get said error.  Create any renderer, you will continue to get said error.

**Comment by clyne** [comment]
Using old version of VDC
