### ISSUE TITLE
Katrina -> SMOIS results in Bad Access

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#80]
To Reproduce:
1. Open Katrina
2. Add barb renderer
3. Set one of the variables to SMOIS

**Comment by StasJ** [comment]
For some of the variables in Katrina, one of the dimension sizes is equal to zero. This is currently not taken into account. How should this be handled?
@clyne

**Comment by clyne** [comment]
The SMOIS variable does not have an associated coordinate variable. There is a question of where to display them in the scene? We’ll have to give some thought as to how to handle data variables that don’t have coordinates. I’ll get back to you.

> On Oct 26, 2017, at 1:47 PM, StasJ <notifications@github.com> wrote:
> 
> For some of the variables in Katrina, one of the dimension sizes is equal to zero. This is currently not taken into account. How should this be handled?
> @clyne
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by clyne** [comment]
The SMOIS variable is no longer accepted as a valid variable because it is a 3D variable with only two coordinates. A feature request is already open to synthesize coordinates for variables that are lacking them.
