### ISSUE TITLE
Settings: GUI needs more polish on Ubuntu

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#803]
Currently a line of text isn't displayed in complete. 

![screenshot from 2018-05-04 16-12-00](https://user-images.githubusercontent.com/814885/39655323-2ae21aa2-4fb6-11e8-8e5b-d9d927dd84c7.png)

**Comment by shaomeng** [comment]
Update on 6/11/2018:
This behavior remains the same.

**Comment by shaomeng** [comment]
Cannot test due to issue #1082

**Comment by sgpearse** [comment]
Fixed.
