### ISSUE TITLE
Not sure if VAPOR's multh-threading capability is still working. 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#804]
Test Platform: cisl-vapor.

Open Vapor, load Katrina. Create a contour renderer, change data fidelity to the highest. Enable this renderer. 

Open another terminal window to inspect CPU utilization via `top`.

Constantly change variables used for Contour renderer. Note that the VAPOR CPU utilization seems to be capped at 100%.

This observation makes me wonder if the VAPOR multi-threading capability is broken?

**Comment by clyne** [comment]
Katrina is probably too low resolution to see any benefit (the granularity of top isn’t high enough). Not sure any of our 2D data sets will benefit much, but a better test case would be the 1/10th degree POP data sets (3600x2400 grid points)

> On May 4, 2018, at 4:25 PM, Samuel Li <notifications@github.com> wrote:
> 
> Test Platform: cisl-vapor.
> 
> Open Vapor, load Katrina. Create a contour renderer, change data fidelity to the highest. Enable this renderer.
> 
> Open another terminal window to inspect CPU utilization via top.
> 
> Constantly change variables used for Contour renderer. Note that the VAPOR CPU utilization seems to be capped at 100%.
> 
> This observation makes me wonder if the VAPOR multi-threading capability is broken?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
My recent experience indicates that it's actually working. Thus I'll close this issue.
