### ISSUE TITLE
Annotation: #tics seems to accept invalid input

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#806]
To reproduce: 
1. Open VAPOR, load Katrina. 
2. Go to Navigation->Annotation. Enable annotation.
3. Type -2 in the #tics box of X. Press Enter after typing. 
4. Guess what, -2 is accepted... 

![screenshot from 2018-05-04 16-39-37](https://user-images.githubusercontent.com/814885/39655982-0e5624e2-4fba-11e8-8132-f32a77bf2cdc.png)

**Comment by shaomeng** [comment]
Update on 6/11/2018
Now it rejects the input on the 1st time you input. 
If you input a 2nd time, it accepts!!!

**Comment by shaomeng** [comment]
Update on 6/11/2018
Now it rejects the input on the 1st time you input.
If you input a 2nd time in the same box, it accepts!!!

![screenshot 2018-12-20 12 39 19](https://user-images.githubusercontent.com/814885/50307005-587f1c00-0454-11e9-8e0d-2813928a430a.png)

**Comment by sgpearse** [comment]
No longer relevant.
