### ISSUE TITLE
Data Fidelity: Default button alwasy in gray. 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#807]
These is a "Default" button in every Fidelity widget. What's weird is that it's always in gray...

**Comment by shaomeng** [comment]
Update on 6/11/2018:
This behavior remains the same.

**Comment by shaomeng** [comment]
Update on 12/20/2018:
This behavior remains the same.

**Comment by sgpearse** [comment]
Default button does not exist anymore.
