### ISSUE TITLE
Apply to all colorbars: not working

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#810]
To reproduce: 
1. Open VAPOR, load Katrina.
2. Create a barb renderer. Enable it. Also Enable it's color bar. Leave the default settings.
2. Create a contour renderer. Enable it. Also Enable it's color bar. Change its default settings so the color bar look different from the barb renderer colorbar.
3. Click "Apply to all colorbars". Notice that the two colorbars are still looking different.

**Comment by clyne** [comment]
This is a duplicate of 406
