### ISSUE TITLE
Open MPAS data: vapor crashes. 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#813]
To reproduce: 
1. Open Vapor.
2. Select File->Import->MPAS, and select the following file: 
/little_glade/data/Source/MPAS/MPAS-O/hist.mpas-o.0001-01-01_00.00.00.nc
3. Create a barb renderer
4. VAPOR crashes.

**Comment by clyne** [comment]
Which MPAS data set? I think we have three or four.

> On May 4, 2018, at 5:21 PM, Samuel Li <notifications@github.com> wrote:
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
It no longer crashes!
