### ISSUE TITLE
Plot: mixing 2D and 3D variables is problematic

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#817]
Mixing 2D and 3D variables in Plot causes incorrect results

To reproduce:
1. Load Katrina
2. Open the plot utility, and plot the U10 variable with default settings. Note the plot
3. Add the variable U and plot again. U10 is not plotted, and U is a straight diagonal line (which is probably not correct either)

**Comment by shaomeng** [comment]
The reported behavior is gone with fix from PR #841. However, issue reported in #838 should still be examined.
