### ISSUE TITLE
Unable to import Sandy data

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#859]
To reproduce:
1) import /little_glade/Data/Source/WRF/HurricaneSandy/auxhist1_d01_2012-10-26_12_00_00

**Comment by clyne** [comment]
@sgpearse does the VDC version of this data set work?

**Comment by sgpearse** [comment]
This should give a more informative error message.

**Comment by sgpearse** [comment]
Looks like the file was a symlink to a non existing file on cisl-vapor.
