### ISSUE TITLE
Statistics: Number of samples disagreement

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#862]
I'm seeing that the number of samples differs between imported WRF data and its corresponding VDC.

To reproduce:
1) Load our most recent Katrina-3.0.0.nc, built on May 10
2) Import the Katrina source file wrfout_d02_2005-08-30_08.  This is timestep 32 in the VDC.  Verify this by enabling Date/Time annotations.
3) In the Statistics tool, add the variable T2 for both datasets.
4) In the Katrina-3.0.0.nc dataset, set the minimum and maximum timestep to 32
5) In the Katrina-3.0.0.nc dataset, set the fidelity to its highest setting
6) In both datasets, extend the geometry extents to their maximum values

The number of samples for the imported wrfout file is 97335
The number of samples for the Katrina VDC is 18216

**Comment by sgpearse** [comment]
![screen shot 2018-05-11 at 3 38 42 pm](https://user-images.githubusercontent.com/9522770/39948035-6abc24bc-5531-11e8-87db-cae0427edb77.png)
![screen shot 2018-05-11 at 3 36 27 pm](https://user-images.githubusercontent.com/9522770/39948036-6ad7bf10-5531-11e8-897b-1517c7479d7f.png)

**Comment by shaomeng** [comment]
The No. of Samples disagreement still exists, but the ` This is timestep 32 in the VDC. Verify this by enabling Date/Time annotations.` verification shows 0 with raw WRF file. I'm not convinced the 32nd step of VDC and WRF file are actually representing the same timestep...

**Comment by clyne** [comment]
@shaomeng please check whether this bug still exists or not.

**Comment by shaomeng** [comment]
The dataset in question is no longer available. Maybe we should just close it? @clyne @sgpearse

**Comment by clyne** [comment]
> The dataset in question is no longer available. Maybe we should just close it? @clyne @sgpearse

Sounds good to me
