### ISSUE TITLE
change renderer name results in crash

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#872]
To reproduce: 
1. Open VAPOR, import the following file:
`/home/shaomeng/data/Source/ROMS/Kauffman/b.n20.B1850CN.f09_g16.09.roms.ha.0001-02.nc`
with its associated grid file. 
2. Create a Image renderer. Enable it. Notice it has a name "Image" in the renderer table. 
3. Type a new name for this renderer. For example, "haha". Press Enter.
4. Click on this renderer item. Vapor crashes.

**Comment by shaomeng** [comment]
Update on 12/20: This is still true. Seems pretty bad behavior, don't know why it got a postpone label?

**Comment by sgpearse** [comment]
Not sure when this got fixed but I currently am unable to change renderer names.
