### ISSUE TITLE
installation of command line tools on Mac doesn't work with csh

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#876]
The command line tool "installation" modifies the user's .profile. I believe only Bourne shell derivatives (e.g. bash, ksh) honor the .profile. Csh derivatives (tcsh, csh) do not.

To reproduce.
1. After "installing command line tools" from the GUI change your default shell to /bin/tcsh, and log back in. The VAPOR installation directory will not be on your search path.

**Comment by clyne** [comment]
The problem is not limited to csh. Scott is having the same problem and he uses bash.

**Comment by StasJ** [comment]
I just tested bash and it works on my system. I don't think we need to worry about it not working with csh since bash is the default shell shipped with OSX. We can assume someone who has a shell preference knows how to find and launch a binary themselves.

**Comment by clyne** [comment]
Agreed.
