### ISSUE TITLE
Incorrect viewing aspect ratio

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#89]
The initial modeling/projection matrix used has an incorrect aspect ratio.

To reproduce:
1. Load the Data/POP/Bryan/one_degree_monthy/* data 
2. Enable the image tab and turn on geo-referencing. Notice the distorted image. This is a cylindrical equidistant projection of the entire globe. The aspect ratio should be ~2:1, but it looks closer to ~3:1.

Note, if the vaporgui application is resized the aspect ratio is corrected.

Platforms:
tested on Mac

**Comment by StasJ** [comment]
Fixed in #74
