### ISSUE TITLE
Use dynamic_cast<> for pointers? 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#910]
C-style cast on pointers always makes me nervous, for example the following code snippet. 
https://github.com/NCAR/VAPOR/blob/040ecf6fd59eb883d4889ebb9a25e10359870d54/lib/render/WireFrameRenderer.cpp#L61
Would it make sense to introduce to our code standard to use `dynamic_cast<>` for such occurrences?

**Comment by clyne** [comment]
Probably.

> On Jul 6, 2018, at 11:39 AM, Samuel Li <notifications@github.com> wrote:
> 
> C-style cast on pointers always makes me nervous, for example the following code snippet.
> https://github.com/NCAR/VAPOR/blob/040ecf6fd59eb883d4889ebb9a25e10359870d54/lib/render/WireFrameRenderer.cpp#L61
> Would it make sense to introduce to our code standard to use dynamic_cast<> for such occurrences?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
We decided to add this rule to the code convention, as we can see https://github.com/NCAR/VAPOR/wiki/Vapor-Coding-Convention
