### ISSUE TITLE
TF Widget fails to display histogram

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#918]
To reproduce:
1. Follow steps reported in issue #917  to have a wireframe rendered.
2. Go to "Appearance" tab. Notice there's nothing displayed on the TF widget, as the screenshot shows.

![screenshot from 2018-07-11 18-01-00](https://user-images.githubusercontent.com/814885/42605369-ccb70500-8534-11e8-8693-239e0071544d.png)

**Comment by sgpearse** [comment]
@shaomeng Hey sam, I'm currently unable to reproduce this one.  Screenshot is below.  Let me know if you still have a problem moving forward.
![screen shot 2018-12-17 at 10 32 43 am](https://user-images.githubusercontent.com/9522770/50104382-18ffc800-01e7-11e9-889e-1f75a376d943.png)
