### ISSUE TITLE
Add support for vertical coordinate transforms

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#927]
Add support to convert from native vertical coordinate (e.g. pressure, Z, hybrid, etc.) to meters. In particular, transforms for vertical coordinate systems used by MOM, ROMS, and CAM are needed

**Comment by wingtorres** [comment]
Is there any progress on this front or a reliable workaround? I would love to use Vapor to visualize ROMS output, but to deal with anything in 3D I would need Vapor to reference data w/ the transformed z-coordinate. Even when importing output .nc files that include the time-varying depth grid (z_rho), Vapor defaults to plotting fields in sigma coordinates. The σ-z transform is straightforward to code up and for CF Convention-adhering files it really seems like this process should happen automatically upon import. I would be more than happy to contribute if someone could point me to where this would happen in the code.

As a sidenote, it seems that the function _roms2vdf_ possibly used to do this (by creating variable ELEVATION?), but now is no longer part of the command line tools as far as I can tell.

http://docs.software.ucar.edu/vapor/Documentation/2.5.0/doc/commands/html/roms2vdf.html

**Comment by clyne** [comment]
Yes, this is something that we can add without too much effort. We appreciate your willingness to help, but it is probably best for the VAPOR team to tackle this. However, help with validation would be appreciated.

**Comment by wingtorres** [comment]
Great to hear that! I would be more than happy to help validate.

**Comment by clyne** [comment]
@wingtorres We have transforms available for ocean_s_coordinate_g1 and ocean_s_coordinate_g2. Please let me know if you'd be willing to test.

**Comment by wingtorres** [comment]
Awesome! Definitely happy to test. Where can I find the updated code?

**Comment by clyne** [comment]
It's in the branch "issue_927", or I'm happy to provide you an installer for Mac or Linux

**Comment by clyne** [comment]
Added vertical coordinate transforms for the CF conventions defined "Ocean s-coordinate, generic form 1" and "Ocean s-coordinate, generic form 2 transforms".  The "Atmosphere hybrid sigma pressure coordinate" transform supported in VAPOR2 has not yet been added.

**Comment by wingtorres** [comment]
I had trouble building from source with Cmake... would you provide a Mac installer if it's not too much trouble?

**Comment by clyne** [comment]
No problem. There is a Mac installer at this link: 

https://drive.google.com/file/d/15WCJUHK_M8ipNIwxL4M-uG_BGKSXRIsG/view?usp=sharing

**Comment by wingtorres** [comment]
Thanks for the link! it seems to work well for the most part, but there's weird behavior in some parts of the domain when I try to make a volume plot. I'm looking at output from an idealized simulation of wave-driven flow on a reef (bathymetry below) where waves breaking at the reef crest drive flow across the reef flat which exits oceanward as a jet via a 20m deep channel.

![vaportestbathy](https://user-images.githubusercontent.com/28067578/78533597-cd2dc380-781b-11ea-9622-9943d0d9cb96.png)

The wireframe plot for bathymetry (2D variable) looks fine, but when I try to plot the vertical relative vorticity (3d) from the model output it behaves quite strangely in the channel. The volume plot goes deeper than it should even w/ vertical exaggeration and there's also a discontinuity at the outflow

![vaportest](https://user-images.githubusercontent.com/28067578/78534899-cc962c80-781d-11ea-890c-3eb4a503d051.png)

here's a link to the netcdf file if you want to download it for yourself. The grid is curvilinear and irregularly spaced

https://www.dropbox.com/s/z94vyb4654kapx9/avg_3hr.nc?dl=0

**Comment by clyne** [comment]
Whoops. There was indeed a bug in the calculation. I've uploaded another installer here:

https://drive.google.com/file/d/11JefzTayEuZ0cD_QcSOssl8ctlP_taig/view?usp=sharing

Could you please give it a whirl? Thanks

**Comment by wingtorres** [comment]
Works great now - no discontinuity! Thanks a bunch for adding this functionality.

![vaportest2](https://user-images.githubusercontent.com/28067578/78645213-bc4b8380-78e9-11ea-955a-a8870a0ee76e.png)

**Comment by clyne** [comment]
Excellent!

**Comment by clyne** [comment]
Still need support for: Atmosphere hybrid sigma pressure coordinate
