### ISSUE TITLE
WireFrame issue with CAM data

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#929]
To reproduce:

1) Open Vapor, Import->NetCDF-CF
2) Select the file:
    /little_glade/data/Source/CAM/AMIP_0.25degree/cam5_1_amip_run2.cam2.h1.1979-01-01-00000.nc
3) Reduce the region (optional, I figured this would reduce compute time.  It takes a while.)
4) On Ubuntu, Vapor will max out resident memory and hangs.  I'm not sure if it returns.
5) On OSX, Vapor will crash

**Comment by clyne** [comment]
I believe that a step has been left out on how to reproduce: after loading the data create a wire frame renderer.

**Comment by clyne** [comment]
Fixed by PR 935
