### ISSUE TITLE
Getting all missing values with 3D CAM data from Grid::GetValue(float, float float)

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#938]
I seem to be unable to retrieve values from 3D CAM variables through Grid::GetValue(float, float, float).  2D variables work ok, and both 2D and 3D variables work ok on MOM, POP, and WRF derived VDC datasets.  I have not been able to load any of little_glade's ROMS data onto either my branch or master.

Unfortunately, there is no code in our master branch that calls Grid::GetValue() on a 3D variable; the BarbRenderer is the first to access Grid values in this way.  Our other 3D renderers use iterators.  Therefore, this bug can only be reproduced on the branch named issue_829.

To Reproduce:
1) Check out the remote branch named issue_829
2) Load the dataset ~/little_glade/data/VDC/vapor-3.0.0/CAM/AMIP_0.25degree/AMIP_0.25degree-3.0.0.nc, or import its corresponding CAM file
3) Create a new Barb renderer and enable it.  It will default to the 3D variables U, V, and 0 for the Z component.  Nothing will render.  The terminal will print the value that is returned from Grid, along with the coordinates that were queried.  This is happening in BarbRenderer.cpp:838.
4) Change the Variable Dimension to 2D in the Variables tab.  Select any of the variables for the X Y and Z components of the renderer.  No defaults are set because there are no variables starting with the characters 'u' and 'v'.

**Comment by clyne** [comment]
Scott, can you checkout issue_938 and see if it fixes your problem(s)? I believe the ROMS issues are take care of, but please see if GetValue() is behaving as expected with CAM

**Comment by clyne** [comment]
@sgpearse please see last comment

**Comment by sgpearse** [comment]
I've merged issue_938 with my own branch (issue_829), and unfortunately it does not appear to fix the problem.  I pushed the merged branch onto origin in case you'd like to test it.  It's called GetValueTest.

**Comment by clyne** [comment]
Scott, 

This problem is specific to the NetCDF CF reader and CAM data. I will add a comment to your bug report. You should be able to do your 3D variable testing with ROMS or WRF data.



> On Aug 2, 2018, at 4:28 PM, sgpearse <notifications@github.com> wrote:
> 
> I've merged issue_938 with my own branch (issue_829), and unfortunately it does not appear to fix the problem. I pushed the merged branch onto origin in case you'd like to test it. It's called GetValueTest.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by clyne** [comment]
This is a problem with the NetCDFCFCollection class. The reader has special handling for the "Z3" variable that is found in CAM data, which unfortunately does not adhere to the requirement that coordinates variables are monotonically increasing (it's monotonically decreasing).

**Comment by clyne** [comment]
Forgot to mention that I just merged issue_938 into master, which provides the fix for ROMS data, but not CAM

jc


> On Aug 3, 2018, at 9:15 AM, John Clyne <clyne@ucar.edu> wrote:
> 
> Scott, 
> 
> This problem is specific to the NetCDF CF reader and CAM data. I will add a comment to your bug report. You should be able to do your 3D variable testing with ROMS or WRF data.
> 
> 
> 
>> On Aug 2, 2018, at 4:28 PM, sgpearse <notifications@github.com> wrote:
>> 
>> I've merged issue_938 with my own branch (issue_829), and unfortunately it does not appear to fix the problem. I pushed the merged branch onto origin in case you'd like to test it. It's called GetValueTest.
>> 
>> —
>> You are receiving this because you were assigned.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> 
> John Clyne
> National Center for Atmospheric Research
> 303.497.1236 (w), 303.809.1922 (c)
> clyne@ucar.edu
> 
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu
