### ISSUE TITLE
Data preparation guide

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#959]
A revised user's guide for preparing data for use with VAPOR3 is needed. 

Topics to include:
1. Getting raw data  into VDC format
2. Changes needed to NetCDF data to make them conform to CF conventions
3. Formats currently supported

**Comment by clyne** [comment]
See #1798

**Comment by StasJ** [comment]
https://ncar.github.io/VaporDocumentationWebsite/dataFormatRequirements/netCDF/nonCompliantNetCDF.html
https://ncar.github.io/VaporDocumentationWebsite/dataFormatRequirements/notesOnDifferentFormats.html
https://ncar.github.io/VaporDocumentationWebsite/dataFormatRequirements/vdc.html
