### ISSUE TITLE
wireframe rendering squares without recovering

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#966]
To reproduce:
1. Open VAPOR, load data `/little_glade/shaomeng/synthetic/sphere/sphere512nc`, create a wireframe renderer. 
2. Use mouth to click the border of "Data Fidelity" tab and the background repeatedly. At some point, the renderer then renders squares. Note that the rendering does NOT recover by itself. 
3. This behavior is captured in the following screenshot. 

![peek 2018-08-22 14-31](https://user-images.githubusercontent.com/814885/44489454-c20f2b00-a618-11e8-84f6-4ca2af767c54.gif)

**Comment by sgpearse** [comment]
I think this is the fast-rendering capability, no?

**Comment by shaomeng** [comment]
Hmm, shouldn't fast-rendering automatically become normal-rendering once the user stops interaction?

**Comment by shaomeng** [comment]
Cannot reproduce on 12/20, thus closing it.
