### ISSUE TITLE
Rename vaporgui to vapor3 and package name to vapor3

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#97]

**Comment by shaomeng** [comment]
I think we decided to rename the package name to vapor3, but keep the individual components the old names, e.g., vaporgui, etc.
@clyne @sgpearse

**Comment by shaomeng** [comment]
Hey Stas,

I just realize our file organization is to have many subfolders in the "apps" folder; each subfolder has the same name as the app that's gonna be created. Wrt this issue, the "vaporgui" subfolder is compiling into a "vaporgui" executable.

I like this consistency and would love to see it's kept. Could you also rename the subfolder from "vaporgui" to "vapo"r? 

Thanks,
Sam

**Comment by StasJ** [comment]
Hi Sam,

Yes, that is doable. I personally prefer to keep the directory name vaporgui. My reasoning for this is that apps/vaporgui is the gui src while "vapor" is the all encompassing app as it is presented to the user. I don't have a strong stance on this and I guess we can vote on it during tomorrows meeting.

**Comment by clyne** [comment]
I agree. Let’s discuss tomorrow.

jc

> On Oct 18, 2017, at 7:03 PM, StasJ <notifications@github.com> wrote:
> 
> Hi Sam,
> 
> Yes, that is doable. I personally prefer to keep the directory name vaporgui. My reasoning for this is that apps/vaporgui is the gui src while "vapor" is the all encompassing app as it is presented to the user. I don't have a strong stance on this and I guess we can vote on it during tomorrows meeting.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu
